In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('Class1/loans_income.csv')

In [5]:
df.head()

        x
0   67000
1   52000
2  100000
3   78762
4   37041

In [8]:
sp1 = df.sample(n=1000)
sp1

            x
44064   50000
32197   55000
28920   45000
12879   56000
20446   90000
33247   32400
5777    64000
8947    58000
49877   24000
13191   62000
33209   49000
19463   85125
5911    45000
31653   92508
48623   62000
2074    40500
23292   38000
32930   40000
22898   68500
30989   40000
14458   18000
36282  144799
35531   80000
30321   40200
27386   86000
6458    33000
8985    68500
32832   74000
20262   65000
44849   60000
...       ...
33213   45000
40504   25000
41091   25000
842     75000
11290  125000
11638   90000
25428   30000
16811   30000
16382   30000
37723   67000
15939   45839
22422   25576
31957   12000
39128   40000
39767   26540
9940   122694
23768   85000
41522   50000
3048    50000
39597   75000
29220   32000
8839    75000
27402   35000
43410   53260
17027   94000
28416   74000
40997   33000
25433  110000
28706   79500
32803   56000

[1000 rows x 1 columns]

In [13]:
list1 = [10, 50, 100, 1000]
for i in list1:
    for j in range(i):
        sp2 = df.sample(n = 10, replace=True)
        print(sp2)
        sp3 = df.sample(n = 100, replace=True)
        print(sp3)

            x
18525   65000
2639    45000
8935    75000
10584   71000
14884   45000
31172   50000
33639   84500
13434  138000
40427   38000
49818  104500
            x
45906   61500
46420   45000
7941    52000
33934   80000
46501  120000
23308  135000
46777   35000
9295   140000
39063   60000
36635   95000
27211   41700
34991  100000
6622   110000
6578    58000
25926   57000
5214    36000
42712   36000
25612   42000
34200   90000
11868   70000
38142   83004
35667   40000
37046   38000
27699   75000
40308   33000
17961   35000
49984   65000
43719   55000
45916   60000
6613    70000
...       ...
44801   40000
18844   53940
19669   70000
39642   28000
36508   45000
9144    70000
29726   59000
19708   40000
5421    85000
45942   45409
13702   42000
2678   107000
28815   70000
3082    92000
2908    38000
507     35000
35786   95000
37445  100000
14783   98000
8032    70000
40584  125000
18575   88000
13442   42565
2388    15000
18349   43000
19650   64000
10371   60000
48913   30000
32495   40000
23240   71000

[100 rows x 1 columns]
           x
33057  65000
24257  96000
21766  25000
39283  60000
45834  50000
28065  90000
36390  60900
37386  57000
35165  58000
18603  55000
            x
20687   50000
12827   62000
37864   60000
10781   25000
5784    42500
23177   54000
25541   88000
177     42500
47632   46000
20574   65000
22190   28000
19255  149000
38113   47000
4431    65000
25643   42000
46195   62700
49994   90000
41894   48000
48523   73000
35141   80400
28805   60978
43108   50000
34168  100000
44649  130000
23288   97000
28151   70000
5340    46000
12053   50000
30900   81000
18077   50000
...       ...
23573   32625
42501   66000
2420    33390
17864   32000
40341   95000
24183   55000
34080   95000
39674   91820
3025    60000
26227  135200
19681   62400
9291    55000
36908   42000
2145   120000
1303    75000
21614  150000
45238   75000
652     72000
35291   56000
19991   59000
30134   17000
34280   93000
25770   43888
7402    63000
37538   72000
35338  135000
18763   63000
25700   28000
26344   50000
1758    75000

[100 rows x 1 columns]
            x
11204   66000
20145   40000
4543   112000
34471   70000
40490   80714
28039   60000
18777   75000
33905   65000
45087   98000
4760    45000
            x
7645    40000
37646   30000
8409    32000
41357   32000
17468   70319
31687   76000
14473   50000
19709   96000
43476  120000
16307  125000
42158   92586
36075   85000
40866   40000
16230   30000
34046   30000
10646   36000
2485    60000
32845  117000
16119   50000
3315    60408
1834    70000
6443   125000
1919    71000
4963   130000
42106   48000
48013   47000
16391   92000
40409   72000
31745   79130
47892   91000
...       ...
29267   64500
14412  110000
23237  100970
46      25000
18219  100000
4544    43000
8381    80000
29440   68000
17271   74000
1783    66800
35940   45500
3442    70000
23236   80000
13695   73000
40369  110000
35490   84996
17051  104000
11962  135000
48754   75000
28744   24000
19190   42000
31210   68500
39889   80000
43474   74000
10917   70000
9611    69000
3473   100000
19643   43796
41258   69000
25099   65000

[100 rows x 1 columns]
            x
24327   55000
16128   57000
22293   60000
5143    55000
8944    60000
32250   26880
47666  100000
39977   70000
24633   65000
9830    60000
            x
34411   59000
12767   86388
24793  150000
2365    37000
42224   62000
41814   50000
22273   60000
13761   50000
37211   34700
30462   42000
36573   76000
17715   50000
6631    72360
13898   80000
26107   30000
31242   65000
8237    85000
29522   92000
11946   40000
26404  120000
7804    56160
36364  105000
24175   30000
10145   37000
18477  170004
28132  130000
24129   52000
44958   50000
45052   38000
24742  155000
...       ...
7331    36000
24332   25608
2377    82000
15561   22000
10099   90705
18449   65000
28525   95040
38303   45000
11339   60000
1302    74000
9251    30000
10642   52000
22156   61000
49620   77676
22517   58000
24032   82000
38456   50000
44545   95000
40056   52000
40013   75000
11190   55000
32033   59000
21294   46000
41186   66000
37902   49000
44038   68000
336    183000
26825   30000
18500   60000
46101   70000

[100 rows x 1 columns]
            x
46894  123000
46170   85000
32789   65000
39065   28000
48543  150000
46271   80000
44288   71000
5167    88000
17686   87000
49308   58000
            x
37139   35000
48250   41000
49155   70000
21679   70000
13989   65000
4130    69000
2287   123600
14267   20598
49289   90000
14929   61000
45605  170000
7435    40000
17472   30000
43818   45000
38438   95000
35127  113000
22878   38000
31958   32000
4414    36400
47793  140000
47837   55000
10346  125000
49918   89000
26623   37174
22821   50000
44093   80492
6928    60000
32280   45000
40431  100000
10281   75000
...       ...
2022    28000
27473   54000
1089    75000
27373   36996
45213   69000
33769   75000
48973   65000
25562   57000
32863   90000
25852   90000
5119    98000
16117   23362
26303   48000
20742   58980
26646  135000
44601   35000
27379   29060
28665   30600
39523    9600
30511   41832
13625   37000
28057  125000
32727  110000
23000   60000
24510   70000
12521  100000
3491    91560
48713  119250
41243   80000
23346  130000

[100 rows x 1 columns]
            x
16074   58320
49142   72500
45927   43000
46969   98000
29393   40000
32737   39359
34493   42000
36877  106854
28612  130000
18012   51000
            x
11503   65000
28152   93400
26040   44000
9600    39456
43161   50000
5035   130000
7712    65000
10775   60000
3461    31000
23982   98000
11097   78000
18418   33000
1719   132000
20521   88000
23559   26000
20788   34465
14042   80000
4061    64000
6732    90000
9344    88500
32122   40000
47430   85000
8357    54000
35971   48000
30857   57700
6403   116000
40347   66500
35241   90000
7583    60000
48223  180000
...       ...
37739   90000
3946   103000
1765    53000
18450  100000
41556   60000
35699   54120
36791   25000
3866    90000
41697   50000
43529   35000
31268   60000
901     60000
26578  110000
27639   60000
42962   80000
7092    72000
4423    43920
3781    53000
44469   62000
27305   33000
8242    16068
1233    79172
5255   135000
31188   50000
27334   50000
23758   96000
38242   48000
11950   55000
7190    85000
13336   55000

[100 rows x 1 columns]
            x
34438   15600
34710   34000
12121   42000
39636   62000
26490   68000
14083   30000
21812  160000
36806   95000
36759   40000
320     74000
            x
28441   68000
36619   34500
42265  160000
42186   81840
27247   42000
26460   65000
33578   49000
40106  100000
42357  130000
44880   50000
39640   38000
21024   29000
23177   54000
20741   42000
20832   48500
24192   65000
3308    53000
35973   85000
39434   85000
2686   120000
11873   95000
6580    44000
49591   40000
2504    70000
38602   50000
42585   80000
18791   80000
2688    90000
4859    56000
8567    59000
...       ...
889     85000
34466  110000
32549   85723
29131  100000
39323   87000
7838    90000
11048  106000
43093   55000
40281   75000
45693   68000
47895   65000
18502   45000
30753   48000
11568   68000
8136    92000
28385   85000
34001   65000
16115   77000
23160   50000
1543    92000
20992   36000
29273   58000
24935   60000
21302   63000
37536   85000
22163   65000
23841   53000
45022  100000
178     71000
9235    70000

[100 rows x 1 columns]
            x
18393   60000
23060   35000
44611  100000
6088    94000
38082  150000
10957   62000
20704   75000
48739  130000
40350   33744
4325    94000
            x
25358   81000
2129    68000
38303   45000
43105   50000
7693    94000
41031  100000
2418    61000
6443   125000
37366  174756
18706   50000
11129   36900
18451  110000
25271   53800
44297   60000
4111    30000
16796   40000
17158   26400
26638   36000
7883    70000
17006   50000
44655   90000
38709   60000
45465   52000
20025   84000
4319    27000
14438   89000
12624   58000
28516   75000
37281   43607
15417   57000
...       ...
13787  129000
35975   52000
24407   40000
8588    54500
14397   46000
38757   70000
18149   30000
44251   90000
44193  121000
38255   50000
12641   88900
38627   50000
3158    80000
3144    54000
34809   57000
13582   66300
43268   75000
49415   60000
20953   55000
48220  128000
38878  125000
27470   95000
26653   25000
49458   60000
41343   93000
27312   55000
18314   52000
30725   62000
17899   95000
38155   56000

[100 rows x 1 columns]
           x
35119  33000
30963  60000
366    80000
29277  78000
36624  60600
31687  76000
26457  33000
19256  40000
27724  65000
38303  45000
            x
12288   72000
26432   48000
39516   50000
15989  102000
29065   47000
7107    75000
21740   60000
8578    67000
39790   74154
44596   33800
12387   65000
13874   80000
32973   80000
3425    35656
16219  125000
13199   62000
35872  120000
30991   38000
41420  175000
4794    52000
28916   82000
37501   90000
1342    96000
26228   19392
49682   72000
25257   21000
44373   18901
13172   73000
34808   40000
43327   95000
...       ...
32483   53000
7860    62000
12064   86000
24370  108000
12682   28000
18564   60000
20435  159000
17127   39000
44463   70000
2019    53000
43922   81000
47649   90000
49865   42485
45148  110000
38518   60000
21065   45000
43368  110000
20934   85000
10285   71000
18396   75000
16690   70000
6142    45000
10880   68000
18864   80796
23055  130000
8461    61500
30592   55000
48123   56000
31910   66791
49703   72000

[100 rows x 1 columns]
            x
24741   55000
45900   80000
34129   64800
14343   65000
16407   57500
40802  146000
14327   60000
13002   82511
17676   60000
220     80000
            x
1261    94000
11031   85000
5201    22000
41924   65000
9879    78999
26898   89000
26120   82500
17145   40000
43945   70000
23234   44500
8827    71000
22006   82000
24010   50000
45166   46000
3990    76000
11518   40000
13873   70000
38310   37726
22075   38000
22783   30000
38905   87400
19648   68000
35362   54700
21813  120000
22410   65000
42041   50000
8668    40000
47208   70000
23048  190000
27309   61000
...       ...
46614  175000
7457    55000
45047   75000
44392   64000
29938   43000
25119   60000
40264   52000
41381   76000
43940  125000
12210   26000
17642   40000
19078   60000
49408   42000
28901   60000
34458   95000
17323   90000
5387    90000
38362   80000
40494  110000
35246   51000
22421   37000
37679   44000
21140   50000
32839  170000
3409    54901
40678   80683
49556   64000
23011   45000
23084   41000
48789  190000

[100 rows x 1 columns]
            x
13797  120000
41663   92000
41485   25000
46407   73000
29595   47904
3178    45000
29934   80000
560     47600
37935   65000
41102   53000
            x
23538   28000
22750   74000
25665   33357
43362  105000
42051  114000
15344  110875
2524    80000
32303   55000
38843   55000
40139  117000
18754  115000
23250   53000
6888    60000
7317    55000
1081    36000
29980   35404
43383   65000
44190   72000
30203   47000
6280    68000
21823   53000
16468   60000
814     54000
12399   60000
8203    75000
16883   55000
19774   90000
40443   94000
17464   40000
1378    48000
...       ...
39115   36000
23609  120000
33821   55000
6888    60000
28438   67332
37118   55000
47592   32000
10978   65000
35160   40000
24039   93000
7133    36000
24652   98000
6825    60000
31620   43000
21836   55000
13308   51500
14741   85000
911     85000
11041  150000
14163   59196
17894   61000
14849   83263
32149   91200
26020  129000
26360   50000
16681   44000
43607   48500
44756   35000
11460   80000
27365   84000

[100 rows x 1 columns]
            x
1259   111600
18530   90000
20562   75000
49905   45000
8383    52000
33616   65000
39042   64000
18970   30200
45479   93000
43485   78000
            x
427     60000
39257   62000
12884   65000
48774   53000
12437   73000
44607   95000
18709   57738
16442   48000
46529  100000
41885  105000
2093    35000
10837   91000
14426  105502
45319   27864
48533   40000
13178   72000
12008   72061
9244    28000
4199    90000
1751    80000
41391   36000
32380   72000
30882  156000
22288   30000
48505   38000
35470   62000
29643  126000
33814   30000
27228   64000
38004   71500
...       ...
13423   49000
36987   80000
15789   53000
20339  135000
45846   95000
45313   90000
33828  135000
26989   36000
20147   51000
1903    30000
3064    70000
4581   135000
28760  114000
42087   32000
30195   93900
48584   75000
40008   45000
12419   70000
13784   60000
13636   40000
11083   40000
2892    95000
26502   72000
40649   28000
40424   40000
34292   60000
36500  115300
22264   71000
34599   29000
45561   48000

[100 rows x 1 columns]
            x
31733   47000
12825  120000
5896    63300
44817  150000
24670   53280
346    168000
8854    50949
40992   55500
37724   40000
2846    43000
            x
18229   45000
38998   20000
30967   79000
32668   75000
23989  120000
23374   54492
15135   61755
7104   110000
3402    62000
30533   24000
25952  100000
44724   95000
30722   18000
7389    55000
13823   80000
40084   50000
31449   32000
19586   68000
16266   90000
30202   87000
24307   60000
26748   53000
13907   66000
5559   107004
25020   48000
21102   43680
2857    88914
10205   80000
8613    50000
39184   76000
...       ...
38329   45000
45981   43000
9384   149700
2100    50000
47838   30000
27121   86000
32452   39000
9406    75000
16210   25000
16809   33000
11543   90000
35831   25000
39254   78000
17158   26400
24382   67000
20008   85000
38616   55000
13502   57000
5209   115000
7832    85000
5159    43000
48156   25000
28401   27000
1574    19200
16171   60000
40863   76500
11055   80000
27142   58700
909     29265
24435   96000

[100 rows x 1 columns]
            x
19198   48000
34258   55000
7488    32000
16564   57600
24638   38000
18991   60000
7041    85000
40811   60000
46004  103000
39215   67000
            x
14516   63000
19999  113000
7882    50000
43041   80000
15571   64500
519     40000
30023   50000
12237   35000
4604   107000
35783  120000
38972   55000
30405   35000
5673    50000
38521  135000
7767    60000
12259   40000
28749   47000
39212  100000
32425   38000
6864    85179
33359   45000
17771  120000
24066   30000
1175    42000
45694  120000
4453    73000
34230   45000
10992   31000
28637   53000
16766   50000
...       ...
43048  108000
19737   45000
48459   65000
47085   45000
6076    90000
4452    31080
706     80000
36479   94000
42009   72000
10187  123500
49582   50000
31647  115000
3465    85000
38092   40000
27063   90000
46588   39000
22853   49898
47322   70500
39976   18500
22733  125000
14546   60000
6736    54000
5153    46000
3457    46100
37148   43350
45796   47000
20298   52500
38573   71598
23259   32000
27832   30000

[100 rows x 1 columns]
            x
11129   36900
14031   64000
19895   49899
29617   43000
5607    30000
2107    46800
11045  100000
1698    52000
21849   47000
1375    66000
            x
49171  165000
31803   80000
3419   136000
21348  165000
48031   50000
32465   92000
42498   50000
14740   40000
40277   30000
36614  105000
36916   13200
4193   130000
4177    89000
23758   96000
20592   44000
17299   93000
27937  105000
29104   72000
8026    82000
9576    65000
38175   70000
18683   31000
26117   95000
38859   60000
49898  130000
2435    32000
42133   35360
46831   64000
17824   99700
28984   53884
...       ...
11453   23000
4379    32000
32756   20000
34240   54000
30894   68000
1127   124000
49461   45000
22282  150000
25191   40000
23071  120000
10341   52000
8308   120000
15448   42000
40409   72000
38      65000
44526   52000
20579   48000
25907   60000
25905   76000
19594   84000
27225   45000
25753   23500
27404   80000
6540    73000
35194   57000
12383   70000
32190   25764
1862    50000
4568    65000
39245   70000

[100 rows x 1 columns]
            x
24656   32448
23210   97540
46715   61200
18608   38117
11735  100000
7748   121752
25017   38000
46407   73000
13746   58600
45      45000
            x
22382   47800
29548   80000
4555   117000
32693   75000
39146   91000
34808   40000
29114   36000
13917   39000
45085   90000
47160   55000
40573   60000
42252  144000
21947  110000
4766    56000
49503  100000
4349    32000
5650    40000
3542    27040
10140   52000
25404   90000
25426   55000
33047   50200
11585   54000
30161   80500
28914   30000
46014   45000
10528   55970
24594   24500
13512  107000
8627    90000
...       ...
48416   59000
25135   20000
47351   72000
10278   43000
34962   91000
43509   42000
43215   85000
7667    31000
30505  180000
42546   31320
33876   45000
21039   62920
40035   47740
25091  110000
5630    70000
38330   52000
20293   47000
37040   41000
48553   82000
14846   70000
10603   35000
48527   48000
46083   54000
47787  150000
31871  130000
45893   42000
37167   73000
13409   70000
8510    80000
48914   60000

[100 rows x 1 columns]
           x
21555  64822
23235  92000
17124  72800
33263  34272
6368   42000
40870  65000
46086  70000
35411  78000
9180   38480
2322   65000
            x
29778   48000
41023  120000
17266   35000
8928    55000
9683    98000
9011   100000
21282   40000
6967    39830
37601   25000
8205   130000
33701  105000
25079   92000
33127   29000
10861  110000
3072    72000
37994   50000
6179   105000
32154   50000
35254   61000
3110    55000
113     45000
44313   50000
39374   42000
14537   55000
19072  130000
5444   102000
8465    47256
10436  100000
26764   45000
38660   57000
...       ...
22916   80000
12012   40000
15573  105000
14481   43000
8446    60000
15277   12000
17449   68500
41278   75000
40463   38000
16679  115000
10438   58000
3354    45000
42688   30000
28868   35000
33800   46000
41815   45000
22110   13500
21902  101000
32850   70500
14031   64000
38858  100800
5879    70000
43346   93000
4916    52000
12614   54389
32192   46000
33579  118000
33856   65000
44326   60000
10453   90000

[100 rows x 1 columns]
           x
37983  40000
19842  58000
4865   75192
23226  44500
21435  19000
15738  55000
34275  40000
44130  41000
41470  55000
28771  65000
            x
11109   75000
44561   66710
39055   70000
12972   82000
28229   95000
21996   25915
47536   31000
17626   30000
33927   52000
30750   60000
28198   80000
29995   75000
38333  131000
36655   33000
24233   48000
46170   85000
15091   38000
1418    33280
18854   63000
35854   25000
24811   59200
32496   75000
28413   50000
4434    88000
20588   43000
32290   80000
32798   96000
48529   33600
7491    24000
2493   190000
...       ...
49959  115000
22026   72000
26685   86500
47962   75000
46880  150000
4468    76700
17896  102000
41149   55000
21779   50000
8085    60000
6287    68000
36394   40600
16816   32944
27317   90000
47219   48000
39156   12000
45405   53000
32039   49000
11134   37000
44298   60000
32415   62000
11236   40000
29678  140000
44749   42000
23317   87800
19215   43000
47544  108000
22306   33000
5063    40000
31772   92000

[100 rows x 1 columns]
            x
12540   63000
46800   75000
34310   56000
17545   55000
15938  106000
6804    48000
3       78762
28031   60000
42849  117000
28206   50000
            x
43999   60000
21144   78000
9756    41000
29449   43000
28105   79635
672    105000
35129  170000
17635   42000
37389   64000
7984    45000
28532   48000
41147   73000
15320   45000
30388   59000
38329   45000
18275   38000
43203   55000
24226   65000
8958    78000
6388    50000
43693   80000
11474   41000
35942   55000
3786    45000
49415   60000
41510   90000
3822    80000
13385   28000
24205   13200
17243   65000
...       ...
3343    69000
84      45000
4656   105000
29366   38000
6835    80000
11044  105000
8163    42000
6070    95000
29082   30000
40022  125000
9630    70000
26322   70000
22852   60000
12448   85000
21754   54000
17225  130000
38112   75000
27163   83000
31987   63924
24863   42000
12123   63000
21602   92000
17628   66000
12689   70000
15219   55782
18430   46256
33058   30000
17118   55000
1088    98000
28288   46000

[100 rows x 1 columns]
            x
36531   38000
10113   27000
8070   108000
48809   40000
2038    75000
32473   30700
27432   38500
14722   36000
27955   49000
25248   66000
            x

           x
24814  54000
570    64000
48960  30000
25819  70000
11451  75000
21711  60000
7331   36000
26819  58000
34930  91000
24499  50000
            x
137    122000
42557   38000
32304   39000
12926   58000
1669    90000
34374   85000
25865   38000
43148   68000
48843   55000
2505    70000
5762    75000
7595    99000
8659   113953
40763   75000
9549    87000
20170   52000
4107    21000
19818   25000
30825   65000
46186   51000
25302  175000
30188   45000
7228    29000
23484  170000
6279    56500
22783   30000
16216   75000
37660   88000
31465   41000
40389   38500
...       ...
41941  115000
34013   62000
42205   22000
42595   82000
28092   40000
13563  100000
25243   50000
7804    56160
49044   55000
34877   50000
42744   67675
35360   48000
47237   80000
12731   74900
35172  125000
10041   59000
26984   70000
31507  150000
30484   38000
31485   35000
16106   45000
21214   90000
1351    65000
31218   90000
17873   45000
16129   19200
18535   48000
3009    52000
765     32000
40811   60000

[100 rows x 1 columns]
           x
37672  42000
36089  47863
14244  55300
12384  90000
7469   61000
24923  40000
42312  75000
44764  80000
5745   47000
38304  87000
            x
29673   64000
9526    85000
47786   77000
33975   61000
1461    70000
13363   50000
3442    70000
29197   66230
38429   69500
11743   57250
21228   60000
43457   40000
14379   57000
36306   40000
5545    93000
47450   85000
3056    73000
3150    24000
45721   47000
4954   107000
18612   73539
10719   54996
11287   24000
43920   45000
17602   50000
37641   30000
6995    70000
20744   50000
24708  125000
33695   24000
...       ...
40207   80000
46958   45000
5664   110000
38028   93000
8593    48000
24718   42500
5406   120000
30236   33000
33494   15000
25526   70000
45938   85000
44000   80000
40354   78000
42333   35100
22133   90000
15778   41000
41670   78000
20488   52000
15367   62004
8393   105000
49327   75000
23847   60000
15507   55000
21975  145600
48950   29804
18911   46824
22211  140000
45717   60000
19163  100000
7739    29120

[100 rows x 1 columns]
            x
10929   42487
10170   80000
34493   42000
18078  111000
37736   80000
43963   95000
36308   50000
10415   70000
40373   39828
44341   45000
            x
28793   55720
40973  105000
23018   50000
32039   49000
19183   45050
20854  103793
39078   72000
37558   67000
16442   48000
33477   73122
7683    40000
23825   30000
38635  114281
12695   70000
27393   60000
5748    90000
34458   95000
4143    57704
7457    55000
45087   98000
46      25000
29198   60000
19891  130000
7525    87308
5601   100000
24286   20157
30167   40000
377    114589
19423   70000
18353   55000
...       ...
18735   50000
10922  160000
34140   57000
12360   21000
28348   48000
43257   37000
19313   40000
25850   41000
49160   30000
39367   40000
35953   47000
5450    52000
38590   44000
27569   72000
20982   34250
6817    65000
10423  110000
5560    75000
12560   26400
27017   52000
19343   66000
20813   27040
4465    49749
1105    96000
13804   82000
37410   60000
23198   42000
42577   60000
45563   50000
49665   22599

[100 rows x 1 columns]
            x
18354  125000
32455   80000
43310  100000
29843   38000
43583   49431
45965   85000
44769  174000
31841   52000
3077    38000
9491    40000
            x
25279   32000
15512   54000
47741   62604
21445  139000
16113   69500
38219   36000
19527   86000
34449   63000
1642    64000
4158    52000
18941   45000
35278   45000
19044   52000
34822   89000
19554   50000
15831   87000
38367  175000
30473   95000
23169   50000
13901   90000
11594   78000
40086   93569
44014   70000
48200   95000
18434   90000
43867   46500
48180   25000
32390   82000
7673    72000
17176   53000
...       ...
17918   30000
2819    97500
25483   67000
15332   50627
36555   55000
33858   57200
23138   48000
26482  100000
38952   91000
4293   165000
6456   120000
20477   25000
13613   48880
18918   45000
3315    60408
39937   40000
16165   90000
6195    36000
21644   38050
5271   120996
1492    75000
29573  150000
7684    45000
7771    52000
27909   80000
34346  150000
27083   92000
8585    68250
44441   30000
7074    62000

[100 rows x 1 columns]
            x
34790   45000
40582   43000
31631   60000
377    114589
47906   35000
3345    90000
47179   78725
15384   38000
28487   60000
719     59850
            x
9595    65000
49622   62000
16495   45000
22126  115000
22824   85000
35436   45000
48237   42000
4059    45000
35696   10000
37099   48000
29038  102000
14181   68000
16292   74000
11912   40000
43252   36000
13472   55000
34650   40000
24955  140000
12106  100000
16252   55000
42497   35000
49111   80000
44173   49920
11365   19200
44622   50000
23545   61822
21170  165000
33983   32400
32611   32000
48849   73310
...       ...
41737  145000
34094   60000
38679   58000
44053   33000
49284   70000
19295   46000
19068   47000
13163   45000
48483   60000
22463   80000
40466  103000
38054  125000
43028   44004
16959   96000
16510   55000
28322  105000
29730   65000
36996  135000
44102   92500
46853   63000
982     47000
32185   75000
47990   40000
25563   95000
45283   93000
39714   22000
46975  143500
43129   70000
32816   65000
20573   97600

[100 rows x 1 columns]
            x
32103   60000
37228   72000
16495   45000
36383   25838
8651   110000
27848   75000
49119   28800
39070   75000
32123   59506
13140   60000
            x
41617   45000
36010  110000
14669  110000
22203   56000
16568  100000
10600   85000
41320   62000
16380   55000
41418   90000
24755   73000
6295    76500
35128   54000
35212   50000
45163   68000
23976   35004
8724    60000
25836   90000
16364   40196
2850    60000
47322   70500
22237  124800
9234    70000
5918    71074
9599   110016
22514   32000
20321   95000
1520    70000
29430   22800
16566  180000
42259   48000
...       ...
13414   35000
27146   45000
30676   48000
34726   54363
11302   60000
38812  108000
33968   89000
25602   58200
6473   140000
20971   60000
17586  130000
21977   49000
39405   40000
7056    33000
36547  167000
43677   80000
48078   52000
41423   75000
37895  115000
47472   42000
45895   31150
27690   33000
40873   60000
22759   50000
4017    50000
40979   97000
24968   32789
3958    40000
31219  106000
49311   90000

[100 rows x 1 columns]
            x
32861   56560
16021  115250
16595   84700
2754    55000
14946   30000
32593   60000
12323   42000
47758   60000
19070   74000
42451   20000
            x
31471   21000
47335   60000
34143  122400
34813   55000
23874   76000
49236   80000
2561    67000
32564   80000
49318   60000
2258    27160
26262   72000
27235   70000
4974    76955
7750    65000
20259   70000
29568  100000
37132   85000
39846   97000
22550   60000
32157   81000
3790    52000
34839  193000
48034   83000
266     90000
17867   59000
42780   24000
22102   89000
13066   38000
21371  115000
19372   48000
...       ...
29598   21000
14587   51500
15883   48000
12057   57000
43882   42000
2354    82000
16741   45000
21323   81000
6125    72000
18985   68000
10861  110000
26999   72322
37180   80000
32716   70000
9681   110000
18646  102500
15655   32400
14402   90000
24752   62200
35352   60000
31762   40000
49523  130000
17600   57000
44679   55000
20439   79000
33858   57200
43074   36000
48017   85000
48598   30000
13499  119856

[100 rows x 1 columns]
           x
1473   85000
24311  56000
48623  62000
5062   52500
25049  48483
39684  55000
45698  47000
38159  80000
21924  90000
35843  36000
            x
38015   35000
287     52000
37951   76000
25067   33000
15125   55000
11429   62000
24094   31000
39131   68289
29028  114000
48210   40000
49534   20000
48043   48000
9165    55000
38962   31588
20961   39390
10731  171600
44134   45000
7295    24840
41750   60000
22292   40800
18620   36000
25431  121000
30117   62000
5182    85000
37484  120000
11249   75000
48706   75000
34654   45000
41229   22000
13436   70000
...       ...
19136   75000
42742   80000
5302   105000
35800   35000
18584   48600
42355   60000
24479   65000
21817   55000
11268   62500
20091   70000
27233   60000
36329   26280
45006   85000
13774  108000
24047   77000
6815    95000
29538   70000
28125   63000
16477   45000
27008   35000
1784    86000
2073    40000
5068    90000
41777   33582
44496   38000
28106  100000
49518   66000
41565   26000
47929   98916
1614    68200

[100 rows x 1 columns]
            x
927    120000
38513  130000
39639   49000
5945    85000
36195   42500
29649  150000
41320   62000
49597   60000
49980  115000
13697   45000
            x
42367   32000
250     39996
45994   77000
12568  120000
33920   92000
19443   41700
25520   45000
23365   62000
2116   100000
724    142000
996     40000
32923   40000
15613   30000
7932    85000
45657   57000
1622    51766
27725   57000
25824  190000
24283   56000
15044   43800
49786  150000
10199  119000
41009  102000
22857   42000
20163   78000
15658   30000
42035   90000
2655    74000
34202   75000
23693   74000
...       ...
49724   77000
33943  105600
24560  100000
5337    61000
39771  105000
26232   75000
31018   57000
811    140000
22348  100000
22274  128000
17012   18000
2095    62000
9324    25000
8276    85000
36553  100000
49892   30000
22159   55000
6652    40000
40015   57000
39670   25000
12873   50000
2900    55000
7293     9936
34240   54000
1733    62400
48873   85000
25822   30000
22923   24277
47780   75000
16070  104000

[100 rows x 1 columns]
            x
19974   44000
14278   90000
22103   85000
33456   80000
45992   68000
25114  145000
18785  129000
22766   82000
29423  120000
40769  115000
            x
40890   45000
11462   56706
29360   64000
27952   28000
3585    57000
3727   150000
3974   108000
35836   55000
9483    40000
13636   40000
19724   95000
33398   43000
28318   21500
48663   85000
3139   100000
23369   67000
31057   50000
49842   80000
4881    62000
24542   57000
19655   90000
1477    51540
31692   71600
47008   80000
23982   98000
42220   21000
24262   64000
17329   26000
36516  125600
27658   48360
...       ...
32025   46800
10114   45000
13062  110000
13906   60000
24545   24000
26796   32000
27875   89000
4638    89000
47827  105000
27883   95000
30207   83000
34737   40000
27130   55000
2322    65000
20811   70000
42550   40000
39857   60000
26063   67000
10467  160000
32568   30000
32365   31164
48847   63000
27368   46000
17519   24000
21091   60000
14678  117000
5173    58000
45495   80000
44674  162000
29916   75000

[100 rows x 1 columns]
            x
7329    14798
43915   36700
10233   43000
49026  110500
2253    48000
38679   58000
6217   131250
15517   60000
47459   68399
37181   60000
            x
14413   25000
10064   23500
36444   67000
49357   13000
19492   97500
23436   23000
37348  156000
37075  109000
32767  130404
24832   40830
43101  120000
7541    73000
44021   48000
20659   19000
23230   46000
42393   50000
32576   46000
16191   68000
36573   76000
34974   57000
39143   82000
4276    31000
29794   69000
11787   33600
15457   50231
40343   75000
8900    26500
30080   37500
2321    40500
35629   60000
...       ...
30959   97000
37633   29112
44445   30000
48777   60000
2040    50000
14904   55000
47092   30000
10979   65000
23884   36000
27743  100366
31990   55000
17605  105000
9507    90000
18812   31361
11771   83500
47650   40000
39542  110500
28363   26500
18449   65000
36223   80000
49853   97000
1690    78000
31367   42000
39175  111016
20590   78000
23201   32000
48390   58800
32433   53000
43771  140000
41565   26000

[100 rows x 1 columns]
            x
6388    50000
249     96000
12536   95000
45165   90000
32383   21600
7798    57770
24882   57840
33737   26000
30129   52000
25418  113004
            x
722    125000
16005   79500
571     80000
10514  110000
11622  195000
27393   60000
13588  100000
49689   83000
2975   150000
17306   22000
13305   40000
4713    88000
34380   72000
45827  104600
8460    75000
27874   25000
992    100495
37714   66000
34628   22000
20931  128400
48017   85000
26851   31050
29955   70000
4285   120000
33280   50000
24435   96000
46401  137000
29016   80000
5365   105000
27930   16272
...       ...
19618  132500
28171   58427
36875   60000
1008    33600
26571   45000
32688   24000
26897   65032
22247  140000
34750   63600
30733   52000
10047   30912
45609   55000
32499   60000
26711   53500
25318   63000
24077   49000
42702   37000
28026   70000
7325    40000
33048   82000
34420   87699
49948   48000
47763   50000
305     38000
4817   180000
38573   71598
26753   75000
47578   48000
31688   72000
48159   46500

[100 rows x 1 columns]
            x
8303   105000
19653   42000
43900  153300
7245   100000
6092    69500
3242    70000
22945   86000
5484    50000
15618  110000
16093   70000
            x
2911    38400
3970   100000
12726   59000
36229   90000
49616  142500
22702   55210
28966  150000
1413    39996
26870   54000
3173    40000
639    180000
36568   80000
3077    38000
39543   75000
31955   19000
14939   47000
20021   32000
22612   45094
3909   100000
44138   55000
3997    68000
28139   70000
14271   62000
44036  117200
18094   99500
24894   68000
38418   60736
35769   72000
6930    62000
37326  175000
...       ...
30046   94957
25399   66000
12800   80000
22006   82000
26169   75000
35853    4000
8895    44000
42243   61000
16235   58000
37355   49000
5780   125000
24758   40000
28581   35000
25067   33000
40427   38000
18976   30000
49086   50000
27289   30000
1904    51000
46408   62500
16778   60000
40329   72000
14051   94000
10806   44000
16284   45000
36223   80000
27834   60500
28479   46000
7923    26316
1275    85000

[100 rows x 1 columns]
            x
33342   51000
47833   88000
20731   45000
43468   60000
31888   41308
27956   95000
23217   32000
28602  130000
12392  127512
2095    62000
            x
3990    76000
8217    38000
5829   100000
49891   64000
38819   95000
15102  105000
22458  125000
30380   74000
44997   47000
38092   40000
8911    51000
47024   27000
27453   42000
42920   46000
27931   65000
39800   82000
26986  137000
21368   80000
30532   45000
34519  158000
11124   92872
46470   45000
39104   55000
23523   37606
35811   35000
44930   35000
29390   72000
9836   145000
3429    58000
27647   78000
...       ...
3717    92000
3532    39000
45782   43800
8534    80000
44801   40000
36070  110000
42742   80000
21834   30000
3039    85000
31821   95000
40432    7200
46229   30000
37805   45000
47078  175000
28855   65000
46870   26200
34812   90000
45904   26500
39819   70000
33053   64800
18655   35000
46803   45000
45099   32653
30372   40000
34409  140000
49970   66500
46645   53000
5724    26000
46468   81000
4060    66482

[100 rows x 1 columns]
            x
39875   40000
35751   40800
1491    33000
7077   138000
21187   47300
37442   70000
10234  140000
16265   53337
33203   36000
32855   84000
            x
8631   117000
45359  123000
6475    30000
30057  112000
26875   76292
4584    45000
257    100000
7396    40000
24865   45000
3987    45600
8780    21600
23411   55000
3477    56030
32040   76300
18549   48844
24524   68687
11008   53000
20296   55000
22928   46000
3273    50000
12970   45000
30459   38000
68     102000
22597   55000
45349   40000
7852    35000
13671   38000
23143   18980
18677   35000
30213   32000
...       ...
41571   40000
11595   42000
49630   75000
22847  126000
6346    85000
26145   78000
8191    95785
11364  108000
33550  110000
2283    18333
24269   50000
30744   71000
17149   75000
17675   26000
40672   70000
25440   90000
17955   46000
28193   55000
34848   70000
21745  107000
12926   58000
4172    65000
1019    60000
16208   29577
15790   40000
7684    45000
46547   35000
48402   40000
1649    41000
22018   98300

[100 rows x 1 columns]
            x
9055    65000
4027    72500
22092   85000
2839    47183
28468  107000
39898  120000
5374    35397
28659   40000
254     52000
39247  180000
            x
43542   27000
34812   90000
37062   67500
5231    40000
34273   72600
8127    56000
35948  106000
31847   38000
11686   98401
38579  125000
14095   75000
44837  105000
37713   53000
18308   51000
31740   42000
13046  120000
33984   50000
47328   90000
41898   80000
18078  111000
48218   41500
41318   99586
21264   82500
12746   45000
19204   70000
27832   30000
49673   91520
27853   80000
46049   70000
10516   44219
...       ...
46227   60000
43845  175000
15382   65000
41129  110000
39783   40000
26703   40000
42019   60000
8378    60000
7217   127000
15763   63000
42437   62000
11990   50000
10670   42000
38018  117000
18858   72000
6183    61000
15564   55000
27957   60000
33586   45000
33807   65000
33614   84000
12829  193000
16600   67942
16047   85833
28499   50000
49144  152000
41657   56000
46775   21000
37880   65000
4504    90000

[100 rows x 1 columns]
           x
41050  65000
45356  45000
47449  48048
10200  55000
8502   55000
13637  80000
46621  36996
21280  20000
26669  55000
48383  48000
            x
30618   45000
34717   56000
19157   60000
3868    64800
46080   48000
19741   55000
37841   50000
47161   42000
38158   62000
7581    82500
47333   28000
33445   89400
46120   48000
35222   63800
23865   55000
23681  110000
11772   42000
36288   66000
28939   72000
14796   40000
6262   100000
8156   103000
47979   50000
38195  100000
41427   85248
39776   40000
6940    40500
25090   62500
9146    75000
35061   67000
...       ...
1587    58000
4728    67000
41881   75000
4329    65000
20411   46000
33378   39000
4074    56000
46737   82000
31932   65000
39850   23500
34813   55000
19659   42500
27307   52000
46483   39000
39722   65000
22920   16000
25426   55000
1358    42000
44640   42000
3572    72000
20226   95000
36301   65000
27623   95000
42150  140000
47      84032
37520   85000
28232   65000
13028   75000
27063   90000
33972   65000

[100 rows x 1 columns]
            x
24609   45000
23788  175000
20647   60000
42647   55000
24279   37167
17189   75000
44913   63200
39343   62400
46039  100000
10189   52000
            x
42096   90000
13598   45000
47547   45000
9852    81000
47036  110000
8852    83000
37796   70000
30703   37000
31511   66000
6585    60000
48197   53000
3125    53000
26684   87000
35967   43000
4971   104000
44628   70000
14980   36000
12239  135000
20850   32000
16143   76000
35963   42000
12999   50000
42647   55000
21646   78155
5666   125000
15868  180001
5876    57500
1316    60000
4896   159883
7624    45000
...       ...
6637    92000
49382  130000
33110   32000
2978    62400
38623   68000
29660   30000
5535    20000
42119   40000
10451   55000
48725   76000
40297   75000
41456   80233
26533  160000
38741   60000
48055   65000
31242   65000
14140   60000
5956    27000
37209   38000
49006   36000
48877   70000
21989   52000
20446   90000
11525   75000
9464    63205
13652  160000
9952    54000
35687   32000
10803   24000
33096   48000

[100 rows x 1 columns]
            x
47920   75000
40122   30000
46452   77000
2349    22850
25014   60000
43872  137500
14272   55000
26527   34000
21818   78000
22367   40000
            x
35965   40000
12456   50000
33006   67000
2819    97500
8931    36000
33592   80000
46305   78700
5425    67000
39314   92000
46841   32000
43566   53000
40022  125000
33757  130000
23495  163000
30740   45000
14392  120000
15557   35000
31278   85000
3662    82500
15952   76409
27328   71000
4619    80000
15754   90000
716     72000
22307   56000
7650   100000
37566   53000
49546   40296
20332  100000
35244   42000
...       ...
14442   93000
23445  115000
10610   69000
32486   66000
21797   86000
41479   67163
2611    74000
4009   120000
28762   73000
23523   37606
22662   60000
14278   90000
16049   85000
35561   85000
39789   88500
12093   82000
46558   80000
15892   45000
28746  156242
46221   58173
47780   75000
11689  180000
14813   54000
21349   62000
30062   50000
24127   90000
11689  180000
40066   50000
12894   30000
45744   28800

[100 rows x 1 columns]
           x
39978  58000
29320  99000
33995  29000
47678  40000
7337   45000
14901  70000
21656  42500
30843  93200
23729  60000
20040  37423
            x

            x
35444   30000
42736   40000
15843   33000
19     165000
9588    75000
20398   57000
30886   55000
38646   40000
3514    45000
47705   50000
            x
1119   130000
16574   50000
44659  120000
10908   87287
20478   10572
13568   85000
29651  100000
30010   76000
24134   62000
32302   55000
6176    71500
36509   85000
18830   72000
23563   38000
6256   152000
45965   85000
10723   78630
7330    29350
25944   82160
41834   40000
8062    90000
17647   88000
36469   27000
47728   45000
29761   70000
29966   29900
2704   180000
32731   55000
1932    50000
42723  115000
...       ...
23226   44500
35977   48000
15139   60000
31074   81500
41841  120000
2142    32500
31619   50000
12671   60000
37598   40000
28103   90000
11729   45000
27572   77000
32415   62000
14564   50000
82      76728
43546   95000
5036    60000
25772   66000
4800    58000
14418  101000
33442   95000
10248   61000
43133   33600
43867   46500
43334   85000
30891   63000
20430  110000
41245   87375
12749   50000
33550  110000

[100 rows x 1 columns]
            x
27404   80000
25800   32055
44856  120000
27666  118500
4382   110000
10405   85000
15545   60000
7414    22000
17694   60000
5275    42000
            x
2648    95000
23448   60000
10051  140000
39320   56000
32717   48000
31427   67500
19671  140000
6292    53000
29314   12996
8181    99000
6904    35000
33936   31928
19229   68000
6630    98000
22340   58000
46836   28000
27308    9600
46324   57219
16371   73000
33174   60000
26680   65000
25152   90000
26251   33000
27853   80000
5007    26000
41134  125000
43732   19200
48092   19120
3468   120000
36638  100000
...       ...
49043   40000
11034   50000
11608   85000
14026   90000
23395   65000
35107  134000
16797   40000
23771  180000
44822   97000
19745   29000
514     65940
9720    26000
31749   36500
29509   61000
43886   72000
20941   80000
46601  166000
41489   72000
30646   38000
5869    32000
5201    22000
46872  120000
43192   34000
36101   45000
18779  101233
28091   40000
27623   95000
847     52000
8933   105000
33904   52000

[100 rows x 1 columns]
            x
24387  112200
35528  105000
5597   120000
27824   35000
11110   50000
47678   40000
31288   38000
18149   30000
34013   62000
29271   30000
            x
43003  100000
10237   53000
7357    62304
48693  108000
26241   72700
11972   20000
36058   41184
47252   74000
35443   67000
42562   45000
11053   80000
46699   28000
9345    70000
15642   71000
41546   40000
19367   40000
39786   92000
37079   78000
25916   66000
38784   35000
30114   80000
5067    55000
14471   32000
31078   61000
18454   70000
5056    67000
29243   50000
48620   70000
25227   50000
33507  110000
...       ...
14530   86000
37812   75000
32878   18372
26561   42252
45828   27388
27551   43000
28904  125000
27218   75000
10694  110000
44369   50000
8787   100000
5750    45756
33871   92000
24512   40720
37208  100000
2249    95000
42950   34000
25889   25000
37520   85000
24023   64800
6282    73000
32634   47000
35835   65000
36340   63000
2377    82000
37731   45000
2065    86000
42555   71200
3885    80000
11040   45000

[100 rows x 1 columns]
            x
862     53000
32472  120000
37104  112000
9675    37000
15125   55000
3370    44000
11756   43000
11824   91936
35618   48701
3470   117500
            x
16028  120000
9280   100000
26260  116000
36266   20000
31469   44116
27132   60000
48338  108000
7391    24000
10468   85000
39256   55600
14564   50000
30094   60000
17605  105000
40856  100000
44982   40000
415     86348
18181   40000
20011   70000
45116   65000
3181    60000
28641  121000
7142    72000
34414   30000
48364   50000
41627   28000
4536    28000
32979  128000
14560   58000
45024   98000
14425   85000
...       ...
7073    51000
15734   25500
19846   60000
37024   58000
35129  170000
24326   56825
3465    85000
31849   41123
19396  115000
48093  100000
26115  195000
8620   150000
46416   40000
27842   76494
13710   54000
8810    30000
33983   32400
30719  100000
17270   50000
35444   30000
12468   56000
33869   70000
17616   39520
42169  123000
42669   39475
35890  104000
47315  171000
22882  135000
48082  105000
41430   45000

[100 rows x 1 columns]
            x
26430   80000
1504    40000
49793   52000
27225   45000
2607    61500
43614   41000
37417  180000
49376   54000
19842   58000
17836   65000
            x
45817   99840
41410   46000
42773   80000
12641   88900
40502   54216
14869   55000
33352   50000
49661   34800
36534   42000
32062   50000
43031   44100
5994    55300
34764   90000
22297   55000
13902   31000
11944   89000
1652   105000
24529  120000
8119    85000
20511   83000
178     71000
36478   45000
28344  102000
27225   45000
28779   95000
32285   45000
42769  105000
19908   61900
17032   65000
11064   25000
...       ...
3237   100000
25619   48000
35244   42000
13594   30000
29303   15600
1248    65000
10727   53754
36658   55000
12689   70000
39858   33500
3498   119537
17222   60000
7495    70000
11500   50000
26812   55000
19363   70370
24122  110000
37022   70000
3039    85000
16453   30000
18708   26000
13153   25000
12016   94969
13835   50000
25283   59506
23334   71164
26921   50000
25302  175000
25380   35000
35177   65000

[100 rows x 1 columns]
            x
12676   46520
18812   31361
32402   30000
29528   40000
10671   50000
4396    65000
30313   82000
6353   110000
37098  137800
9182    90000
            x
27948   28000
43229   37000
52      85000
14436   24000
32148   54000
25157   32000
13076   88000
19940   45000
24943   40000
29585   70000
28423   43000
18713   48000
37296   15000
20928   53925
44615   35000
3548    78000
32814   92000
49376   54000
3730    50000
4601    80000
47635  110000
33886   42000
12433  167000
36316  120000
13530   50000
44400   43200
36189   59800
36314   80000
23323   48000
22857   42000
...       ...
27516   30000
40990   41000
17026   45500
7549    85000
4283   100000
16754   67000
47762   30000
37317   65000
23412   60000
13957   54600
23698   80000
46010   80000
33027   49000
27484   34000
11374  137480
32498   36000
35391   41000
21306   56000
27708  150000
33704   56000
7416    85000
33873   60000
16017  120000
1746    40000
20262   65000
4013    38000
6291   150000
34012   70000
9595    65000
10896  116000

[100 rows x 1 columns]
            x
45974   84000
31004   49500
26222   89000
12177  110000
4419    60000
32005   85000
2653    67000
36453   60000
47576   70000
8934    48000
            x
5741    90000
15703   33000
27614   50000
47072   20000
5721    61973
39484   70000
17106   94695
15728   76800
31000   55000
32982   68000
20984   28000
43977   25000
1467    84700
8872   100000
23843  130000
14336   50000
22364   55000
19657   35000
43241   49000
148     53000
44741   48854
6542   160000
19741   55000
27124   71375
29883   39000
41715   25000
1915    38000
47747   45000
9490    69000
36553  100000
...       ...
17303   85000
3449    45000
31238   37750
46571   90000
48966  110000
6037    65000
39012  180000
10626   95000
8716   150000
24482   42640
34132   65000
30344   40000
10800   88700
10176   66000
14456   51000
20770   60000
45255   90000
39272   60000
25486   68000
31505   55000
36845   51000
43983  115000
7478    82500
8070   108000
13977   54000
7983    40054
16459   12000
25948   34500
10767   75000
12840   78000

[100 rows x 1 columns]
            x
44152   32000
32696  125000
31656  102000
13687   72000
31469   44116
8238    50000
42928   55000
22950   98000
40297   75000
42267   32000
            x
15480   35000
33962   45000
40027   60000
45702   45000
49459   30000
40203  155000
38376   26400
510     44000
27077   75000
12070   83000
15285   60000
17884   66000
40270   60900
39477   45000
39172   57000
6151    39992
6714    97896
16444   30720
7639    36900
12807   29000
19199   54436
23594   76336
24643   75000
44973   31000
8129    75000
46209   70000
47151   57472
23690   79000
5766    32000
33220   53000
...       ...
44172  108000
24922   67000
16771   80438
9777    23000
17988   77248
39613   56000
40758  150000
42782   90000
32      40000
46224   45000
31997   48000
38315   54926
19414   58000
31738   36500
41013   45100
17868   52000
30344   40000
5028    83731
39504   28536
41516   90000
842     75000
44646   48000
7530    93000
28355   55000
42665   80000
47567   27000
19022   30000
47227   55000
49399   28800
6899   105000

[100 rows x 1 columns]
           x
6387   80000
48803  98000
42161  60000
48384  29574
123    60000
238    53300
15628   8652
26036  62000
31139  45000
20344  31000
            x
24899   68000
1319    71000
1787   128000
21512  115000
26900   58500
37586   64000
49376   54000
20540  154500
33436  120000
8353    55000
6269   175000
31837   29000
13901   90000
25033   40000
7236    70000
30126   40000
15314   79000
2229    98000
6208   100623
49045   65000
49106   73000
32901   30000
29826   53000
4982    63000
15024   44000
35415   60000
33127   29000
32453   65000
11168   54000
4747    50000
...       ...
25375   96000
30270   60000
30014   90000
12681   55000
31186   81360
9365    39000
8049    32000
19617  100000
49703   72000
45091   60000
18682   44000
48192  120000
44719   65000
40683   62100
41408   45000
5176    82000
4332    40720
38641   16440
43710   35000
41847   35000
20573   97600
25485  131000
25837  125000
43654   45000
32890   97500
35180   80000
21941  175000
45596   67980
12429   85000
7397   147500

[100 rows x 1 columns]
            x
34589   20000
25274   58000
20174   49000
28626   55000
5452    29500
3592    80000
40446  164542
22352  150000
47096   65000
14899   62000
            x
39886   84460
4246    87713
13548   59000
25179   45000
32078   31000
46821   60000
30390  132000
47508   50000
42791   75000
7233    58000
46667   80000
27700   37000
19562   29004
44299   52000
28884   85000
47012  111700
26821  184000
13370   68000
45223   39000
7961    95000
10803   24000
10610   69000
45973   81560
25001   79000
47963   21600
39608   52475
48020  125000
7391    24000
5083    62609
46375   40000
...       ...
42811   80000
24198  110000
170     46576
18296   48000
45266   11340
8120    30000
25436   27600
45226   64000
37540   57000
17650  130000
21385  120000
18966   70000
28636   60000
8499   101500
42072   29500
25249   31000
43174   27000
25156  108000
44565   45000
49026  110500
49666  180000
18175   55000
40119   70000
4197    80000
44357   97000
49957   50000
6855   100000
48010   50000
33515   57616
26477  122000

[100 rows x 1 columns]
            x
16889   52000
12003  119600
13308   51500
11397   30000
1751    80000
45968   35000
11208   31600
39711  109464
48616   34000
4749    60000
            x
20005   38000
5141   110000
46898   55000
29995   75000
48392   62000
13213   34000
8086   100000
14122   36000
39065   28000
8622    83000
17658   88000
36190   65000
8640   150000
2376    61000
22649   41600
20253   50000
46670   57000
28757   48289
33697  171000
1310    52000
17111  125000
36893   94000
6351   125000
1638   110000
42541   51000
37865   34000
16290   45000
15366   51000
11586  115500
22977   41000
...       ...
34723   39500
48032   81000
13987   50000
28081   45000
48672  107000
22044  125000
34320   75562
30549   83000
11153   74000
30250  105000
3772    36000
5192   103000
40870   65000
14023   47000
17979  150000
22021   43420
5317    85000
35355  130000
12613   25000
45853   32500
25865   38000
32056   80000
6538    70000
46754   54000
25174  110000
12759   70000
6948   172000
11931  103390
37511   98200
6616    30000

[100 rows x 1 columns]
            x
26203   65000
16982  125000
32599   50000
27872   45000
20601   50000
10980   60000
26831   45000
35241   90000
32310   48000
33082   28000
            x
30160   44000
2531   115000
33073   82700
2441    92000
26500   65000
26497   51000
28151   70000
29136   42000
33479  160000
14567   45000
28480  110000
18581   85000
40205   91000
35313   86000
12532   58000
2018    60000
22544   48000
41107   50000
18023   55000
9675    37000
25677   45000
42082   50000
22811   58000
28107  115000
23508   26000
45481   92000
37362   43000
37583  150000
23074   45000
6452    23000
...       ...
11046   55000
28581   35000
29498   90000
36352  105000
25725  100000
26484   58200
38497  175000
23732  112922
34264   33800
36920   52000
33748   91000
13998  173750
36564  110000
7251    54000
35597   75000
33863   68670
2853    37000
663     60000
22694   70000
10635   35000
43467   95000
18705   34000
25714   45000
7353   132000
13423   49000
28785   60000
807     55500
25743   54000
32106   49000
49317   46000

[100 rows x 1 columns]
            x
1384    13200
12685   24672
49040  100000
6961    84000
1335    58000
13478   40000
29896   82000
13314  105000
43250  105000
10401   50000
            x
26690  112500
45100   99000
18306   37488
13185   34000
47488   59000
28779   95000
39159   45000
34787   51000
18211   36000
30278   85000
18576  125000
49863   42000
36820   32240
32433   53000
31707   17280
14990   75000
49337   32000
47325   38000
2640   115000
38779   55000
5220    80000
18538   41000
9969    57600
12766   75000
30506   47500
1464    36609
32205   80000
21134   89000
38102   90000
19630   38400
...       ...
9420    32000
28112  115000
39530   48600
23568   55000
42835  120000
1657    55000
27792  120000
44382  104000
35443   67000
32931   47700
7716    40000
28161   35000
22477   60000
27162  123000
19204   70000
11525   75000
25493   85000
15052   67000
21628   69440
20998  128000
30209   42100
15120   64000
34157   55000
46677   35000
3409    54901
7160    55000
8082    85000
24797   89000
13837   79500
20722   66000

[100 rows x 1 columns]
            x
31832  118000
47188   65000
47146   40000
48863   65000
7015    65000
30882  156000
19635   24000
30717   40344
25697   26000
15373  115000
            x
21408   96000
26285   70000
15399   41000
1274    70000
2085    97862
32572   56000
44507   42000
48243   50000
22030   65000
11249   75000
4264    42000
32020   80000
14019   96000
19419  121000
27564   76000
34263   56000
7987    73000
20589   73500
24335   60000
18314   52000
40625   40000
26796   32000
20190   54000
42545  116000
28438   67332
25082   70000
36682   25000
45701  130000
39840   80000
33614   84000
...       ...
42709  139000
45890  186000
832     70000
38713   30000
15475   65000
48580   61000
46693   49000
4902   110000
28386  140000
42635   75000
11270  136000
31652   29120
18020   72500
27945   40000
33423   52092
33353   69446
22335   70000
30295   40000
3395    60000
27678   53000
33509   44886
30502  100000
9071    38000
1869    48000
7548    65000
32810   40000
33006   67000
46926   41000
11425  110000
2833    62000

[100 rows x 1 columns]
            x
10184   55000
32176   65000
8434    48000
22550   60000
27920   45000
32612   40000
16157   42000
4550    48504
38294  125000
29592   65000
            x
35804   60000
30450   42000
33911  115000
34673   41000
42662   52000
15780   20000
12394   60000
41230   70000
46347   67190
994     40000
11645   42000
37911   39783
4914    69072
17647   88000
18196   26500
41773   60000
44226   18000
34640   30000
33655   38000
20980   21000
9702    43000
27199   27250
21439   90000
39334   44000
13      65000
17850   65000
44194   20000
47753  100000
43618   40000
23938   75000
...       ...
43226   37702
37632   55000
18459   87500
23906   45000
4473    60000
14068   35000
35480   36336
12100  144000
23885   66000
35015   49000
5757    65000
6622   110000
11378   33000
8937    41000
48688   65000
17237   50943
31053   45000
25197   74000
33606   36000
25520   45000
369    110000
20125   80000
9804    50545
24411  165200
21519   68000
27362  185000
16950   54000
42898   85000
23433   44000
25111   60000

[100 rows x 1 columns]
            x
18393   60000
12063   54144
8612    45000
34788  119000
37769   80100
47045  160000
10276   45000
23592   85000
23556   59000
7990    55000
            x
7087    36000
19224   90000
16575  105000
34372   55000
1310    52000
21838   51609
9596    54000
21786   26000
4009   120000
7878   150000
26627   47153
15147   26400
38609   59000
29988   60000
5252    33000
16153  190000
36211  102000
42894   60000
40353   90000
5773    44000
17215   90000
1733    62400
4888   100000
34354   42983
21380   70000
16149   61800
4393     8000
28419   15480
43067   30000
2903    58500
...       ...
44306   80000
6808    62000
24511  120000
16882   60000
11796   68000
48041   80000
33094  105000
7190    85000
19065   92000
15409   65000
28135   45324
36214   49500
40866   40000
7295    24840
31142  106000
23739   75000
47273   72000
4440    87500
39225   75600
38825   58006
46318   65000
26760   57500
44159   86000
8959    40000
18391   25000
43388   95000
13946   43200
35699   54120
2663    45000
38852  120000

[100 rows x 1 columns]
           x
1256   47000
28682  65000
10516  44219
45124  55000
38558  95000
17372  36000
16279  55000
4377   28000
34981  63000
31220  92000
            x
40276   71000
35608   70000
12003  119600
32363  112000
951     40390
42395   54000
44103  100000
10932   44160
6086    80000
35526   49280
37528   55000
22920   16000
45986   50000
48084   52061
31360   51200
28406   80000
16713  119200
42376   88000
26019   52000
24135   95000
36753   40000
43504   58000
41736   62000
39457   60000
3937    80000
5348    68000
9095    75000
8429    65000
12029   65000
34297  102870
...       ...
20722   66000
35684  103000
21064   27000
8206    51000
16324   55000
24867   82000
13080   80000
41292   46000
13351  105000
5788   143000
26585   49000
49734   60000
11170   75000
18303   80000
30291  120000
5267    42000
42319   64000
30353   95000
11188  101000
45041   90000
45687   52000
36508   45000
30523   43659
34123   53000
22255   84000
11720  160000
17910   41000
47374  105400
31982   40000
15762   43000

[100 rows x 1 columns]
            x
5582    38000
48434   40000
3455    28000
3210    74000
9073    52000
28262  160000
23240   71000
37524   33500
20018   41250
10737  120000
            x
47348   37500
32585   40000
39786   92000
438     80000
11753   90000
3897   105000
41739   85000
29473   87000
29113   50000
7724    80000
24521   63000
22002   32000
37967   65000
47440   55000
35595   24947
13411   16048
29070  150000
17122   48880
3915    36000
24710  105000
23349   82000
34505   44160
33836   30000
4252    63000
45668   91000
23154   30000
37554   36000
10921   75000
33172  115000
34995  101000
...       ...
19804   50000
35583   40000
9320    40000
47869   98000
44697   50000
19953   30000
5498    39000
35543   41000
27615   72500
12061  120000
32548   55000
43212   54000
26895   96000
6434    86000
4863    53000
23427  150000
17541   40000
47553   35000
4508    56000
23530   71000
19628   80000
30368   85000
28435   77000
41174  100000
37573   65000
13924   35000
6393    56000
39475   18000
27800   50000
15846   89000

[100 rows x 1 columns]
            x
45999   24000
8135    34000
2407    32000
1428    30000
36073  101000
41788   56300
35210   46000
9357   125000
34120   27000
23159   55000
            x
44347   46000
33346  185000
8527    36000
28029   62000
35512   33000
26879   64947
12779   45000
26634   82000
12103   40000
31878  105000
25518  117000
29611   72000
33714   40000
25466   38256
22579   57000
26298   95000
42757   48000
24587   57600
32253   40000
6207    55000
47814   61950
44181  171000
46295   50000
20886  110000
13181   33000
46348   53000
5642   163000
38829  110000
33230   75000
27953   78000
...       ...
28816   64000
44290   61763
42285   70800
8504    77000
48687   76000
11221   50000
33208   43000
48774   53000
8162    60000
34795   75000
17504   45000
26001   94000
40152   53000
42348   49000
31671   45000
36902   75000
4886    60000
39873   40000
39969   53000
39669   80000
35937  105000
26368   53000
7000    33700
7448    86000
13781  185000
42716   27000
15604  105000
30326   52000
26278   36000
18229   45000

[100 rows x 1 columns]
            x
45135  143000
21709   55000
11476   39000
38157  150000
45572  115000
33963   98600
30240   50000
44259   69000
19701   40000

            x
28043   35000
8211    75000
20079   59400
41603   71000
33693   48000
9032    45000
24408   62000
8063    78000
31722   37000
21143  120000
40913   65000
34993   59904
14677   40000
23284  114000
40968   50000
6624    52595
41646   83000
6756   130000
142     80000
2423   171000
32738   62000
36136   90000
8119    85000
45808  157333
24156   65000
8986    80000
28226   54000
25206   63000
4311    87000
43718   62000
...       ...
38191   80000
9635    82000
29933   95000
31574   50004
15729   55000
22565   48000
5987    60000
23534   35000
44371   65000
37516   74000
14923   70000
28435   77000
44750   78000
39946   27500
449     33000
14540  135000
10962   35000
7719   125000
35508  130000
40272   68000
17812   51500
15317   87000
27269   70000
37320   58000
14134   45000
35199   94200
36368   69996
32633   95500
15445   56756
472     41200

[100 rows x 1 columns]
            x
34558  125000
11669  100000
34789   80000
44460   80000
17744   65000
30275   80800
42315   50000
46160  100000
28851  145000
30547   50000
            x
10151   63000
7636   125000
24257   96000
4928    70000
37188  160000
12734   50000
19976   68000
12747   36480
42367   32000
22481   75000
35450  170000
1945    80000
37958   62000
33402   65000
45264   52000
35165   58000
41216   35000
20860   63000
39751   30000
6227    24000
3715    23000
12329   74000
42766   33600
48931   51000
49780   30000
15353  120000
43842   37000
29484   65000
13317   19680
25792  120000
...       ...
15684   58000
19334   65000
45213   69000
19672   87600
13069   70000
6848    92000
27863   83000
1577    30000
35969   34000
16814   73426
1166    40000
42472   75000
5438   117000
17778   30000
2404    99996
35990  105000
10121   26000
26075   90000
29795   42000
41386   40000
48834   80000
20371   51000
17217   92000
37212   83000
30734   82500
43580   60000
49411  108000
17085   21600
44018   32467
6448    50000

[100 rows x 1 columns]
            x
38981   23000
21752   52000
17653  170000
37526   77000
44142   32700
5490    31000
29250  110000
2372    70000
39154   41000
35256   30000
            x
43332   31200
27544  133000
39228   69000
22551   52000
10311   98000
17922   52000
27772  125000
2234    50000
43328   86900
29958   82000
14250   35000
48040   38000
1758    75000
231     51000
12531   75000
20327   39000
39019   40000
5398    90000
25548   46000
48480   45000
1122    50000
32636   50000
32543   60000
48203   28000
32298   36000
8148   100000
2055    66000
32788   45000
29464   35000
42651   50400
...       ...
37154   50000
46655   23000
45305   40682
2695   130000
41595   27000
19776   80000
11181   25000
43389   55000
14840   45000
37367   86520
40905   71500
4628    62000
6544    72000
18268   40000
46092   32000
35986   83000
4563    18276
26895   96000
2558    30000
8282    64000
29295   52000
28441   68000
42222   62736
869    100000
20569   90200
47958   40000
7656    92000
3080    85000
22605   57600
49850   40000

[100 rows x 1 columns]
            x
26098  100000
36968   49000
11569  182000
27060   63600
19383   47000
3816    95000
3171    65000
28773   50000
8806    90000
7282    31000
            x
43993   45000
24203   34000
4857    75000
30953  105000
12028   50000
960     52000
12630  110000
43056   40000
26698  140000
29749   85000
3137   104000
2974    44196
20073   49000
3169    80000
12864   37000
30087   54235
21553   35000
17872   22000
22169   52000
23608   92700
4456    93500
28983   74628
48776   42000
14669  110000
34943   21304
23563   38000
1164    88690
35188   27000
20601   50000
5354    54000
...       ...
40567   51000
12480   40000
9463    60000
12334   95000
25156  108000
32709   45000
23090   75000
22125   45900
2995    70000
6878    40581
27624   35000
36171   65000
21897   60000
47687   62000
17320   46000
6747    41000
30343  126000
9613    65000
10946   40000
19477   54500
44102   92500
15432   98000
33918   71094
7338    65000
43634   80000
35877   28000
18777   75000
43063  100200
28886   35000
6360    77000

[100 rows x 1 columns]
           x
23011  45000
45149  88992
25458  89000
15399  41000
46381  46000
32561  37850
34339  60000
304    54000
4513   82500
45119  79000
            x
11690   39500
28651   68000
32642   45000
17847   55000
38702   70000
37316   77000
37033   52000
10890  121000
17255   48000
49868   40500
19603   32000
8183    80000
42099   75000
41955   43000
5865   120000
17547   65000
10758   61500
24339   54000
4713    88000
23875   19896
24090   85000
363     58446
14382   41000
5586    40000
28492   50200
37616   54000
38914  100000
4957    60000
4692    90000
38924   45500
...       ...
37795   78000
7915    32640
27922  100000
21710   58000
4895    61000
3480   125000
31405   60000
27410   72936
11906   47210
49860   42000
49748   30450
2434    38000
41695   90000
48105   31841
43155   60000
26762   70000
25618  121000
16068  105000
27135   85000
2361    65000
778     30000
40681   71500
45086   30000
31906   33792
19764   90000
40541   45000
16712   98000
18563  100000
31736   88000
43413   41000

[100 rows x 1 columns]
            x
15043   28800
7390    90000
33322   65000
30046   94957
10348   66000
22133   90000
40138   63000
34773   52800
8652   110000
32424   70000
            x
14669  110000
36681   62800
30995  100000
46593   70000
1349    24000
37636   33000
5805    70000
31064   70000
4976    67000
45068   45000
2728    74567
5565    39000
9290    53000
19027   51000
10067   40000
7252    19000
27735   82500
46415   65000
22182  100000
12056   96000
15590   29000
14563   32000
11537   41000
9519   100000
37701   35000
33507  110000
12512  120000
46401  137000
14479  120000
38665   37000
...       ...
27039   77000
14987   89600
30954  104000
25798   47235
19307   48000
34200   90000
41737  145000
24272   58200
29109   90000
41867   70000
34748   50000
6823   133000
18879   69273
34189   75000
32698   45000
4849   108000
31658   55000
30968   28700
16467   50000
23848   54000
19498  120000
31043   37440
28328   43871
38749   97500
3558   105000
7922   100000
24276   55000
26693   40000
48296   72000
22665  120000

[100 rows x 1 columns]
            x
17688   27500
49627   30000
8923    34000
37541   36000
25646   40840
42338   55000
9571    41500
1174    80000
37211   34700
12195  106000
            x
4081   150000
24541   53000
3462    86250
29977  177000
4090    65000
13081   55000
24071   85280
16600   67942
22032   60000
28477  110000
11946   40000
135    160000
40066   50000
10367   47000
28066   90000
12423  140000
45563   50000
7605    84000
45079  104000
12387   65000
20305   43000
12643   83876
14796   40000
48025   32500
16948   80000
31336   96000
45575  115000
14286  110000
17995   33204
44983   56000
...       ...
15028   56841
5125   105000
10769  150000
24091   83000
28680   46000
49499   55000
15674  125000
40173   80000
45614  102000
4037    95000
14891   38000
31017   60000
29502   31000
35062   55000
36618   27680
25543   55000
38429   69500
16387   72000
26900   58500
32678   24000
7052   103500
44806   46000
13154   49000
45579   50371
16754   67000
34024   83000
14040   55000
16243   95000
11304   86056
24567   41600

[100 rows x 1 columns]
            x
46341   50000
13565   46000
5223   132000
27621   65000
33423   52092
31896   80000
19926   85000
47875   52000
32886  126000
11888   65000
            x
35830  135600
39163   50000
27979   50000
30998   97500
32169   39000
44040  100000
21206   65000
22898   68500
27430   45000
30730   55000
1296    75000
28801  140000
49969   67000
39837   45000
18292   45000
24793  150000
29844   45000
38977   65000
40637   58700
36046   28000
23604   50000
20003   80000
37176   30000
16067   80000
49776   60000
26321  145000
49996   54000
27018   40000
19691   65000
35328   68000
...       ...
12952   95000
43671   60480
30716   72000
7584    45000
22283   76000
43511   56000
25896  110000
47013   52000
2067    44000
28650   30000
43827   37000
24385  160000
42526  135000
6240    72000
24680   56000
38427   50000
7064    53000
34765   45000
48603   21000
39482   80000
46095   38000
3887    45000
39029   35000
1288    68750
15623   45000
12143   38000
44448   37170
15860   70000
11004   53000
39363   70000

[100 rows x 1 columns]
           x
42467  42000
23386  20572
49766  92000
48340  83366
16459  12000
16183  39000
27728  52000
30408  60000
41289  52000
41798  56000
            x
48923   73000
18342   75000
2578    40000
48943   36000
4270    52000
41867   70000
47753  100000
34504   64000
5782    60000
45999   24000
1197    58000
18788   60000
3861    57850
28203   42000
26031  115000
31445   80000
37372   60000
8075    72000
19186   55498
29372   40000
43155   60000
26932   27000
13376   84000
47115  110000
46968   82000
45777   45000
1445    50000
147     98000
1970    58000
33580   85000
...       ...
44802   86000
33687   62331
45087   98000
32431   77000
29741   43000
14625   29000
47043   90000
21853   67000
22753   60000
21387   43000
39424   50000
11766   41100
26562  120000
40661   85000
17942   47000
32673   82500
11714   96000
46828   67500
9117    95000
42379   58000
35319   40000
9027    60000
47358   35000
22854   70575
31899   55000
39728  100000
30776  136750
24214   40000
16095   28000
1800    12472

[100 rows x 1 columns]
            x
3305    50000
22930   90000
30433  110000
18576  125000
28064   54000
32364   40000
35923   55000
48682   35580
33487   30000
4815    72000
            x
45258   72103
36876   34000
36878   60000
36319   60000
39163   50000
43921   60000
37438   17000
38323   42000
11054   81000
42010   42000
49672  140000
11030  160575
46781   51000
41693   77000
22331   43000
41856  100000
17768   25000
14329  150000
14056   85000
44293   65000
8586    76000
39145   70000
30422   43000
41243   80000
12798   73400
12688   54000
11370  179000
40253   65000
21546   98000
18880   42000
...       ...
2124    36000
39308   21221
1127   124000
43824   64000
28386  140000
18964  120000
17578   25000
24316  140000
49064   28400
9136    45668
47025   56000
4126    31900
42779   42000
43544   63000
1900    54324
9808    14260
21252   47000
26899   90000
29756  168000
49248  130000
9279    90000
49181   50000
43841   42000
17415   55000
40962   62500
22617   50000
15367   62004
31342   40800
9813    55000
41666   25000

[100 rows x 1 columns]
            x
34833   72000
42644   65000
26130   42000
28352   44000
22736   46000
41500   96000
32920   62000
37662   44000
27809  134500
19317   60000
            x
21586   95000
39389   50000
19601   29500
37751   50000
26188   21538
48342   27000
26910   31000
25372   71000
42091   50923
1945    80000
2866   120000
23125  106000
31798   37668
25885   70000
21038   48000
23556   59000
41126   85000
30182   32000
47672   36000
39007  120406
45205   28500
14107   50000
4696    30000
1228    94000
13367   72000
16382   30000
39072   35200
10913   86000
3883    49000
22849   70000
...       ...
32587   65000
5992    54000
7631    57000
47362   22000
16382   30000
36307   33800
27445   37000
38620   74000
38824  105000
7542    25000
26794   72000
31629   69000
33123   21000
21591   60000
27083   92000
30482   65000
32533  100000
40227   52200
7024    55000
2682   100000
22918   23000
35930   85000
17136  120000
9201    56000
34942   36000
25259   49000
14952   50000
9943    48000
48634   80000
396     50000

[100 rows x 1 columns]
            x
18364   60000
1441    33000
17518   66500
24539   80000
12464   70000
5317    85000
12308   85000
23206   42000
33407   52006
41124  120000
            x
30741   80000
24280   53000
46436   52000
17386  154000
35942   55000
42133   35360
18656   79000
7276    37000
34616   30000
23543   22272
42745   40000
2496    63000
8706   116000
3097   104004
3840    16800
6399    65000
43650   37000
31841   52000
39017   72000
31511   66000
24761   44000
30996  103000
16468   60000
23070   90000
1062    50000
17860   46000
45369   41000
37804   30000
41183   82000
47940   16391
...       ...
30871  160500
31541   44000
31781   80000
37341   46000
44086   38000
27574  120000
28854   75000
47197   44500
13565   46000
21238  123000
25495  101000
5443    41000
12525   80000
28157   85000
14525  100000
43607   48500
25427  150000
17649   71000
46322  100000
31828   90000
25492   42000
36608   70000
21741   56000
43034   58000
31856  130000
34814   80000
40906  135000
12490   90000
30868   24000
3211    60000

[100 rows x 1 columns]
            x
26550   50000
38851   30000
45614  102000
38722   85000
6577    66328
35113   31000
9644    70000
46727  120000
3147    40000
21669   38000
            x
25240   46000
16762   70000
22296  128000
40000   51000
19515  120000
3507    55000
2805    62000
9983    45000
26262   72000
49607   41600
41319   65000
35054   71500
12531   75000
35123  120000
1193   130000
44355   47000
35096   70000
21615   32000
19288  180000
20708  115000
42805   72000
34508   55000
11258   43400
44206   45000
21411   99800
4438    58000
10159   43000
4548   135000
19175   60000
17899   95000
...       ...
39605   51000
48680   45000
45293   72000
17886   59000
15996   55000
38008   60000
23338   30000
44647   80000
41870   90000
22985   35000
43839   55000
31690   70000
30487   98004
45798   45000
15747   78400
41729   30000
34133   48000
44780   85000
17067   11200
36039   98100
15883   48000
46250   42999
3530    62000
26372   75000
27598   90000
30511   41832
15993   85000
10610   69000
6006    68000
30075   62000

[100 rows x 1 columns]
            x
19166   60000
39661   52650
39501  149000
9179    42000
1455    80000
3552    40000
38203   75000
46396   42600
43200   60000
26740   22000
            x
12106  100000
42301   21600
36130   95004
46495   75000
18072   60000
16225   96000
24160  115000
6200    45000
0       67000
14597   70000
35991   95000
35750   50000
40624   70000
35035   50760
18798   70000
49193  103900
18941   45000
38883   79000
21575  120000
36587   70000
25398   58000
37794   64000
48555   65000
16029   58000
30986   90000
17604   32000
37630   74000
41057   49000
36002   67000
28735   58000
...       ...
5816    84000
43239   40000
7240    75000
3006    95760
2446    40000
3776    55000
48697   95000
2125    51488
39646   60000
46413  123000
33642   90000
12716  100000
20475   35000
11890   31200
19535   32000
41377   38480
15849   80000
13010   83546
2081   100000
39695  110000
45309   70000
39915  136000
14024  114000
42336   65000
6357    75000
28639   50000
6738    51000
26529  105000
10675   38000
7098    30000

[100 rows x 1 columns]
            x
24670   53280
24666   88000
49320   90000
33648  130000
8770    12000
18630   44000
1553    80000
34449   63000
28055   60000
37796   70000
            x
22488  105000
48277   92000
21025  100000
26342   32000
17731   64000
1617    43000
41110   75000
38237   88000
37136   48609
3643   130000
32477   99000
36784   60000
1265   103000
49183  130000
19527   86000
11132   80000
12831   57000
36675   33000
13802   48500
45737   80000
12530   69000
11989   58000
33883   45552
16188   80000
32464   54880
819     75000
35575   45600
43577   34000
36996  135000
19636   57000
...       ...
2138    44000
26666   75000
22880   74000
10585   85000
15124  126000
15104   35000
45850   65000
45730   32400
46171   25000
23725   58000
5754    54000
46444   56916
27511   60000
44203   93000
30473   95000
31694  100000
15557   35000
28919   33000
21487  120000
2361    65000
43058  115000
39448   85000
49625   94000
31580   70000
40158   40000
16198   42000
23604   50000
31204   69000
35890  104000
45332   55000

[100 rows x 1 columns]
            x
48623   62000
4712   114531
35862  180000
19801   89000
35227   85000
22390   36000
10626   95000
49657  100000
32506   75000
1006    37000
            x
2187    37000
10230  120000
44236   40000
42863   68000
40766   72000
30908   65000
9988    94000
4800    58000
49782   28000
35650  100000
32200   32000
44706   57000
7629    68004
32319   10140
4712   114531
35467   38000
40407   90000
23619   55000
2338    90000
49429   69000
12724   55000
49217   41600
43353   62500
5519    28000
15119   50000
36487   88000
42575   97000
11995   55000
33784  130208
40852   70000
...       ...
39553  120000
4914    69072
35172  125000
42312   75000
44032   75000
4831    80000
15393   26000
33193   75000
20422   37128
30023   50000
13877   26000
44408   72800
22111   52000
32690   54000
30352  106400
36974   50000
10810   89000
34381   53000
28577  150000
1861   123531
13759   30000
34451   37000
1311    45000
37686   52000
18814  133000
4088    70000
4640    91000
20733   84000
16272   90000
28380   42000

[100 rows x 1 columns]
            x
10168   52276
7702    38843
5111    43000
18610   90000
27493   36000
6424    12500
12981  103000
45869   45000
43567   35000
41866   45000
            x
5231    40000
26504   42000
5704    35000
46795   46000
32173   41000
21959   34278
41462   81000
28925   84000
31636   48000
47953   24000
873     79000
18106   95000
5441    71000
49171  165000
16460   90000
32406   70000
5459    85000
35412   88000
17296   70000
28009   45000
38285   29000
4469    35000
8989    60000
23989  120000
35190  143000
39864   65000
9880    45000
43205   56000
2618    16500
6637    92000
...       ...
26859   30000
23435   75000
37737   23000
1839    65000
49657  100000
33335   50000
43706   65000
30406   55000
45989  120000
11739   45600
15230   56000
33632   25000
25128   26000
29344   50000
36986   63000
42855   90000
47205   35000
13450   40000
45670   96500
18376  104000
48308   85000
9330    34145
34642   70000
42239   53700
14031   64000
38948   50000
25997   86000
37160   95000
7381    80000
7743    40000

[100 rows x 1 columns]
            x
11200  110000
12613   25000
6542   160000
40961   82000
35807   22128
23598  154000
29181   37800
12999   50000
42164   55000
48116   41604
            x
24079   67855
24747   42000
9251    30000
41889   83000
21564   45000
48078   52000
44514   45000
7462   120000
43805   58000
4890    30000
14142   50000
17370   67000
36282  144799
34135  125000
23794   68000
1164    88690
2924   110000
4955    79432
3125    53000
49795  131939
15430   66500
33381   75912
22815   82000
4215    90000
16166   70500
39904   58000
3475    24000
9884    36200
22321   45000
26101   80000
...       ...
44429  163000
2027    51000
46631   65000
19395   90000
47307  100000
16868  120000
3032    79000
34339   60000
2406    35000
40706  115000
9969    57600
20432   54000
6346    85000
18724  103000
40552   95000
42889   45000
29985   35000
47920   75000
3219    65000
47255  160000
40536   52000
49680   78500
2490    65000
38615   32000
25492   42000
36744  190000
12565   35000
34029  120000
26484   58200
3816    95000

[100 rows x 1 columns]
            x
11738  104000
4775   100000
10483   57000
42377   42000
12287   85000
32843   75000
18677   35000
17330   42000
23517   80000
148     53000
            x
45102   88000
11198   55000
41960   61200
5112    75000
19881   88000
48370  165000
6252   135660
47253   90000
43364   32000
41811   94500
34625  110000
33636   70000
42094   60000
8279   135000
29652   41000
7306   120000
14231  154000
27992   58000
7523    26700
42677   70000
28755   24000
45036   95000
30329   50000
20970   75000
15135   61755
14986   45000
24704   94500
45111   94000
14268   40000
4693    37332
...       ...
32301   88740
35581   30000
42736   40000
8119    85000
24979   27000
40437   78500
828     24985
9956    99000
26590   65000
30277   70000
46839   73000
14656   77000
12356   45000
36470   66480
20619   50000
12949  144500
38375  100000
20192   22000
39632   67000
8165    57000
18879   69273
29340   55000
48375   32500
16702  140000
25083   56000
29217   36000
34078   28000
42584   75964
4105    52686
18037   59915

[100 rows x 1 columns]
            x
9168    50000
8443    36000
2113    62000
44627   77368
1800    12472
19289   26871
41940  161000
41813   80000
12779   45000
15244   81000
            x
4246    87713
9341    87000
5727    55100
8182    81000
34058   43861
13353   41005
34605   64191
46398  135000
26801  125000

15989  102000
            x
27949  105000
48599   40000
45150   27000
32290   80000
15188   35000
13018   32225
24255   65000
45476   28000
16627   50000
41582   45000
25782   53000
6581    45000
10182   75400
38410   60000
20618  110000
22659   90000
16870   22880
20151   15080
20721   40000
47792  115000
15407   60000
23594   76336
26273   87000
22830   60000
42512   40000
47475  150000
6726   128000
36366   42000
39225   75600
22897  108000
...       ...
9232   139000
22324   90000
11970   63000
34999   25896
30598   52000
27951   65000
45981   43000
33858   57200
39629   60000
14340   32500
40894  155000
49934   80100
32291   50000
43387   70000
43578   70000
19413  100000
32208   60000
5426    80000
26409  170000
22154  108000
13475   50000
10629   50000
20049   70000
7840    19080
38548   72000
27688   48000
22234   40000
25163   45000
43800   45000
48175  106000

[100 rows x 1 columns]
            x
43236   63000
41502  115000
15919   54814
31182  100000
19027   51000
46688   50000
34573   75000
49738   52000
18299   85000
2857    88914
            x
20096   37000
1539    64000
37309   80000
41334   40000
34523  159350
13564   47520
897     27000
18240   25000
18918   45000
7335    25000
5425    67000
9990    50000
40153   54000
46332  100000
27964  100000
17535   46000
35200   61000
32713   42000
22900   50000
27573   30000
37896  142000
23643   75000
43243   40000
42959   75600
10076   61000
31268   60000
32102  160000
12388   52000
41972   36000
17845   70000
...       ...
7593    80000
13188   60000
11653   28000
31657   52000
33844   50000
23005   45000
40032  181250
34694   41600
47677   83000
6505   195000
31027   75000
49735   60000
15030  100000
38686   48500
10529   70900
29917   95000
38244   50000
20301   62000
37431   68000
8100    78500
40520   27500
120     80000
32642   45000
32411   86000
9247   100000
400     82500
43689   21504
24600   14000
7872   165000
13001   25000

[100 rows x 1 columns]
            x
32511  120000
41984   55000
36021   72000
42686  120000
38848   85000
34298   50000
28294   48800
39974   22000
19290   62000
16330   48000
            x
34231   40000
10519   47500
36792   59000
22116   95000
16958  125000
31548   50000
32454  130000
20382   60000
42556   44000
40733  145000
39654   40000
16511   60000
48486   19667
42260   45000
34754  100000
20217   39833
3690   103000
46737   82000
30398   60000
14602   76284
18015   69000
9672    75379
45614  102000
38433   24000
45397   55000
12060  100000
37926   42000
8915    80000
38694   72000
41844   86000
...       ...
8760    65000
31742   85000
34666   41000
38810   54000
24945   40000
17622   87000
6819    40000
13262   39000
16299   50500
39940  160000
2750    24996
994     40000
33293  165000
14701   51947
17026   45500
26911   36400
36485   75000
35879   89700
28186   72800
33878   48000
10577   76000
31721   58600
38752   98000
22336   61000
49931  106000
47712   60000
2272    34000
23664  110000
14570   65000
17923   32496

[100 rows x 1 columns]
           x
36435  96000
24040  90000
48144  24000
17103  65000
23893  43000
33949  20315
47097  44000
40378  66000
42462  45000
42465  98000
            x
23932   90000
3442    70000
27120   82500
22034   46000
9884    36200
38201  130000
32103   60000
5160    65000
43671   60480
4165    40000
44699   63500
16181  100000
44518   45000
15342   65000
26284   43000
17953   60000
29982   60000
47209   48000
1615    80000
38151   55000
36042   60000
23106   65000
35763  150000
35560   73196
40169   35000
44939  105160
26718   79800
41339   84500
16052  105000
31012   40000
...       ...
38567   60000
2452   180000
6011    45000
35666   60000
8201    40000
26438   52000
40360   38000
16431  142000
39652   65000
5724    26000
47519   75000
34319   41000
37747  120000
22259   48000
48160   74600
25551   55500
37480  100000
12814  160000
25004   77000
14516   63000
38154   66800
29114   36000
17082   86188
14476  165000
43903   65000
49491   46880
17454   75000
23195   37512
6821    28500
6325    85000

[100 rows x 1 columns]
           x
20772  50000
41843  78000
13256  67350
802    32100
24715  68350
23428  67000
24228  86000
6398   80000
40623  72000
49164  85473
            x
11429   62000
17966   26000
46204   61800
25939  122000
45405   53000
3510   130000
30601   52000
15397   27000
29074   85000
47599   40000
5959   105000
49381   40000
37030   26800
27876   75000
10796   58000
34610   56500
4004   100520
3963    80000
24310   75000
33811  149000
29110   80000
37568   50000
2620   112000
21162  103000
14698   64944
5831    90000
3086    50000
22409  134000
19272   33000
25755   72000
...       ...
42018  101000
38779   55000
9377   120602
35351   38000
43736   95600
46274   72000
12664   65000
43097   70000
4293   165000
23057  101000
150     48000
17826   98000
18413  110000
10257   85195
11302   60000
48537   67000
36917   83678
14519   36996
21319   85000
5541    45200
29626   90000
21285   60000
31278   85000
4373    36000
13526  128000
37629  105000
23588   75000
25731   48000
20425   42000
22835   45000

[100 rows x 1 columns]
            x
48286   80000
28041   90000
31771   58000
1776    75000
25491   75000
27229   89000
41888   45000
7449    43200
21709   55000
38683  125384
            x
16982  125000
26524   85000
6740   138055
22165   50000
48942   85000
37198   60200
21035  120000
18915   41000
41874   54000
28763   65000
17415   55000
44613   75000
18896  110000
45861   90000
8295    78000
34287   80000
1606    61435
29230   83000
803     40000
48335   65000
33469  100000
25156  108000
4720    60000
419     35000
16766   50000
38613   78000
30008   85000
16687   24000
46343   54295
1840    34000
...       ...
41694   35000
32906   63000
44753  125000
16904   67000
23812   88000
42504   22000
5105   130000
15649   40000
45193   90000
20489   55000
5552   102636
30699   61402
36513   48000
29466   71000
11838   30000
11028   47000
9328    91000
30141  138000
26360   50000
29819   65000
42899   85000
27884   45000
45028  160000
24775   46728
19409   90000
30693   50000
30194   38000
24602  109000
21344  120000
10377   48000

[100 rows x 1 columns]
            x
15861   43000
8838   100000
7887   137000
43676   65000
14564   50000
8471   151680
8010    73800
37170   71000
33745   39000
15255   90000
            x
47001   40000
16222   51000
16172   69000
35890  104000
41574   46000
4487   131500
42824   39200
37276   73400
9282    49000
37197   40000
37182   58000
44270   20000
22401   75000
27831   54000
30516   85000
10055  110000
23350   40000
37799   36000
41605   36000
11274   60000
33680   48000
14959   36000
41877   74000
11745   75000
42557   38000
29323   60000
11991   39000
45336   41004
36490   76078
9760    56000
...       ...
9709    92000
44232   65000
25997   86000
41253   58000
38470   53000
33845   75000
3117    55000
10397   90000
45284   63000
26337   54000
6983    44482
35262   22000
10718   66562
41701   62000
32379  130000
10815   58427
37857   41000
29319   44000
37063   60138
24540   68000
16277   70000
31807   50000
35142   82000
3713    71060
31613   93000
26067  106000
2624    47000
48081   36000
23817   37000
13605   72000

[100 rows x 1 columns]
            x
4865    75192
44661  115000
13653   90000
12404   52000
34237   50000
42914   95000
5844    75000
11376   65000
42161   60000
34456   90000
            x
35234   40000
13499  119856
8914    40000
30739   42000
9418    55000
28367   40000
31425   60000
33700   42000
9118    50000
26667   60000
9711    21000
6627    39000
31244  100000
44142   32700
22064   80300
6076    90000
14859   63000
6812    40000
8745    45000
43553   74200
39503  133000
21209   48829
41031  100000
36771   43000
41136   49000
11214   56000
43881   65600
46496   39000
35210   46000
39845   75000
...       ...
21897   60000
42412   58000
30834   31200
36931   59000
3871    56000
2557    50000
14134   45000
9419    36000
9874    96000
15251   40000
30400   55000
18557   22000
46890   97144
25329   52000
25861  180000
41099   24000
34193   32000
7736    32000
25214  130000
9413    41000
47014   75000
44132   90000
14941   20000
1806    99500
30274   40000
796     64000
15541   60000
23515   55000
47431   51000
34770   65000

[100 rows x 1 columns]
           x
9978   48000
31898  79768
23390  85000
45206  32560
20751  70000
18525  65000
10746  33200
7913   78000
23012  78000
22240  50000
            x
8347    55000
21409  105000
40114   73923
31120  104000
35062   55000
29919   83000
16625   84000
30933   70000
11918   55000
49909   42760
8013    59136
48589  165000
22135   78000
22438   75000
44899  114053
14137   74000
7023   180000
46889   57000
39612  100000
12932   54000
33154   65000
6408    85300
10606   55000
3952    50000
33816   80000
35702   87500
7510    92000
5654    75000
44335  107390
2971    65000
...       ...
21398  120000
13652  160000
40446  164542
11958  110000
36927   25000
16843  115000
31467   65000
29298  118000
8532    40000
10566   78400
22921   85000
17529   90000
7362    99000
24869   94000
9591    52000
1762    65000
23507  133000
27382   71000
41875   75000
33006   67000
19293   51000
6012    30000
26946  115000
4009   120000
35094   65000
26333   90000
40430   76000
49489   45000
30214   41400
49909   42760

[100 rows x 1 columns]
            x
6423    60000
8417    95000
41327   60000
46949   34000
46381   46000
1935    44000
37588   32000
8979   104000
24556   53500
17609   17400
            x
35498  100000
41847   35000
5646    85000
49121   26000
2739    55000
26879   64947
10463   14184
42782   90000
43765   50000
15515   35000
34169  102000
1264   175000
7316    52000
35404   82000
9847    40000
29579   90000
14526   65000
24071   85280
10352   66000
3166   100000
3587    89000
24459   57000
47755   42000
269     55000
30662  110000
20276   28000
33854   85242
5270   105000
43215   85000
33843  100000
...       ...
18573   37200
25551   55500
5235    40000
9295   140000
21758  120000
10230  120000
1834    70000
4617    55000
13412   50000
14461   63000
37043   65000
9420    32000
23270   76000
8349   118260
42368   55370
41268  106000
8549    60000
36347   62000
6701   123000
47060   31000
49387   87000
22112   55000
13411   16048
13953   73000
17746   40000
15069   40167
20542   35000
24178   62000
17066   36000
20440   62400

[100 rows x 1 columns]
            x
22206  117000
17668   65000
16078   50000
19136   75000
37475   37397
38763   93500
24666   88000
26608   10000
34125   42500
28472   38188
            x
40384   75500
16923   80000
34043   47000
78      88000
21025  100000
20858  120000
3761    39000
3237   100000
21383   50000
3785    21000
28182   85000
17554   80000
21832   92000
10473  102000
35427   50400
41123   28709
21497   70000
28576   41000
15737   57996
43655   39132
14827   54000
24056   98000
28586   40000
22583   75000
18502   45000
40299   98000
43584  190000
24262   64000
20577   26453
26269   70000
...       ...
47533   75000
10815   58427
2405    53000
44552   70000
11935   28800
25055   39000
47970   43971
24687   48000
43282   80000
39053   76000
20423   28000
43886   72000
18866   70000
5624    42000
16156   95000
43637   67000
30130  175000
43483  109000
31585   64000
605     50000
26437   96000
32162   84000
15584   90000
38057   43000
35757  118000
7816    32000
41107   50000
20123   34000
3733   105000
35603   60000

[100 rows x 1 columns]
            x
32739   50000
13081   55000
28591  145000
27514   32000
21158   50000
22440   30000
41225   67000
1391   120000
49417  166000
18107  160000
            x
44592   35000
22487  120000
38333  131000
21143  120000
26886   62450
39587  120000
49707   72000
6101    44500
21714  118000
13737   30000
48362  100000
23446   97000
31099   27000
37835   55000
27327   21150
7439    63000
27400   89000
27529   74000
9931    28000
3120    28000
43262   35000
29149   60000
39132   80000
14114   35000
30240   50000
39559   87000
23445  115000
20884   80000
1219    90000
44587   62000
...       ...
772     36000
21349   62000
5331   117350
49930   11500
10897   40000
10345   51000
13602   17000
45368   84000
7548    65000
19085   73500
4929   150000
3739    44678
32198   31900
40191   40000
1859    45000
47181   95000
34871   98700
28092   40000
8944    60000
34539   88400
31103   65000
10274   78000
26374   46000
5711    35000
40029  123000
49889  104000
23071  120000
3583    43000
11158   48000
35218   28700

[100 rows x 1 columns]
            x
28521   40000
1724    70000
28233   95000
20848   50000
27172  103000
17866  110000
41084   40000
28554   65000
39207   32000
27879   72000
            x
12812   37689
11315   61000
27132   60000
2456   175000
38973   80000
22073   53000
26173   77000
25394   36000
8687    74000
25321   75000
14220   65000
39817   38000
39379   60000
34551  100000
20763   70000
49423  125000
45476   28000
33998  150000
34630  120600
18270   45000
19311   30000
45785   52500
20916   56066
35748   39000
48201   36000
5437    62000
39763   68940
8884    38000
39753   95000
32259   30805
...       ...
2637    80000
16325   42000
8594    40000
5619    39000
39583  117090
19357   33000
49748   30450
43180   65293
37880   65000
36206   93000
14188   40000
20151   15080
7563    50000
15729   55000
15142   65000
2484    60000
31652   29120
36711   60000
36062   35000
36626   39600
42904   64000
86      57000
26947   43000
1312   108066
8030   121000
36840   49067
46089   68800
27636   63000
49349   51000
26781   67000

[100 rows x 1 columns]
            x
43403   60758
38941  125000
42076  100000
3950    62000
37919  128956
23563   38000
27511   60000
19439   63775
41937   55000
30305   73500
            x
27184   50000
38439   75000
26610   40000
44569   48000
4338    29000
33899   95600
7617    40000
3927    60000
39703  180000
11119   45000
27609  109000
28564   40000
13947   37000
48461   72000
27401   37000
11828   34000
30782  100000
4528    62000
78      88000
36806   95000
39929   45000
49079   58000
21237   50000
6402   115000
39823   55000
39424   50000
8025    58000
40164   29000
21104   85000
130     70000
...       ...
38521  135000
16328   34000
4990    58240
26816   60000
33775   75928
39503  133000
20132   81000
37394  100000
35552   42000
2972    84000
38300  110000
46463   58000
37458   45600
1532    25000
7231    36000
42988   35000
17103   65000
25259   49000
18654   48000
47355   69000
10975   32000
21802   53000
8536    60000
22234   40000
12508  100000
1406    35000
8057    72000
14220   65000
23079  143485
6641   145000

[100 rows x 1 columns]
           x
48470  30000
24647  60000
37194  39000
39431  96000
2402   66000
30992  48000
24058  59000
27228  64000
29476  60000
39477  45000
            x
22218   51000
21814   27000
4381    48000
15685   62000
4390   123000
19672   87600
19051   39000
8330    79000
30364   50000
20472   51000
19252   80000
32922  106000
23653   18000
36830   32000
24495   60000
575     85000
15802   55000
20504   85000
8951    73000
36615   67087
27191   55200
5328    71000
43794   69000
40401   63000
13051   65000
6690   110000
4888   100000
20688   41000
5139    50000
16136   65000
...       ...
41374   47353
19277   85000
23183   98000
20534   60000
11947   67860
18319  118450
3033    87500
7269    90000
22793   40000
17952   46000
31661   43000
47746  100000
5689   120000
1887    32000
47576   70000
49274   90000
33765   34000
36013   38000
8457    76000
42106   48000
47046   45000
44044   45000
46957  110000
46699   28000
49790   60000
14593   47000
26322   70000
5221   145000
29137   60000
18524   38000

[100 rows x 1 columns]
            x
25918   30000
43464   95000
23981   83000
7500    27000
11559   65000
49948   48000
49471   40000
5596   170000
27780  152687
26907   69000
            x
31254  180000
43371   58400
31007   90000
41505   35004
47710   45000
10280  100000
20672  150000
39107   45000
19744   56000
25844  100000
35979   97708
7992    62000
21927   73200
25959   41000
28357   84000
47159   52000
19892   25404
4624    38000
33466   80000
33319   92000
6500   103686
42480   80000
13012  100000
10427   70000
19236   60000
34071   36100
16383   70000
40645   75000
18565   65000
49898  130000
...       ...
45565   50000
29415   60000
16378  125000
29506   85000
17151   29000
37491   50000
20801   60000
17026   45500
11565   96000
934     65000
36929  145000
1444    98500
36329   26280
48799   25032
28167   60000
24281   65000
12486   60000
37008   53840
17177  120000
34498   50000
3213    70000
21862   86000
12670   45000
1251    40000
40847   75000
6521    40000
21202   31600
46036   59000
6503    83000
32947   22776

[100 rows x 1 columns]
           x
14862  50000
18293  60000
17130  88000
3208   26400
21580  44000
26827  60000
10289  67000
29379  50000
34955  42000
5088   75000
            x
40173   80000
48872  110000
26716   82000
28773   50000
3979   100000
18936  125000
19834   55000
33355   17352
23117  101000
3412   165000
45567   36000
47776   64000
29450   50000
39286   81000
33912   90000
24761   44000
46145   36000
31633   55000
4215    90000
21787   31204
3359    50000
43757   35000
47650   40000
12728   54000
1060    63000
9235    70000
34711   60000
38264   45000
26088   73000
43344   38500
...       ...
26733   59300
26727   52000
28956   60000
3381    84000
48599   40000
40918   84000
493     66000
38133   29000
33270  101000
734     49300
38934   42000
13419   85000
10099   90705
29353   56000
11896   52000
15254   70000
2500    75000
10466   90000
6375    80000
35796   25000
15458   33000
625     78000
8897    50000
28675   78000
37910   61000
21947  110000
41828   22000
9426    54200
24388   40000
42653   44400

[100 rows x 1 columns]
            x
35867  107000
10196   74000
25894   72000
3809   170000
15412   25000
31699   65000
4581   135000
46414  100000
7940    56000
48619   40000
            x
5440   110000
48391   51600
34591   60000
14436   24000
35054   71500
25451   90000
38166   49356
40663   80000
43027   45000
33358  100000
33612   53000
25333  160000
37594   40000
10354   39000
14751   70500
36005   30000
32333   59000
17548   61639
48925   80856
28425   68000
47929   98916
13892   31000
16716   52800
25437   61464
19746   26640
31124   35000
41442   95000
25147   70000
2304    55000
45047   75000
...       ...
46452   77000
29305  123042
46605   83004
49419   42000
29761   70000
17354   46000
45273   25500
49979   68000
35410   50000
2753    40000
40477   64000
19417   77004
14030   90000
11553   32000
4008    42000
44014   70000
2354    82000
33628   98400
25635   67058
28015   90000
13972  100000
45190   96208
11334  125000
32324   41000
27986   33000
26543   80000
35986   83000
14114   35000
20968   55000
25361   61500

[100 rows x 1 columns]
            x
44147   40000
10549   42500
24038   47000
26754   40450
39367   40000
33313   35000
2499    35000
16985  150000
41333   75000
8503    60008
            x
12925   45600
17930   59000
3360    90000
8386   100000
24624   47710
20896   48000
21529   16400
18444   65000
37641   30000
4064    35000
23      80000
35013   45000
37089  138850
31145  110000
37202   50249
17315  150000
3156    45000
33548   69500
4308    34000
47689  137000
3376    65000
33782  120000
24472   65000
43132   55000
35161   30000
25337   87377
11444   45000
35494   85000
1460    75000
34393  102000
...       ...
29180   51996
25208  120000
41960   61200
12736   55000
33535   85000
43435   52000
4557    62000
31974   36000
32264   50000
20123   34000
13372   27000
15316  125000
18911   46824
28798   78000
13896   52127
34509   53000
33239  160000
46457   55000
15804   75000
33909   80000
12574   60000
33786   78000
46213   78513
3464    96500
14101   68000
46858   66000
32767  130404
26040   44000
4296    96400
8828    35000

[100 rows x 1 columns]
            x
8825    54000
46127   38000
48647   42000
15031   25000
30908   65000
16122   88500
1654    75000
5299    40000
22680   89000
3074   120000
            x
38228   52000
30364   50000
6450   120000
42001  105000
314     35000
23741   55000
27914   45000
822    100000
35371   30000
21992   85000

            x
49903   65000
22378   65000
22967   68000
26674   50000
37483   35000
23090   75000
23835   60000
45985   48000
16989   63000
946     91000
46944   50000
1741    30000
39132   80000
22402  125000
9652    95000
36667  148222
4764    43680
43970   34000
27445   37000
32226  154000
1304   128000
8598    40144
33588   50000
36919   90000
35277   76000
47649   90000
39204   61000
10062   42000
8971    70000
28785   60000
...       ...
36185   56000
46261  102000
18026   55450
13210   63000
29894   31600
12220   75000
37121   68000
38648   40000
17549   33600
46751   38348
3113    40000
12064   86000
30602   45000
40151   90000
5318    85000
15005   84554
20044   60000
11780   33000
7815    74400
15465   15000
39464  123000
13700   64000
42104   51000
34688  170000
47127   45000
40735  110000
21798   52000
36844   94837
40624   70000
48249   85000

[100 rows x 1 columns]
            x
1245    65000
13101   63000
10535   40000
9742   115000
27899   75000
39352   40000
33674   65000
30463   42000
33994   38500
17265   70000
            x
14360   25000
32160   46200
24427   65500
20610   28800
28728   70000
36022   58000
30747  150000
32154   50000
20249   46000
674     32000
46065   58000
2938    85000
37032   82000
42349  120000
24870   63780
35692   52000
32123   59506
34445   70000
40512   40000
19367   40000
44699   63500
11709   54500
7368    18252
35441   72000
42749  186830
38381   71000
14654   42000
27266   33000
43903   65000
28959   30000
...       ...
35629   60000
857     37224
42327   75000
31753   90000
9319    70000
11651   54600
24320  111000
27375  126000
182     55059
18561   70000
12330   56000
36103   48000
25234   62000
39836   45000
29070  150000
24300   84996
612     87000
33220   53000
46839   73000
17966   26000
41279   60000
49392   48000
6157    37544
35735   55000
44694   56000
22599   52000
36671   39000
48525   51000
17333   40000
46945   60000

[100 rows x 1 columns]
            x
44064   50000
35789   24000
23834   92000
23409   37440
28840   90000
14629   87000
34451   37000
8041   110000
11352   72000
27337   52000
            x
11828   34000
29350   55000
11426   42000
9034    65500
10578   62397
28069   45819
38974   42000
19750   35000
15781  104000
69     115000
12827   62000
22426   55000
39499  100000
1063    50000
2835   170000
8727    96152
1049    88000
35645  127000
14339   80000
5043    46000
31639   40000
48376   75000
16590   38000
5930   120000
39712   50000
30974   72000
6673    60000
10086   85000
6333    49000
33107   60000
...       ...
3361   115000
5472    57996
41460   71000
34095   42000
1155    60000
35314   49000
19286   52000
23874   76000
17963   90000
7968    34000
44650   59864
18956   96000
37063   60138
2486    50200
13229   80000
18960   72500
35404   82000
15511   96000
19015   42340
28476   65000
4681    40321
24237  178000
1489    25560
35491   95004
46529  100000
21624   80000
22133   90000
37212   83000
40587   28000
47228   70000

[100 rows x 1 columns]
           x
10445  57000
24859  66500
18749  75000
11733  80000
19802  45500
24773  70000
17544  55600
43913  42000
43903  65000
29561  29000
            x
18249   33800
43165   76000
9496    70000
4549    95000
62      44000
35660   38244
48689   45000
3633    65000
1542    47342
8173    73000
41577   70000
28423   43000
18662   72000
48698   65000
38479   56000
12634   22986
5411   100000
38714   60000
13486   65000
45149   88992
21443   85000
10643   40000
17416   35000
35353   75000
45770   24168
38352   46000
32178   35360
36613   35000
17389   30000
18937   60000
...       ...
8103    35000
38612   26030
49370   98500
20652   30000
28634   40000
30818   70200
24623   40000
6404    60000
8978    48000
11418   53000
40371   47000
119     26000
20015   55000
40206   55000
21279   64000
26770   42000
3318    68000
8943    55000
45610   55000
35058   80000
33175  150000
25557   70000
37823   87000
41237  115000
43257   37000
30528  120000
33672  131000
9019   125000
9737    39528
45101   50000

[100 rows x 1 columns]
            x
40577   27096
3009    52000
28366   60000
2968    63000
5000    55000
14761   72000
2224    70000
38481  160000
23111   50000
11963   21588
            x
15367   62004
27687   52000
11858   92000
17441   57000
48526   24000
48794  141660
763     57180
22113   40248
4166   130000
1127   124000
42412   58000
48852   95000
43407   40000
5862    63500
15935   26000
36377   47000
20714  119496
3108    52000
36676   70000
5053   120000
25416  110000
7717    55100
11523   30000
29914  120000
15806  110000
33513   31000
48393  130000
35925  127000
39355  100000
4893    49000
...       ...
47729   86000
44583   65000
21568   70000
35196   60000
2176    45000
25818   56525
47416  100000
42016   96000
23308  135000
20581   84000
32555   44000
6309    42000
16419  145000
23089  120000
25424   66222
38464   67000
10365   60000
16397  108000
8955    82000
23698   80000
16562   20792
43044   30020
37294   52000
9262    30000
209     43000
40621   52000
16811   30000
17672   61000
6532    82500
42650  100000

[100 rows x 1 columns]
            x
37896  142000
46429   57000
31284  125000
36693   53400
28866  128000
30760   57900
21361   88000
41284   99900
11321  145000
5233    75000
            x
22174   54000
27197   83824
24215   30000
23042   25000
27464   40000
40322   76000
10847   84000
37276   73400
41137   31000
36049   62982
24423  104000
19324   66000
29701   72500
14955   36000
40237   90000
14477  102500
48802   38000
38759   40440
19354   35000
49022   23000
43453   70350
41735   78000
43793   52000
14549   60000
7326    90000
6633    80000
28425   68000
40167   85000
5981    98000
31262   30368
...       ...
38050   50000
46306  155000
42878   82000
4834   105600
13027   58000
46348   53000
18226   65000
36840   49067
38395   75000
35419   64000
22179   97000
11908   75000
21723   55000
36709   35000
926     69000
18996   45000
12275  103000
49044   55000
38528  150000
21537   17000
14808   90000
31427   67500
24936   65000
34183   94000
17097   68000
30832   53760
44033   61000
752     64314
23893   43000
40212   85000

[100 rows x 1 columns]
            x
17192   29000
30379  170000
39182   65000
23909   80000
6023    30000
39177   70000
25462   33000
21518   24000
34868   80000
9943    48000
            x
38969   50000
12746   45000
7957    45000
7024    55000
38983   48000
17624   50000
36103   48000
17980   45000
24264   58800
6065    85000
47291   53000
41227   53000
47814   61950
24089   35000
34850   38000
34427   35000
14449  120000
21365   56472
23428   67000
40825   45900
17477   42000
18467   50000
34889   26000
15738   55000
4930   120000
24282   30000
14231  154000
39232   53000
24656   32448
44320   37200
...       ...
42277   60000
43702   95000
25846   85000
9454    45000
16634   49000
13302   80000
23691   53000
27275  106000
20860   63000
44456   74000
37788   20000
39922   40800
17526   76960
33357   85800
1837   120000
11135  125000
1092    37000
2234    50000
15930  120000
37821   40000
18207   72000
2741    38000
16232   50004
2504    70000
46033   60000
12536   95000
28088   93000
45896   57000
25193   78000
10749   75000

[100 rows x 1 columns]
            x
5747    31200
16037   80000
3394    77991
16370   62000
35817   32000
48236   70000
48891   77200
14689  115200
3455    28000
34194   54000
            x
31384  110000
28428   76800
25213   40000
367     38000
7408    23000
35368   18000
20843   98000
32891   40000
48715   44000
1638   110000
2659    27894
19363   70370
11437   65750
10371   60000
45220  124000
18689   65000
11148   48000
288     79100
1203    68000
26394   60000
29422   60000
27974   49200
37517   51356
48520   58000
5819    25000
47458  109000
34316   67000
6623    43000
46736   42500
2694   165000
...       ...
48361   15000
16740  150000
27478   29120
9319    70000
24452   70000
8740   130000
13390   31200
14847   34000
33622   80000
37369   80000
5270   105000
45921   80000
28145   76000
20260   70000
40923   42000
47814   61950
14440   35000
1473    85000
41674   77500
26703   40000
4719   117700
29043   58000
18248   22000
47614   56000
6911    90000
32618   70000
40763   75000
2119    75000
21299   80000
8027    35000

[100 rows x 1 columns]
            x
4600   105000
2502    60000
26733   59300
16704   25000
7060    60000
8401    70000
14139   90000
297     30000
11620  110000
10824  110000
            x
14259   48000
3490    39000
35265   39000
24870   63780
6887    55000
31463   34000
21322   37200
21882   27500
39896   25000
20746   95000
24838   68500
39139  120000
44581  160000
27809  134500
39508   74860
28416   74000
41917   47000
6423    60000
27456   80000
26607   65000
21556   36000
25336   80000
43257   37000
13987   50000
48228   70000
27768   55000
37423   25000
16070  104000
44339   52000
33927   52000
...       ...
38586   45000
10206   52000
37416   54195
13758   37000
42714   45000
45647   25000
33277   42000
7959   125000
40519  100000
37452  128960
9179    42000
24136   38000
14704   44000
36142   82000
39825   51602
6045    45000
13277  106000
40029  123000
9043    60000
31768   55000
41824   42000
22328   20300
4467    42000
49348   52000
36228   52000
4896   159883
43627   97000
39567  109000
18380   49000
27849   60000

[100 rows x 1 columns]
           x
25335  34550
1860   57000
41727  39500
29151  65000
4722   43000
15886  82000
24783  31000
11547  78000
41778  54912
22694  70000
            x
48363  160000
30958   65000
40478  108000
2056    25000
20546   35000
1370    73000
31893   62500
24995  105000
28090   39000
42913   51600
27110   83000
46642   81640
29699    8412
17734   80000
33534   49000
8892    60000
35440   42000
22902   63000
7895    40740
46440   85000
29107   68000
35705   81000
15488   93000
44899  114053
4087    96000
636     72000
33528   37440
4758    62400
44651   75000
41597   83000
...       ...
36479   94000
13814   41400
47849   55000
41170  137500
26266   50000
22089   35000
38810   54000
46618   56004
46852  108483
7161    12174
33905   65000
41462   81000
40795   85000
6687    52423
18805  150000
12503   87000
2973    90000
7104   110000
10456   35004
25148   66934
41222  110000
45490   85000
10195   41725
27107   76700
6716    50000
29475  175000
33498   85000
31809   40000
47523   85000
26290   48000

[100 rows x 1 columns]
            x
21393   90000
42790   25000
3125    53000
2724    57600
24404   90000
403    100000
32948   84000
28769   80400
2532    78000
2027    51000
            x
702     48000
10082  115000
28802   38500
39223   51000
32975   35000
28259   57500
32344   60000
33593  180000
42145   50000
12554   80000
45230   80000
8052    65500
7992    62000
24066   30000
32325   70000
48571   55000
4988   114000
25418  113004
15376   52000
43046   15312
41937   55000
30314   75000
29283   40000
30055   52000
22890  110000
27722   51000
12457   57200
23279   85000
20263   42000
47049   82000
...       ...
9141    79000
44346   70000
45317  100000
10955   70000
16797   40000
5835   140000
26629   92000
47561   35200
4528    62000
16633  102000
13627   40000
47741   62604
22944   98965
14758   46000
17805   30000
46109   58000
33732   40000
7355    80000
23673   38000
7642   187000
45762   62000
11769   14540
33641   35000
3290   102000
28363   26500
31833   30000
309     59168
38515   41000
33683   38500
7819    70000

[100 rows x 1 columns]
           x
30844  80000
18418  33000
24926  45000
38022  65000
31916  31000
37748  79000
26762  70000
41504  73500
31921  48000
33809  70000
            x
20870  101000
13421   50000
8185    45000
16749  140000
37141   35000
7077   138000
18396   75000
9092    70000
33479  160000
5128    60000
48841   96000
24919   80000
25890   35000
40961   82000
36008   68000
15386   95237
20426   61000
22456   30000
13611  129700
31208   70000
14492   41000
34581   95000
42796   57000
1152    53000
49984   65000
25561   36000
22762   98000
1922    84000
22116   95000
44361   30000
...       ...
27495   67000
47642   43680
43359   45000
8685    60000
10413   42312
2082   195000
201     37000
1551    61782
16580   69910
26727   52000
40080   43200
9706    58500
31272   50000
8747    43000
37556   82000
15195  120000
28040   86000
13085   25000
2930   118000
35313   86000
22852   60000
7077   138000
40247   39276
25354   70000
19983   35000
39759   84000
11181   25000
26322   70000
20517   33000
21780   26542

[100 rows x 1 columns]
            x
37518  198000
10347   37000
37228   72000
3454    62000
28117   41470
881    116000
22224   60000
17999   41000
28601   34452
43227   90000
            x
42103   50000
38411   52000
31907   55000
47764   24000
38857   64000
42251   38000
10056  150000
9409    80000
36264   52000
8679   100000
10461  130000
20033  150000
3537    79000
28553   63000
4317   106000
27419   45000
14148   27000
2101    96000
44518   45000
22212   62000
26473  175000
14684  131000
30356   42000
20239   42000
45016   44000
16569   72151
31397   37500
45088   52000
38407   64000
12190   75000
...       ...
40200   70000
30502  100000
3038    46030
30863   65000
41651   80000
49740   76000
13536   84000
30619   85000
35693   42000
49349   51000
59      22500
31315   83356
39391   50000
38596   56000
2004    42000
39898  120000
2106    88000
29908  145000
40078   60000
6340    70000
42511   25000
13000   45000
33028   73000
12417  120000
44354  100000
3527    35000
16726   75000
2762    70000
20434   42000
34820   45000

[100 rows x 1 columns]
            x
36445   80000
38386   43000
41408   45000
46496   39000
22853   49898
15623   45000
45146  106000
32708   98000
28188   28000
4485    65000
            x
22935   54000
17736   72000
44678   58000
17214   33000
27924   45000
19823   72000
7648    93000
11780   33000
14989   17500
11749  185000
10659   20000
46646   98000
21062   40000
10227   50000
20401   27000
22238   90000
36002   67000
38003   25000
19286   52000
41560   82000
15322  105000
16203   60000
11159   90000
21596   80004
42032   47000
21920   45000
37770   41000
4788    72000
39321   80000
40293   72000
...       ...
34487   60000
6986    75000
16862   63000
25867   64000
42584   75964
46220  115000
34492   50000
23397   40000
49772   60000
10127   84500
21887   35000
28339  135000
18673   31200
9042    99120
14840   45000
16238   83000
36469   27000
18311   25000
31324   41000
11878   16094
10599  100000
15386   95237
40890   45000
1402    60000
31486   89000
4859    56000
47279   83382
4793    46000
17971   52000
29553   79599

[100 rows x 1 columns]
            x
21915   48619
30217   68000
15890   50000
13468  100000
17273   82500
14164  194000
33048   82000
39370   67000
30577  110000
16479   24000
            x
20485   34000
6289   173000
14794  123000
29888   95000
43544   63000
22541   45000
21160   50236
6182    75000
18382   80000
27210   30000
48126   50000
7250    40310
12928   36508
46894  123000
11245   54900
49610   54000
31004   49500
33840   70000
3677    90000
20767   12000
38643  153800
9074    16000
40589  133250
15899   76000
33349   49600
37500   31000
38609   59000
20231   62400
44540   75000
12439   40000
...       ...
35852   43500
4685    56791
18994  115000
29041   71000
22308   72000
29017  125000
11879   52000
20121   50000
47316   42800
29103   43900
2347    28620
48483   60000
38273   70000
44711  125000
5741    90000
41606   45000
13176  105000
22077   75000
13923   78000
18269  120000
6640    62467
22160   30000
26991   40000
1556    70000
38709   60000
34499  116480
28959   30000
49818  104500
358     77000
23679   27000

[100 rows x 1 columns]
            x
7889    35000
40895   80000
2163    26000
34820   45000
33427   72000
7007    52000
48086   90000
24030   55000
8307    25000
37810  120000
            x
44796   65000
36630   40000
37117   29152
4023    60000
22041   60000
15609   78000
11193   85000
45685  190000
24331   45000
15489   80000
33211   95000
10682   22800
41881   75000
38994  120000
20209   60000
47396   65000
12835   40000
4037    95000
41126   85000
18655   35000
46901   70000
4170    62000
18325   55000
13992   77000
20058   70000
10607  100000
1785    42000
22199   28296
10442   34687
37930   86250
...       ...
7475    36500
19110   52000
40124   23155
22935   54000
17636  180000
9296    57000
35222   63800
22793   40000
32725   30000
19304  108000
2762    70000
16236   70000
37648   71000
25196   36000
19108  129000
23098   56000
38710   85000
46594   75000
25829   95000
33225   90000
43024   61000
28523  140000
1841    40000
41031  100000
10506   52000
35604  110000
1812    45000
24344   72000
33081   50000
26338   45000

[100 rows x 1 columns]
           x
8387   41011
6288   84000
27742  28000
4043   48000
2297   56400
3445   36852
45202  48000
43898  26000
16637  75000
29311  72000
            x
14816   41000
16500   80000
12262  150000
16797   40000
40399   43000
5696   130000
15137  115000
8877    84000
40043   48000
17620  102000
17988   77248
10222   98000
775     36000
10406   80000
22786   96000
33487   30000
4314   155000
14086   38500
26525   90000
9188   130000
14674   51000
15621   53000
13319   70000
24659   40400
31512   64000
15693  150000
28501   65000
11206   27900
39421   60800
35808  120000
...       ...
20957  102000
13617   75000
13593   50000
31137   72000
34655   85000
28969   85000
45114   55000
23236   80000
17256   48000
2229    98000
6973    73440
11364  108000
30034   77000
7662    25000
23416  159000
8481    63000
17188   45000
31222   85000
20922   48000
42926  142100
47046   45000
27117   86000
46148   75000
49003   55000
23042   25000
41717   27200
30020   94000
34886   59000
8486   124111
17328  125000

[100 rows x 1 columns]
            x
16822   43582
477    100000
33     153000
6753    64000
41323   60000
37991   57000
4800    58000
34344   80100
21557  142400
11395  100000
            x
5008    55000
42626   76000
2802    50000
6347    64000
1321   115000
13951   62000
27981   32500
31581   50000
4733    91000
26340   84000
31459   32240
41827   40000
15830   58000
29896   82000
45051   73000
40624   70000
12907   28269
32112  156000
10599  100000
30877   48075
35006  110000
39415   51600
26451   70000
15749   33000
23391   62000
11745   75000
5998   145000
43936   75000
30716   72000
35696   10000
...       ...
10041   59000
11960   78000
12833   24000
33282   40000
486     80000
5438   117000
45474   57500
13252   84000
42587   61000
6060    53000
45647   25000
44265   82000
4182   113000
6866   145000
40618   35000
29752  108000
10830   60000
33547   68000
25119   60000
40670   89571
23638   81000
217    100000
45320   79000
47330   66000
33500   62000
49692  115000
9696    65000
1419    42000
17967   41820
30850   82000

[100 rows x 1 columns]
           x
37255  72000
41468  51900
42420  35000
6104   46000
40683  62100
20204  84000
30510  46800
35566  42000
39240  85000
15174  30000
            x
3283    69000
48397   56000
16398   50000
44796   65000
30192   70000
29993   52000
27725   57000
22093   98000
5742    80000
14089   65000
21291   58300
48263  105000
1480    50000
12023  100000
40564   60000
48932  137000
44448   37170
30315   58000
12883   75000
25830   46000
31379   97333
37888  140000
2496    63000
2277    50000
16265   53337
35875   52000
48860   90000
21706   78000
43835  111400
30879  135000
...       ...
32903   60000
45632   30000
24935   60000
38203   75000
6330    89000
42537  125000
40915  151000
27947   85000
45089   48000
24674   60000
9128   180000
39192   49000
1125    97200
4956    47631
39405   40000
1460    75000
18895   50000
27118   60000
10333   97000
37033   52000
42308   49200
16251   65000
1224    30000
3741    35000
3630    80000
5926    43000
11409   80000
23335   60000
10665   70000
40787   72000

[100 rows x 1 columns]
            x
41299   85000
7869    76628
14829   70000
46704   85000
16270   48000
2859    52000
2361    65000
21980  170000
7084    45000
38659   31000
            x
39694   65000
43537   50000
7197    42000
38944   90000
41681   50000
44605  185000
24482   42640
43180   65293
34835   65000
49109  108857
21456   35000

            x
10746   33200
20812  120000
48217   80000
5606    43987
44965   75000
21763  140000
31080   36000
13038   75000
2169    95000
13017   45000
            x
9865    55000
42495   75000
35916   40000
26934   68000
22805   48000
13146   48000
8441    49000
40246  110500
25125   95000
21979   50000
578     50500
39899   53000
48404   79000
10047   30912
34688  170000
35811   35000
21587   72000
21427   78000
31710   49000
23405   51000
21524   28000
21197  103000
46117   40560
48063   70000
5713    55000
27593   78000
18382   80000
18948   47616
22213   60000
12364   80000
...       ...
45174   99500
27032   50000
34230   45000
3495    70000
25663   37000
38104   75000
9669    41000
18204  112000
10629   50000
4432    60000
44366   68000
42627   10350
29698   72500
16320  119000
22345   70200
24101  105294
36340   63000
16079   50000
38071   45000
4765   115000
25933   60000
44251   90000
39276   45000
17983  116000
24590   60000
13021   55000
30964   65000
41192   48012
10959   90000
33716   42000

[100 rows x 1 columns]
            x
20337   32640
2820    45000
41746   37000
33675   65000
3909   100000
5931    82500
11121  105000
7125    53000
27996   62000
40556   53000
            x
10674  130000
33234   83000
30268   42000
17116   40000
11497   42000
37112   45700
1845    62000
25188   60000
41065   75000
45015   47299
38850   44000
46117   40560
38974   42000
44084   77000
49719   70000
7946    94074
2868    94000
34420   87699
7113    81200
46111   35000
42798   80000
5374    35397
33604  100000
31406  138000
47578   48000
4883    84800
26765   39520
25304  130000
17037   76000
19398  150000
...       ...
26376   79000
15531  135000
30423   67000
26950   75000
17985   81000
3362    45000
41351   92000
7783    45000
49867   98000
43325   56000
39225   75600
18075   63000
11507   75000
24280   53000
38121  102000
32320   86000
33455   35000
11336  120000
21335  110000
22650   33000
42709  139000
44582   49951
33260   31000
231     51000
24974   55000
49817   36000
19187   76438
8540    20600
13357  133000
15898   81000

[100 rows x 1 columns]
            x
44200   49000
19786   35000
28995   80000
2779    40000
2081   100000
43531   36000
28545   76000
11205   75000
9851    35000
20106   47844
            x
39821   65000
44950  160000
43266  109000
14890   97000
2912   114654
39800   82000
17963   90000
30197  120000
49840   62500
24981   89000
33581   33000
26648   27000
29013  110000
8286    40000
13502   57000
23611  160000
39573   54996
24689   52000
7192    70000
36138   60000
23714   36000
19711   81000
48729   68000
18912   50000
975     55000
37363   70000
23314   53000
35113   31000
8514    85000
32123   59506
...       ...
29900   70000
17487   80000
45141  131000
8692   100000
13490  120000
24179   30000
49260   30000
12676   46520
49141   57000
48883   18000
40392   80000
46460  125000
47901   85000
19203   83000
14818  100000
9763    65000
17343   75000
32807   78577
3860    32000
20148   67608
21337  116000
48800  125000
13121   75000
34506   62000
25040   72000
26277  120000
21498  123000
14617  108000
42398  125657
15071   85000

[100 rows x 1 columns]
            x
48220  128000
15989  102000
15788   71000
48610   45000
8082    85000
28862   98000
2516    45000
24933   67951
20544   42000
3318    68000
            x
47563   37000
36739   85500
32556   97500
26501   40000
35452   51000
27606   50000
32203   32000
18614   82800
11507   75000
45089   48000
970     54000
44052   92000
26679   25000
14047   89606
27574  120000
30691   26000
21690   90000
12045   30680
40905   71500
27561   80000
39624   48000
8693    64000
44113   67000
26410   90000
43674   82000
46287   50000
10705   85000
37085   40000
10206   52000
10723   78630
...       ...
15724  145000
13468  100000
33000   85000
33004   95000
47864   53888
22795   80000
42444   70000
42463   46000
11512   59000
27727   75000
4985    50980
8962    42000
49122   37200
33655   38000
44105   37498
4481    38000
12534  104000
48403   60500
41003   24044
932     58000
34634   85000
46830   90000
22418   40000
41063  100000
47083   65000
2063    50000
1438    42900
49514   30000
13703  100000
10716   57500

[100 rows x 1 columns]
            x
24174  104000
25609  150000
11661   55000
3040   145000
6867    35000
29976   80000
22070   40000
20942   95000
2850    60000
24937   41000
            x
15699   58800
25118   50000
35649   51200
41365   45000
27787   70000
40452   85000
18331   60000
21421   73759
32004   89000
49171  165000
11345   19464
27917   27200
20570  155000
26415   60000
23557   61992
24768   72720
15208   95000
16896  150000
2333    88000
48303   74000
2224    70000
18030   74000
21294   46000
45218   95000
34453  112000
3819   165000
28503   85000
7105    48000
24252   70000
41758   80000
...       ...
49836   52000
35340   70000
19811   50000
19325   67000
28478   35000
32294   95000
32094   31200
49651   13000
21983   51000
920     81000
16470   40000
45161   50000
7528    65000
212     86000
11729   45000
36893   94000
46716   50854
15767   90000
32713   42000
5475   145000
47650   40000
47903   74000
20471   85000
48289   72000
29170   45000
14040   55000
33034   60000
29036   75000
47030   50000
45502   50978

[100 rows x 1 columns]
            x
7103    29112
20246   25000
45893   42000
30118   42000
11202   80000
36661   65000
18093   28800
41249   35632
28760  114000
9347    60000
            x
9181    45000
26920   75000
45011  150000
44429  163000
31661   43000
48154   45000
18105   55000
38000   36000
1971    60000
35566   42000
25412   75000
25344  130000
19865   65000
4487   131500
32312   52000
11583   48500
8029    70000
49878   91000
48195   40000
26865  123000
31356   41000
38899  110000
30085   26000
5347   160000
42254   70000
39668   95000
21815  128000
44925   47000
14081   16000
32028   75000
...       ...
27233   60000
38234   36000
42451   20000
21982   65000
10282   40000
22052   37300
14533   65000
37302   81000
44752  135000
15700   50000
18109   47320
21705   33600
49139  110000
48487   58000
19527   86000
9819    48000
1854    65000
46402   65000
27458   41000
17800   55000
28518  107000
29926   50000
3081    28000
26273   87000
19003   60000
26711   53500
29261   55000
28230   41000
42436   43000
20563   33000

[100 rows x 1 columns]
            x
30914   53000
29144   44000
48965   54000
47786   77000
26019   52000
22623   40500
34089   58000
3786    45000
30347   89000
39852  122000
            x
9950    32000
9848    50000
14497   36940
16561   30000
27265   43000
3932    30000
31144  192000
29897   42000
3609    30000
40084   50000
47823   70000
26381   66000
152     44976
33781   46000
32988   46500
37688  125000
21417   70000
4302    45000
7781    35000
46906   28000
32952   80000
12070   83000
30651  120000
37234   93000
1535    42000
32684   65000
48841   96000
8384    48000
1014    56389
43688   81800
...       ...
9706    58500
26946  115000
61      30000
28032   59000
4314   155000
41780   93000
38172   40000
39398   42200
40088  108000
25883   89000
33733   41000
12138  110000
29836   70000
21828   46800
45532  109500
40672   70000
16139   58310
9145    75000
27647   78000
42041   50000
28671   38000
17158   26400
24582   55000
1492    75000
12392  127512
21488   30000
35252   57000
27075   32200
1856   126000
23225   40000

[100 rows x 1 columns]
            x
15247   80000
15132   60300
45758   85000
7116   115000
25226   49000
6306    93000
43268   75000
7052   103500
31047  120000
33459  153000
            x
10825   60000
11880   29559
42278   60000
16553  115000
8121   172000
42526  135000
37719   66000
14758   46000
48      70000
35927   90000
29524   60000
22399  120000
18148   48000
5328    71000
11525   75000
6268    50000
14839  160000
1558    70000
16009   86000
36540   42000
43109   55000
5371    62000
48965   54000
17908   25000
5723    31000
32921   37000
41275   86000
1998    59000
39793   65000
44749   42000
...       ...
28040   86000
24204   75000
40254   75000
2010    65000
46147   70000
33354   66832
30826  155000
5802    50000
4564    58000
27334   50000
11601   51985
7104   110000
40866   40000
9154    50000
11639   55000
8437   100000
28995   80000
1641    45392
8650   100000
28365   35000
5671   157000
12699  150000
33345  100000
8531    95000
10250   55000
5866   134000
39143   82000
18372  150000
14517   35000
44160   21000

[100 rows x 1 columns]
            x
18933   90000
33717   42000
30957   78762
36372   80000
20821   36377
40146   25000
20981   62500
6589    40000
3875   120000
41363   42500
            x
14193   38000
11655   79000
6034    65000
17944  150000
40342   78400
18255  104000
45626   78660
4510    75000
6377   130000
7504    55000
4885    54000
16119   50000
11053   80000
3110    55000
43226   37702
10261   45000
22279   89500
250     39996
37566   53000
2086    51000
38394   60000
34282   71000
6199   180000
47877   38000
44687   79000
2896    49200
31380   55300
31497   98600
1245    65000
39910  120000
...       ...
32703   72000
44893   71000
7406    87000
18599   22000
7015    65000
27467   38000
17867   59000
18548   65000
28286   63000
11910   60000
28281   65000
27459   40000
4450   105000
36604   55000
41715   25000
37424   65000
44945   75000
17455   72000
6464    21600
20258  114000
6960   108000
40281   75000
35160   40000
34446   35000
10927   80000
20326   70000
33021   54000
32133   50000
38607   68000
45346  130000

[100 rows x 1 columns]
            x
1423    67566
9884    36200
4660    72000
42400   26000
2474   100000
23257   60000
37519   80000
28055   60000
9727    40000
41851   26000
            x
23700   33276
10992   31000
36381   96000
46920   56463
46974   30000
3209    24000
15128   67000
48056  150000
13302   80000
39442   56000
14782   80000
40830   55149
35418   60000
6712    76000
24839   45000
27193   45000
31059   40000
8122    53000
44792   80000
39219   56000
2658    87000
16034   77865
31946   55000
16434   51500
22899  112000
13188   60000
36083  137000
35445   85000
9803    90000
25      60000
...       ...
42205   22000
8848    22027
23827   81000
13565   46000
1336    70000
34346  150000
5251    45000
869    100000
15461   62000
47014   75000
42282   92000
9687    44388
22461   84000
15633   52000
4540    40000
6022    38000
10060   43680
15383   85000
2101    96000
3712    70000
33728   44000
44574   90000
19694   42000
32403   82300
11325  107000
4173   140000
29990   35000
2511   120000
23899   15300
21662   89000

[100 rows x 1 columns]
           x
18417  82000
9365   39000
47174  45000
21222  70000
29720  45000
34601  70000
7142   72000
745    99600
47786  77000
39316  38000
            x
11964   79000
24665  100000
29157   69600
29419   60000
34967   66000
1147    64107
36328   48000
16780   64890
46114  123000
32945   57000
25571   57000
12770  107000
454     40000
13567   50000
22043   45012
6595    44000
4469    35000
48570   75000
18275   38000
21313   72000
20661   88000
14759   24000
13608    9000
3015    36000
26064   34000
6135    55000
37109   72000
7012    37000
28440   53000
5890    69000
...       ...
29649  150000
36521   25000
20491   45000
38728   61000
38437   55600
34790   45000
11807   70000
26896   92000
10636   70000
6485    78000
30454   53500
38278   82400
47751  140000
1236   130000
39498  110000
5588    55000
38778   40000
17471   94700
17342   52000
12552   35000
28534  110000
3899    30000
1936    68000
40588   37100
40578  126000
32202   53000
14302   90000
13106   46000
17475   38000
41940  161000

[100 rows x 1 columns]
            x
46589   60000
1095    63150
43960   53000
28770  130000
12711   69000
12750   65000
16076  130000
6642    98000
37509  148000
41929   70000
            x
26224   45000
3553    79000
16939  175000
9412   150000
28155  130519
24331   45000
16494  120000
14814   48000
42010   42000
37721   44000
38793   38836
12101  100000
39256   55600
24188  115000
1575    91475
24723   33280
40704   25000
26993   55000
34215   64000
23608   92700
7023   180000
1850    36000
5830    82500
4418    55560
16307  125000
180     48000
27321   85000
13778   40000
2118   130000
31519   35000
...       ...
19136   75000
11013   50000
29352  110000
26008   55000
13014   38000
21892   40000
34317  120000
17012   18000
21160   50236
26952   73000
46127   38000
17139  110000
16245   52000
10267   57500
42701   32000
23080   75000
44876   93600
9792    60000
17814   92000
35366   31000
17533   68000
2343    25000
24917  104000
36982  100000
3881    60000
14985   60000
21798   52000
30234   47000
3615    42000
1476    25500

[100 rows x 1 columns]
            x
3802    31000
35761   88000
36881   37000
9683    98000
32347   80000
31858   49500
5223   132000
29189  160000
6070    95000
12236  174000
            x
26509   65000
2720    90000
28397   52800
18301   40000
22719   54000
27603   25000
11571   72000
19378   97000
40071  105000
1273    59000
43178   68000
808     68000
43569   85000
35895   54000
768     45000
45435   60000
10925   96000
43438   75000
31140   51000
32965   54000
36409   68496
28829   50000
45953  117000
42207   65000
37879  100000
29185   38000
45582   50000
6149   180000
14961   86500
45233   72000
...       ...
27183   66000
35902  113000
1960    72000
6891    48000
37447   82000
23018   50000
25126   24000
30379  170000
47666  100000
48589  165000
6812    40000
42705   11376
11195   41000
33523   35000
37984   40000
44568   95000
31241   46500
7088    60000
25279   32000
30672  154438
4902   110000
36814   28000
30862   65000
10090   65000
44598   69996
12442   48500
23435   75000
31440   65000
7592    90000
7188    60000

[100 rows x 1 columns]
            x
23668   80206
37393   65000
35859   80000
15234   41159
14733   60000
49128   50000
15621   53000
25172  103000
22229   60000
30388   59000
            x
20990   60000
48530   75000
38630   60000
26787   45000
47442   54000
42445   33215
21456   35000
7340    48000
19116  165000
142     80000
27027   55000
36136   90000
15236   40000
1686    51600
34982  122000
29982   60000
47574   48814
23823   36000
45273   25500
6651    50000
46629   18412
45562   90000
38199   89000
31929   45168
37924   65000
12611   60000
18862   43896
28381   90000
41875   75000
17694   60000
...       ...
39253   70000
49574   98500
48929   30000
255     91000
25139   37873
26405   48000
28764   50000
35200   61000
4099    54000
33322   65000
25008   72000
30312  165000
34831  130000
39755   70000
49684   40000
29026   78000
33432   45000
38218   55000
31142  106000
7681    62400
24248   40000
26562  120000
15032   24000
17327   37000
27279   21184
32688   24000
36469   27000
22783   30000
15556  130000
38663   70000

[100 rows x 1 columns]
            x
9564    98480
3052    58350
10421   80000
13899   60000
6175    70000
849     32600
5378   140000
47042   70000
42103   50000
16168   53000
            x
41287   94000
19309   74000
26785   80004
20150   56160
10034  145000
5967    56724
36042   60000
43984   65000
10853   34124
28766   40000
14252   43000
9122    60000
45883   90000
33573   25000
4955    79432
10539   89000
45811   78500
18708   26000
14101   68000
4257   120000
2778    67000
43294  176000
26529  105000
2089   100000
30193   38600
33656   64000
27026   65000
17182  110000
41320   62000
4213   105000
...       ...
49057   40000
42871   75000
47976   48000
23478   70000
35187   46000
20703  125000
24031   51000
7034    75000
41630   61000
18459   87500
16217   58000
19936   22000
30926   70399
49597   60000
47138   70000
35892   54192
4002   120000
21317  100000
13199   62000
27429   61500
19485  150000
43270   65000
45077  150000
22997   98004
17007  120000
3736    60000
9278    37600
34803   48000
22922  114000
24443   50000

[100 rows x 1 columns]
            x
26531   32000
4898    42000
3054    40000
27789   88000
14851  128000
3069    25000
15381   87000
35945  147384
47977   26668
2122    60500
            x
8886    45000
37873  190000
23437   48000
39723  110000
31617   60000
22286   43000
2824    75000
9765    80000
28863   98000
17161   95975
22350  145000
39590   48000
8479    50000
21169  115000
31747  100000
7762    92500
16722   24000
8827    71000
22516   92250
23889   72000
10497   58000
1053    52660
49161  125000
19717   49000
46046  140000
41750   60000
20252   65000
13400   90000
32416   65000
1769    40000
...       ...
5114    33975
19449   47586
45047   75000
4292    33500
41864   65000
32093   65000
44465   47000
42146   90200
25156  108000
18210   65000
36740  146000
20509  106000
41975   55000
35159  110000
1001    28000
34087   27000
34241   64000
1632    32822
8496    62000
43301   48000
39434   85000
32453   65000
43140   80000
37086   80000
19789   92000
8024    62000
7182    52500
6407    50000
16615  135000
49403   80000

[100 rows x 1 columns]
            x
20892   51000
30054   26880
3664    30000
44739  105000
36584   44228
47374  105400
20960   46000
8982    45000
39539   56000
36333   20000
            x
7093    65000
5012    53000
5724    26000
22147   38000
44005   35000
13730   70000
6994   100900
35633   80000
5553   126000
35501  108000
10902   54828
25311   89400
32533  100000
11037   70000
33688   45000
48400   30000
33982   40000
28222   75000
3442    70000
47508   50000
29792   45000
18747  105000
26078   80000
6409    98000
4939    36000
34861   30000
4034    24960
39126   53500
29323   60000
15608   54800
...       ...
6651    50000
17829   34000
26870   54000
28885   67000
32333   59000
25203   70000
35681   55000
7338    65000
29286  120000
36805   70000
40146   25000
34085   54600
13229   80000
22044  125000
20057  109000
2871    53000
40234  108000
32865   50200
39436   39524
25197   74000
41112  130000
41450   80000
35557  155000
16164   68000
20832   48500
49026  110500
25267   56000
40267   23484
45841  102000
29968   42000

[100 rows x 1 columns]
            x
8834    50000
7981    17000
25125   95000
23127   65000
14264   56000
32385  118000
21805   43000
17149   75000
32825   30000
21361   88000
            x
28252   36000
34194   54000
27779   20800
6016    75000
48223  180000
38116  139294
41453   30000
31755   50000
5818   120000
40711   53000
14460   70000
33651   65000
23077   62000
15102  105000
380     37000
38275  100713
1118   120000
35793  112000
49512   25000
39795   20000
44977  103000
40643  128000
32480   48000
30322   27040
30020   94000
21103  135000
5083    62609
6099    35000
34983   54500
27529   74000
...       ...
42623  125000
15123  100000
46603   50000
42558   53000
13849   46000
15848   63000
1699    30500
4052    65000
41380   85000
39945   44000
13394   63000
41248  156000
31732   85400
37835   55000
3591    55000
5066    50000
36209   30000
11031   85000
45748   56000
22113   40248
40784   60000
13024   34000
35044   75000
34282   71000
18451  110000
1916    36000
45934   75000
11367   85280
12802   91000
21260   35000

[100 rows x 1 columns]
           x
38440  45000
36729  60000
6900   45000
7327   29000
40977  96664
45448  87000
9957   57000
27996  62000
22749  92000
33322  65000
            x
1157   144500
36534   42000
37579   50000
34466  110000
41767   35832
23170  120000
23796   78000
44219   25000
9207    74000
38327   47000
5252    33000
5708    67822
19470   38000
48681   90000
39068   65000
48509   59000
26319   40000
25160   39000
42271   64000
29781   37000
5254   109000
15069   40167
39219   56000
37659  155000
6703    80000
48406   60000
8308   120000
41920   27500
3909   100000
12692   72000
...       ...
18553   48000
3840    16800
40410  144000
30706   80000
19869   50000
48987   37000
42921   29926
44794  102000
9220    75000
31463   34000
31213   76000
6449   171700
43529   35000
23613   35000
2208    88000
23964  100000
8226    94000
28719   75000
31443  106000
31230   25000
46165   75000
25703   50000
49331   55000
39072   35200
20208   63000
41053   62000
33794   60000
4715    78000
24329  105000
6340    70000

[100 rows x 1 columns]
            x
11088   42000
9345    70000
36139   91728
38316   49000
23166   72000
11108  144000
34307   60000
28128   75000
48102   84000

            x
21795   25000
29092   84000
37459  175600
12457   57200
43285   68000
32942   60000
40024  135000
18120   84000
36488   43971
31825   50000
30200  120000
25264   78000
20693   42000
20451   85000
31935   79900
27176   35000
42840   75000
48777   60000
28472   38188
6368    42000
44558   43000
46914   90000
15279  150000
48923   73000
27904   62000
17460   32000
19317   60000
15367   62004
33852   90000
37548   70000
...       ...
30982   51000
17545   55000
14092   42000
27379   29060
23447   79000
3928    20000
14239   47000
4356   128000
3672   110000
8982    45000
44854   67000
30302   36000
31692   71600
13190   45000
24070   44484
4887    75000
8832    87500
8215    97000
22555   74000
44983   56000
29889  102000
9196    55000
22705   52000
38286   81500
43256  130000
46473   56500
8735    92000
25318   63000
274     68000
20629   95000

[100 rows x 1 columns]
            x
5707   120000
16321   42000
2846    43000
49388   60000
49988   60000
38778   40000
38919   46000
27316   65000
14212   22000
21319   85000
            x
23124   20000
17121   58342
6084   140000
43819   80000
47631   87000
46352   99700
7131    43000
3684    76000
4559    45000
29324   42000
23516   50000
23268  125000
43424  120000
47942   48000
12547   25000
34546  108000
47925   75000
14105  100000
21732   80000
48398   78000
6208   100623
20952  118000
27828   75000
38566   70000
17514   42000
42977   51000
9387    60000
25579   45000
4227   110000
42165  103000
...       ...
27899   75000
576     55000
39364   36000
22047  125000
19063   32000
38822   95000
21649   40680
14674   51000
47476   75000
39758   45000
24634   29000
7306   120000
43958   58000
37102   58000
40782   29120
26797   32000
35289   80000
21395   26000
43343  127000
11454   41990
29738  187000
34525  125000
16082   30000
11417   36000
26172   49000
22114   75000
23050   30000
29913  180000
42210   70000
564     55000

[100 rows x 1 columns]
            x
46086   70000
9458    32445
32203   32000
35725   54000
36204   45000
24490   82000
44474   66000
12647   36108
32289  105000
2484    60000
            x
20290  114000
44075   74000
42631   47000
23549   52000
14616   80000
37644   27040
17831   30000
8684   115000
10468   85000
21556   36000
24214   40000
47317   62400
44363   42000
25337   87377
48363  160000
13774  108000
10081  150000
15503   68000
7552    47340
32906   63000
37276   73400
25769   64000
26395  102000
284    100000
3482    35000
12438   67000
19407   51800
16209   40000
42230   64600
36890  175000
...       ...
28545   76000
28339  135000
43211   78000
13882   25000
6670   120000
19416  148000
45574   60000
13380  156000
37671   45000
28390   90000
5002   130000
17126  100000
39290   48750
35713   60000
1444    98500
46905   50000
45901   80000
18145   46800
30847   76000
7737    48960
38570   87115
780    153000
679    110000
28098   95000
23372   75000
39935   57000
28021   85000
41316  105000
7983    40054
31618   88000

[100 rows x 1 columns]
            x
34209   46000
40522   37440
33106   90000
21031  150000
32127  120000
43076   63800
1346    45198
17738   36000
16558  105690
13059   99000
            x
22794   65000
35838   64000
32576   46000
39558  120000
40652   35000
508     33600
10780   60000
21878   95000
44928   59000
33659   60175
46642   81640
40960   20000
24326   56825
14323  102280
35934   43000
23506   80000
16011   52000
17200   34500
35880   73000
3969    55000
42927   60000
45240   39000
22456   30000
25688   70000
234    105000
49236   80000
13778   40000
34233   57000
1781    87000
21970   78000
...       ...
48940   40000
16295   20604
40344   58000
3900   105000
27616   25000
5286    65000
20619   50000
31055   95000
39040   22000
14332   50000
48648   90000
38877   36000
43786   70000
49882   50000
31368   45000
21800  120000
45436   50000
47558   70000
31544   90000
2325    57200
14828   29328
9469    92000
27704   90000
40729   35000
20279  135167
36005   30000
36957   38000
21853   67000
37574   39635
46296   70898

[100 rows x 1 columns]
            x
48406   60000
35950   59000
32905   30000
47655  120000
46648   65000
19257   58000
44067   65000
2207     8652
14964   28000
26053   32300
            x
49857   69000
17735   57500
266     90000
24988   72000
16722   24000
25763   55000
9258    62500
30506   47500
5879    70000
11511   85000
43747   65000
23482   83000
36410   39000
19324   66000
5943   110000
11012   65000
12672   70000
24694  110000
26828   36000
15801   60000
13091   45600
34271   32000
43168   18000
48284   85656
19371   70000
38386   43000
24529  120000
28148  110000
11399   80000
25425   69000
...       ...
22213   60000
34271   32000
33278   67000
38347   80000
33629   52000
664     60000
10756   43000
9357   125000
21628   69440
12000   56000
29089  108000
6839    97000
8953    60000
36139   91728
35248   67500
30119   55000
18176  145000
44564   27000
19622   23000
44257   45000
14064   73500
5425    67000
8363    69000
9219   127127
36580  110000
32638   84000
9641    59000
15444   48000
29782  120000
38560   70000

[100 rows x 1 columns]
            x
41079   45000
29017  125000
40217   38000
13255   78000
2949    37800
27661  135000
49605   90000
45711   50000
45602   35000
18134   38000
            x
5996    51000
1461    70000
41960   61200
30283   53000
2646    62000
23805  160000
14569  107120
46904   26000
28347   43888
43700   29100
44134   45000
33255  120000
11583   48500
2529    45000
11878   16094
44382  104000
30951   55000
37836   35000
28050   60000
45101   50000
47753  100000
2999   190000
35745   68000
5065    70000
46590   40000
43840   50000
32848   45000
32218   87000
33688   45000
32182   75000
...       ...
37336   45000
30816  104000
6074    40000
8171    45000
33226  120000
48913   30000
17385   72000
21811  100000
20116   36000
4452    31080
8513   156000
21416   50000
45881   61000
28826   75000
48252   64918
42237   28000
18110   32000
29787   90000
12511   80000
36508   45000
17383   49429
37380  109600
14259   48000
49933   85000
6812    40000
35424   40000
34581   95000
26879   64947
9786    50000
34063  150000

[100 rows x 1 columns]
            x
7156    60000
5897    77000
44051   50000
49002  165000
48938   38000
48027  145000
23475   22000
22188   82000
32136   25000
16131   42000
            x
44043   57000
28846   90000
42752   79000
29260   79104
49138   27000
31162   38400
2430    50000
14208   66560
43572  160000
2261   125000
41693   77000
12944   32000
182     55059
5027    28000
4945    72000
814     54000
14231  154000
8377    95000
11689  180000
4287    80000
5323    47000
46781   51000
30941   41000
5163    43700
40353   90000
41035   69000
15056   95000
34499  116480
44061   43000
9328    91000
...       ...
13152  132000
12486   60000
27850   60000
5904    39000
11470   68640
26950   75000
35567   90000
30898   65000
44537   37400
8125   155000
45418   39000
8546   130000
41749   72000
39726   56200
37165   45000
29932   50156
37922   68000
8689    71000
9226    66000
1288    68750
22798   72000
22609   53000
43083   32000
32127  120000
35268   45000
18594  111000
48710   36000
12333   89000
32952   80000
34019  190000

[100 rows x 1 columns]
            x
10762   66000
1420   130000
15341   36919
36660   75000
3205   110000
20329   63850
47959   35000
34797   50000
1848    55000
41587   38000
            x
30166   52000
20664   51000
3766    64900
40777   62400
19552   55000
49260   30000
23130   75000
16666   90000
46362   78000
20102   29000
11697   33000
19701   40000
2616    60000
5487    53000
40835   28600
45389   87000
48619   40000
23061   52000
45765  192000
2678   107000
10123   75000
5086    25000
19174   90000
42299   48000
3047   125000
7497    44700
19317   60000
16482   60000
28315  120000
18158   38000
...       ...
36242   57000
28167   60000
34940   70000
26875   76292
35015   49000
5508    33616
12778   45000
1379    90000
28655   91000
37813   40000
1411    75000
8671    65000
38393   34000
16869   71352
2550    50000
23329   40000
41168   64000
25270   60000
41612   50000
15360   45000
35512   33000
13728   85000
2038    75000
32528   60000
15822  100000
38938   72000
2559    68000
10435   26000
34406   65000
16615  135000

[100 rows x 1 columns]
           x
46695  43000
32761  45000
9275   33000
9951   42000
15149  45000
12452  60000
5911   45000
42500  95000
33970  75000
41131  90000
            x
971    125000
11441   77000
49278   60000
1303    75000
43045   95000
16021  115250
41785   86000
48632  150000
35836   55000
34709   68000
11876   75000
33514   56700
18252   45000
42508   59000
7396    40000
32572   56000
3278    99000
45802   30000
16571   33000
10988  140000
46513   23040
15316  125000
7462   120000
20367  110000
14395   94000
17941   78000
44245   36100
20973  100000
29967   85000
14268   40000
...       ...
29367   40000
2999   190000
18608   38117
25913   60500
34478   38000
11721   81000
10400   85000
16384   80000
1896    36000
10714   41000
36914   74000
14037  150000
4819    32000
5838    38000
29687   46000
15765   34320
10032   55000
37956  145000
19654   40000
47071   56000
485     66000
9613    65000
11728  150000
11218  103400
37931   59360
1416    97000
41761   40000
26735   89000
36350   50000
45425   39520

[100 rows x 1 columns]
            x
11067  120000
43177   65000
6933    52000
14633   50000
44415   31200
37418   37000
5124    98500
6171    85000
13608    9000
39877   53004
            x
12863   34000
5180    72000
48575  107000
19353   96000
11436   47000
14908   50000
30722   18000
20922   48000
31296  105000
38127   40000
34126   35000
49464  125000
25007   26500
15350   50000
31078   61000
34007   36500
2349    22850
37342   60000
49999   70000
22652   40000
43257   37000
15163  100000
14297   34000
45072  104000
10327   74000
41666   25000
35052  117000
31506   52000
19434   45000
49062   25000
...       ...
15047   80000
36982  100000
48510   30000
42668   65000
4340    51500
27065   38000
17356   70547
5794    56000
34307   60000
22990   81600
35909   95000
42200   52380
23711  125000
7792    62000
415     86348
32300   65000
39827   98000
9284    35000
45092  120000
28972   75000
33033   32000
14893   53000
23210   97540
25174  110000
27359   94374
49865   42485
45685  190000
6157    37544
10781   25000
8992   121000

[100 rows x 1 columns]
            x
16757   65000
37367   86520
47998  110000
44280  168000
33230   75000
38520  110000
30124   48400
42105   42000
43208   70000
39327   63000
            x
8015   163500
41817   33600
43479   69000
10218   57000
39286   81000
21091   60000
42039   83000
57      23000
40202  114000
8759    61000
18775   55000
32779   90000
30229   42000
22463   80000
36911   55000
3584   125000
24026   43000
15196   99996
8305    29200
6938    48000
21450   70000
26261   74460
22378   65000
38016   62000
41742   47932
13664   35000
41181   78000
46255  130000
39648   67000
47160   55000
...       ...
11484   45000
46641  100000
11286   40000
8527    36000
21704  120000
7290    90000
32297   42500
6365    40000
11285   90000
30231   66000
20254  130000
19563   38000
39451   35000
26779   55000
44794  102000
46881   51996
21333   20000
12799  185000
33179   76000
17112   80000
28590   75000
14935  110000
6144    69400
22414   78000
35417   90000
45203   48000
24668   56000
13504  180000
34861   30000
36305   47300

[100 rows x 1 columns]
            x
26772   76000
35679   32500
40312   50000
5785    85000
46365   73000
43502  135000
45978   60000
43847   38000
7951    64259
40909   75000
            x
30690   85000
5020   140000
37956  145000
10368   32000
43044   30020
18283  112000
17521   90000
28412   84000
34139   48000
21832   92000
21699   65000
7548    65000
33812   35000
37074  122800
8429    65000
15309   34000
5579    23000
13829  140000
1849    75000
31114   48000
22920   16000
4561    91000
6785    97000
42059  110000
29422   60000
42721   93000
9525    95000
42671  100000
44681   30000
2325    57200
...       ...
35473   80000
25243   50000
8526    30000
19366   50000
44922   72000
27497   41000
45950   60000
17328  125000
21776   65000
38275  100713
7417    64000
39851  154000
4568    65000
49078   14000
6445    85000
27273  104000
9651    58000
48468   61296
42927   60000
4605    56000
34350   93600
27398   37000
48290   36000
21571   34056
5846    84000
28485   50000
42701   32000
9343    27000
7766    65000
18885   72000

[100 rows x 1 columns]
            x
21709   55000
15724  145000
19305   30000
40392   80000
1576    35500
6248    40000
38976   27000
23452   67000
20802   68900
31988  115000
            x
17047   28000
7225    84996
3099    98000
27643   34000
34946   50000
26196   55000
34855   42000
35348   70000
22434  150000
37938   50000
29777  125000
35620   40000
5249    32000
11322   98400
49838   70000
46534  110496
23974   86000
17837   55900
17499   43000
23557   61992
38350   90000
34607   70000
48139   50000
17657   84000
28054  122500
33778   42367
32697   65120
25357   71000
17562   45000
45010   36000
...       ...
30578   32000
17794   74000
14845   65000
32240   65000
33736   46000
16207   39500
42174   58000
32884  110000
30218   30000
33815  120000
48338  108000
12951   80000
25150   30000
460     67000
38816   56650
14221   95000
24951   19956
26600   72000
19255  149000
34112   79000
15572   55000
49662   48000
20759   80000
48961   70000
45868   99000
35342  120000
39506   30000
28330  110000
3680   189000
44081   99167

[100 rows x 1 columns]
            x
32273   77392
21131   68000
14972   40000
16349   59100
32717   48000
24579   57600
26968   65000
1965   150000
7788    45400
28235   60000
            x
16237   64500
40345   56000
2495   116000
45454   27000
29052   92000
6863    38000
7327    29000
15627   85000
32056   80000
17833   34500
26069   83000
17758   48000
19319   35000
11330   83004
5815    98000
47797  120000
48640   36000
47745   55000
32570   60000
44746   68000
37883   68369
31321   57000
38337   40000
28428   76800
32916   27840
201     37000
48638   83500
46196   76000
21947  110000
30543  165000
...       ...
36251   50000
23348  154000
34312   32000
9135    38900
31595   90000
29949   36000
41927   75000
32482  140000
30968   28700
838     49000
26364   40000
6250    36996
31924  100000
48669   68000
9977    73000
23130   75000
567     64000
19801   89000
20759   80000
3434    37000
39138   50000
16472   56850
34227   95000
7656    92000
36803   34000
21121  142000
47776   64000
9152    75000
42466   45000
48843   55000

[100 rows x 1 columns]
            x
8359    52500
32640  110000
38178   33000
16973  104000
9842    70000
38785   55000
47126   75000
48352   80000
37525   55000
41650   42000
            x
13848   29000
3715    23000
6693    45000
36376   51000
41974  103000
43393   75000
5313    80000
5015    53000
33492   58000
1764    43075
740     30000
29087   48000
16259   38000
25993   34979
34373   35064
29456   34000
44023   65000
46253   70000
44861   97000
36385   57000
23431  198000
38699   32900
3886   100000
3822    80000
45623  150000
32437   80454
1054    98000
10527   75000
1920    37000
11340   62999
...       ...
37552   45000
43066  196000
5386    93000
22648   27800
47044   58000
23716  192000
18802  115000
49081  120000
44646   48000
17652   29000
36384   45000
19727   36000
47839   42500
46138  105000
31080   36000
22737   44512
22398   69000
32192   46000
2500    75000
48741   75000
21486   80000
42027   74000
42149   90000
5309    35000
17413   90010
32927  105000
23023   50000
5406   120000
33191   64000
9123    31000

[100 rows x 1 columns]
           x
18989  46000
5550   42000
7590   42000
13025  89793
23550  42000
41281  60000
13374  51000
40100  42000
29930  62000
16529  45000
            x
35478  115000
47072   20000
36474   79000
18557   22000
34007   36500
7750    65000
36693   53400
47683   65000
10078   36000
4616   124000
7620   100000
25275   44000
39830   53819
30124   48400
10303   76000
12439   40000
30787   45000
23654   53000
49909   42760
37081   20000
40090   57333
4509    50648
176     30000
12196   28000
40652   35000
14893   53000
7107    75000
42617   75000
2413    75000
35065   26000
...       ...
15948  135000
22817   72000
38330   52000
24169   80000
27696   42000
3096    65000
41933   50000
22119   72000
34855   42000
28494   84000
38548   72000
44541   86000
21902  101000
26426   29000
23303   96000
49733   75000
31067   53000
7023   180000
43562   45900
10709   70000
14980   36000
41502  115000
9317    61000
47016   60000
2383    45000
2614    45000
10573   25000
39976   18500
32514  130000
36660   75000

[100 rows x 1 columns]
            x
38331  109000
24733   64000
43317   30000
21243   40000
46464   30000
22062  158000
23950   58000
49467   60000
35852   43500
9887    90000
            x
24113   95000
11480   96000
11449   22000
8894    59000
32747   75000
43244  110000
25172  103000
41957   95000
43599   43000
14653   45500
22254   30012
40503   82000
30478   35000
10899   55000
28195   59000
49546   40296
24346  125000
34810   28000
17821   48000
31996   65867
10128   66900
44203   93000
32851   35000
31612   60000
2093    35000
36680   50000
19706   83200
13042   80000
6685    60000
25685  112000
...       ...
34890   62000
45764   65000
19129   68000
44556  110000
7846    55000
34137   80000
38155   56000
15442   72000
12425   78996
42885   75000
25315   95000
25071   50000
3183    61200
43865   48000
23820   97500
45177   57988
42124   44000
17247   82000
27001  150000
37408   62200
3809   170000
34519  158000
27677  104400
12231   59000
25381   26000
10411   91560
31378  100000
24487   43000
38630   60000
35478  115000

[100 rows x 1 columns]
            x
1346    45198
20185   33190
42777   65000
30553   70000
34011  150000
36999   98000
40172   51660
48677   36600
2635    56000
26537   50000
            x
19603   32000
40916   24000
37187   40000
20395  127594
23829   44700
1719   132000
28428   76800
38996   30410
16037   80000
43033   79000
2071    55000
3131    60000
8290    65000
40604   71000
16339   18000
1094    48500
31104   56000
46120   48000
41008  105000
13923   78000
41184   70000
44954   44000
2298    85000
283     58989
18828   48000
8914    40000
6868    51000
11276   75000
70      36000
41032   65000
...       ...
35160   40000
4775   100000
11970   63000
26368   53000
26775   45000
40823  114600
34107   82584
40421   41448
29736  115000
35558   55000
32392   55000
4190    50000
20089   57000
40196   60000
41146   66000
13942   41000
28673  116000
13062  110000
25131   14000
5122   145000
9505    52000
45998   23000
19117   85000
25311   89400
49992  104000
23774   50000
26088   73000
23584   85000
23730   85000
32322   55000

[100 rows x 1 columns]
            x
31742   85000
44735   50000
2527    63000
12139   27600
26720   73000
18998   42000
33102   39000
48679   60000
5235    40000
13156  107000
            x
31785   40000
29914  120000
33827   60000
28761   57000
30683   55000
31811   50000
32560   65000
11624  111000
15288  125000
40813   89004
29198   60000
4868    57000
4432    60000
5729   115000
35192  110000
30790  129000
4244    80000
17598   78000
29078   48000
37345   56000
46987  100000
8077    60000
10226   59670
4184    35000
25494   88000
28200   78000
26687   75000
24081   55000
45282   44000
11595   42000
...       ...
1538   105000
6402   115000
26489   21500
48045  120000
2577    46000
10219  180000
1958    35000
48325   36000
14562   45000
21476  100000
29192   70000
5955    75000
27505  107000
1357    40000
46322  100000
19249   44851
10200   55000
40890   45000
12789   47300
38543   16627
48560  105900
3628   120000
2630    76000
39113   85500
46919   40000
15458   33000
11827   37500
18257   27000
28585   75000
31599  110000

[100 rows x 1 columns]
            x
18523   55000
26841   83000
33776   26004
49460  121000
43807  105000
39056   42000
1559    35000
24910  115000
5537    42000
11527   14880
            x
12621   85000
14163   59196
21897   60000
26139  160000
28875   52000
5159    43000
17452   51000
16896  150000
330     85000

            x
12753   30000
1650    40000
48723   60000
30211   51000
15139   60000
15173   35651
4418    55560
20571   90000
37027   61000
9584   140000
            x
6623    43000
47677   83000
23080   75000
10466   90000
44581  160000
18002   34000
31318   55000
33809   70000
1649    41000
1296    75000
38858  100800
48883   18000
12983   45996
28024  105000
25310   75000
6506    80000
14030   90000
9134    55000
43851   55000
14462   42400
35506   31000
5900    29444
9342   160000
31457   50000
43504   58000
41872   80000
5127    60000
44648   60000
8529    41715
44152   32000
...       ...
26420   65232
25058   95000
16869   71352
36714   60000
21954  126000
26148   59000
1570    67000
46774  107000
22168   65000
41866   45000
35044   75000
5131    75000
34565   60000
37482   30000
15402   51000
12087  160000
11437   65750
19101   63999
4603    48000
34508   55000
490     45999
1786   179900
7782    82000
1987    90000
23386   20572
48521  150000
5958    80000
29971   33000
15536   60000
21156   32000

[100 rows x 1 columns]
            x
13081   55000
40233   30000
19117   85000
47498   24000
1381    67238
20963   62000
6850    75192
13519   80000
19108  129000
35584   46000
            x
9124   140000
45927   43000
48801   40000
2048   136000
33971   55000
18039   75000
8662    72000
15613   30000
44036  117200
24637  101922
14688   54000
14679  140000
25615   52000
8230    60000
20997  180000
43055  118000
37118   55000
43742  120000
31427   67500
38334  150000
32118  100000
3299    40000
741     91000
22512   40000
39486   12000
4345    55000
26123   43000
30634  165000
32781   50000
18806   47000
...       ...
43382   38000
27763   82000
1238    65000
27046   60000
32902   92000
39424   50000
37208  100000
499     80000
44031   98000
19443   41700
35259   45000
29927   98000
5960    30000
3076    45000
44242   20000
34039   95000
49591   40000
49332   78977
45200   22680
13786   56000
10854   74706
906     47000
44596   33800
16346   50000
40989   91084
24331   45000
47561   35200
21628   69440
34641   90000
10287   39600

[100 rows x 1 columns]
            x
31560   66000
3854    70000
12514  130000
48946   95000
31175   80000
16955   77000
36099   56000
49271   25000
34198   50000
42151  120000
            x
1565   125000
8849    29000
20070   99800
18907  138000
28256   42090
20317   47000
30624   54000
21349   62000
823     50000
37728   97000
40847   75000
33412   85000
30342   45000
15759   84996
728     87000
17240  110000
32355   60000
28893  115000
14748   40000
42491  146368
36455   56400
10279  110000
38057   43000
23576   76000
35178   33000
29787   90000
4177    89000
35253   15000
21495   49000
43757   35000
...       ...
22484   30000
30211   51000
16212   80000
17472   30000
32283  130000
12977   45000
15328   48000
48887  110000
18828   48000
10048   52000
11657   80000
26521  140000
25784   27000
33982   40000
27055   70990
14770  120000
27418   50232
6014    35379
19006   68000
27043   32797
32771  130000
45599   68000
4456    93500
11033   31587
17997   72996
15237   21250
9005   102000
48240   79000
41078   64962
30278   85000

[100 rows x 1 columns]
            x
22421   37000
4951    53334
18771   70000
20933   75000
41149   55000
4802   170000
16241   60000
21474  115000
38670   78000
11912   40000
            x
26654   96000
4224    40000
16139   58310
4364    38000
10803   24000
13302   80000
12568  120000
5292   102000
7044    75000
31992   80000
42855   90000
183     27889
49939   90000
7409    46500
19578  100000
10230  120000
15248   45500
39138   50000
48019   54000
9490    69000
45393   71508
16918   61000
47059   80000
47247  100000
20806   80000
24314  119000
33011   59000
35348   70000
5435    36000
3355    46000
...       ...
15892   45000
6485    78000
16692   74000
26768   47000
23996   95000
17818   80000
45214   70000
10279  110000
53      30000
27120   82500
46702   60000
49829  118000
20451   85000
44653  128000
28046   65000
43516   30000
29625  101000
29308   78000
34758   95000
21201   85200
38874   32004
29234   65900
45395   78000
49538   50000
24389   40000
21054   45000
42467   42000
6732    90000
24855   30160
41260   68000

[100 rows x 1 columns]
            x
46406  191000
12343   21120
7521    95919
10542   76000
26711   53500
44782   93000
5612    52000
36003   56000
33870   36000
49213   65000
            x
47002   73000
8071    85000
5179    85000
26888   19200
18169   95000
23980   41000
28042  100000
9532    90000
12299   55000
18787   75000
34769   45860
3830   150000
9543    41000
18407   70000
24014   95000
43043   37956
9391    40000
21250   63000
6454   185000
36372   80000
37450   75000
10844   42000
29259   98000
8369    50000
32539  175000
25940   47500
31788  114000
48707   69000
1158    61235
23435   75000
...       ...
35547  177000
36647   90000
31617   60000
14026   90000
40086   93569
29263   44000
43019   65000
34594   50000
35062   55000
41985   90000
11044  105000
193     38825
8596   120000
12440   90000
2678   107000
1098    70000
3383    50000
19641   85000
16793   45000
41952   70000
39845   75000
41817   33600
44080   29400
35618   48701
47894   66700
21352   22000
13097   42280
7228    29000
27855  110000
17207   28000

[100 rows x 1 columns]
           x
36402  67000
13513  54000
43680  88926
1158   61235
20409  72000
5272   83000
32304  39000
28703  55000
174    35000
36687  58000
            x
19849   41766
41709   89000
6173    51200
16148   80000
31057   50000
27103   29000
49040  100000
40471   43500
38077   48000
20993   64000
27349  104450
47782   58000
26976   54157
29379   50000
2281    42000
46976   49000
47611   65000
24088   80000
31373   61104
43132   55000
27454   76000
41146   66000
3714    38000
35465   66000
15909   70000
26108   38000
48186   33000
10631  100000
835     60000
22388  105000
...       ...
24942   31844
34483   40000
13243   75000
18037   59915
26135   63000
29774   87900
19298   80000
23391   62000
30156   60000
23823   36000
32162   84000
1582    90000
43107   37000
42774   52000
12535   47000
49051   42290
6753    64000
21197  103000
40535   50000
42590   57000
9999   110000
28954   44140
2287   123600
39081   80000
18966   70000
12722   79000
13547   95600
40372  100000
42654   60000
13240   93926

[100 rows x 1 columns]
            x
29690   34474
6593    64000
38411   52000
16064   70000
18742  175000
2714    53000
14935  110000
46723   41800
6638    66000
18991   60000
            x
21664   29120
10865   43500
37341   46000
28730   87000
4507   105000
46919   40000
13182   95000
38831  104000
15917   52000
29679   70000
36529   85000
17508   52000
11835  128000
30537   68500
15940   85000
37779   46000
18588   94000
495     70000
21052   96000
33202   78000
14785   68000
2979    59436
38759   40440
29611   72000
4878    73000
31415  104911
8243   115000
47313   45000
38117   39000
21227   30000
...       ...
22868   23500
18134   38000
9070    62000
26031  115000
45236   49000
22150   49000
19753   35000
5837    15800
41479   67163
6414    48000
5064    95000
6335    35000
13067   45500
8982    45000
33425   47000
35618   48701
46346   44565
10811   38000
6283    40000
3670    60000
30337   97000
45140  104000
49327   75000
4505   124000
17107   31000
34195   49000
16316   22000
45096   55000
3330    36000
44428   75000

[100 rows x 1 columns]
            x
26808   70632
27231   20000
45750   36000
13827   41250
12290  131000
45323  120000
9539    39000
19665   59000
18064   85000
49221   72800
            x
46835  172000
20696   82000
10852   43000
12149   72000
19198   48000
47698   70000
43372  110000
12263   70000
11505   75000
35811   35000
28549   50000
1988    67500
9499    43000
15563  136000
40431  100000
40491   44000
21684   63000
20244   62000
41421  107000
5191    34853
42541   51000
44024   84000
1401    78000
27595   65000
44041   65000
22720  100000
1483   104500
26001   94000
33230   75000
22908  130000
...       ...
20380   54000
26045  140000
29660   30000
1428    30000
30060  110000
41289   52000
171     87400
4081   150000
10039   40000
18410   48000
21025  100000
34154   40000
46743   38000
49976   73000
43810   40000
5754    54000
17160   55000
47771   25000
45274   70000
17809  115000
927    120000
40854   47352
30968   28700
34383  130000
7366    74000
22892   67000
3453   102000
26308   60000
3021    65000
28357   84000

[100 rows x 1 columns]
            x
28530   45000
14427   45000
46757   49000
38411   52000
41248  156000
30966   48160
36648   74000
2055    66000
38656   40000
49948   48000
            x
3389    46000
43258   75000
6954   120000
8780    21600
47115  110000
31666   64000
363     58446
21026   52000
17270   50000
10421   80000
23676   50000
18083   78000
43401   72000
3216    50000
29404   47000
43563  125000
31842  145000
22544   48000
42366   15000
36705   50000
3315    60408
38894   55000
36434  105000
1548    24000
21822   42000
37983   40000
16617  150000
31763  110000
26684   87000
14352   64000
...       ...
1170    50000
39869   69996
29174   80000
22108   70000
17326   52000
3419   136000
28141   99000
17828   45000
38997   94000
47789   51094
21517  115000
29475  175000
44306   80000
41310   50686
21231   97000
23686   15500
16832   48000
27536  155000
24450   36000
31313   58000
32772   65000
19913   36000
18973  118000
31170   57000
44572   42000
37877  160000
3854    70000
3545    50000
1303    75000
11125   55000

[100 rows x 1 columns]
            x
33500   62000
26496   29120
19009  100000
30422   43000
4408    90000
10790   71000
11072   42000
25105   40000
33189   45000
6768    54080
            x
34744   21000
31154   50000
7451    89000
30260  123000
45267   60000
48608  123000
27242   40000
4801   105000
7703    27800
24820   70000
8785    95000
15402   51000
49925   84000
23366   68000
16754   67000
26787   45000
26313   98000
6219    59500
16574   50000
6978    52000
41581   25000
32644  170000
20911   40000
14821   63000
46943   51000
35867  107000
42089   57782
17954   63000
11639   55000
43116   21600
...       ...
34707   84000
13952   41000
10294   80000
23101   80000
12903  120000
5916    24000
33784  130208
47857   80000
6765   120000
39156   12000
10925   96000
49330   45000
11562   45000
49801   69500
18581   85000
32048   30000
32038   43000
8192   100000
16922   73000
790     50180
23109   50000
6261    35000
29238   62000
32953   60000
35049   62000
16937   40000
22456   30000
26702   46000
13316   58500
46970  124800

[100 rows x 1 columns]
            x
21510  185000
17014   65000
47263   80600
12903  120000
125     75000
47673   60000
23623   55000
6967    39830
25281   60000
29198   60000
            x
8279   135000
49014   54000
31326  110000
15845   76800
34298   50000
42001  105000
6418    54000
37858  115000
10169   35000
28759   33000
18056   85000
11666   36000
41884   72000
25700   28000
15374   65000
47251   41000
18040   55000
25836   90000
26411   97000
28870   42000
30630   50000
44741   48854
45605  170000
7490    32000
33467   37000
851     70000
17810   50000
33619   70000
45395   78000
13920   65000
...       ...
11403   50000
3625    50000
16159   26000
49547   65000
1655    42000
11341   60000
47506   65000
292     60000
47778   84000
22480   49000
14723  120000
35055   35000
35354   42000
8441    49000
15770   48000
17919  140000
45136  190000
48633   55000
5509   100000
32379  130000
22105   55200
41033   67075
3613   110000
29781   37000
4218   100000
44208   37000
22194   92000
16721  110000
32843   75000
6397    43893

[100 rows x 1 columns]
            x
10940   48000
36089   47863
45932   68000
42875   45000
22032   60000
47499  110000
26417   42000
33282   40000
5256    21360
48947   30000
            x
26119   54000
4917    60000
25080   85000
47138   70000
8486   124111
7230    85000
21673   75000
42727   40560
19741   55000
31789   24000
16808   50000
40964   55000
29767   25000
30367   63050
17001   65500
33625   76500
31057   50000
14262   92000
29242   35000
15787   60000
33504   30820
4462    80000
20679   72000
9937   106000
1540    60000
8506    96000
24028  180000
49605   90000
36023   40000
9006    52000
...       ...
39098   43000
48352   80000
8718    88000
28440   53000
29120   52000
13408   24000
19831   78000
41179   84000
22836   66000
18318   56000
27191   55200
1094    48500
19069  120000
12747   36480
10107   37191
30807   85000
42035   90000
36034  195000
35429   45000
44245   36100
24493   50000
22188   82000
33437  105000
15762   43000
30963   60000
34220  175000
3094    65000
1491    33000
7244    35800
35286   55000

[100 rows x 1 columns]
           x
29728  75000
9301   38000
41056  25000
33710  74400
19771  72000
12370  70000
43537  50000
13514  77000
36588  19000
46176  41000
            x
49012   50000
34384   55000
32207  137000
35811   35000
32657   50000
19976   68000
11286   40000
29006   61896
34110   90000
39534  170000
27881   34000
13833   31000
3479    35000
19595   50000
4942    34128
22757   75000
12780   30000
46768   41000
34778  104000
26925   60000
42166   31000
5760    56000
37506   32000
369    110000
27317   90000
23861   73000
19996   45000
2525    32000
28909   35000
33136   55000
...       ...
36246   34000
3136    95000
39791  115000
26316   70000
32531  130000
39801  113000
4008    42000
30754   50500
25260   40000
49232  100000
31976   42000
8367   150000
19294  118956
20274   50000
14261  155000
17824   99700
90      26000
37619   80000
39327   63000
14420   78000
16140  143340
9414    70000
28925   84000
42584   75964
33020   80000
18350   77000
23681  110000
34583   45000
28865   65000
14181   68000

[100 rows x 1 columns]
            x
5384   145000
14202   35232
26467   57000
23219   31000
34483   40000
22633  120000
21362   58000
5124    98500
16646   42000
47133   18108
            x
35948  106000
46656   60000
45955   52000
37042   62000
28878   48000
9188   130000
36523   86000
43082   25000
8741    58000
35790   57000
38418   60736
49622   62000
32469  140000
1563    63240
5823    65000
17480   50000
37125   51000
21335  110000
43305   75000
29461   34200
15022   45000
2651    50000
30627   45000
21992   85000
630     43000
14304   61516
12670   45000
25958   40000
33216   74000
18809   47800
...       ...
45754  105000
21833   95000
30167   40000
21387   43000
25632   23148
5958    80000
36573   76000
20475   35000
12802   91000
6801    50000
11717   62000
11684   56000
8256    43000
26586  115000
10149   90000
8836    49500
29585   70000
48227   45000
1539    64000
42593   90000
8554    85000
47686   43000
6292    53000
2502    60000
19639   82000
48717   46000
40385   80000
6951   102000
24785   75550
15741   55000

[100 rows x 1 columns]
            x
19985  120000
9223    75000
100     42000
19387   56500
10955   70000
45703   50000
31783  107000
25311   89400
740     30000
41360   32000
            x
6698    82000
39092   95000
4967    63960
25847   60000
43579   62000
28917   40000
7246    38166
46365   73000
49249  165000
4236   125000
6418    54000
40561   75000
6758    64000
9377   120602
40400   65000
24710  105000
45820  112000
34916   96000
48920   83196
46739   55000
5751    67700
17682   79000
24266   50877
46034   90000
10799   50000
84      45000
39800   82000
33774  135000
29398   24960
17237   50943
...       ...
14020   41000
24070   44484
15745   24000
41633   35000
21200   85000
25648   67000
41782  105000
13802   48500
29282   80000
6353   110000
46576   59065
47548   70000
31812  103000
24388   40000
42152   42342
10033   49500
19171   25000
34628   22000
45350   20000
26515  160000
33520   70000
42572   68000
38854   49000
29008   90000
16936   59712
34489   65000
31615   38119
18424   54000
35014   89000
25900   17500

[100 rows x 1 columns]
            x
27977   70000
19232  175000
29172    8892
40939   31200
15381   87000
949     40000
20143   80000
46757   49000
47776   64000
43988   30000
            x
13810   67600
12372   50000
19668   57000
187     53000
45024   98000
22022  130000
10105  100000
739     70000
27667   21768
39618   57000
20669   75000
36847   86000
3391    80000
37611   45000
36311  120000
15118   85000
4217    38200
47184   35800
45459   36500
49353   77000
19759   33300
30831   66000
7889    35000
43787   31000
6281    31000
40714   95000
41764   30000
6376    60000
26976   54157
40547  105500
...       ...
27828   75000
32011   37100
34574   40000
6798    44200
18902   70000
43613  110000
49406   45000
40374   80000
29264   88000
45344  120000
48862   91000
15561   22000
2634    47000
29490  110000
28998   48000
3611    65000
10223   45000
34665  125000
30159   45000
35517   32000
12208   58240
2911    38400
7362    99000
26568   42000
18521   12000
38753   54505
3647    41000
5552   102636
9613    65000
30907   63000

[100 rows x 1 columns]
            x
44247   60000
10920   88000
20712   59870
9702    43000
47637  108000
24443   50000
38887   75000
19278   45000
45193   90000
9098   190500
            x
16687   24000
31807   50000
49101   75000
7747    86000
38412   86000
37637   65000
48948   52000
43049   45000
20586   45000
25479   63000
45948   79500
14611   87000
11446  100000
31916   31000
29292   71603
5973    75000
10082  115000
44341   45000
34651   36000
6307    60000
16205   25000
4501   107000
7606    60588
2470    65000
49670   69000
38181   42000
7394   113000
42186   81840
27168   49300
5760    56000
...       ...
8900    26500
44120  150000
23087   35000
34189   75000
11827   37500
28929   65000
15236   40000
14986   45000
47301   45000
21676  138500
31018   57000
7411    76000
33526  127000
36943   59800
32742   50000
37240  119000
23285   39000
23658   41000
43928   87400
47970   43971
3136    95000
31123  103000
24692   41000
21792   68450
42353   65000
5529    79000
12591   39200
21621   56500
21885  142000
3198   122000

[100 rows x 1 columns]
           x
49306  47500
6475   30000
47930  54996
224    43000
12596  85000
16913  75000
24493  50000
26423  30000
24215  30000
13382  95000
            x
27222   98000
15419   23000
19776   80000
925     35000
7452    95000
19417   77004
38138  120000
17500   62400
11566   49000
31725   60000
2666    86000
21182   48000
43728   42000
43534   60000
15666   54000
46214   45000
16473   28000
14460   70000
5482    45000
14851  128000
6717    62680
31329   38000
29244   66034
19413  100000
24727   83000
30625   52000
19907   36000
2666    86000
18343   29000
40905   71500
...       ...
26884   14000
20975   75000
44555  130000
9462    64040
18786  100000
35749   38312
3652    38000
49135   80000
38510   51000
20753  135000
45645   47000
44984   45000
49389   85000
44190   72000
24497   33000
37322   60000
34632   75000
941     30000
35190  143000
40957   25000
28751  185000
38810   54000
34551  100000
37906   52500
11527   14880
44252   42000
2428    28600
10018   30000
17178   47520
6453    53000

[100 rows x 1 columns]
            x
39374   42000
46673   41000
23131   52000
24131   92000
8160    24000
40173   80000
162    145000
45656   56000
26948   56600
19623   71500
            x
25119   60000
22935   54000
2956    60000
27804   71300
1498    41000
40038   36000
47070  120000
35820   38000
5851    42000
20039   78604
42603   36000
23854   49000
47148   40000
37602   40000
26189   54000
29478   35900
36178   65000
49549   68000
35152   18000
37123  100000
35779   50000
33907   90000
39339   75000
21986   85000
7370    90000
23280  180000
3762    60000
45626   78660
3716   168000
9127    52200
...       ...
3744    92400
8236    28000
12048   60000
49367   30000
49748   30450
37950   36000
34515   48000
29712   64000
16092   36000
13828   57640
36975   51000
40181   50000
14657   20000
12198   80000
32757   72000
18400  175000
2835   170000
28773   50000
29312   46915
5461    60000
25215   20000
20421   99000
47454   49500
42841   59184
21732   80000
28784   86000
17892  109000
4320    56000
36121   84000
22528  100000

[100 rows x 1 columns]
            x
469     75000
23845   46800
5747    31200
39791  115000
27662   65000
29186   90000
2926    25000
29853   32000
26390   25000
33950   30000

            x
4309   150000
15272   24000
28740   80000
23623   55000
42329   70000
27993   69000
4872    97000
39325   85000
25419   24000
43624  146600
9462    64040
34946   50000
37301   80000
31578   28000
39244   46000
32821   35000
21765  110000
7653    57200
33030   66705
354    103000
1410    87000
35239   56000
21972   50000
48073   93000
7774   106000
15556  130000
9538    54000
36880   28000
13274   70000
38409   73000
...       ...
25202   50000
29669   75000
23591   68000
14694  100000
22694   70000
9590    88700
47739   75000
3616    28000
11723   48000
39937   40000
17385   72000
4993   120000
5994    55300
47876   97000
27772  125000
17239   59016
34769   45860
14484   67000
22745   70000
37163   65000
20484  100000
15625   53000
6763    37000
34647   50000
16596   42000
9428    60300
10453   90000
44224  101000
23256   50000
17217   92000

[100 rows x 1 columns]
            x
49219   45000
9407    97500
19542   80000
11238  115000
46771   90000
43804   30000
8467    72000
21677  158000
33796   30000
35667   40000
            x
30509   55000
43703   70000
47236   72000
47653   70000
16047   85833
16656   65000
20083   62000
3401   150000
27610   65000
34611  158000
44190   72000
41324  168000
8583    55200
25030  130000
7562    72500
10195   41725
9266    92000
8228    35000
17149   75000
17236  195000
38006  170000
17633   88000
45106   39000
11085   90000
47982   73000
2896    49200
16109   48000
29139   30000
41542   26000
26325   96000
...       ...
37447   82000
24304   64000
2799   108000
33824   56000
35681   55000
6964    35000
30919   79000
12320  120000
21593  107000
17835   91000
29091   50000
26529  105000
31768   55000
19693   80000
11059   11295
28475   85000
15891   63000
3698    30000
43909   46200
14561  110000
22179   97000
7329    14798
18000   68000
48949   32000
36650   44000
10981   61000
49687  120000
4487   131500
19691   65000
28661   61000

[100 rows x 1 columns]
            x
14950   55000
18803   61776
41314   85000
23465   36000
49632   52000
41896   30000
45708   58000
3020   125000
6647    40000
40759   62500
            x
28224   54000
47386  100000
42369   98000
43625   84000
49232  100000
16761   72000
36746   50000
16489   60000
16895   43680
47700   52000
11042  101900
49911   35000
7216    45000
15924   37200
43584  190000
32855   84000
13862   99996
41408   45000
6625    44000
29306   40000
8944    60000
9511    85000
45710   51000
43513   77000
4935    45611
14690   70000
35944   47000
11300  105120
18086   90000
10667   70000
...       ...
44506   95000
38256  157000
15916   30000
6750    30000
9271    73000
38761   75000
23537  130000
28924   38000
38828   52000
45032   59900
46706   60000
443    158000
40080   43200
31514   30000
10667   70000
6370    65000
38008   60000
14795   60000
8275    54000
20533  125000
24658   24960
29996  114000
32644  170000
17112   80000
7253   120000
28945   69744
15056   95000
15197   67129
25616   30000
1090    15000

[100 rows x 1 columns]
            x
6802    75000
4634    82000
47637  108000
38321   70000
19816   91000
14500   80000
2207     8652
20079   59400
42870  103000
6350    44000
            x
46685   83500
23361   56000
1755   128000
32733   70000
12647   36108
14174  125000
38171  105000
22255   84000
47263   80600
5787    31200
30351   80000
47718  100000
22589   81000
27737   45000
9776    54860
22836   66000
40330  108600
42361   55000
3135   105000
27488  100000
21117   56000
25497   24440
48813   47000
19311   30000
9768    80000
27419   45000
42282   92000
19625   50000
49647   33900
47529   75000
...       ...
10042   57900
6439   125000
1467    84700
17190   86000
21464   60000
41157   68500
48306   95000
15707   23196
9596    54000
22128   94000
5806    30000
18000   68000
31488  155000
30316   50000
30250  105000
42926  142100
45302   73000
4465    49749
24476   45000
22032   60000
30533   24000
23332   70000
40534   33000
35188   27000
37383   53144
47620   44900
18166  108000
14021   60000
46039  100000
4665   102000

[100 rows x 1 columns]
            x
1033    70000
12634   22986
45632   30000
8667    70000
1230    45000
25634   80000
3452    53301
16508   40000
9518   138000
11659   78000
            x
28083   99500
15624   54000
1170    50000
11552  168000
19598   50000
11871   36000
23825   30000
12716  100000
17162   57000
25456  100000
7081    80047
4437    75000
46895   46000
29881   44000
1730    38000
43948   90000
2816    70000
27973   65000
41069  100000
9082    51200
46082   65000
34025   56000
3272    51000
30919   79000
29916   75000
472     41200
23386   20572
41101   70000
25197   74000
16910   52400
...       ...
10134   40000
44436   40560
29216   38500
29292   71603
14710   60000
47422   30000
20880   38000
20551   95000
30379  170000
45263   80280
21034   20000
24219   41600
1563    63240
4503    38000
198    153816
30575   90000
700     51000
39333   75000
14947   55000
20630   63000
45390   40509
9575    72000
10220  123000
35566   42000
27908   47000
36720   60000
6463    26880
20737   28000
11089   29000
8480    70000

[100 rows x 1 columns]
            x
23794   68000
49967   60000
11062   60000
4847    36000
39520  117100
28679   65000
48044  160000
41565   26000
7926    33000
39464  123000
            x
18735   50000
2921    55000
18661   35000
25859   80000
2246    65004
21181   60000
1661   115000
5632   150000
17758   48000
25876  107000
1168    44000
40286   45000
14255   72800
9678   100000
25012  125000
38102   90000
20144   40190
19173   45000
10951  140000
1811    88000
12925   45600
23923   47000
30095   90000
33909   80000
49391  130000
3466   145000
25092  105000
36666   60000
11143   36000
26034   58000
...       ...
48824   14400
11833   45000
15870   52000
43973   70000
43409   36000
23956  103000
16533  130000
8669    32000
26450   48000
12095   47000
22550   60000
3098   160000
43448   35000
40922   49000
19453  100000
18192   42000
6209    85000
40208   76400
11598   80000
17740   44200
35157   40000
24275   50000
21054   45000
49112   60000
10815   58427
47905   53000
22689   30230
41378  118000
28648   58000
21600   60000

[100 rows x 1 columns]
            x
43747   65000
13902   31000
46944   50000
18255  104000
12133   39000
22042   38000
14331   43408
24285   96000
45200   22680
8071    85000
            x
5897    77000
30000   70000
29797   41000
19459   51000
27056   70000
7753    32000
6899   105000
34437   70000
40746   53330
22254   30012
12333   89000
27122   38000
5733    67000
33775   75928
8557    37900
48723   60000
20847   44000
5970    20064
16040   94000
25474   82000
4957    60000
40083   92000
41471   52250
42268   65000
30968   28700
17685  165000
31893   62500
30020   94000
26380   60000
12254   60000
...       ...
47492   28644
23654   53000
45452   22000
34148   18144
8434    48000
40243   48000
38671  120000
4608    85000
11188  101000
19998   65000
9498    56000
40574  149000
11583   48500
18962   70000
15293  137000
46707   61700
39483  101000
9243    51400
14092   42000
780    153000
36803   34000
7835    96000
48014   48000
32338   64000
45541   89500
4738    35000
45663   36000
987    105000
18061   35100
39917   40500

[100 rows x 1 columns]
            x
39414   75000
5481    55500
46609   53500
15235   40000
32659   65000
39663   60000
42754  139000
29407   63000
1176   107387
29849   30000
            x
28612  130000
17258  150000
36179   38000
32469  140000
2052    90000
44995   47000
49636   85000
1331    32000
48777   60000
42441   75000
7667    31000
25019  150000
2849    48000
3047   125000
12743   60000
17625   53000
23392   48000
21852   82000
28224   54000
3942    38000
7888    65000
27718   50000
12610   85120
40261   60000
20187  100000
24303   40000
19692   50000
21308   70000
1345    85000
22469   80000
...       ...
33242   45000
24331   45000
36656   65000
23147   35000
16793   45000
14864   34569
27101   59886
4301    60000
44222   55000
35055   35000
3026    40000
3889    85000
42883  110000
9830    60000
8585    68250
16003   25200
15018   60000
25526   70000
30880   80000
8039    94500
48032   81000
8030   121000
34752   60000
17825   98200
42239   53700
37361   55000
48591   31000
42901   80000
36869   47250
49235   50000

[100 rows x 1 columns]
            x
35344   13440
22983  185000
18649   39500
17524  135000
3225    45000
26363   29120
43640   72000
33909   80000
43473   57465
13858   40000
            x
49812   63000
24890   78500
23305   68254
48423  125000
16098   40000
2930   118000
45578   62000
16382   30000
7531    38000
48868   38788
29935   63000
11715   98450
39394  125000
12060  100000
11314  152000
15708  140000
37973   38000
21628   69440
30570   82000
4195    78000
27169   68000
14232   65000
29830   65000
21263   97200
29382   90000
46140   73500
2897    70000
21332   94000
39825   51602
29216   38500
...       ...
486     80000
33661  120000
24399   81000
11053   80000
45352   46000
29140  180000
29638   36000
48591   31000
48618   42000
43529   35000
17458   64000
31154   50000
8973    80000
43699   42000
28486   74000
22468   77000
7524    81000
24689   52000
12762   30000
17412   36400
12492   42000
48321   75000
18524   38000
49741   55000
28135   45324
10291   63000
45227   54000
9399   139000
28423   43000
16159   26000

[100 rows x 1 columns]
           x
2418   61000
36607  80000
13427  47600
6761   50077
12668  90000
18498  74000
27498  77500
14053  51000
39052  70200
5854   45000
            x
23352   42000
28920   45000
23107   60000
149     60000
533     80000
26808   70632
47627   30000
39665  125000
5019   160000
27974   49200
38750   90000
23860  100000
25451   90000
23165   43000
6647    40000
47333   28000
37299   85000
23136   54000
21718   72286
2025    45000
43193   92000
14490   50000
16897   90000
49900   67973
4568    65000
26365   43936
13831   62000
1677    35000
4050    40000
39158   31000
...       ...
27170  124800
16853   72000
46998   75000
583     88000
5022    38000
33215   86000
31629   69000
45077  150000
24708  125000
46453   80000
18094   99500
5901   115000
26954  126200
16136   65000
43962   28500
47277   46000
16875   46000
29238   62000
47256   50000
32342  157000
49245   60000
9541    57000
12685   24672
20171   52548
2358    65000
38527   80000
15439   45000
31873   58000
8336    55000
6471    52000

[100 rows x 1 columns]
            x
10862  142000
17388   88000
21358   31000
28649   82000
22767   58000
9358    87000
24641   72800
29404   47000
47543  110000
5191    34853
            x
27647   78000
9739    59500
17585   52000
21630   56000
19783   35000
17074  150000
22681  135000
26879   64947
37135   74714
31468   71000
12356   45000
16585   28000
25686   31411
18824   71000
36936   67000
9000    60000
1515    23772
33097  150000
33661  120000
33771  145000
18835   45000
16866   69000
23374   54492
41288   75000
26134   61000
40454   36000
35618   48701
34297  102870
35990  105000
23702   27000
...       ...
17818   80000
25028   73000
17821   48000
17370   67000
22108   70000
1760    64614
4825    80000
1086    71000
29813   56500
35458   44200
17472   30000
3266    75000
14709   44000
22506   91800
5355    31000
9628    65000
4206    30000
39809   23000
31777   71000
18176  145000
37108   37000
32868   48000
41046   50000
39681   57000
9099    64000
19694   42000
39884   72100
17342   52000
31929   45168
42931   35000

[100 rows x 1 columns]
            x
135    160000
40668  125000
13187   69867
29993   52000
8657    95000
38838   90000
34826  109000
627    196000
30558  110000
29631   45000
            x
1256    47000
4614    86400
21906   26000
47706   75000
23285   39000
17908   25000
7966    80000
49601   39000
2308   128000
47661   63000
13401  150000
8600    87000
3852    40000
9613    65000
47027   80000
2483    50000
16251   65000
40319   50000
6998    80000
18087   80000
14513   40500
9821    75000
27010   91000
16919  120000
30608  100000
12695   70000
21036  105000
19249   44851
24453  155945
19965   52000
...       ...
11499   84357
14888   60000
21582   60000
2175   125000
2978    62400
49778   27000
40026   66000
614     35000
21623   42000
20244   62000
20081   42000
21883   70000
4815    72000
38384   89000
12897  102400
20386   50000
48755   56000
15623   45000
24899   68000
7186    42000
30179   80000
48277   92000
39171   50000
35727   30000
15416   47000
18909   55000
44841   60000
9887    90000
21604   65000
8001   101000

[100 rows x 1 columns]
           x
43760  97000
31880  65500
4039   39000
42592  93000
12415  50000
16873  75000
46701  93000
4643   60000
7549   85000
43169  62000
            x
30762   61440
43159   42000
28500   50000
4403    70000
7500    27000
10709   70000
7919    80000
11847  108000
26608   10000
4918    83000
10940   48000
44441   30000
39404   65196
43813   25000
15715   50000
47161   42000
27561   80000
17801   30280
4673   106266
5433    25000
40092   70000
12952   95000
8501   112000
23963   33000
22264   71000
31403   45000
32468   67000
47941   28500
5989    34480
14169   26352
...       ...
33902   63275
39271  110000
37082  160000
31353   56000
41491   80000
40442   60000
34534  171000
14507   38000
32412   70000
43951   50000
17365   45000
1687    75000
40096   38750
42453   70000
2724    57600
412     67600
14743   54000
41081  150000
33231  160000
40256  185000
27279   21184
47862   36000
3809   170000
19448   68000
36528   80000
32972   45000
12368   45000
34342   42500
39858   33500
9124   140000

[100 rows x 1 columns]
            x
22747   64000
37206  105000
49878   91000
5381    60000
37295   60000
29757   46000
36106   63000
20868   37000
43781   48000
39012  180000
            x
48343  120000
11145   55000
43240   35000
30047   42000
38304   87000
42253   97000
33782  120000
9649    23000
1533    60000
13115  114000
15149   45000
36493   74000
21744  145000
40567   51000
19051   39000
9998    54000
34373   35064
7073    51000
26919   85000
11469   86320
44357   97000
2875    62000
2781   100000
3922    38000
13848   29000
12632   47000
22828   65000
4316    85000
23592   85000
36095   71000
...       ...
45436   50000
1083    61000
37124   70000
4819    32000
37734   82000
20568   71000
42006   75000
44781   60000
30750   60000
20457   73000
20524   86000
47140   95000
16947   85000
15124  126000
1270   115000
15994  145000
19525  110000
49770   40000
10306   90000
7010    19500
13750   65000
13673   63000
26374   46000
30462   42000
5453    50000
29236   96000
12148   39000
31163  135000
10282   40000
18915   41000

[100 rows x 1 columns]
            x
42162  150000
11365   19200
24448   41907
23347   30000
41876  100000
16358   80000
48211  144000
23510   37500
20943   15000
10735  114000
            x
17324   54000
48970   80000
37427   45000
18472   51040
31534   68000
42783   65000
37710   38000
10871   59000
48703   88000
16363  101000
48976  103000
48576   45000
2547   102000
10311   98000
28309   25000
28278  128000
35100   34000
18084   90000
24403   55000
38735   38500
14217   71000
23635   74800
1688    50000
7989    78000
39880   50000
35389   77000
49365   54000
21679   70000
1394    42000
13901   90000
...       ...
21622   98474
8550    22884
19285   84000
34796  180000
44400   43200
9919   100000
48560  105900
25242   70000
10812   50000
36100   71000
27514   32000
2399   114750
39031   62000
1037    83000
8490    85000
6524    55900
8413    38000
1913    62500
16099  104100
30465   50000
32320   86000
12894   30000
38688   62000
1975    30000
28850  120000
2774    44000
4113    50000
31261  104004
23647  100000
34727   78000

[100 rows x 1 columns]
            x
7967    65000
49215   90000
32095   37000
32549   85723
7508    84103
32283  130000
1070   100000
6002    38650
4510    75000
21008   42000
            x
10267   57500
26729   83600
30737   52500
1766    55000
11090   35000
28564   40000
3976   100000
34110   90000
783     36948
47915   70000
2572   130000
10790   71000
1702    65000
22872   73000
13720   84000
44660   99700
22737   44512
1324    80000
15107   36000
12522   72000
19338   88000
43302   48000
38999   30000
34537   60000
14550   60000
19707   88000
12319   74000
12100  144000
1054    98000
15966   80000
...       ...
17204   39996
43494   50000
25519   42000
36154   78000
22501   32400
44633  100400
21444  194000
43094   34500
9551    19200
22166   85835
7030   140000
30896   89000
10708   69552
41273   47000
15267   35000
39078   72000
29111   59000
39395   65000
11696   85000
48967  100000
46901   70000
4801   105000
49414   85000
17630   55000
21230   33500
2911    38400
7258    60000
2262   165000
35132   68000
19481   28596

[100 rows x 1 columns]
            x
6093    98000
45953  117000
4788    72000
17771  120000
47835  157200
40831   46000
28918   62000
17683   38400
35597   75000
31374   65000
            x
35498  100000
1295    60000
18817   52200
43594   60000
35256   30000
31345  110000
1826    95000
33215   86000
21928  165000
46855   50004
25713   70000
5271   120996
32673   82500
35734   37440
6415   105000
31722   37000
25217   61000
34981   63000
15033   67100
983     65000
27881   34000
32614  135000
49672  140000
14709   44000
48868   38788
3496    60000
10629   50000
1757   120000
39301   50000
30112   60000
...       ...
37170   71000
36992  108000
30687   60000
22945   86000
46919   40000
31194   60000
15076  135000
41478   42000
9099    64000
16682   50000
40505   78000
44427   50000
39836   45000
18846   18720
6472   122000
6779    30000
16309   55000
34151   37000
27440   36050
23574   90000
15764  109000
25672   27000
35325   72000
27002  115000
25308   83000
10161   33000
25197   74000
41665   65000
28035   42000
35841   43000

[100 rows x 1 columns]
            x
26830  145000
28706   79500
25504   37500
39849  100000
43011   56000
26205   42000
13566   26000
10769  150000
19584   80000
26980   47110
            x
45939   37000
25675   35000
29263   44000
13293  120000
38091   78000
38911   70000
26481   49000
4412   160000
4840    91228
7901    20000
10871   59000
46964   52000
24116   30000
149     60000
4850    60000
40367   57200
18124   65000
30910   67000
3509   135000
25658   65000
7284    65000
44496   38000
37384   48000
40592   38160
4317   106000
30273   90000
8525    80000
37305  130000
9973    72000
44884  165000
...       ...
15606   80000
7798    57770
3396    55000
39091   65500
5205    47928
7459    49000
45809   70000
20281   43200
855     26000
3512    90000
2      100000
17327   37000
22914   50000
9941    36500
34748   50000
27186  102500
7872   165000
29564   66000
33887   38000
18114   72000
4913    42000
34758   95000
23759   54000
35249   63969
47622   36000
10246  117000
3109    80000
38530   34500
11174   95000
15144   72000

[100 rows x 1 columns]
           x
10967  40000
5101   78000
38400  70000
24144  75000
47256  50000
9065   76000
17392  89000
30894  68000
40094  38000
21863  33900
            x
45395   78000
8991    90000
8494    24000
44307  110000
24340  160000
36751   45000
30901   48000
6709    55000
19924   82400
28285   50000
33459  153000
48973   65000
31616   38500
14631   57600
19718  130000
25648   67000
24469   78000
18887   50000
49074   18228
9114    63000
34510   68250
27649   69600
46096   71000
24252   70000
24747   42000
47720   65000
12126   29000
39192   49000
42559   77000
31573   25000
...       ...
7474    60000
880     65000
47118   42000
31172   50000
2233    86000
21044  115000
36907  102396
47338   80000
15716   65000
49653   50000
22393   60000
36378   58000
29347  116000
21357   30000
13218   13000
11615   96000
16478  120000
29664   60000
16438   55500
9809    80000
12819   44063
46839   73000
42577   60000
38985   48000
22131   70000
1093    75000
20764   24456
42438   50000
34233   57000
49604   94000

[100 rows x 1 columns]
            x
5942    62650
39839   35000
6016    75000
24157   40000
31380   55300
38156  147000
18760   50000
18874   52000
2012   125000
35621  100000
            x
1002    60000
47430   85000
1308    57000
21923   52000
26942   90000
41703   65000
7986    71000
1675    74467
49532   60000
4895    61000

           x
23091  70000
6735   55000
44981  85000
42335  50000
32674  60000
49210  75000
9649   23000
3887   45000
9881   45760
41147  73000
            x
49866  182952
26076   37490
34396   65000
48612   27000
22562   46000
15899   76000
21246   48000
12899   60000
49746   50000
10058  114800
7794    93000
27293   42560
39628   80000
18063   45000
12961   66000
34950   41000
9876    39900
46503   95000
15585   41500
2290    60000
13022   95000
35693   42000
18951   60000
46497   42000
8766    22896
28713   72000
33771  145000
21634  105000
22214   39500
6665    90000
...       ...
21738   52000
36014   68000
10439   95000
6756   130000
993    109000
28215   65000
6103    48000
13950   37000
41823  102000
11509   58000
5562    75000
29239   53200
8107    61200
23336   23579
37283   39800
49023   70000
3607    65000
90      26000
6591    64000
11621   60000
11750   40000
45989  120000
27455   41000
10985   35000
17738   36000
14773   39000
35784   65000
24150   81000
18490   57000
29082   30000

[100 rows x 1 columns]
           x
22803  55000
33154  65000
23569  35000
27168  49300
45928  90036
5138   52000
26125  36000
19302  52000
18496  32000
30518  30000
            x
45464   49500
31764   28000
3249    43000
29569   60000
18974  115000
45176   65000
33236   63500
23356   40000
30153   45000
10921   75000
39550   50000
33671  100000
33743  106000
46198   70000
35116   35000
42158   92586
35218   28700
26059   58000
3999    60000
27845  121200
16890   73000
38244   50000
25677   45000
7850    60000
29645   65000
707     45000
34105   95500
31328   72000
5634    16800
38761   75000
...       ...
24682   50400
26027   51000
15987   65000
42792   55000
21428   56000
20024   53000
3826    12000
2077    75000
25743   54000
14872   73700
9064    23000
14380   64800
28204   65000
17020   31000
5169    87110
12298   64000
6991    50000
21808   87500
24252   70000
29057   23000
44221   30000
11830   49000
45785   52500
26012   26000
30037   42048
23247   50000
1845    62000
1807    80000
8787   100000
4174   115000

[100 rows x 1 columns]
            x
34525  125000
12569   30000
11878   16094
22537   39000
8906    82000
47145   50000
37135   74714
13910   60000
14578   60000
45202   48000
            x
6247    81000
44363   42000
46614  175000
22735  150000
9847    40000
17336   45000
10910   62000
43275  100000
6728    40000
19286   52000
46673   41000
5738    68000
12659   72000
42255   38000
46537   38000
34924   60500
48246   95000
46853   63000
47062   98000
7558    62400
3716   168000
31514   30000
35805   59636
27662   65000
28016   60000
20350   53000
8841    50000
36093  180000
2782    62000
20216  145000
...       ...
16835   37440
27788   72000
3370    44000
32138   87000
42445   33215
45613  120000
33154   65000
6926    58000
5515    40000
41361   52942
4966    48500
30944   85000
49945   51000
49233   68000
30278   85000
42533  190000
6441    90000
43145   55000
10403  130000
39435   60000
10373   33000
19720   62000
15741   55000
23898   46000
28328   43871
10244   38000
12254   60000
28940   72000
37863   31212
20044   60000

[100 rows x 1 columns]
            x
39267  110000
28470   15600
2578    40000
13242   86000
12796   81000
20636  125000
34626   69200
49875   57000
34765   45000
15090   34000
            x
43409   36000
47804   65000
35769   72000
21428   56000
30373   60000
7020   106400
31761  155000
34820   45000
23236   80000
46458  102000
13712   44916
7092    72000
9036    60000
13743   52000
16557   34000
48834   80000
20848   50000
45725   70000
48850   80000
46602   65000
26950   75000
39700   55000
44066   75000
48451   97000
35910   60000
31313   58000
17546   60000
15980   33800
45632   30000
41372   32000
...       ...
10149   90000
40249   30000
21187   47300
41193   40000
11385   62000
11434   45000
25413   19000
4253    40000
47823   70000
19858   59000
28091   40000
23867   75000
31943   15000
15354   75000
8631   117000
8004   125000
9621   100000
39620   44000
13227   58197
10371   60000
24601   55000
45719   44185
36355   25000
43763   65000
16620   70000
18475   65000
10709   70000
29180   51996
14682   48000
19893   34000

[100 rows x 1 columns]
            x
323     34600
24137  146000
25804   75000
3956    48000
26986  137000
32656   38000
27545  100000
12746   45000
29682  150000
32638   84000
            x
45723   92000
38947   65000
11803   60000
1612    72000
42801   52000
195     68000
24696  175000
14272   55000
23904  110000
13821   28500
23492   34589
3234    83000
192     90000
21705   33600
542     60204
29340   55000
32612   40000
34783   75000
27293   42560
21503   79000
36204   45000
4540    40000
20072   60000
42611   55000
6786    45000
25247   94000
36277   85000
44411   35000
8050    50000
14362  160000
...       ...
39730   48000
49554   43000
46627  125000
48771   30000
31393   79000
40454   36000
12229   62000
6726   128000
984     65000
28441   68000
5380    40000
6563    22000
13452   74000
24749  160000
4518    66000
9605    62000
19035  104000
37536   85000
18912   50000
28483   75000
40373   39828
328     99000
20726   39030
27925   40000
11820   75000
167     80000
28302   75000
24447   65000
25268   70000
27377   50515

[100 rows x 1 columns]
           x
27759  65000
28940  72000
5688   73000
34670  78000
22736  46000
44291  30000
20706  80000
28593  48000
27334  50000
13077  51200
            x
11876   75000
69     115000
14971   94000
24096  101000
11060   26000
5467    83200
16145   35000
29059   84660
9469    92000
33224   52000
9217    80000
7397   147500
6140    70000
37122   85000
22541   45000
13890   39000
31688   72000
36615   67087
3947    55000
27525   21324
19783   35000
39095   45000
40616  105000
30800   48000
47266   71000
9438    61500
39035  120000
14486   75000
7675    85000
17595   75000
...       ...
33073   82700
13005  125000
49855   82656
48341   49500
26986  137000
5018    72000
956     56400
21425  148516
1314    62000
11467   50000
35194   57000
15056   95000
11411   20000
24030   55000
20539   65000
36189   59800
7692    50000
29019   45000
26388   90000
22752   49236
4482   100000
42092   62000
17457   80200
21345   40000
38697   45000
9105    55000
12779   45000
5701    63000
46547   35000
17568   41000

[100 rows x 1 columns]
            x
21791   60000
10751   62000
37732  125000
39966   56000
29504   85000
44289   60000
41033   67075
33087   30000
17545   55000
1088    98000
            x
19377   43000
2573    72000
21505  120000
38623   68000
13701   50000
33674   65000
9561    40000
8776    68000
26835   60000
35220   44000
20977   60000
23018   50000
13156  107000
29065   47000
25016   40000
41493  120000
29755   50206
13970   95000
45064   60000
11585   54000
42775   35000
8541    35000
23117  101000
42745   40000
19996   45000
30504   41652
12328   51000
7437    50000
49088   60800
35110  118000
...       ...
25137  150000
44988  180000
38164   36000
22741   25000
15539  103000
28007   52000
14292   58000
40568   43300
34649  105000
18917  110000
5054    61200
40504   25000
23716  192000
3693    52000
7086    31000
9063    75000
17748   58000
14360   25000
48545  151000
6438    63102
42165  103000
1864   180000
24668   56000
7174   120000
30456  145000
39207   32000
47491   61000
19542   80000
17561   60000
10315   55000

[100 rows x 1 columns]
            x
32811   86000
23280  180000
40778   45000
2647    75761
10679  120000
41960   61200
12564   95000
6516    64000
47906   35000
8004   125000
            x
47644   75000
16888   55000
41924   65000
33278   67000
47154   42000
44512   70084
48950   29804
22527   24000
975     55000
40494  110000
17250   70000
12972   82000
48960   30000
19665   59000
29013  110000
29315  126000
30431   77000
4787    54000
43598  111605
11034   50000
11330   83004
41795   47000
46790  105000
40892  116136
26494   60000
47949   30000
24413   75000
876    145000
33414   41885
20374   59000
...       ...
40643  128000
11288  120000
107     64000
30609   80000
38106   57023
9843    43000
14254   47500
43241   49000
3401   150000
48852   95000
8408   120000
31968   36000
20342   85000
38451   52000
10767   75000
8578    67000
28295   91986
38639   65000
42000   30000
29637  130000
12086  102000
34040   38000
24828   35000
30541   66000
22631   66000
19202   29000
3998   102000
44066   75000
39867   63000
18818   24000

[100 rows x 1 columns]
            x
43157  100000
47571  102000
10060   43680
19944   42000
23203   54000
43470  120000
13394   63000
26293   75000
10345   51000
36142   82000
            x
6956    45000
40192   78000
40821   47000
28326   90000
8137    41500
43763   65000
15789   53000
8264    93000
4517   118000
18549   48844
24547   69500
39480   34000
43504   58000
25129   88000
2829    95000
42632   72000
34171   52000
636     72000
31179   29000
33413   26000
7030   140000
31888   41308
18106   95000
19637   85000
12514  130000
49546   40296
2080   130000
26775   45000
20390   97000
35032   55000
...       ...
10901   96000
49412   24000
18196   26500
22570   26000
3094    65000
39938   75000
14363   45000
35568   43000
35693   42000
43442   55000
39644   32000
29375  135000
8812    98000
18550   85000
36808  165000
11437   65750
33689   72000
28265   80500
48541   30000
36394   40600
11596  150000
15429  110000
2625    69000
26894   86000
2072    23000
25855   59934
32510  105000
14767   38000
1511    70000
38638   84000

[100 rows x 1 columns]
            x
26539   30000
27009  100000
49075   62400
15318  115000
35710   92000
4987   130000
21336   40000
4920   100000
32922  106000
1188    75000
            x
7450   108000
34242  194000
4812    70000
43037   60000
19004   50000
2747    60000
21199   65000
1955    81000
17721   90000
18644   45000
24193   32000
535     92000
1304   128000
39297  106000
32758   55000
47294  122400
28379   64000
39563  115000
47227   55000
23268  125000
32938  101000
7119    70000
41230   70000
20413   40000
19799  148000
45262  130000
39793   65000
37964   59300
23762   61000
11751  120000
...       ...
6330    89000
3       78762
28625  136240
31867   40000
32937   82500
37161   48500
2792   160000
25694   50000
31824  120000
18855   53100
43893   60000
5679    67000
7564    65000
32502   68500
35087   45000
39867   63000
23004   36000
4137    95000
47256   50000
43466   70000
13510  110000
13743   52000
38423  110000
11469   86320
10635   35000
30482   65000
27475   50000
28341  158400
23798   82000
48129   42000

[100 rows x 1 columns]
            x
2904    45000
32379  130000
18472   51040
24460   47000
21061   50000
45577   50000
22816   65000
15628    8652
14648   33400
3204    65000
            x
16559  125000
31188   50000
39012  180000
2370   140000
23321   13400
38288   38000
37775   48000
16297  126000
489     53000
48626   62000
17282  169000
11150   70000
46516   68000
32375  195000
8128    46900
34791   90000
17949   85000
22939   23000
29435   95000
16122   88500
32014   56400
32633   95500
40148  110000
39979  150000
28973   30526
26681   53000
39755   70000
20194   85000
8857    94000
12077   70000
...       ...
116     93000
7243   105000
35162   67012
7099    39600
8500    58000
2137    15108
47158   49000
2395   125000
4995    85000
11448   90000
34541  101741
7375    87500
44479  145000
38231   65000
45998   23000
33322   65000
27266   33000
21226   67500
18488   71000
45052   38000
33633   78000
30571   40000
16952   76000
967     56000
47563   37000
26966   30000
5173    58000
28782   62000
7495    70000
18814  133000

[100 rows x 1 columns]
            x
30604   74028
36220   62000
10492   40000
26362  118000
15772   90000
30911   49000
2728    74567
16659  100010
33341   65273
21837   72500
            x
42589   48192
2430    50000
8595   100000
13313   33500
8913    54000
22190   28000
6923    39970
22277   98000
32513   18000
24434   60000
12078   48000
20991   75000
42000   30000
48700   45000
43166   60000
42647   55000
479    125000
4241   155000
49302   54000
11816   44170
10768   94000
673     33280
35325   72000
8961    73500
1145    43900
40375   60000
17933  105000
36404   49500
22626   79000
2691    37000
...       ...
18339   80000
32438  120000
35595   24947
48681   90000
28272   38756
8688    35000
26137   46000
40009   43000
15902   82000
38419   85725
12951   80000
46088   72231
41767   35832
24106   31500
28310   33000
46661   25000
3753    70000
15932   49000
33538   35000
34773   52800
43210  130000
7637    80000
40485   60000
21222   70000
27301   47254
47915   70000
7890    60000
4036    62000
18082   42500
45502   50978

[100 rows x 1 columns]
            x
27953   78000
11640  190000
42554   69000
23565   30000
19239   65000
9370    50000
21569   44750
40002  125000
3992   175000
24744  120000
            x
8856    54000
2690   103000
35178   33000
2709   160000
5674   103000
11266   35000
9620   152000
4999    60000
1298    62189
27851   65000
13143   40000
26181   41000
17088   51825
17408   65000
19722   75000
11912   40000
11607   62000
13958   75200
7493    36000
35430   60000
29112  120000
33794   60000
48521  150000
11792  120000
23362   31400
43896   35000
33137   75000
6540    73000
27943   90000
28783   80000
...       ...
2454    22000
40371   47000
22323   31200
42102   25000
11312   84000
9712    57000
25296   33000
41153   30000
18211   36000
9613    65000
6960   108000
23419   30000
33392   40000
25519   42000
47250   95000
44200   49000
33252   70000
9868    34000
40629  100000
1974    48000
13736   36000
31957   12000
23204  100000
7368    18252
3373    69000
22227   46925
31934   72000
37480  100000
21759   20000
22502  120000

[100 rows x 1 columns]
           x
13169  47000
1230   45000
42995  73000
25164  64000
2374   85000
41975  55000
1233   79172
23428  67000
2939   55188
5584   40000
            x
42446  160000
6123   120000
48581  170000
17654  135000
12163   60000
41347   25000
28980   75000
41628   52500
33004   95000
16369  120000
48591   31000
24147   35000
22804   35000
45950   60000
4317   106000
18787   75000
10480  110000
24116   30000
5671   157000
9380    60000
31886   75000
28079   38000
20331   88000
12623   31200
10052   80000
10411   91560
13523  133000
23124   20000
4427    50000
2219   110000
...       ...
19622   23000
19738   70000
47598   45000
42568   75000
48815  109000
18041   23000
13535   33000
23995   80000
12687   61234
14695  104944
29517  180000
46952  110000
25156  108000
24072   55000
36      90000
14160   95000
750    120000
16319   28000
16383   70000
36350   50000
8048    63000
33665   58000
23929  135600
38109   55000
19892   25404
5455    30000
46391  101000
38769  120000
11144   36000
28017   55300

[100 rows x 1 columns]
            x
13679  103000
7356    84000
29468   47000
18370  175000
38304   87000
35732   35000
17054   37700
36523   86000
49978   50000
49127   28000
            x
32871   55000
8649   131328
27927  152000
40312   50000
31117   85000
37714   66000
41494   40000
43281   40000
38153   65000
32755   20458
1165    36000
10307  110000
21543   30000
45264   52000
4514    35000
37384   48000
31872  130000
15193   30000
18509   45000
28723   34000
34159   20000
11653   28000
31821   95000
1169   118000
13967  125000
29209   30000
1650    40000
39376   68000
35147   54000
16146   26000
...       ...
31298   14000
44676   56000
44984   45000
5710   120000
29970  135000
13301   46600
7917   125000
44449   36000
25439   75000
48459   65000
48594   41000
20171   52548
30418   80000
31066   73433
24676   43000
49950   31877
41098   50000
32163   35964
12447   95000
13484   50000
12114  100000
14209   75600
4648    95000
49566   62500
29469  105000
29854   60000
13247  170000
8037    75000
12093   82000
14854   50000

[100 rows x 1 columns]
            x
15206  102000
36124   50000
38758   25000
34277  120000
34082   52000
21295   58000
1961    52000
30257   62000
7173   160000
20660   77870
            x
5631   195000
7339    80000
18360  170000
18803   61776
27932   40000
48638   83500
33667   58000
24487   43000
24454   55000
35452   51000
29230   83000
26624   43076
16492   63000
17042   93000
49121   26000
32792  130000
29993   52000
35110  118000
36797   34000
46337   96000
20866   60000
40110  130000
1141    80000
10142  122000
32552   68835
46695   43000
10572   96000
18864   80796
45467   68000
21852   82000
...       ...
23460   69000
20056  106000
1912    80000
44707  113500
40507   58000
32083   55000
31584   15000
44556  110000
30537   68500
14111   44800
45787  150000
38377   90000
48315   90000
24430   95000
36932   56535
46629   18412
19678   48300
30790  129000
15005   84554
21155   20500
23764   55000
36332   69000
47235  150000
3916    70800
8009    35000
44420   37000
18723   40000
37143   70000
47682  165000
35237   77000

[100 rows x 1 columns]
            x
45248   21600
10756   43000
3347    90000
19762   51500
11906   47210
28001   95000
25580   44000
24216  132300
42864   52000
35050   90000
            x
33516   20405
19325   67000
4263    68000
15636   43000
46730   78000
41990   75300
38865   47500
26168   75000
23075   95500
26449  160000
9732    85000
16700   35000
46880  150000
48504  107000
17214   33000
4433    77000
47164   55000
38676   69000
42724   70000
24536   48000
33500   62000
27824   35000
23489   78000
23790   55000
38590   44000
14862   50000
33267   35000
46295   50000
40970   69190
4893    49000
...       ...
28943   52000
25707   65000
24950   60000
13459   34000
14376   80000
22665  120000
43004   37200
2257    90000
45906   61500
20648   84000
44088   70000
24277   50000
2996    57000
17452   51000
41914   41000
32287   39300
48353   70000
4233   110000
3346    45000
40323  105000
22974   28000
39098   43000
3745    50000
37087   17000
38692   40000
46023  103000
38012  100000
9395    99000
33465   63000
45191   14150

[100 rows x 1 columns]
            x
49580   57000
4028    52000
20529  109000
44353   40000
10770   29000
46389   31534
42037   77000
5411   100000
15663   50000
40231   92000
            x
11245   54900
43789   95000
23748   38280
39329   60000
29376  100000
20110   80000
35745   68000
25868   18000
1359    85000
6388    50000
29424   44000
11675   76192
25548   46000
4476    40000
45202   48000
36127   80160
3859    55000
41871   44604
3472    82200
49538   50000
20638   84000
32747   75000
44624   75000
15136   51000
19809   65450
1169   118000
25462   33000
10807   64000
5451    51000
21658   69500
...       ...
33014   36000
25787   54000
10402   86250
19466  100000
21651   28000
4226    40000
27940   56000
35258   46500
28412   84000
29      80000
15643  110000
22838   70400
36261   50000
36586  165000
24199   34000
7924   125000
38673   30160
242     80004
7848    70000
34592   42000
3966    56800
26479  114400
25165   74000
482     75000
25128   26000
22042   38000
9428    60300
5168   175000
38219   36000
45355   80000

[100 rows x 1 columns]
           x
47912  78000
47153  50000
27365  84000
27334  50000
7664   47000
44546  34000
592    48000
31516  42000
30387  25000
20481  28000
            x
44472   38000
7055    65000
13706  100000
5319    34400
24222  101000
36710   62000
27272   36441
25533   50000
3935    53760
117    110000
1911   102000
11537   41000
4719   117700
5765    55000
14618  130000
48301   50000
29044   61000
47394   90000
15749   33000
39821   65000
37040   41000
48780   80000
12165  175000
15644   64480
47335   60000
18363  140000
6035   100000
8207    76000
21275   52500
49687  120000
...       ...
2726    96000
1348    40600
26790   42240
30509   55000
28945   69744
28686   80000
36706   40000
3738   107000
19437   80000
13214   81000
40527   35000
17251   65000
27059   82000
11008   53000
4196   118000
26918   37000
23601   43000
10737  120000
43470  120000
27281   64000
14576   71500
32353  125000
11699   40000
33867   39000
11911   67000
46971   45000
40135   80000
23890   92000
39068   65000
12205   48000

[100 rows x 1 columns]
            x
6740   138055
27969   58747
12351  110000
18819  125000
13071   60000
30938   50000
46993   45000
32586   50000
6298    30000
42870  103000
            x

            x
13383   38740
1460    75000
42427   60000
39671   32000
15034   57308
15698  100000
3848    60000
35451  120000
39161   24000
20352   55500
            x
21877   90000
43363   93000
206     39200
36997   40000
44540   75000
19406   40000
24228   86000
29247   48000
43571   70000
18066   85000
15695   65000
39040   22000
44581  160000
4872    97000
47992   80000
31504   90000
15492   75000
9529   120000
39852  122000
30133   45000
34708  110400
11738  104000
40060   40164
8919   100000
17588   60000
48058  100000
1954    68000
10381   33000
46493   48000
32393  123000
...       ...
5482    45000
35207   89000
30163  100000
8869    50000
11063   71250
41346   22000
33537  120000
1102    44532
32919   52000
25381   26000
28207   68000
37029   45000
31922   80000
43353   62500
19582   39500
456     50096
36489   84000
46637   25000
11318   30000
27989   55000
42634   56000
45489   60000
6399    65000
2088    35000
9468    40000
8714    80000
17957  100000
49054   33600
49679  145000
41345   83000

[100 rows x 1 columns]
            x
38732   78000
3318    68000
4643    60000
42447   58000
47411   80000
41117  130000
46141   75000
23999   31200
9221   148000
40881  157100
            x
13366   75000
28929   65000
46524   46000
14741   85000
13847   29000
33715   50000
37274   75000
30331  108000
19312   50000
23743   37897
35326   55000
11287   24000
25281   60000
39898  120000
45212  120000
14130  140000
25455   38000
12807   29000
35609   51000
16253   56000
45924   25000
3593    50000
12286   50000
25258   80000
18879   69273
21759   20000
30658   65000
1397    25000
47565   25000
41308   38000
...       ...
24381   49145
1040    35000
25862  130000
42032   47000
25981   42000
43811   32000
31775   34000
24798   70000
46986   55000
4197    80000
10744   50000
31027   75000
18904   48500
23136   54000
9979    75000
37986   65000
13392   47500
49784   52000
38957   75000
31463   34000
37682   35000
18276   49500
47390   53000
16055   30000
24878   82000
34854   40000
31326  110000
14344   52500
9815    38800
43232   36000

[100 rows x 1 columns]
            x
34992   62000
34219  112000
14091   60000
18419   40000
44079   80000
45956   94000
19622   23000
15926   50000
42608   48500
48931   51000
            x
42554   69000
39390   55000
11533   31500
18224  125000
21592   34800
20602   72800
6720    64000
17752   60000
22528  100000
315    100000
3927    60000
46826   80000
3565    34000
96      80000
46060   50000
35092   60000
49620   77676
29968   42000
27538   36600
26183   55000
17358   45000
1827    51000
49037   56000
44970   70000
7878   150000
26660   60000
40931   50600
28688   60000
18166  108000
14601   79000
...       ...
23248   90000
29003   55000
25557   70000
10189   52000
29557   60000
43993   45000
2902    48880
10158   55000
18213   23000
45973   81560
44460   80000
10727   53754
19898  120000
8405    80000
4694    72000
12691   38500
49485   10624
29036   75000
23599   80000
12131   75000
32052   24000
33838   98000
4380   110000
46732  140000
407     48000
44337  105000
24412   65000
44156   72000
22687  150000
42748   37400

[100 rows x 1 columns]
            x
40173   80000
10911   56000
28405   20000
28334   55000
17876   50000
7759   111000
35990  105000
249     96000
7027   127000
35808  120000
            x
43167   55000
17498   71000
12676   46520
28127   65000
15090   34000
20797   20000
7342    65000
43630   54000
8364   180000
33515   57616
17272   36655
10177  120000
29476   60000
4558    52000
9653   126500
24498   95000
32542   45504
1951    75000
16858   49960
6299   112000
4685    56791
16214   90000
25665   33357
39341  130000
44715   38000
2027    51000
30034   77000
26766   38480
3488    26240
85      40000
...       ...
27102   25000
18434   90000
40929   45000
37835   55000
42187   52000
47862   36000
13854   35200
42568   75000
2744   119475
21082   53000
33976  100000
38139   92000
39795   20000
16676   77000
43280   75000
22417   62340
27274  100000
20459   48500
20886  110000
27622   39000
23126   34000
49517   30028
16766   50000
45557   93300
41128   75000
24947   53000
19339   65000
14842   60000
45892  170000
23492   34589

[100 rows x 1 columns]
           x
13824  50000
5782   60000
29638  36000
7315   65000
12951  80000
34448  40000
20564  50000
35708  48000
39333  75000
29897  42000
            x
38804    9000
31578   28000
46198   70000
16943   50000
11972   20000
16332   87000
41139   60000
5590    83000
49066   32500
26575   60000
7774   106000
27617   28000
38066   30797
2702    52500
12306   36000
39360   48000
2018    60000
8789   100000
39554   60000
24230   54000
34297  102870
10652   90000
49862  140000
40093  108000
24759   52000
20669   75000
18741   75000
72      84000
17938  104000
42301   21600
...       ...
16763  100000
36279   45000
40396   90000
3657   130000
25310   75000
1714    25000
43055  118000
5340    46000
22986   70000
5697    99913
38313   30312
30231   66000
33729   55000
32363  112000
20018   41250
12558   97000
25445   52000
17980   45000
17236  195000
2483    50000
6565    70000
26373   75000
13551   60000
46547   35000
31485   35000
4133    53000
15834  159723
27413  132000
24803  104000
7603    75000

[100 rows x 1 columns]
            x
34964   82000
22610  125000
41607   44000
27073   62952
45887   35000
16659  100010
16957  150000
16171   60000
6930    62000
45092  120000
            x
16063   83000
980     70000
40570   68000
8728    31200
19095  125000
28550   50000
2874   130000
47147   72000
31219  106000
22650   33000
26436  103500
24598  110000
22945   86000
20063  100000
32517   58000
24028  180000
1898    55000
17822   35000
27470   95000
1606    61435
47435   18000
11428   60000
41554   40000
11025   60000
190     43980
26769   57000
19889  180000
29074   85000
34276  112000
2471    75000
...       ...
22419   52000
40784   60000
10528   55970
47594   94200
27321   85000
46136  116000
7414    22000
31823   35000
41934   85000
30141  138000
9252    33600
40509   50000
48820  115000
49921   84237
29523  130000
48971   60000
22382   47800
4442   140000
18818   24000
34616   30000
44430  135000
8271    50000
28725   60000
14092   42000
15372   22880
506     54720
32744   65000
20934   85000
20634   50000
6179   105000

[100 rows x 1 columns]
            x
10177  120000
10105  100000
25354   70000
23370   55000
45563   50000
24692   41000
42521   32240
43379   12000
12790  133325
21845   92000
            x
1452    90000
5688    73000
15978  130000
12643   83876
1976    75000
42846   75000
30114   80000
46837   55000
16320  119000
33589   48000
21621   56500
3791    50000
33883   45552
25806   21000
17712   52000
28485   50000
48698   65000
41168   64000
1152    53000
48748   30000
19209   85000
7683    40000
17172   38000
18933   90000
20658   75000
8399    30000
43541   38000
16710   66000
36684   70000
43491   50000
...       ...
45457   35433
21193   70000
22375   70000
24219   41600
26095   42000
20241   85000
32780   30000
47400   46400
42225   50450
40422   51000
29867   67500
18391   25000
40403   43000
6216   100000
9362    70000
23057  101000
7853    83400
26862  110000
33932   60000
32456   40000
32524   43000
42315   50000
10308  100000
38895   24556
31921   48000
1822    36000
32884  110000
7897    68000
46737   82000
13428   28000

[100 rows x 1 columns]
            x
29405   62400
36880   28000
16089   60000
17721   90000
37992  144000
35849   92500
33991   68000
2579    40990
38166   49356
6455   106000
            x
37714   66000
43357   61000
49171  165000
41155   34000
25242   70000
34380   72000
32274  100156
19896   75000
17038   30000
27787   70000
19150   50000
7030   140000
32938  101000
13166   67000
21499   60000
12711   69000
42122   70000
15487   80000
26762   70000
34802   55000
2173    52000
44901   28000
16934   95000
28046   65000
21694   75000
17428   84700
9956    99000
18875   51700
10000  110000
38755   33000
...       ...
23597   43000
32382   71000
46902   81000
1752   140000
40146   25000
8915    80000
13064   20000
34252  100000
30985  183000
21948   38750
32309   80000
5828    34840
6155    22000
25924  120000
39689   42000
5619    39000
40433   50000
11689  180000
15519  115000
39164  108000
39342   18000
1342    96000
9420    32000
30918   98000
49956   65000
22874   45000
31841   52000
31614   95000
27589   45000
39000  115000

[100 rows x 1 columns]
            x
41852  115000
14930   55000
254     52000
48778   38000
8287    35000
1487    60000
39872  117000
44393   60000
39899   53000
9804    50545
            x
49135   80000
42699   52400
13556   54000
10315   55000
42685   55000
35098  101000
28738   92000
7998    66000
6891    48000
49599   55000
16717   42000
25826   99000
16221   75000
16862   63000
16840   75000
45367   55800
20321   95000
8269    60000
41627   28000
19408   75000
25246   65000
46570   52000
2658    87000
2268    67000
3844    37000
37791   48000
6503    83000
10507   82000
44920   35000
13221   55000
...       ...
33006   67000
40773  117000
8059    45000
17516   64000
37499   51000
3555    70000
6062    85000
30927   48000
29536   41640
27097   40000
16592   67000
11933  140000
1432    56000
47364   75999
43620   80000
39008  128000
21934   36275
25318   63000
13541   50000
45830   48000
47331   82500
42535  120000
3814    65000
44578   35000
27195  178000
10177  120000
31282   75000
8531    95000
14941   20000
10997   60000

[100 rows x 1 columns]
            x
27813   60000
24355  150000
45519   52344
7064    53000
10887   40000
25688   70000
11609   31500
16276   73000
16398   50000
40453   85000
            x
41933   50000
2180    80000
43905   63000
14310   50000
21330   50000
14478   45000
24423  104000
26294   98000
6537    70000
48379   96000
886     42000
7524    81000
44108   95000
12223   35000
33828  135000
9087    27000
42984   30000
23449   47000
24689   52000
34359   85000
45307   95000
43753   34000
30476   65000
43296  101000
1415    60000
28470   15600
12723  120000
10146   69000
11602   55000
40118   80000
...       ...
16713  119200
3146    69000
35508  130000
503     48000
44618   92000
13616   59000
25587  100000
18136   74800
34097  127500
2934    42000
48312   37000
40113  100000
35921   55000
30710   24000
25115  130000
17291   53000
17575   75000
46619   41000
16112   52000
14623   57000
13380  156000
14840   45000
40144   60000
31139   45000
28523  140000
49659   48000
34522  120000
22565   48000
37012   50000
36732   59020

[100 rows x 1 columns]
            x
33433   58500
11370  179000
26876   35000
9201    56000
45858   46000
10849  125400
24830   84000
29833   72000
46811   57000
28260   51000
            x
32799   70000
18235   31200
35891   75000
30070  100000
36222   55000
46073   51000
21481   85000
6011    45000
20349   78000
5895    60000
42471   58997
5306    35000
48999   60000
14496   55000
26408   55000
32058   31000
45229  100000
25029   68000
45724   84000
1614    68200
43110   50000
47017   27000
36950   30000
22810   55000
26671   59000
1680   101250
28724  130000
49807   30000
1899    67500
25250  175000
...       ...
4108    50000
29847   71000
2743   111000
39286   81000
37717   54000
6854    95000
10687   42000
43549   67512
30597   87788
5279    37500
3796    60000
42825   68455
39841   47200
27633   58000
24163   91326
14347   48000
9191    35000
559     65000
4415    72000
45832  100000
46811   57000
15647  175000
25025   62000
28719   75000
43590   60000
16800   76000
47800   96000
2082   195000
7263    99000
36700   70000

[100 rows x 1 columns]
            x
43322   33000
31120  104000
2509   109600
3479    35000
36233  145000
32827   60000
22664   78315
37380  109600
18919   51000
14596  100000
            x
4241   155000
15964   30000
28032   59000
48469   87000
22802   30000
22833   70000
32116   70000
42466   45000
19930  153000
35159  110000
11692   51371
46344   50000
38377   90000
24752   62200
33285   45000
44395   48000
23835   60000
6206    54000
26137   46000
35231  115000
19744   56000
6498    47200
39989   37000
13403  100000
9429    47000
39140  110000
15680   80000
2500    75000
17019   68000
7304    75000
...       ...
1484    91300
21578   54000
24095   91000
25347   85000
9892    37000
18938   52000
16280  112214
15541   60000
5934    73000
10393   30132
42148   60000
31833   30000
48496   48000
47162   90000
31331   36000
9609    52000
41700   75000
18110   32000
14171   65000
2164    87500
838     49000
31540   60000
29217   36000
23046   63000
31711   63350
33488  125000
7612    25000
25022   92000
24963   75000
38842   47000

[100 rows x 1 columns]
            x
49171  165000
37201   30000
18855   53100
16852   56000
44641   57000
34621  140000
4168    70000
48298  140000
10068   35000
40021   67000
            x
697    100000
43387   70000
35567   90000
11738  104000
5857    38500
17582   35360
10967   40000
30531   21000
36310   70000
43181   37000
38658   16656
9111    45000
45155   56004
17992   72000
22918   23000
4357    45000
31429   50000
42875   45000
21009   91844
21484  100000
30318   70000
49582   50000
36164   30000
46326   95000
38866   55000
22839   50000
35445   85000
14349  124000
41272   50000
23881   68000
...       ...
19228   32000
21918   92400
42476   64000
15797   35000
47008   80000
20121   50000
22812   75000
44721  110000
13661  102000
41624   46900
19661   50000
7905   110000
24692   41000
30733   52000
1130    65993
1439    47700
44601   35000
26394   60000
46879  120000
21436   25568
47068   57000
31970   54500
19111   40000
44598   69996
9868    34000
30376   24000
38733   52000
36981   72000
40116   55000
22615  171000

[100 rows x 1 columns]
            x
48626   62000
36723   70104
23138   48000
23074   45000
29664   60000
12051   22320
45599   68000
32661   90000
16702  140000
46427   76000
            x
8248    92000
36993   50000
25075   70000
16901   56100
16554  125000
32208   60000
15531  135000
614     35000
39296   75000
27344   70000
29843   38000
20604   63000
16161  120000
41083   40000
12919   42000
20344   31000
37738   39360
30297   36000
41413   47000
1174    80000
40592   38160
21126   45000
24459   57000
31678   74000
46037   50000
17293   26000
46822   65000
27015   60000
26234   43000
46311  130000
...       ...
38504   28000
19790   90000
48921   60000
4585    35000
31056   86524
43838   78500
42830   58000
16600   67942
24300   84996
40644   58000
22817   72000
15115   52000
20934   85000
22299  130000
16183   39000
45005   57000
40828   83000
9631    55000
2191   120000
18003   82000
22919   94000
23923   47000
33350   60000
26751   63000
45897   58000
18381   90000
47497   15000
30835   55500
6690   110000
9400    60000

[100 rows x 1 columns]
            x
10546   43000
29583   56000
21879   65000
12094   62500
30108   40664
21056   71000
29329   50000
13361   58000
7764   130000
10940   48000
            x
37304   85000
47836   53000
28713   72000
29668   40000
25853   43000
19871   85000
23817   37000
1287    55000
41276   50000
27257  137000
15790   40000
16682   50000
9958    21000
28358  150000
41558   72000
23600   70000
37666   46000
14292   58000
23029   56000
39387   45000
46823   60000
13252   84000
16762   70000
40839   80000
2426   130000
10521   51000
43397  140000
15774   30000
5445   183000
16239  135000
...       ...
28435   77000
39060  120000
15223   47000
32721   40800
46727  120000
25504   37500
40362  120000
28662   35000
16289  187485
18167   50000
31945   40000
1997    45000
44989   32000
40332   39996
41222  110000
3424    50000
30567  100000
43982  120000
3621    56000
43961   47300
19114   82000
27235   70000
41881   75000
30645   95000
24792   34000
31102   34600
38381   71000
24789   25000
18793   56000
48527   48000

[100 rows x 1 columns]
            x
10677   55000
35339  120000
23768   85000
48440   90000
11890   31200
34377   51000
19486   40000
42603   36000
26523   62000
23828   50000
            x
9565    11690
15945   44458
47753  100000
28850  120000
38744   55000
41136   49000
45591   62000
6492    35323
26112   25200
25609  150000
7836   175000
13152  132000
23194   68400
39989   37000
40407   90000
20489   55000
32492  150000
11373   82500
501     37000
29944   86000
19012   60000
10086   85000
26033   42000
23091   70000
37560   46400
3365    60000
31463   34000
29292   71603
212     86000
45653   75000
...       ...
29564   66000
30453   56000
592     48000
2076    55000
7941    52000
5687    35000
8541    35000
41464  105000
39154   41000
46686   42000
1101    76000
31664   86400
8305    29200
11126   55000
10371   60000
10176   66000
22965  109000
49348   52000
29700   45000
15593   45000
37977  162000
8404    45000
16239  135000
2706    89000
4824    70000
5478   122000
17903   35000
34285  106712
18367  110000
35637   50000

[100 rows x 1 columns]
            x
43695  105488
36946   38000
48978   30000
2355    55000
33511  110000
32847  140000
14176   33000
5890    69000
37061   60000
27911   68604
            x
35401   65000
26773   35000
18408   55500
6326    60000
33814   30000
15830   58000
28532   48000
45676  166000
13691   46000
42232   28000
40959   73000
48628   77000
11433   55000
37089  138850
23930   25884
16733   93000
25571   57000
25882  126500
19905  130000
39719   22356
44765   45000
6535   132000
3628   120000
13445  124704
32091   82200
22534  100656
42065   47300
32268  119867
47982   73000
32603   40000
...       ...
5256    21360
8964   129000
14634  105000
29285   51000
34233   57000
24340  160000
36545   60000
24645  175000
6700    57000
6290   135000
1749    72000
33452   67000
1302    74000
6277    45000
25842   40000
15363   50000
32874  158000
3083    75000
34565   60000
7295    24840
33800   46000
8149    62736
48728   58800
14075   65000
48382   60000
26541   32000
16563  125000
28325   80000
36140  125000
43302   48000

[100 rows x 1 columns]
            x
18350   77000
35722   88000
29913  180000
37667   54000
48330   85000
19509  115000
38491   65088
44042  130000
24100   58000
21790   34715
            x
40373   39828
31910   66791
28948   50000
4852    46000
36436   94420
43818   45000
43000   80000
28607   45000
10302   45000
38032   69850
27631   65000
47362   22000
8790    53000
44342   88518
30514   90000
20100   75000
31066   73433
47936  102408
19559   51000
35005   64000
10712  125016
24156   65000
40465   62000
6239    60000
21669   38000
9760    56000
42455   65000
16998  165000
49260   30000
41476   36000
...       ...
14645   11340
14537   55000
11882   74500
37005   50000
37818   92200
12544   76000
13893   42000
17819   56000
7891    28000
5139    50000
47767   85000
24203   34000
33577   50000
7280    40000
10362   90000
7098    30000
25626   36000
6076    90000
17852   55000
12255   89000
14466   90000
378     80000
3825    50000
15687   30000
17165  144000
13995   80000
4232   100000
599     39896
7807    74500
31390   43200

[100 rows x 1 columns]
            x
461     30000
7431    38000
49399   28800
18155   61400
14478   45000
40494  110000
46326   95000
16658   47000
35394   76452
24828   35000
            x
3942    38000
33390   50000
13639   40000
43630   54000
33940   71000
42542   53000
8862    45000
4637    46000
36686   80000
42068   72000
24481   91800
42881   60000
26453   80000
40972   45000
30051   75000
8651   110000
34349   40000
9333    20000
10189   52000
17667   50000
19098   30000
19471   40000
9102    65497
40117   88500
7305    50000
33774  135000
49566   62500
28485   50000
45418   39000
17127   39000
...       ...
12598   58250
9489   110000
13706  100000
19157   60000
48859   52000
1664    30000
34539   88400
30381   75000
3047   125000
41107   50000
26215  115000
45499  103033
3468   120000
46911   51000
30863   65000
32310   48000
25328   70000
40185  105000
28292  117000
49093   60000
1361    75000
47562   30160
49583   40000
22045   75000
49495   60000
35218   28700
38714   60000
39402   37500
11615   96000
38057   43000

[100 rows x 1 columns]
            x
11345   19464
37831   76000
8398    25000
2776    55000
44125   63499
16882   60000
40261   60000
30481   42000

            x
32970   65000
47886   45000
10314   86000
43075   62500
18202   24000
24248   40000
6645    87924
25849   42000
811    140000
16646   42000
21697   86992
33009   77000
43308   80000
26744  150000
45861   90000
18898   70000
37938   50000
20119   37500
13632   35000
31803   80000
44673   35300
3903   129000
17175   40000
34506   62000
47391  124000
18575   88000
17281   48000
93      10000
22937   70000
46938   80000
...       ...
45842   79562
19358   30000
20852   30000
13151   41300
48011   37000
21844  135000
37756   90000
4798    48000
18445   43000
33630   90000
5594    63000
28523  140000
37742  100000
611    110000
29386   48000
10455   29000
5312   115000
29370   35000
22816   65000
26569   61000
17157   40000
38076   74500
32650   42000
26042   35000
18939   28000
38243   75000
49031   26000
11349  175000
33935  140000
6437    50000

[100 rows x 1 columns]
            x
2434    38000
38751   42000
30340   45543
3304    85000
48512   90000
49609   75000
37118   55000
5620    65000
34970   57200
32127  120000
            x
41417   37000
2070    57000
49355  120000
46467   78000
45712   84000
6888    60000
7864    88000
7187    30000
8483    74000
5699    34000
13742   28500
37930   86250
10880   68000
2369    45000
28587   35500
44439   70000
45117   65000
17607   67044
17422   30000
30344   40000
44267   70000
8492   105000
7112    88000
16546   70000
32447   80000
34290   78000
20920   69000
11746   49000
23874   76000
12876   26000
...       ...
28664   76000
16918   61000
11559   65000
5197   110000
48907   74000
26529  105000
16490   34100
33749  160000
38204   57000
14011   48000
24703   72000
26987  110200
33292   80000
21530  100000
47155   87550
5788   143000
707     45000
23476   81000
48418   51600
35829   65000
32949   35000
46987  100000
46604   80000
3925    80000
3156    45000
45878  110000
25249   31000
47163   42000
1712    76450
43387   70000

[100 rows x 1 columns]
            x
9214    78000
27192  160000
49724   77000
35346   75000
24451   40000
11994   46000
7365    55000
45938   85000
38441   49000
33811  149000
            x
6119    74400
8065    65000
36415   38000
38847   52000
41759   35000
46033   60000
20947   80000
29317   68000
36714   60000
29556   85000
17582   35360
45409   84000
175     43200
31390   43200
16460   90000
8405    80000
25877   52000
3449    45000
39427  139000
32028   75000
143     34122
33047   50200
4937    87914
9451    51500
701    106783
38924   45500
35817   32000
43931   75000
19761   21600
6697   185000
...       ...
4587    50000
11326   52000
3857   150000
16542  105000
46505   24000
45711   50000
48011   37000
28111  115000
21183   55000
25618  121000
12361   35000
1096    42000
42625   23200
8409    32000
10251   30000
40455   66000
42704   62000
16060   38000
6202    65000
200     80000
1314    62000
36337   21000
15330   38000
38508   74000
45858   46000
33854   85242
44265   82000
26776   62000
32833   50000
48171  165000

[100 rows x 1 columns]
           x
49995  40000
48623  62000
26722  72000
19745  29000
6230   30000
45848  65558
9381   95625
26621  70000
5589   30000
28549  50000
            x
3548    78000
6565    70000
30501  145000
40001   80000
29188  100000
17359   52000
45725   70000
4682   102000
17765  130000
47281  144000
13298   72734
16394   90000
43001   95000
47301   45000
8330    79000
13766   80000
22627   27009
6159    95000
21935   60000
12451   35000
167     80000
17542   65000
14867   33000
39830   53819
39973   50000
31108   35000
23565   30000
23856   40000
3583    43000
39534  170000
...       ...
15619   60138
358     77000
3120    28000
29468   47000
21786   26000
42759  177000
36312  110004
18309   84000
24424  100000
42031   33000
17469   18647
13570  160000
14768   45000
42343   50000
3556    37000
447     84000
24822   99197
18467   50000
18732   73390
21701   48000
14723  120000
37261   64224
44794  102000
25773   67000
41452   65000
19079   35000
36460   40000
47583   55455
30713  118830
10598  101500

[100 rows x 1 columns]
            x
18944   82300
10130   90000
48902   60000
38338   35000
7717    55100
23959  129051
41059   64000
16053  196000
34928   35000
40478  108000
            x
5933    70000
44313   50000
26948   56600
5317    85000
15575   86000
41715   25000
35487   75000
244     60000
43091   27000
29652   41000
38843   55000
48551   81120
47775  125000
13543   37663
17437  112000
1557    50000
2347    28620
24782   60000
5080    60000
205     59839
29520   83682
26770   42000
14414   52000
38240   60500
40209   33500
44198   39000
48262   66043
32992   75000
7987    73000
48138  130000
...       ...
17644   34000
2783   108200
25447   52000
41979   72000
23799   65000
38128   26000
4821    45000
1379    90000
849     32600
36246   34000
46714   55000
12882   65000
32242   25000
39930   50858
18464   54996
19559   51000
36595   72000
28341  158400
4972   150000
38185   60000
35018   43200
48987   37000
32252   30000
7151    35000
32335   62000
197     80000
18359   40000
23751   80636
30713  118830
47817   52000

[100 rows x 1 columns]
           x
32777  40000
3405   85000
14272  55000
27783  51000
31546  65000
29696  60500
29985  35000
44151  37800
10982  91000
4495   72000
            x
36317   70000
512    104000
25079   92000
30388   59000
49294   56000
34186   43000
37158  102000
35154   98000
27043   32797
20467   50000
19761   21600
33508   78000
22112   55000
46659   52000
41394   64000
1465    86000
4982    63000
16710   66000
40791   66000
14820   39996
36137   98000
14181   68000
13298   72734
20091   70000
8030   121000
35711   75000
11752   44000
10460   48000
40869   57000
10218   57000
...       ...
38583   70000
11926   45000
43631   51000
39719   22356
14265   90800
40113  100000
38089  103000
26813   34445
24698   45000
49998   82000
33561   26500
29168   50000
29355   28800
26612   59000
13065   57000
28121   18000
21880   26000
38349   39962
7819    70000
1382    40000
6028   120000
6637    92000
36958  100000
10799   50000
16290   45000
44759   51000
28479   46000
31725   60000
24232   55000
24681   40000

[100 rows x 1 columns]
            x
40896   52000
9761    47000
24921   32000
21210   40000
33122  115000
22551   52000
33449   55000
28448   72000
6527    50000
19299   25000
            x
39804   72000
3555    70000
37302   81000
48559   90000
38181   42000
31443  106000
40173   80000
44915   43000
39216  140000
25210   46000
25568   56000
25646   40840
3434    37000
39366   83000
39500   34000
12332   20000
36622   81000
14875   84000
40224   65000
27901  101000
47636   45000
23936   32000
49992  104000
6700    57000
47767   85000
41309   56600
17125   83000
9183    33000
42606   46865
6452    23000
...       ...
17851   41000
17032   65000
16657   85000
35758   45000
4246    87713
43870   72090
40121   91000
15948  135000
40696   75000
38324   36000
26512   64000
673     33280
33727   30000
14776   55000
2284   130000
37777   37128
3045   150000
3727   150000
43625   84000
5166    50000
46988   32000
49241   57000
404    150000
12777   81996
25392   67000
46522   55000
12606   56000
23373   54900
43824   64000
46843   75000

[100 rows x 1 columns]
            x
42330   50000
35210   46000
13690   80000
20804   35000
13456  105000
25456  100000
1890    60000
10539   89000
24733   64000
18664   78000
            x
36300   60000
22611  106000
16229  105999
8234    53000
8148   100000
19781   55000
29598   21000
12480   40000
45460  186000
831     40000
14991   32000
358     77000
29897   42000
1591    50000
29628   48470
27134   76000
46109   58000
40055   52000
8664    87000
13570  160000
20400   40000
12008   72061
7288    64238
10887   40000
44056   53000
30045  123000
13014   38000
28751  185000
41288   75000
12866   65000
...       ...
24245   60000
37678   60000
4889    36200
48103   72000
27111   58608
35991   95000
4181    37200
6979    65000
4105    52686
11694   45000
24097   35000
18129  185000
3676    62500
3350    75000
3067   185000
20466  108000
39788   40000
38510   51000
38790   32000
27094   82000
48568   57000
43147   76399
29666  130000
37230  145000
45017   65000
36564  110000
17183  103000
36004   65000
37968  126000
7578    85000

[100 rows x 1 columns]
           x
30610  90000
4308   34000
47964  24000
24364  80000
8238   50000
19183  45050
23773  43395
25683  55000
15601  40000
3650   53000
            x
27244   60000
33887   38000
21765  110000
39858   33500
4994    50000
12037   65000
46902   81000
24396   60000
19336  110000
16880   57000
32450   46500
42764   44000
18939   28000
42455   65000
25584   60000
36184   90000
23345   60000
19556   72000
45699   68000
17578   25000
30921  122400
23714   36000
17539   75000
33495   37000
17721   90000
31637   18000
49781  125000
12828   85000
40563   40000
18278   34000
...       ...
5072    75000
4816    97000
49955   35000
49918   89000
29730   65000
36210   35000
22897  108000
12105   21700
21693   40000
8754   130000
40544   85000
17222   60000
43615   55000
820    176000
7434    95000
26290   48000
47852  117000
33138   36000
38405  125000
17587  168000
26038   86000
27055   70990
8531    95000
5984    52000
49367   30000
42123   28428
10181   50000
16408   48000
38109   55000
27653   35000

[100 rows x 1 columns]
            x
5194    75000
15542   75000
45754  105000
9773    84600
2199   105000
35892   54192
49110   70000
5296    51045
21453   85000
18522   22000
            x
20406   91500
38941  125000
30891   63000
4572    32200
46262   50000
24673   43000
48407   55000
38750   90000
19612  165000
46392   50000
8445    65388
11374  137480
13326   38000
11661   55000
32770   38000
4178    54000
48454   77000
30648   49250
37705   36000
2129    68000
2383    45000
31368   45000
45423   38147
36795   50000
34972   40000
38487   75000
13504  180000
19889  180000
17648  120000
42350   67000
...       ...
24676   43000
12543   35000
13625   37000
18311   25000
25622   31000
22573  105000
32867   82500
41396   26500
9730   113000
49304  120000
9287   120000
41459   65000
7202    47000
6135    55000
269     55000
13771   60000
37859   41000
4484    90000
13494   95000
49926   48500
24148   56600
49257   40000
41571   40000
37058   34600
31222   85000
10735  114000
36570  100000
12508  100000
7998    66000
14824   52000

[100 rows x 1 columns]
            x
1518    37512
6783    55000
41463   65000
37271   95000
25744   47000
9429    47000
345     54000
3164   143000
2894    75000
38981   23000
            x
24167   50000
49688   76000
10391   82000
29395   70500
15637   55000
34747   70000
17460   32000
44592   35000
10249   85000
709     35000
14682   48000
34551  100000
17201   95000
16492   63000
24933   67951
3370    44000
5156    90000
26185   75000
9335    82000
9631    55000
39513   64000
18906   40000
5438   117000
13348  100000
44432   88000
21408   96000
15012  100000
28413   50000
27160   38000
29560  102000
...       ...
38472   44000
24205   13200
23303   96000
26245   62000
38821   65000
36167   39000
18159  155000
11351   52000
33985  180000
33011   59000
41155   34000
8314    21000
40106  100000
26008   55000
33791   55000
27341   80000
9245    52000
26303   48000
31498   93000
36981   72000
12921   40000
30418   80000
19343   66000
49196   50000
6817    65000
31214   60000
25176   85000
4711    28000
4709    49000
7205    49758

[100 rows x 1 columns]
            x
21027  165000
21841   43000
31024   54000
1177    72000
3807    56000
25492   42000
46317   65000
31674  117000
19068   47000
2223    90240
            x
5548   110000
46458  102000
33637  100000
28738   92000
49767  106000
2822    79000
6252   135660
37493   30000
7011    65000
44922   72000
11621   60000
28315  120000
15584   90000
15727   30000
27491  112000
11133   36943
24764   50020
30875   97000
9513    70000
4272    60000
35163   40000
42215   45000
31283   18000
34062   40000
36629  140000
32714   39000
9007    90000
3276    41000
34907   49920
2549    60000
...       ...
47552   19000
38606   70000
8478    50000
21683  100000
47499  110000
857     37224
43643   39000
13280   96000
45850   65000
41908   82500
23963   33000
45350   20000
40368   85000
34598   70000
27962   68500
22215  110000
1417    62000
44327   56500
38675   45000
47256   50000
12024   78000
5119    98000
36136   90000
30233  120000
10678   54000
5268    72000
23701  100000
40741   70000
3142   101914
34610   56500

[100 rows x 1 columns]
            x
30471   26665
13176  105000
23974   86000
30442   65400
31807   50000
1480    50000
23920   39000
22860   91000
14354   67500
17920   35989
            x
17814   92000
24489  130000
10312  128000
14992   50000
31994   43000
37075  109000
5923    91000
33125   62000
17706  140000
8440    27000
18149   30000
38862   36000
22840  130000
5204    70000
22962   36000
41634  110000
44610   71416
25785   31863
37196   39500
8645    58000
28517  102000
13882   25000
13497   60000
29939   42300
36114   31000
36203   72000
10963   32000
15670   64992
39505   26000
44404   95000
...       ...
28287   42000
46596   70000
42736   40000
9493    40000
13630  107728
450     79800
22779   81000
21794   88000
11167   98000
22278   65000
5647    87000
35089   63000
38105   63820
47454   49500
20271   40000
43124   50000
34324   73000
15140   28000
38735   38500
25545   66500
31767   50000
7258    60000
20545   68400
40716   80000
23188   90000
3455    28000
27296  120000
10708   69552
11336  120000
46426  117081

[100 rows x 1 columns]
            x
33818   53000
1936    68000
7575    60000
49163  120000
44656  102000
8508    60000
3865    52000
5841    70000
43858  132000
4437    75000
            x
34862   52000
40495   69000
48139   50000
13054  108000
16622   90000
48756   73560
46099   26000
37547  104250
7755    68000
416     73000
30252   90000
17957  100000
19392  185000
42384   98800
798     65700
30309   44310
19490   77022
24350   75000
49266   82800
11353   62000
31526   64000
10198   25732
47161   42000
16707   70000
42250   56000
33981   34560
20185   33190
47772   60000
41379   45000
3518    26000
...       ...
43133   33600
134     46345
20808   50000
38768   55000
16196   75000
46388   55000
15803   72000
5473    72000
45737   80000
10828   34000
12016   94969
24842   65000
24473   57600
13167   76183
40514   40000
26493   67500
40215  105000
16282   65000
27279   21184
20576   35000
44861   97000
47182   32000
28378   40000
30145   52000
31825   50000
31673   50000
24906   37750
16621   35000
45221  101000
30428  124000

[100 rows x 1 columns]
           x
18752  34000
45952  70366
27980  75000
34489  65000
30479  86000
9313   32000
38883  79000
34437  70000
32086  50000
8837   35000
            x
49170   45000
48566   69000
12020  199000
29283   40000
16727   61000
12942   36000
15764  109000
17549   33600
22796   36120
48163   98000
36946   38000
39013   70000
44269  103833
20451   85000
48745   45000
38185   60000
10919   75000
36369   67000
16094   80000
17497  162000
22237  124800
2238    30000
2279    75000
913     28000
29781   37000
44496   38000
40501   48000
38163   30000
41171   83000
27631   65000
...       ...
48592   13500
49219   45000
42      55000
8211    75000
13328   64000
33334   60000
17262   19000
49370   98500
41887   90000
17457   80200
39611  100000
20506   70000
9744    60000
15088   58000
117    110000
11624  111000
18493   25000
44717   56000
22946   75000
14690   70000
13623   45000
14135   40000
40049   60000
5086    25000
21710   58000
16858   49960
23121   27000
6804    48000
25837  125000
16624   34000

[100 rows x 1 columns]
            x
48333   78000
17517   96000
23077   62000
39735  110000
3820    60000
38729  112080
15884   31000
43741   33600
6320    32000
9363    52000
            x
23989  120000
49314  110000
20110   80000
42001  105000
859     50000
9160    68500
18482   65000
48598   30000
36115  118971
13457   23000
27266   33000
25616   30000
28570   55000
28926   24000
14997   32004
44049   50000
9494    29000
23632   32000
3127    22000
6974    70000
4187   120000
40663   80000
273     58500
44119   32000
48052  110000
18856    8000
35128   54000
14572   35000
433    110000
15468   68000
...       ...
42015   55000
11178  101004
8983   125000
21771   15674
46922   65093
45930   72000
9095    75000
32573   21500
31024   54000
48878   90000
26368   53000
9123    31000
4273   125000
24936   65000
3738   107000
17520   52000
22080   95000
8941    45000
10961  100000
28858   60000
34181   86400
46457   55000
40674  140000
3233    30000
19118   70000
46114  123000
28779   95000
22902   63000
28923   30000
18780   90000

[100 rows x 1 columns]
            x
2666    86000
32288   60000
37905   35000
16546   70000
16919  120000
14034   82000
41628   52500
11258   43400
10405   85000
6888    60000
            x
37152   20000
35642   71968
6752   150000
32217   65000
29260   79104
27464   40000
34203   85000
35046   42000
23076   35000
39765   72000
27053   42000
37428  110000
24457   62000
39799   80000
9228    80000
26771   58000
9147   120000
22833   70000
4888   100000
47484   40000
29650   75117
21667   60000
27375  126000
45306   77400
47339  168586
25300   40000
7201    70000
47527   93000
29991   30000
43971   80000
...       ...
31455   58000
34347   60000
24414   51000
20413   40000
29157   69600
12620   73000
17875   80000
14156   71000
30886   55000
42576   30000
43702   95000
8074    83000
47895   65000
26099   57000
46616   52000
27570   38600
29730   65000
43801   51000
5324    54891
22260   96000
15905   50000
39205   60000
47855   98000
785     45000
5453    50000
6923    39970
49202   78000
42450   64000
48375   32500
2506    55000

[100 rows x 1 columns]
            x
22564  129000
14258   84000
14734   75000
48985   53000
16904   67000
30040   51000
8715    35400
28632   72000
48927   80000
34418   95000
            x
27606   50000
32638   84000
11096   55000
38170   40000
8999   163500
32666   30000
854     48000
14869   55000
34588   75000
33473  147000
39248   67000
48760   62000
36584   44228
26971   99000
10398   95000
20551   95000
49185   80000
21898   22409
21630   56000
4502    36000
42667   60480
16337   84914
27283   65000
27421   52000
37749   42000
16676   77000
15364  117000
24164   61000
25353   45000
22870   31000
...       ...
26531   32000
34831  130000
2172   101000
38839   75000
25772   66000
2234    50000
14028   41000
27441   48000
41125   53600
11688   62000
40058   88892
6942   150000
23831   95000
17809  115000
48548   80000
32962   93200
27846   55000
46748   80000
8478    50000
40229   80000
10597   72000
23849   90000
29849   30000
36489   84000
22862   41000
6013    75000
11054   81000
15570  100000
28717   50000
22797   43680

[100 rows x 1 columns]
            x
6742   140000
38775   50000
27668  110000
19197  174000
17104   37000
37951   76000
27765   84815
10100   35000
43835  111400
10648   48442
            x
22825   79475
26887  130000
34951   90000
37150   45000
44847   95000
35056   67000
18166  108000
13981  126000
25304  130000
14486   75000
10283   34071
42435  194000
37328   45000
993    109000
40097   70000
19847   39000
2164    87500
32989   62500
40446  164542
31111   50000
1171   144000
10632   41000
2718    82000
45648   56000
14073   23000
9856   110000
16677   30000
44910   42000
17717   84000
35993   86000
...       ...
19194   86500
19380   70000
49626   45000
6500   103686
12366   30000
41902   45000
59      22500
40188   70000
23653   18000
1455    80000
14649   46000
497     55000
9671    28080
8782    90000
48351   57000
45017   65000
24027   46000
32424   70000
3015    36000
15751  112000
42020   40000
13720   84000
28045  100000
26388   90000
9101    68000
3327   135000
44794  102000
4305   140000
13356   80000
31816   80000

[100 rows x 1 columns]
            x
6152    75000
42269   70000
4124    28000
7429    65000
7243   105000
12089   44000
47785   60000
38485  100000
23498   65000
46383   25000
            x
35251   83000
20887   57000
2606    90000
34653   56000
21564   45000
46466   60000
9561    40000
38099   65000
27106   90000
49458   60000
49849   76723

            x
11995   55000
3702    54000
7328    61000
25384   60000
38942  140000
15087   40000
28060   80000
1452    90000
16452   80000
36523   86000
38502   79000
9285    68000
49730   51000
49416   70000
48899  114000
30895   40000
31065   73000
47592   32000
2371    48000
49253   60228
4132    87000
4429   131053
39669   80000
34621  140000
34954   48000
27701   52000
29796   65000
39597   75000
27847   24000
43769   73000
...       ...
1860    57000
6521    40000
41449   13288
6696   108800
7087    36000
42814   45000
28349   83000
3293    60500
43048  108000
16413   60000
8421    74872
20083   62000
28955   40000
47931   80000
19773   97000
32220   66000
28060   80000
6129    47500
4028    52000
21783   75000
35270   64000
40082   85000
33634   52000
42133   35360
39543   75000
17259  120000
22123   34000
11354   90000
7927    74000
46441   90000

[100 rows x 1 columns]
            x
24149   86000
7604    55736
23140   90000
24000   71000
47721   39500
2024    90000
19424   73000
4806    35000
27708  150000
20026  175000
            x
10417  100000
1923    52000
24227   79000
42810   60000
26160   36000
40946   48000
67      95000
2167    42500
31100   50000
3273    50000
28584   45000
1618    85000
17409   30000
6325    85000
33938   42000
39587  120000
43537   50000
47413   31000
11549   27040
38424   43000
32976   80000
34060   65000
22552   55000
3329    20988
39887  120000
29334   87135
6958    39000
18241   65000
43563  125000
43518   65000
...       ...
10650   51000
459     63000
781     48000
30753   48000
20181   58000
46181   71500
35833   65000
41244   60000
21215  180000
43793   52000
29475  175000
48560  105900
32944  130000
9478   125000
34177  195000
20820   20000
17356   70547
28858   60000
3059   110000
48361   15000
5900    29444
3367   118000
34208   58000
21992   85000
16095   28000
43850   26026
14137   74000
47500   48500
45364   56328
5833    60000

[100 rows x 1 columns]
            x
42464   28000
23895   87000
14854   50000
2561    67000
5018    72000
2747    60000
23602   72500
35063   80000
7677    60000
40466  103000
            x
7670    38000
34443   95000
11577   48000
6927    55000
10662   47000
26772   76000
27651   50000
37693   99438
1149    35000
24788  155000
5790    86708
934     65000
568     31000
20330   68000
12026   25000
42496   99000
42819  102000
47358   35000
46115   55000
13341   45000
8265    68000
38019  120000
36051   52000
26102   83200
23975   48000
6901    22000
15047   80000
13293  120000
41816   66096
16750   50000
...       ...
48579   46000
36424   72500
31366   75000
7663    58000
33796   30000
40362  120000
15131   41000
20843   98000
7123    97064
2298    85000
13237   85000
46858   66000
12898   40000
5140    72000
37858  115000
46749   56935
36876   34000
40592   38160
43655   39132
3832   112000
4481    38000
25071   50000
27274  100000
3965    70000
12624   58000
29829   75000
40254   75000
19472  120000
23932   90000
17865   62000

[100 rows x 1 columns]
            x
16352   35000
9474    55000
13147   42000
19923   72000
13071   60000
9893    70000
42912   42000
49013  125000
28017   55300
25694   50000
            x
11170   75000
37232   40320
21187   47300
24251   50000
21985   22880
31371   35500
17903   35000
2070    57000
16660   53000
13714   32136
42871   75000
26698  140000
25604   45000
14589  165000
33480  120000
38342   28000
37561   35000
39202  125000
32422   51000
28182   85000
41471   52250
15611   32000
37593   52000
7494    54500
35236   56652
48539   68900
37223  100000
31280   65000
49351   41000
14446  165000
...       ...
19281   48000
1750    89000
46076   40000
1585    65000
5147    63000
24294   93000
7019    68700
3984   110000
38838   90000
37550   19200
31874   40000
29958   82000
34757   85000
6401   160000
27211   41700
3616    28000
32617   93000
22103   85000
28227   77220
3654    38000
35861   85000
22312   38000
47230  150000
3601    73000
7709    86000
27601   42000
8190    50555
45209   92000
4032    83002
16254   38397

[100 rows x 1 columns]
            x
41552   36208
18269  120000
47728   45000
10354   39000
35570   71560
6102    90000
48913   30000
19219   70000
41186   66000
16639  110800
            x
26772   76000
42863   68000
34496   55000
26575   60000
37137   42000
10942  149532
40967   56000
12606   56000
14775   58700
4528    62000
41084   40000
22392   63000
17250   70000
21556   36000
11826   70000
39432   56500
33588   50000
22097   40000
12191   32000
42150  140000
12218   80000
12761  120000
3765   128883
30014   90000
26439   49740
33934   80000
20623  100000
30572   70000
45560   55000
25856  110000
...       ...
28376   80000
7780    35000
1408    53000
33997   62000
10784   68000
23731   45000
46295   50000
22950   98000
42582   70000
1674    20640
25363   48000
29305  123042
44374   26400
19080   42000
22503  143000
44756   35000
7390    90000
44167   60000
49100   65000
3066    56000
10041   59000
8524    60000
4308    34000
13739  100000
13322  120000
28747   36000
15675  135000
312    185000
24491  114750
20140  139380

[100 rows x 1 columns]
            x
4926    45000
20873   77000
21309   76000
35433   24000
9681   110000
30690   85000
14799  165000
45941   65000
26542   43453
31624   58000
            x
35189   42000
10065   65000
35844   22000
13157   90000
5917   109000
49811   80000
47029  105000
23717   73000
26468  100000
2333    88000
4034    24960
38463  110000
39531   91000
41180   65000
12564   95000
3630    80000
40232   64000
27748  117600
2611    74000
15645  150000
41252   85000
36222   55000
5834    71000
6141    41000
27576   75000
46722   78000
18839   48000
24968   32789
586    100000
36064   54000
...       ...
46128   77000
5371    62000
19383   47000
38850   44000
19023  115000
21908   45000
39850   23500
11214   56000
35481  100000
1802    43000
8332    68000
36592   35000
26903   60000
44591   82000
4630    27000
23842  185000
16891   48000
23692  132000
11746   49000
37074  122800
26935   12000
8184    28000
12407  110000
693     71200
26265   70000
29736  115000
19747   35000
47973   92000
24901   75000
41598   58680

[100 rows x 1 columns]
            x
29624   40000
20466  108000
36556   90000
13285   73000
5663    74000
17249   31000
24864   58530
8979   104000
27648   45000
21758  120000
            x
46798   81300
39652   65000
46222   53000
8501   112000
14856   51000
15323   55833
16957  150000
483     16000
15541   60000
16616  116000
26245   62000
45220  124000
6644    48000
10059   59000
33830   29702
23974   86000
40324  150473
43840   50000
21518   24000
28086   82100
35853    4000
48200   95000
36762   84000
12260   65000
9745    48500
3406    30000
31198   42000
1220    50000
23732  112922
11484   45000
...       ...
24977   24000
1154   150000
43518   65000
15180   92000
37745  180000
21286   35000
38334  150000
13155  109000
22954   62000
34352   90000
41882   46000
17829   34000
9139    35000
38581   86500
16851   70000
49030   56000
204     70000
14038   67000
21505  120000
4703    67000
18986  105000
36764   62000
10312  128000
2511   120000
27062   70000
41220   55000
4438    58000
39692   63000
43727   67000
23828   50000

[100 rows x 1 columns]
            x
10282   40000
21998   65000
36872   69000
14015   70000
35088   28000
37918   53000
47123  120000
33255  120000
29355   28800
33520   70000
            x
13080   80000
2846    43000
35599   28000
43110   50000
21724   73000
42105   42000
42992  103000
24615   46500
33243   92000
21337  116000
27326   33000
34347   60000
21454   80000
32014   56400
3874   120000
33351   82000
39974   22000
40462  130000
7317    55000
44207   60000
43187   28993
47394   90000
49720   70000
7788    45400
4599    28800
20999  108000
19393   38862
8992   121000
19157   60000
1407   120000
...       ...
17143   40000
19729   64000
24234   75000
46944   50000
1273    59000
29341   42000
11670  110000
13768  100000
7262    75000
15898   81000
28908   27052
3592    80000
19827   75000
15478   40000
45010   36000
13997   37000
17242   38000
32067   80000
44535   45000
18639  130000
46193   60000
12056   96000
16008   38000
343     50000
15217  155000
40460   49700
11788  120000
17003   25000
40121   91000
24962   50000

[100 rows x 1 columns]
            x
4620    35000
15461   62000
42266   65000
40414  138000
1433    70000
38643  153800
28129   31000
24335   60000
13336   55000
6518    52000
            x
22397  100000
7867    45000
43672   45000
38079   43000
42837   80000
1210    43000
37995   55000
13635  112260
11234   67000
33024  126998
30207   83000
42804   54000
34383  130000
47464   32281
39063   60000
4805    40000
38084   46000
6950    65000
48690   45000
47912   78000
36171   65000
7439    63000
20976   46000
26925   60000
39451   35000
7671    68000
45692   80000
16444   30720
44215   47000
22154  108000
...       ...
44646   48000
39523    9600
38310   37726
37021   41004
37116   60000
6174    82000
19969   45000
47788   54800
45168   31200
17346  180000
11055   80000
5439    46000
27237   68000
17922   52000
49715   45000
31758  100000
18636   50000
18584   48600
41559   70000
20695   45000
4893    49000
27765   84815
6525    65000
35917   49993
26201   49000
23413   41000
8939    53471
48607   67000
29217   36000
43724   62000

[100 rows x 1 columns]
            x
45546   75000
34828  128000
22165   50000
2618    16500
39519   54760
48664   45000
3037    40000
42349  120000
21065   45000
47974   58000
            x
32003  120000
18150   49000
7846    55000
24580   95000
48273   67000
28845   60000
48463   45000
45164   70000
28398   73000
2740    65000
48818   51938
18340   95000
22844   84498
4853    40000
23043  130000
28679   65000
8448    58000
4192    58000
25088   75000
13845   90000
13250   93000
5976    60000
10144   79000
30870   78000
47112   95000
3358    58000
3607    65000
45627   42800
6415   105000
29571   96960
...       ...
21292   25000
48133   50000
12264   37000
49341   40000
2884    81000
9446    85000
48373   90000
19588   80000
22199   28296
3113    40000
25311   89400
8767    32000
40633  138000
22757   75000
16265   53337
6114    95000
26875   76292
3599   110759
6649   110000
35821   67800
1184    48000
30292   32000
42262   52000
15952   76409
49544   55000
30233  120000
3037    40000
28143  117873
9112   120000
30632  104000

[100 rows x 1 columns]
            x
39436   39524
19429   45000
25414   38000
24014   95000
40837   75000
41145   43000
38305  130000
23695   90550
41454   88000
22127   56000
            x
20488   52000
33103  114000
20770   60000
12957   35000
28658   55000
26638   36000
9442    14172
25922   60000
3836    75000
25231   40000
35670   46000
37741   80000
7921    48900
38785   55000
38837  109000
11592   46000
7393    41000
3231    26500
5858    65000
39695  110000
14989   17500
32882  108000
14532   55868
5362    43000
4010    69497
15814   50000
48446   78000
37646   30000
34819   42000
12794   35000
...       ...
173     63000
5584    40000
11822  165000
47121   40000
15790   40000
45517   72000
4060    66482
18214   48769
5057    42000
25952  100000
27872   45000
13086   40000
38344   45000
5051    55000
3131    60000
20548  121000
32821   35000
24254  100000
32070   95000
48648   90000
41482   51000
34284    8000
30455  111000
22968   80000
5257    60000
41237  115000
8556    52000
7315    65000
14933  110000
26589   48000

[100 rows x 1 columns]
            x
49116   52000
38309  123000
41248  156000
5880    40000
40080   43200
49538   50000
7674    70000
35184  100000
21477   50000
22852   60000
            x
27761   75000
16122   88500
31995   55000
84      45000
30347   89000
4828    60000
30411   60000
25005   22000
7299    38000
5513   120000
30852   44000
22291   40000
10400   85000
36334   82000
3668    90300
33252   70000
10849  125400
15117   54000
8143    30000
13164   67000
5802    50000
10061   78000
47419   60000
44968   46000
22147   38000
31629   69000
523     95000
43771  140000
1534    70000
2055    66000
...       ...
44133   49000
48750   57000
23067   42000
32524   43000
32091   82200
12023  100000
49371   72000
24653   42000
43021  105000
25701   77000
9091    47500
24175   30000
11870   90000
48041   80000
46933   56000
2073    40000
25443   85000
39152   60000
41109   37000
41555  115000
43882   42000
27713   85000
15090   34000
29839   23842
43221   55000
20958  180000
37737   23000
11046   55000
46935   57500
1291    48712

[100 rows x 1 columns]
            x
44659  120000
38610   50000
7623    45275
45794   25041
15325   36000
31572   50000
43864   49500
5088    75000
2549    60000
27000   32000
            x
42748   37400
11258   43400
43383   65000
10849  125400
3367   118000
48932  137000
36974   50000
19421   83000
322     85000
45045  102000
34069   36000
6021    43000
24236   55000
19096   82000
16770   30000
47152   30000
49666  180000
48979  175000
10359   83000
43094   34500
31231  107000
39944   82000
40979   97000
21231   97000
46086   70000
16243   95000
37206  105000
6860   120000
6812    40000
43812   82000
...       ...
16844   42802
24168  100000
40555   90000
13643   48000
17605  105000
34997   57000
5254   109000
10611  110000
48083   28000
18306   37488
43397  140000
37642   43000
2173    52000
49586   85000
34229   50000
22957   19000
29029   81000
34715   50000
30933   70000
35624   37000
48534  110000
37893   45000
12065   64916
33572   65000
34403   28000
4084   115000
20830   60000
41936   57000
37313  175000
36439   58000

[100 rows x 1 columns]
            x
16067   80000
46413  123000
38454   40000
46762   68000
18613  101000
15830   58000
41549  142000
44741   48854
10463   14184
16054   58000
            x
33259   65000
22488  105000
29387   61000
9216    70000
22155  120000
45593   91000
24747   42000
46700   85000
35205   66000
46279   45000
31465   41000
1791    58000
48284   85656
28514   50000
9472    58000
24456   45000
15307   60000
47554   52600
42242   95000
44426   69000
13911   46000
6508   155000
44612   50000
12458   59000
37743   65000
27539   96000
24780   68000
28599  115000
19214  170000
46769   25200
...       ...
49272   89000
16228   60000
462     63000
13058   85000
12379  155000
33324   23000
7277    86000
40035   47740
47176   50000
16430   35000
25602   58200
44283   48000
7630    65000
24624   47710
43862   75000
37782   60000
12858  144000
17193   50000
38431   90000
14774   55000
18239   54000
25202   50000
41636   75000
14900   63000
6937    60000
24522  120000
34870   50000
13875   68000
20095   50000
29776   58900

[100 rows x 1 columns]
            x
5197   110000
41677   55000
37344   90000
3860    32000
35155   85000
42      55000
33676   82000
10416   45000
38507   60000
48098   53040
            x
24323  134000
42337  112000
3015    36000
29641   58000
28259   57500
16965   93000
13019   68000
1328    98000
8342    86000
8797    82000
2195    95000
11982   68250
7954    65000
42090   71500
8275    54000
21371  115000
6043    24000
1466    63000
30415   48000
11464   70000
16633  102000
17928  198000
45281   33000
26618   76000
49549   68000
27596   53102
25303   42000
17689  140000
42619   40000
21963  150000
...       ...
31551  107500
40153   54000
41732   71000
22192   82000
344    130000
8917    48132
33212   34000
37051   70000
31211   40000
45903   60000
16558  105690
27566   30000
16758  100000
5846    84000
7725    42000
36744  190000
31452   63600
46311  130000
1588    34000
40093  108000
20300   39000
25556   95000
33201   60000
10919   75000
29249   77585
6597    35000
8244   131000
9783    92000
26975  125000
472     41200

[100 rows x 1 columns]
            x
45317  100000
48906   58000
45451   40000
48541   30000
41154  156000
33467   37000
10946   40000
25484   56000
5098    83600
12236  174000
            x
10385   58600
38777  100000
23742   72000
35444   30000
16926   95176
38908   60000
21338  110000
1034    45000
496     95000
10616   24000
42865  156000
12224  150000
28763   65000
46928   45000
5745    47000
48596   72000
23116  150000
88      45000
13559   76000
20742   58980
13701   50000
13646   31557
29500   96771
1223    30000
36102   22000
39628   80000
40692   63000
34914   40000
2993    40000
9975    35000
...       ...
47584   80000
22420  111400
41125   53600
17706  140000
26303   48000
14887   48000
11649   41000
26513   76500
49416   70000
24648   42000
46542   76000
22366  139000
41191   60000
43223   45000
34740   95000
38299  105000
12366   30000
25047   80000
3864    87000
44625   35000
16615  135000
28779   95000
40750  121571
22493   40000
36685   54000
42023  126000
13205   87000
8865   140000
18391   25000
20150   56160

[100 rows x 1 columns]
            x
24266   50877
28268   30000
4210    52000
3755    33000
5317    85000
20117   71700
1137    55000
24481   91800
48999   60000
27505  107000
            x
1007    90000
44939  105160
23010   35283
39444  120000
14441   80000
45217   47000
6090    40000
20937   79000
34910   80000
2477    43000
37808   72000
15190   45000
9706    58500
44966   25000
34378   45000
23698   80000
5866   134000
44851   60000
45522   70000
35273  130000
25643   42000
13168  150000
7608    57000
46942   49000
30718   45000
14933  110000
5679    67000
47949   30000
43073   40000
5119    98000
...       ...
24686   40000
21324   15000
17327   37000
28554   65000
2724    57600
12748   90000
44956   50000
42781   77000
11631  100000
32058   31000
32792  130000
34266   38368
11605   55000
14112  128000
48091   80000
35568   43000
35590   57000
30812   48758
45072  104000
32601   75000
3451    90000
6585    60000
1142    94600
6707    40000
14650   52655
33966  100000
32327   75000
13058   85000
1063    50000
43922   81000

[100 rows x 1 columns]
           x
26317  87000
2592   43300
18511  78000
47884  25000
16169  52000
16933  70000
41997  37500
41497  48000
31340  60000
27340  27000
            x
27914   45000
9272    73000
37676  105000
17178   47520
14589  165000
39945   44000
43753   34000
39204   61000
36158   83000
49911   35000
12304  165000
12150   72000
5692    14000
33110   32000
30570   82000
5116    31000
31132   65000
32503   57600
17982   58000
36085   52088
41152   74872
43375   40000
24539   80000
43781   48000
12947   16000
38228   52000
41843   78000
29834   60000
16483   43452
25725  100000
...       ...
23242  108000
4204   170000
1155    60000
31666   64000
4603    48000
31029  155000
36069   81000
34561  150000
18202   24000
21356   90000
39408  120000
33106   90000
43025  110000
22825   79475
6472   122000
46222   53000
16415   59000
29589  147300
46814   42000
28024  105000
20892   51000
43121   43000
30740   45000
27858   55000
47941   28500
39741  135000
34643   35000
32746   90000
14297   34000
15709   17000

[100 rows x 1 columns]
            x
45552   62000
3272    51000
10242  120000
49799  132000
15182   40000
12630  110000
8296    35000
43242   41000
23874   76000
19011   60000
            x
26554   78000
1162    50000
46049   70000
47664   38040
1949    38000
43654   45000
34472   55000
30592   55000
4342    65000
23397   40000
15658   30000
25746   92000
41460   71000
20906  130000
3239   100000
37214  150000
44906   33280
41841  120000
33159  120000
3988    20163
38425   16000
11512   59000
47575   42900
12723  120000
36297   45000
30096   80000
49127   28000
13001   25000
46983   80000
49155   70000
...       ...
21611  146342
2468   165000
30645   95000
22837   75000
17667   50000
16637   75000
34931   43000
9833    82000
22788   85000
29122   50000
18054  136843
25288  135000
27800   50000
34193   32000
20154   20000
5482    45000
20234   99800
32797   53800
5966    74000
46781   51000
46384   57960
20370   60000
32471   40000
44399   55000
43690   54000
32543   60000
41912   38000
45690   61000
10087   38700
12597   25000

[100 rows x 1 columns]
            x
26548   40000
18406   51000
39017   72000
1737    55000
42039   83000
32261   72000
37761   55000
24295  125000
38462   54000
36251   50000
            x
17263   70000
30412   39000
22709  170000
24069  150000
29208   24000
16211  100000
26694   82000
26102   83200

            x
2103    40000
9744    60000
12991   41000
46647   40000
5331   117350
12243  160000
31549   30000
17128  105000
17401   92000
23680   83000
            x
8593    48000
12861  115000
38763   93500
11220   35000
16238   83000
6054    67177
41588   75000
29858  101000
24299   40000
6976    82000
36768   50000
18058   55000
18629  105000
36197   25000
31862   95900
26309   54000
6363    80000
35933   38000
17739   65000
48906   58000
45263   80280
25872   65000
30872   93000
1096    42000
27358  118000
29934   80000
8997    70000
13331   52000
15726   52000
48755   56000
...       ...
18044  145000
40633  138000
31548   50000
42607   61800
8285    72002
4806    35000
22711   71100
12134  140000
24031   51000
21979   50000
17456   47600
13791   80000
47489   66000
6985    50000
21898   22409
13781  185000
11455  124000
39747   28296
12290  131000
1072    49000
4011    48000
22249   61000
40186   50000
29576   45000
2190    65000
42020   40000
23230   46000
29509   61000
14065   51000
13393   52000

[100 rows x 1 columns]
            x
44609   65000
44184   67000
13532   48000
26436  103500
48748   30000
34802   55000
36440   71000
6081   175000
22834  103000
33639   84500
            x
49306   47500
43559  110000
35311   86000
30394   33000
43680   88926
12508  100000
12873   50000
18091   65000
39715   65200
10359   83000
34898  100000
8116    95000
4921    50000
6431    68000
48183  133000
20000   73000
14343   65000
12433  167000
11111   45000
35932   53500
38733   52000
48326   69000
34097  127500
23607   52000
44681   30000
40477   64000
45933   45000
23700   33276
9090   195000
5223   132000
...       ...
7477    85000
17124   72800
393    120000
6074    40000
7483    86400
22989   54300
33239  160000
27662   65000
27226   65000
14930   55000
21399  100000
44557   85000
19695   96000
38692   40000
34396   65000
14727   56000
23314   53000
5523    78000
348     79000
8497   148000
20183   99000
3769   108000
48747   55000
40965   32400
28333   57000
46317   65000
7828    90000
31166   30000
30646   38000
20014   40000

[100 rows x 1 columns]
            x
6904    35000
44910   42000
19748   65000
8254    75000
32897   28000
48480   45000
27436   78000
23476   81000
30962   48000
36263  115000
            x
41747   32000
15990   42000
17444   92500
15019   40000
1356    59000
20288  100000
35852   43500
41633   35000
46981   48000
32345   14369
24215   30000
9671    28080
19977   66000
24409   35000
46686   42000
1508    79000
6632    25000
19872  100000
29826   53000
2750    24996
12541   42000
37176   30000
30     126000
5055    57000
32759  106000
46784   49836
26568   42000
49651   13000
34878   35000
49337   32000
...       ...
24189   51265
41867   70000
41028   42000
22297   55000
7876    88000
19912   57000
23105   51000
17097   68000
23863  180000
24712   46500
37785   29000
34447   42000
42813   36000
10948   52000
38134   85000
117    110000
39089   87000
39417  100000
18148   48000
2353    26000
9678   100000
1619   114000
24878   82000
49663   30000
20515  115000
26543   80000
44030   30000
31403   45000
7202    47000
9479    98600

[100 rows x 1 columns]
            x
314     35000
47913   85000
6189    32000
16180   40000
32293  128000
46309   84000
37049   64000
18366  140000
25621   50000
48070   75000
            x
10439   95000
30539   27705
12278   46000
32685   58000
27506   60000
14146   65000
20321   95000
47208   70000
31734   58974
39555   68000
39482   80000
12715  168000
45628   48000
36849   30000
37960   62000
23096  195000
30243   32000
6004    53000
11951   69539
935     34000
18663   78000
41278   75000
8643    74000
29038  102000
8872   100000
13991   72000
28351   80000
36767  103000
39721   60000
41665   65000
...       ...
35      58000
30219   29435
26436  103500
25262   40000
35932   53500
1577    30000
9844   126600
42994   81696
261     35000
9453   110000
38521  135000
15802   55000
25680  120000
9775    49900
32184   69000
36207   75000
40062   32000
26565   46000
48724   65000
13812   27000
33678   38000
29432   39458
25296   33000
39139  120000
4540    40000
31510   43000
26691   66000
37584   47000
41937   55000
42841   59184

[100 rows x 1 columns]
            x
39368   90000
25146   57000
45562   90000
33256   25000
7197    42000
38555   65000
12684   85000
3148   163000
4414    36400
14202   35232
            x
43625   84000
34148   18144
2317    57000
49799  132000
32945   57000
36380   70000
47414   92000
7956    52000
40096   38750
39695  110000
31987   63924
14981   52000
4797    80000
5619    39000
47780   75000
42866   85000
35393   42000
37305  130000
18995   50325
47668   93000
17228   44000
3909   100000
34976  140000
42315   50000
21626   15300
28111  115000
20711   94827
3865    52000
14623   57000
12246   66000
...       ...
35607   66756
9426    54200
4750    48000
6673    60000
12372   50000
43280   75000
48703   88000
31435  120000
8829    48000
7313    63000
172     36000
17042   93000
44192   48000
44987   75000
42149   90000
44433  110000
22981   85000
17154   62000
47496   30000
13387  136248
37015  105000
29787   90000
32757   72000
19029   33000
7005    42000
9179    42000
2970    88000
18637   60000
1837   120000
31602   43000

[100 rows x 1 columns]
           x
47968  24800
19516  60000
12336  75000
1426   70000
33542  78000
21965  65000
1532   25000
49453  62000
15906  40882
39629  60000
            x
13165   32165
47723   67000
19160   40000
30502  100000
9043    60000
15947   50785
2649    79000
40820   75000
23393   24000
16160   66000
12230   45000
35414   65000
7016    50000
19857  115000
21970   78000
12914  130000
48214   42000
1289    60000
28751  185000
13155  109000
42165  103000
14867   33000
4301    60000
18405   85000
315    100000
25318   63000
11901   75000
38110   40000
48866   60000
11395  100000
...       ...
40970   69190
4996    60000
45766   82000
43147   76399
18237   60000
3088    38000
37392   60000
11592   46000
20409   72000
37065   42200
37642   43000
28026   70000
26735   89000
1654    75000
5012    53000
26512   64000
38765   19500
22169   52000
22792   85000
30073   42000
12524   70704
31852   60000
2963    35000
17173   70000
46723   41800
27372   66000
48086   90000
27405   41000
35666   60000
11906   47210

[100 rows x 1 columns]
            x
35225   60000
6695    53000
371     48500
17340   69000
19646   40000
4236   125000
21030  115000
38496   59000
48566   69000
39126   53500
            x
33289   27000
6338    20000
48550   44000
37177  123000
27793   68000
4224    40000
10565   34000
7865    56000
20917   75000
27645   48000
46795   46000
930    105000
5531    53004
42597   32000
36257   45000
37585   60000
10324   35000
3953    53374
28567   30000
22543   98000
405     49070
20701  116000
34528  140000
37038   45000
37148   43350
34573   75000
45897   58000
33534   49000
22247  140000
32778   68000
...       ...
257    100000
37833   67000
5556   101000
49700  100000
18140   98775
42760   82116
6950    65000
38988   95000
2940    37440
14110   52000
14888   60000
31733   47000
45388  160000
33228   87445
30719  100000
22926   28000
39      81000
14044   55000
7347    90584
44139   50000
23700   33276
578     50500
2342    39000
35753   74872
829     35000
21086   48000
6233   100000
18734   56000
41028   42000
45060   41000

[100 rows x 1 columns]
            x
41403   84000
1270   115000
11650   43000
44774  110000
8846    32000
31541   44000
21084  101000
10688   31000
15048   37000
32090   84403
            x
30114   80000
24523   46000
2667    63000
1170    50000
27700   37000
8950    72000
6646    30000
25113   40000
21752   52000
20203   40300
41884   72000
323     34600
32942   60000
21495   49000
20605   56000
32938  101000
45900   80000
7574    40000
49770   40000
34556   36000
11473   33532
36880   28000
10204   28000
24244   15600
37280   65000
18160   48000
2602    24000
36207   75000
43872  137500
1807    80000
...       ...
13484   50000
34955   42000
26375  123000
16330   48000
10230  120000
47799  185000
1795    72000
28822   42000
38205   52000
36903  125000
1880    75000
42405   55000
6410    30000
31344   60000
12941   64000
2474   100000
12858  144000
45926   50000
46324   57219
3841    18288
16390   41000
42474   42000
9276    87106
22781   47500
38448   72500
827     78000
8277    80000
43523   98000
42427   60000
20379  103000

[100 rows x 1 columns]
            x
36969   67000
36408   77000
17267   46800
38919   46000
6078    30000
32772   65000
49299   90000
38965   55000
42723  115000
9170    43000
            x
26902  160000
12533   96415
6013    75000
25089   42000
13770   62000
21029   65000
33586   45000
16832   48000
17386  154000
37854   70000
24426   33000
15178  115752
43025  110000
20736   36960
38941  125000
39721   60000
18761   90000
21345   40000
19279   43160
48497   67500
32132   43000
2661    60000
25077   21600
30791   60000
11109   75000
38996   30410
22716   50000
28732   60000
35520  125000
1593    45000
...       ...
8178   110000
49915   32000
29853   32000
8657    95000
21633   68004
23068  106000
11416   35000
19004   50000
7653    57200
27969   58747
37312  100080
14569  107120
30931   70000
41753   80000
41948   70000
35556   89000
46633   15000
41467   49000
37865   34000
18654   48000
17184   60000
18439   50000
25951   80000
26954  126200
23256   50000
26410   90000
25725  100000
12521  100000
28859   48000
18248   22000

[100 rows x 1 columns]
            x
29135  145000
4644    28000
5385    35000
34519  158000
19332   60000
37146   85000
4917    60000
36540   42000
28186   72800
47164   55000
            x
31912   70000
17666   45000
16454  120000
5040    90000
48800  125000
26280   30000
33136   55000
38955   60000
45496   84000
24147   35000
14975  148000
35863   96000
10294   80000
33205   45000
12606   56000
26655   41000
12026   25000
32301   88740
20740   39000
30519  120000
23214   28000
26582   60000
22906   60000
49872   60000
12371   46250
42793  115000
14871   86800
40309   46600
206     39200
22091   60000
...       ...
15322  105000
29841  105000
7995    72000
801     90000
6288    84000
45890  186000
44268   26000
45001   19000
28315  120000
1350    76000
11639   55000
34105   95500
30431   77000
21774   66143
34378   45000
39242   25000
20407   90000
37376   14400
26243   77600
47781   72155
43835  111400
37788   20000
35667   40000
26058   51072
13170   13000
49788   67000
9639    60000
35583   40000
45273   25500
16503   20200

[100 rows x 1 columns]
           x
24204  75000
13039  30000
40039  45450
44183  19000
35418  60000
29344  50000
22053  49700
17275  50000
123    60000
42999  55000
            x
27800   50000
47486   82000
20160   66560
15394  110000
27667   21768
47636   45000
20655   45000
47663   43000
35348   70000
18007   88000
40686   85000
2283    18333
33860   34000
23969   96304
21520  110000
22453   70000
36496   75000
32627   35000
14730   62000
20916   56066
10278   43000
22256   50000
33617   48000
25081   83513
7470    46000
49819   68809
46273   52484
17133  110000
43964   65000
1200    74000
...       ...
14236  120000
23096  195000
5946    60012
7075    73000
33939  140000
28691   30000
41222  110000
30964   65000
40626  125000
40031   13000
46203   66000
27922  100000
27429   61500
14005   65000
24064   85000
934     65000
27137   14400
6630    98000
24598  110000
44740   55000
33856   65000
835     60000
7205    49758
8267   112000
40745   40000
25582   98000
9363    52000
16933   70000
36810   64000
6226    44547

[100 rows x 1 columns]
            x
30307   55000
18903   40283
25267   56000
25101   89000
7287   122931
31055   95000
33468   70000
35294   10000
23246   81000
30046   94957
            x
49197   19200
16590   38000
11608   85000
9841   100000
37724   40000
41663   92000
49982   85000
20571   90000
47379   56100
32445  140000
23813   89000
654     75000
14375   44000
44015   53000
29666  130000
43298   54000
38658   16656
39815  110000
10388   30000
13143   40000
17394   92000
1929    34080
48751  102000
15576   73000
35523   91000
45612   50000
16041   60000
29963   50000
31406  138000
29713   71000
...       ...
28688   60000
45400   36000
2881    65000
44855   64000
29859   53000
42608   48500
13081   55000
24515   91673
49216  125000
15731   65000
23008  103000
24942   31844
153    105000
5290    67000
18237   60000
34086   31000
26086   73000
16862   63000
49430   35000
10669   55000
21106  110520
28060   80000
23118   43000
28555   52000
17225  130000
49332   78977
46985   75000
9764    47500
12638   55000
37117   29152

[100 rows x 1 columns]
           x
22719  54000
11090  35000
5688   73000
30872  93000
9398   48000
18351  58000
36746  50000
10321  90000
35807  22128
24949  90561
            x
14846   70000
41709   89000
25092  105000
15732   80000
26758   86000
39200   62000
41324  168000
37275   34000
8430    52000
45433   43000
2069   130000
20235   50000
36083  137000
44464   35000
15486   48000
421     51376
27583   46000
37405   75000
41972   36000
5369    63000
29674   50400
33735  120000
34117   78000
20875  120000
15930  120000
33541   34800
8693    64000
5143    55000
1346    45198
28358  150000
...       ...
47160   55000
44301   40000
433    110000
28799   60000
32541   41356
8478    50000
12210   26000
23808   24000
45410   22000
18637   60000
47297   58000
2901    85000
9279    90000
12064   86000
46672  130000
17845   70000
43744  160000
13547   95600
18494   72400
4283   100000
4491    70695
2961    68000
43268   75000
11981   75000
27158   30990
19209   85000
21512  115000
18053   34000
30522  100000
21700   90000

[100 rows x 1 columns]
           x
22138  38000
19271  16000
667    52000
34760  75000
2154   75000
9545   68000
11082  58000
8037   75000
2840   69000
16696  80000
            x
23699   74000
5479    49000
47469   45000
7627    64000
49730   51000
34067  135000
24244   15600
2299    62349
23884   36000
4043    48000
28005   52000
23557   61992
6443   125000
12274   58000
22582   36000
32620   99000
14805   18000
42689   75000
9072   105000
47369   96143
43831   39000
20464   66000
7179    66500
27308    9600
27866  110000
35845  100000
2440   165000
35425   40000
29974   55200
46840   39996
...       ...
49754   60000
7739    29120
21465   50000
26050   27000
28068   52000
46001   14400
32824   48000
49136   27000
28107  115000
18538   41000
12894   30000
601     44000
33462   38000
23530   71000
1203    68000
5539    37760
18758   84000
46601  166000
36942   49920
43868   48000
33636   70000
43255   75000
42099   75000
7217   127000
27119   45000
22311   36500
3394    77991
188     20000
43558   25000
16902   48000

[100 rows x 1 columns]
            x
14253   60000
16766   50000
1363    75000
39586   52000
34388  100000
43235   82000
3517    48000
22201   37000
29137   60000
19577   52000
            x
32359   35000
20946   15372
506     54720
46184   40000
48588   51000
30948   50000
25911   57000
15001  102000
5508    33616
43203   55000
29900   70000
29737   95000
44453   37000
3841    18288
42138   85000
40879   46000
16169   52000
44993   70000
30318   70000
4844    90000
26941   85200
29150   81600
18788   60000
7274    60000
16823   93000
41350   90000
7444    85000
27400   89000
25227   50000
7517   110000
...       ...
34083   47301
12416   31200
23813   89000
48174   37550
12110   59084
9738   110000
35679   32500
26954  126200
21626   15300
36951   60000
25958   40000
45288   36600
1226    53000
1193   130000
45237   65000
3252    92000
42945   48000
6013    75000
41935  102600
48718  150000
38935  105000
35195   90000
18153  122004
40424   40000
13878   75000
22463   80000
37000   41551
3107    80000
38129   50000
48560  105900

[100 rows x 1 columns]
            x
34559   50000
605     50000
10009  110000
8358   160000
3738   107000
47113   70000
10787  147000
24813   80000
28107  115000
8134   110000
            x
48822   45000
13810   67600
817     60000
29682  150000
36102   22000
1524    49000
21754   54000
40420   33446
37122   85000
35917   49993
43071   40000
18770   63800
13543   37663
9020    50000
40457   75000
18495   40000
23867   75000
47592   32000
2823    74000
20339  135000
31332   38000
38724   90000
7499    43000
20390   97000
25137  150000
32671   36000
12894   30000
25342   70000
14137   74000
49276   32112
...       ...
3098   160000
686     95000
41718   26000
6026    35000
33534   49000
5135    30000
13951   62000
36576   75000
34329   63000
19273   30000
35877   28000
19115   60000
15804   75000
30591   25000
47055   60000
49537  104000
49247  140000
18270   45000
30757   51619
17502   82000
14842   60000
30759   50000
29857  172000
15483   55000
17056   74000
6293    40000
6121   185000
44379   70000
41658   95500
26195   21000

[100 rows x 1 columns]
            x
9987    45996
4117    50000
11325  107000
200     80000
44095   61100
8402    40000
28752   27900
5073    49566
19749   60000
27749   79000
            x
18902   70000
30501  145000
25457   74000
29276   61000
40251   70000
12436   57000
12576   42800
23251   57000
49109  108857
45475  130000
39412   57000
5181    35000
13582   66300
30764   57000
9855    53500
34720   28800
33388   45000
4807    56400
14515   48000
31690   70000
2673    64404
45818   28549
11837   37000
26139  160000
22236   32000
43579   62000
25106   54000
16007   60000
14254   47500
16835   37440
...       ...
7097   112500
37098  137800
13623   45000
27178   65004
8174    49000
1007    90000
11448   90000
30004   30000
24815   70000
27549  100000
37203   49000
4018    79878
25911   57000
14846   70000
2829    95000
15707   23196
19226   78000
19223   50000
32574   57000
38734   65000
36087   75000
44198   39000
9491    40000
44242   20000
17876   50000
41094   32000
23671  160000
20028   60880
22003  157922
9494    29000

[100 rows x 1 columns]
            x
36031   50000
37979   25000
7515    59295
32813   40000
28548   35000
8085    60000
6695    53000
39141   75000
46852  108483
33865   41600
            x
46870   26200
13648   46800
34470   96000
6716    50000
9706    58500
47535   49555
5162   120000
9997    48000
22264   71000
13781  185000
25567   80000
1238    65000
21646   78155
3378   133000
24386   36000
46440   85000
29088  153000
45894   32000
33549   98000
37577   75000
5042    73500
39388   32000
1232    35000
37289  125000
38858  100800
40051   98700
47822   60000
38712   40000
11132   80000
11910   60000
...       ...
49250   99500
17599   60000
33361  120000
37966   62000
10969  125000
19534  135800
38113   47000
11854   79000
4536    28000
22833   70000
34738  129697
46726   35000
36042   60000
19506   36000
25500   75000
35232   70000
15083   72000
47475  150000
12286   50000
48617  110000
6007    53000
49759   60000
1421   110000
2136    46000
31446  111000
21120   70000
45957   35000
32465   92000
30599   22000
35603   60000

[100 rows x 1 columns]
            x
23139   77000
41246  100000
2938    85000
27279   21184
1654    75000
32015   43000
22032   60000
17715   50000
1942    55000
4917    60000
            x
49293   50000
37815  150000
41942   50000
10129   50000
30691   26000
41660  108000
48118  120000
39836   45000
24648   42000
20226   95000
29028  114000
37084   65000
43655   39132
32507   29120
8755    70000
26944   32000
20040   37423
6078    30000
1567    82000
5327    48000
18952  129000
9851    35000
29939   42300
4591   132000
48180   25000
10150  130000
3514    45000
43823   57600
8535    74000
33212   34000
...       ...
11864   45000
8072   115000
29300   38241
18669   68000
473    100000
33543  120000
40212   85000
43945   70000
20141   63000
22039   58600
45359  123000
27388   26000
12126   29000
27428   75000
35245  110000
49316   21000
8014    22884
48840  165000
6883    32000
20340   55000
32035   62000
10253   70000
41380   85000
35630   51000
27235   70000
49274   90000
17253   32000
27032   50000
40434   36000
39861  116000

[100 rows x 1 columns]
            x
22981   85000
21086   48000
10978   65000
10097  110000
45963   70000
13096   75000
19288  180000
37451   46000
3382    54000
29246  126600
            x

            x
42790   25000
8499   101500
43239   40000
28583   50000
31666   64000
20285  130000
13395  120000
20807   32000
30900   81000
11791   50000
            x
46755   27000
45521  108000
46038  120000
41916   57000
36600  105000
48371   53000
30188   45000
5452    29500
18207   72000
21790   34715
33161  130000
13223  110000
829     35000
29904   62000
171     87400
22844   84498
24146   34000
2614    45000
28831   45000
48571   55000
22480   49000
21123   42000
18037   59915
46935   57500
31304   58000
12783   74000
24754   45000
44259   69000
10046   50000
28828   37000
...       ...
35713   60000
35060   24000
40528   30000
28471   78000
14650   52655
49273   48500
12981  103000
28582   32000
29955   70000
29998   46000
28924   38000
33942   26000
21276   60000
16970  132562
43629   25000
25493   85000
31091   52000
285     71000
48722   40000
14530   86000
8631   117000
23674   43000
40712   43000
7641    65000
9409    80000
48988   75000
46798   81300
46884  120000
23903   11000
8491   130800

[100 rows x 1 columns]
            x
44358   32000
31617   60000
42667   60480
37699  160000
35147   54000
3065    20400
26035   54800
49071   72000
21587   72000
25859   80000
            x
395     64590
4038    50000
31532   55000
31390   43200
25637   46000
39210   65000
38552   41000
35137   60000
34997   57000
38515   41000
31606   80000
13713   56160
14917   66601
12203   50000
4982    63000
36121   84000
35241   90000
10872   66000
43932   30000
47208   70000
48820  115000
11561   30000
47637  108000
1606    61435
36893   94000
18450  100000
40173   80000
4836    30000
19852  143000
34843   30000
...       ...
22380   66900
41202   51000
35643   78000
5537    42000
41263   62500
28646   41000
31641  110000
39923   27000
20319  175000
24297   52000
48192  120000
41358   40000
11770   50000
20163   78000
13222   95000
32155   45500
37048   54000
16609   36742
35796   25000
11120   29406
16410   92700
12808   70000
14361   59728
45150   27000
3896    56000
3857   150000
48742   55000
21845   92000
9571    41500
13821   28500

[100 rows x 1 columns]
           x
6614   80000
11390  40000
449    33000
25594  49000
26771  58000
41052  90000
6695   53000
20305  43000
6173   51200
18336  92000
            x
1324    80000
28161   35000
46487  115000
31398   39000
37092   26300
667     52000
12246   66000
21511  135000
42157   40000
37100   30000
20305   43000
9504    64000
20788   34465
28996   53000
49055   88000
19087   76344
36294   48000
8811    52000
29760   32000
26695   75000
8717    10080
42167   40032
1152    53000
1016    70000
44040  100000
21620   68000
39094  145000
224     43000
34425   48000
20539   65000
...       ...
18378   58500
48490   80000
6250    36996
6650    39000
20      30000
25505   97000
43701   49000
36720   60000
43393   75000
35204   38000
12143   38000
25895  100000
39993   32880
24081   55000
35090   62000
4558    52000
31660   89000
33303   62000
20946   15372
29452   70000
41898   80000
7894    19100
1468    57000
38647    8000
7137    65000
23123   35640
7633    80000
30295   40000
9263    96500
19916   70000

[100 rows x 1 columns]
            x
9348    84000
39989   37000
20200  111400
30996  103000
49229   30000
43440   47502
47160   55000
24944   97000
38920   65000
30083   65000
            x
24890   78500
10958   65004
49632   52000
40855   45000
45000   40000
19879   51000
29757   46000
16114   33000
2694   165000
34500   88000
7655    30000
33495   37000
612     87000
35231  115000
32352   66000
3021    65000
28912   41000
46057  125000
20265   82656
46914   90000
21787   31204
4107    21000
43626  115000
16183   39000
26832   55000
31844  105000
7141   110000
34635   50000
41007   82300
46352   99700
...       ...
35839   73550
33337   50000
2244    50000
13871   67000
38710   85000
32156   89000
20730   22000
10501   60000
18247   97000
44794  102000
7685    60000
671    118000
26087  110656
29644   25000
2418    61000
47568   37340
8353    55000
3190    42000
16641   44000
25164   64000
16283   40000
31550   68000
3119    48000
26466   87000
11362   65000
42467   42000
45264   52000
18119  100000
24451   40000
39743   20000

[100 rows x 1 columns]
            x
7464    62000
33570  100000
41082   32000
8655   120000
42811   80000
15902   82000
46643   48000
13600   87000
30747  150000
546     50000
            x
37432   95000
5896    63300
18837   57000
33786   78000
42912   42000
48109   95000
36888   42000
3842    63600
898     36000
14472   26000
25199   33500
12750   65000
19732   75000
36544   82000
17952   46000
37611   45000
29715   66000
29702   95000
7890    60000
11331   69000
1080    60000
44849   60000
30280   42000
43364   32000
17953   60000
33677   75000
44039   40000
38713   30000
16005   79500
44321   97200
...       ...
18627   24000
3710    60000
20690  110000
8994    28000
34963   46000
19149   75000
7665    41000
42370   81000
17588   60000
2287   123600
34864   39000
20372   45000
11077   85000
39620   44000
25527   72000
16195   75000
30882  156000
30372   40000
21690   90000
1134    75974
43363   93000
35359   51000
49467   60000
36525   52000
31206   65000
32587   65000
7187    30000
13952   41000
18184   75000
22635   85000

[100 rows x 1 columns]
            x
45579   50371
20700   70000
17794   74000
43940  125000
2926    25000
8691    37068
9020    50000
38111   27336
40764   60000
35820   38000
            x
44688  130000
4745    95000
1381    67238
32802  170000
13733   36400
43795   65000
3065    20400
41230   70000
43763   65000
2732    54000
29395   70500
31373   61104
6552   108000
23181   42000
28046   65000
15040   73000
45017   65000
545     70000
26871   15000
22775  100000
22764   60000
34813   55000
14591   40000
19709   96000
12694   80000
4934    59000
35979   97708
36737   74872
36208   65000
12244  130000
...       ...
31382  140000
17185   70000
10797   24000
38699   32900
10795   70000
3838    60000
16539   44000
47739   75000
49966   58800
15484   62000
34620   42000
42932   43000
30856   70000
43495   30000
14358   73000
19505   52000
40463   38000
11449   22000
45741   42000
42968   85000
32516   52000
40855   45000
35249   63969
44733   41000
41086   48492
16792   60000
30555  110000
24657   25000
9429    47000
37749   42000

[100 rows x 1 columns]
           x
47387  50000
2203   66000
5636   28000
35996  30000
7785   65000
35025  70000
35745  68000
15766  51000
34767  80000
27802  96000
            x
41844   86000
47807  125000
42526  135000
36372   80000
3109    80000
17070   80000
22802   30000
44266   52000
48058  100000
42516   90000
33510   82000
36923   45000
23433   44000
18517   80000
3946   103000
19221   40000
14511   61000
31051   18000
49695   66000
1794    59000
47710   45000
28502   40000
35116   35000
16887   76000
6588    25000
23658   41000
37737   23000
46207   35000
46424   71000
26276   42000
...       ...
13562  125000
9993    37286
24552  110000
36279   45000
31631   60000
11580   24326
8811    52000
29295   52000
2580    60000
37057   32000
26262   72000
48096   91000
7387    85000
6661    60000
6298    30000
6171    85000
7638   132110
32383   21600
16734   95000
46997  178360
1556    70000
32581   36000
24463   27747
20827   30000
34149  141000
3508    40000
46068  125000
34904  115000
38807   58000
35793  112000

[100 rows x 1 columns]
            x
40946   48000
19911   30000
1137    55000
11756   43000
28234   75000
34895   23000
29299  137000
41751   94000
48772   98000
32777   40000
            x
22577   22800
1081    36000
15983   83900
8743    74000
6067    85000
21847   35000
27837   44000
9425    93450
39692   63000
41568   81004
18061   35100
16265   53337
2280    65000
11447   92000
44086   38000
21837   72500
6365    40000
17658   88000
25397   33000
12268   90156
4349    32000
4205    58000
10847   84000
25821   60000
31103   65000
20024   53000
15638   50000
16326   50000
26206   97000
47662   80000
...       ...
8447    46000
6188    61000
14381   28000
44762   50000
8444    46000
47331   82500
34496   55000
17106   94695
8796    54424
8983   125000
37487   62000
13309   30000
46187  180000
2718    82000
34278   63000
45302   73000
34462   51000
28005   52000
11408   57500
42624   72500
43155   60000
49552  165152
44570   25000
34340   60000
2680    40000
9133    34171
2797   140355
866    105000
25580   44000
34160  115000

[100 rows x 1 columns]
            x
28860  100000
4928    70000
48074   96000
25962  104000
39842  135000
33620   55000
18      53000
9070    62000
1716    50000
49821   50000
            x
22291   40000
196     63000
40280  100000
26424   63000
38600   83000
27261   40000
44803   33272
8968    62500
47228   70000
21286   35000
24998   95000
24655   53000
44076  100000
44749   42000
30021   60000
16735   35000
49052   60000
36568   80000
27969   58747
29818   65000
1067    45000
16266   90000
27008   35000
21052   96000
39739   25000
367     38000
16306   67500
44711  125000
27567   36000
20886  110000
...       ...
27656   20000
9282    49000
34503   80000
33957   71000
47584   80000
47448  180000
10068   35000
14995   35000
15144   72000
6227    24000
17748   58000
45256   42000
23883   65000
40533   70000
37843   79000
41634  110000
19947   50000
38159   80000
19623   71500
2741    38000
23495  163000
34742   74000
42848   80000
16619   49000
28441   68000
25392   67000
26325   96000
46784   49836
47442   54000
6884    24000

[100 rows x 1 columns]
           x
48823  48000
18566  90000
4337   60000
7328   61000
37173  61000
33385  85000
29392  30000
49665  22599
12334  95000
11479  64000
            x
31189   60000
30583   84000
27145   60000
20470   60000
17914   53000
48889   51000
26864   72000
45367   55800
33582   64000
34084   65000
8649   131328
19224   90000
9086    65000
47201   60000
30346   60000
10233   43000
3382    54000
16674   35000
41478   42000
34859   89000
41861   52000
11967   72000
25941   48000
568     31000
20661   88000
47174   45000
48653   51000
461     30000
41431   75306
4210    52000
...       ...
3463    32400
2635    56000
2542   103000
46913   41000
17955   46000
341     60000
32236   58000
13373  100000
44942   35000
41774   44400
25625  155000
46075   30000
2866   120000
3445    36852
11272   40000
17894   61000
41105   38000
21348  165000
31420   85000
1660    55000
28670  135000
10158   55000
10128   66900
49655   92151
1628    65000
5040    90000
21066   38000
48010   50000
1255    39800
5953    38000

[100 rows x 1 columns]
            x
36713   69000
29175   51000
47199   77000
37312  100080
9933    44000
35713   60000
45816   34000
12136  110000
9677    98000
48636   65000
            x
45209   92000
39421   60800
40888   80000
14591   40000
17413   90010
15090   34000
9373    65000
26376   79000
26041   82000
20229   60000
47108   94350
28536   23000
49709   40000
34994   35000
10078   36000
7622    40300
39365  111000
33867   39000
40401   63000
44442   58000
16458   35000
44157   75000
26636   35000
7198    14352
20738   60965
48726   68000
20956   59980
38164   36000
16345   40000
40431  100000
...       ...
30779   13000
20854  103793
38672  135000
37936   45000
40958   41280
7974    63000
27022   49571
26468  100000
847     52000
26028   54000
36298   90001
19120  120000
42506   54000
31413   58000
48222   41000
28434   69000
8849    29000
13422   62370
10678   54000
7094   113000
33742   27500
20371   51000
16012  158750
34785   38000
41735   78000
28599  115000
42039   83000
18358   55000
16337   84914
24114   56000

[100 rows x 1 columns]
            x
27765   84815
24196   71000
44455  106000
38540   53000
24345   75000
35332   56000
29488  104000
4123    48000
49945   51000
16180   40000
            x
1288    68750
1409    37620
42176   75000
27277  105000
49346   58444
45960   90000
18517   80000
48582   32627
36692   89000
22700   41000
29755   50206
49048  100000
48022   52000
409     70000
2496    63000
3897   105000
34405   98127
44661  115000
4541    39200
3664    30000
20787   33000
14700   58717
47481   83000
11833   45000
28657   65000
22359   74000
2464    78000
1620    78000
1945    80000
48992   75000
...       ...
24104   29000
13734   80000
22457   65000
4062    80000
15055   55000
35769   72000
7825    48000
42775   35000
44888   24000
37037   65000
2984    58000
8789   100000
16985  150000
21253   90000
45179   90000
35534   92000
10085   40000
40980  108000
14670   10000
12689   70000
48148  106000
21584  145000
37473  125000
13631   65000
12452   60000
7304    75000
32748   50000
39268   47240
37552   45000
41949   50000

[100 rows x 1 columns]
            x
47014   75000
16032  100000
3287    36000
41447   60000
22931  130000
22372   32000
29633  123000
39827   98000
3769   108000
22830   60000
            x
12945   75000
10211   65000
18029   86000
27930   16272
20312   52000
14371   55200
11917  125000
45448   87000
11958  110000
10208  105000
26218   60000
23280  180000
5932    74000
13221   55000
396     50000
43325   56000
45632   30000
43615   55000
8559    60000
23117  101000
4365    55000
6411    40000
2311    55000
29353   56000
11172   65000
39913   41000
39930   50858
14356   50000
3478    36000
44360   95892
...       ...
2295    85000
46899   42000
2115   185000
14945   67581
5028    83731
10187  123500
457     75000
18119  100000
47277   46000
4756    64700
27665   76500
35651   35000
34410   61000
40892  116136
35441   72000
24199   34000
49034   47000
30596   40000
19250   38880
5686    29000
33516   20405
15471   62000
42362   67000
30488   84000
521     23000
36523   86000
46271   80000
21702   36000
26110   78000
29052   92000

[100 rows x 1 columns]
            x
29961   79000
15404   94000
15492   75000
37408   62200
28870   42000
43369   89000
6530    36000
6044    42000
30257   62000
28851  145000
            x
25041   48000
10398   95000
25692   65000
43122  106500
46179   45000
41624   46900
40462  130000
30628   60000
38859   60000
43704   45000
28939   72000
2979    59436
45579   50371
40399   43000
35370   40000
4286   115000
23361   56000
41840   50000
39285   45000
19464   50000
19386   50000
39901   45000
11791   50000
40631   60000
21899   73000
4412   160000
15524   50000
5681    80000
19048  123000
34641   90000
...       ...
32214   71000
7128    80000
15640   40000
24019   57500
14814   48000
36728   17628
25402   98000
23436   23000
9728    25000
35569   35000
38864   47000
28376   80000
18709   57738
25914   60000
11948   52000
36601  120000
20632   45000
11466  125000
27919   60000
36840   49067
29801   36000
6122    32000
43308   80000
36505   53000
14792   30000
11841   41000
14506  132000
8420    63000
26940   55000
6326    60000

[100 rows x 1 columns]
            x
49838   70000
33258   85000
6196    65000
41722  170000
103     50000
4137    95000
6631    72360
30742   23000
28746  156242
37126   45000
            x
11985  103000
37978   54996
43827   37000
36870   54996
48733   80000
43417   79000
42816   50457
43130   90000
44903   60000
42921   29926
19423   70000
36287   54000
33396  105000
5334    98000
44496   38000
13904   90000
29177  150000
30116   98000
23228   30000
37577   75000
13380  156000
29708   85000
9068    32000
39530   48600
21663   28000
16694  150000
37255   72000
11366   88000
17498   71000
28494   84000
...       ...
21950   94000
6034    65000
28395  100000
8415    42000
5128    60000
44788   60000
2709   160000
40795   85000
31586   40000
9822   120000
33726   90000
11456   50000
47485   70000
30183   40000
36291  103000
916     65000
12350   50000
46587   75000
22974   28000
14646   30000
35979   97708
11781  115000
19658   81600
9688   113537
46562   46000
19683   26000
26928   92500
5538    45000
14460   70000
38177   57900

[100 rows x 1 columns]
            x
9086    65000
21134   89000
7620   100000
37647   40000
44262   85000
49808   96000
11143   36000
22716   50000
2857    88914
35384   66300
            x
43126   34000
47126   75000
35342  120000
31431   50000
17067   11200
31153  135000
26091  119000
23114   45000
6704    43000
21876  120000
9967    55000
33487   30000
24088   80000
32144   35000
19027   51000
31937   55000
33365   62000
564     55000
45110   85000
32736   50000
3133    72000
16411  112000
67      95000
42115   50000
5616    43000
1726    28000
2433   105600
24821   69000
29292   71603
39706   95000
...       ...
26754   40450
35032   55000
37061   60000
5938   117990
12542   34000
35858  102000
2453    60000
44492   59088
25145   40000
32093   65000
1256    47000
42805   72000
21552  160000
26088   73000
6038    89131
24846   30000
44957   40000
46720   86000
45479   93000
27380   71000
35517   32000
43310  100000
40550  120000
798     65700
9276    87106
37123  100000
43003  100000
28302   75000
38714   60000
23847   60000

[100 rows x 1 columns]
            x
29215   85000
15434   60000
25547  100000
48072   93000
44079   80000
1684    90000
31221   78000
12644   80000
49905   45000
5574   190000
            x
4707    75000
17878   22000
33234   83000
8773    32000
40281   75000
7244    35800
3190    42000
38580   82000
24142   29500
35920   46000
49647   33900
27969   58747
41325   57000
39668   95000
29557   60000
22507   36000
19242   62000
15332   50627
4590    60000
11485  120000
8499   101500
11220   35000
49256   55000
285     71000
9097    78972
26422   34000
35879   89700
36991   89000
1699    30500
5473    72000
...       ...
24383  106000
42591   70000
4663    75000
26028   54000
14441   80000
18753   51000
17154   62000
4260    47059
31097   61200
44480   50445
49044   55000
683     42000
6149   180000
16405   18500
34741   36000
35588   42000
113     45000
45800   30000
16819   97000
3937    80000
32465   92000
38736   70000
25014   60000
30900   81000
5658   150363
21116   37439
37739   90000
9437    50000
25775   42000
6112    32000

[100 rows x 1 columns]
            x
42578  165000
2644    40500
17853   32640
32726   67277
4198    59000
44881   30000
26632   80000
35201   55000
36202   37500
45987   28000
            x
44936   53000
6535   132000
15559   40000
8399    30000
366     80000
21321   70000
23434   48000
5465    45000
3470   117500
45848   65558
29615   80000
22176   60000
31285   50000
13753   70000
1709    31000
46666   55000
47473   33000
5333    45000
6769    78000
29258   95000
44744   75000
6649   110000
37679   44000
36167   39000
693     71200
45836  132000
17355  110000
7729   115000
14176   33000
6650    39000
...       ...
45494   22820
46786   48000
2731    72000
4555   117000
38888  110000
28660   60000
24255   65000
34816  116000
28833   38000
827     78000
25080   85000
14007   48000
39328   51500
46285   87000
41907   60000
7241   110000
42119   40000
19964   80000
35273  130000
7647    30000
23537  130000
20256  125000
14854   50000
21302   63000
8259   167000
48435   52000
33717   42000
25127   52000
32451  110000
33640   14844

[100 rows x 1 columns]
            x
36491   54000
47923   36000
9593    38000
33927   52000
48310   55000
2313    80000
1483   104500
30252   90000
28166   27172
18000   68000
            x
43106   46000
28551   97000
15327   38000
14276  100000
26024  101000
21382  180000
12274   58000
32634   47000
42091   50923
46306  155000
37611   45000
96      80000
1479    73000
15563  136000
17401   92000
34403   28000
28920   45000
44729  130000
39809   23000
37351   52000
29013  110000
43331   45000
40789   42000
29748  100000
14191   70885
27340   27000
27056   70000
38386   43000
23554   38000
41195  100000
...       ...
45964   65000
11197   62352
10640   52500
42837   80000
19872  100000
12185   58000
18808   50000
7885   170000
20351   75000
30618   45000
6757   120000
27241  122500
28136   60000
43603   75000
47359   85000
11739   45600
46244  100000
7490    32000
29462   34500
44501   48000
19436  157000
12780   30000
36261   50000
49232  100000
5788   143000
15157   60000
31896   80000
42863   68000
24583   85000
15314   79000

[100 rows x 1 columns]
            x
18094   99500
24339   54000
47886   45000
30410   55000
12923  124000
1849    75000
25288  135000
6621    60000
35403   40000
35077   26500

[100 rows x 1 columns]
            x
21388   87000
43747   65000
42555   71200
37695  110000
34074  110000
2523    41004
25480   54000
11128   42000
30625   52000
21654   98000
            x
1289    60000
8810    30000
21469   26400
40419  100000
47022   32000
33172  115000
24400  141500
28327   33000
15348   65000
27918   31200
15917   52000
12978   36000
35041   84872
38989   42000
4917    60000
592     48000
30016   42000
45536   52000
49715   45000
25858   68900
23118   43000
39650   49000
37043   65000
14347   48000
6778    98000
35111   33000
34807   29577
31306   70000
29764   86000
24953   60000
...       ...
5731    45000
47736   71000
39584   54900
13646   31557
48347  124000
21783   75000
43365   30000
37512   68000
22219   44000
3254    36120
31225   80000
39373   38000
22558   41000
28508   55000
10878   77004
49431   30218
47434   82000
38878  125000
30696   84012
24689   52000
34600   28000
10238   42000
1474   100000
12122   49174
30125  136000
45032   59900
46987  100000
33383   50000
24101  105294
18181   40000

[100 rows x 1 columns]
            x
34291  135000
21764   90000
6231    40707
39862   65000
38099   65000
4650    76000
26910   31000
45585   28000
29703   26000
17579   65000
            x
14442   93000
40459   60000
13806   89004
15577   61000
34656   98000
36495   73000
47786   77000
45922   82000
27578   69700
19275  140000
5161    69000
22283   76000
15150  104000
25623   78000
30180   32000
38898   23000
12232   80000
4388    42000
26559   78000
32147   25000
13384   45000
29907  101000
31569  120000
25640   63000
14662  100000
10811   38000
23628   52000
45615   55000
11449   22000
20729   55000
...       ...
37510   38000
46799  109200
46537   38000
39873   40000
49981   92500
15162  120000
13772   35000
3244    55000
19107   65000
20852   30000
43391   75000
13961   63000
11447   92000
40254   75000
30324  120000
27494   50000
44766  109000
2810   123000
49177   26000
21284   81258
39435   60000
47969  140000
5946    60012
12114  100000
38063   38000
4569    80000
17080   55000
49848   50000
47850   65000
13491   30000

[100 rows x 1 columns]
            x
32790   55000
44581  160000
28734   40000
18551  125000
5766    32000
46209   70000
11743   57250
23184   62000
30023   50000
14626  151000
            x
2248    45000
38362   80000
18237   60000
7341    38000
24473   57600
47846   29904
8393   105000
35877   28000
7072    65000
34487   60000
31020   25000
15419   23000
23918   58000
15020   70000
7673    72000
974     47200
24404   90000
23257   60000
44543   37888
22441   47000
23012   78000
24008   30250
24623   40000
26034   58000
39877   53004
10013   47000
28169  120000
11690   39500
26254  104000
41192   48012
...       ...
27777   54000
49337   32000
20766  100000
9213    74326
33229   30000
40629  100000
14311   34000
31069   50000
22591   28600
26686   40000
7439    63000
44190   72000
45959   26880
22197   60000
3083    75000
40847   75000
38857   64000
3101    70000
17888   70000
49313   42000
39650   49000
41038   35000
41060   48000
49998   82000
44948  102000
8009    35000
30229   42000
20626   35360
44108   95000
1257    69616

[100 rows x 1 columns]
            x
40003   50000
2772    72000
4035    80000
6525    65000
19619  115000
41472   49000
20407   90000
22997   98004
32402   30000
49043   40000
            x
17937   34800
3391    80000
17850   65000
22116   95000
23103   54000
48750   57000
31980   40000
6052    92004
45696   24000
44388  104000
39594   60500
42944   48000
12246   66000
10856  102000
10156   40000
8346    36000
41660  108000
27764   82500
22635   85000
27024   37000
7542    25000
24108   35000
41090   50000
15183   52000
19337   50000
1551    61782
34867   60000
25654   95000
1541    72000
37367   86520
...       ...
30495   72000
12449  160000
17841   80000
29134   38000
29434   55000
6229    84000
20564   50000
29111   59000
30048  110000
45388  160000
38086   72000
30815   50000
30041   44000
19975   70000
36055  110000
15695   65000
46853   63000
42072   29500
21082   53000
4083    60000
14972   40000
22929   41350
38665   37000
31255   60000
40033   38000
2526    30000
19434   45000
40810   57200
23453  100000
4902   110000

[100 rows x 1 columns]
            x
41460   71000
5566   150000
31671   45000
5056    67000
8684   115000
28035   42000
39453  120000
21794   88000
1411    75000
39627   46500
            x
29626   90000
33602   51000
30658   65000
46213   78513
3920    50000
10691   50000
10054  124800
33322   65000
36890  175000
46917   85000
1592    66000
11086   55000
41990   75300
34330   54215
33298  175000
34601   70000
26879   64947
16589   27000
16353   66000
39500   34000
42935   60299
29193   32095
16592   67000
13858   40000
46857  100000
33818   53000
47377   35000
45609   55000
938     85000
18103   70000
...       ...
29803  110000
17400   92000
13127   31000
36041   65000
15392   76763
17596   38000
30332   50000
33194   36000
6755    40000
9884    36200
7368    18252
28045  100000
39106   82000
17780  153000
40425   55000
23672   38000
12682   28000
3892   109000
26810   23500
38863   62000
43904   70000
47296   57000
33133   65000
32045   42500
14083   30000
7309    38790
36884   50000
19237   60000
10693  163000
416     73000

[100 rows x 1 columns]
           x
23691  53000
11979  51000
14224  70700
4432   60000
28953  75000
34786  65000
21789  94000
15907  60000
33573  25000
13866  60000
            x
6147    90000
49416   70000
7839    90000
34442   60000
24895   52931
47773  140000
30510   46800
9511    85000
41544  150000
37946  180000
11355   50000
4934    59000
16830   60000
37427   45000
39136   35000
21545   28250
20081   42000
20830   60000
26196   55000
25473   58000
30880   80000
34141   48900
17488   45000
40594   67000
3929    23000
38405  125000
23401  160000
1296    75000
21851   50000
12842   65000
...       ...
24875   37932
37553   68139
130     70000
17948   94000
49016   55000
19064   31500
23      80000
14983   68000
48287  160000
10654  147030
40812   34000
9571    41500
30202   87000
29730   65000
25786   50700
47873  100000
24997  127000
38160   48000
11309   40850
34160  115000
10094   31000
25230  120000
25566  120000
21623   42000
7691    90000
5830    82500
43402   97000
28441   68000
24827   65000
45586   70000

[100 rows x 1 columns]
            x
47099  149500
39086   45000
20651   90000
6350    44000
38095   90000
16115   77000
881    116000
48517   55608
34844   39000
5187   150000
            x
45331   38400
3396    55000
45361   58000
6576    66000
38094   60000
45494   22820
32979  128000
16556   52000
9414    70000
10201   60000
24519   35000
18957   40000
41778   54912
36779   90000
23349   82000
42879  175000
9529   120000
21577   95000
8931    36000
32341   40000
24801   88580
38376   26400
41230   70000
6993    51000
40932   56000
33885   48000
10584   71000
28219   60000
35921   55000
2420    33390
...       ...
17666   45000
33450  152400
26693   40000
12989   28500
15959  107100
56      33600
22858   43000
32053   40000
19771   72000
29043   58000
9163    46000
34930   91000
32266  130000
39225   75600
41391   36000
11652   60000
33129   25000
18623   40000
22167  160000
22919   94000
27272   36441
39647  110000
43993   45000
9023    88000
13589  160000
44792   80000
35808  120000
15901   55000
14990   75000
28144  155000

[100 rows x 1 columns]
           x
214    57000
43511  56000
32773  40000
44599  55000
44301  40000
7904   29000
43337  81150
42847  58000
7966   80000
46974  30000
            x
38755   33000
39694   65000
11119   45000
36977   80000
15428   65000
35586   56000
43391   75000
1145    43900
26035   54800
306     52000
16651   70000
21048   56000
18071   85000
37649   27000
14354   67500
24428  100000
9987    45996
3110    55000
14012   71800
32410   59750
33506   42000
12885   91000
34229   50000
6669    54000
18034  130000
39165   45000
47996   45000
32244   45000
36265   74000
10236   30000
...       ...
1307    60000
20417   59159
32921   37000
5720    49000
37793   54000
10343   59995
35588   42000
18882  119000
38510   51000
23225   40000
41826   36000
38476   52384
39447   30000
8022    72000
4521    75000
1403    82000
20260   70000
44651   75000
26301   88000
8004   125000
1303    75000
2804   150000
24783   31000
10414   36163
34739   88920
45753  186000
10217   69000
20929   50000
16674   35000
49255   42600

[100 rows x 1 columns]
            x
45754  105000
49382  130000
4034    24960
49806   50000
44879   40000
32062   50000
9019   125000
21605   30000
43783   54000
22791   65000
            x
28833   38000
24214   40000
2391    35000
32173   41000
26826   85000
45523   34026
43282   80000
30431   77000
10347   37000
36875   60000
45826   90000
14844   50000
47269  107000
8166    40000
593     24000
39181   71000
31959   46799
7566    28000
17315  150000
36973   62000
14649   46000
21908   45000
18429   86000
7744    70000
19159   36000
6441    90000
17282  169000
13107  130000
11979   51000
18523   55000
...       ...
41961   30000
47587   55000
10610   69000
9232   139000
37046   38000
23723   35000
37232   40320
42309   35000
6379    76000
21580   44000
38292   45760
45409   84000
48724   65000
24194   75000
1355    53000
46050   75209
14518   80000
21678   67490
37173   61000
30777   18500
4946   127000
19829   70000
22860   91000
37312  100080
4420    36241
40493  145000
11213   48000
19583   43500
36154   78000
24900   29000

[100 rows x 1 columns]
           x
35745  68000
22946  75000
18146  88000
37021  41004
40745  40000
17566  88596
46784  49836
39624  48000
439    91000
1096   42000
            x
7497    44700
19424   73000
36096   98000
29726   59000
34221  102000
14193   38000
25003   60520
27626   40000
13115  114000
24181   28200
36562   65881
42053  125000
3672   110000
14827   54000
42559   77000
28769   80400
3411    28340
3953    53374
28728   70000
37503   90000
36325   12000
24757  160000
16315   29000
7599    66000
34401   32000
26916   45000
46911   51000
4238    76000
11889   45000
5805    70000
...       ...
11403   50000
28904  125000
27794   85000
31270   14000
48888   77425
16086   68000
18290   86000
25317   55000
35364   30000
47816   27600
37645  120000
48902   60000
34234   90000
46653   53000
27183   66000
9533    32000
46846   85000
16969   70000
48284   85656
34651   36000
30941   41000
31987   63924
48258   55000
33863   68670
49706   45600
45193   90000
12538   70000
45352   46000
39602   47000
16503   20200

[100 rows x 1 columns]
           x
19927  80000
43830  40000
8962   42000
32395  83000
5838   38000
28276  53000
6840   65000
38741  60000
32822  77000
21950  94000
            x
43647   75000
37905   35000
2889    32000
2202    80000
42415   58000
35258   46500
4382   110000
3116    80000
24705   38000
40968   50000
43578   70000
26772   76000
31472   48000
22756   43000
25439   75000
39534  170000
35829   65000
17169  136000
24415   46000
40781  108000
12672   70000
19686   40000
41454   88000
33476   50000
20392   38000
32695   40000
39603   34000
28171   58427
25826   99000
8541    35000
...       ...
28632   72000
9268    20000
47972   30000
40556   53000
43501   65000
10788   37000
17558  115000
21883   70000
8756    45000
7697    32500
1389   100540
25853   43000
46947  125000
26594   56400
31513   40000
34470   96000
6415   105000
16846   34500
45811   78500
38287   66080
36437   70000
45939   37000
2393    41000
23449   47000
18219  100000
11822  165000
36550   77000
9068    32000
20864   50000
29377  148000

[100 rows x 1 columns]
            x
7642   187000
44080   29400
16779  100000
17805   30000
43321   66000
17221   75000
14764   66000
15147   26400
20673   76000
7881    60000
            x
18331   60000
32640  110000
26998   45000
2413    75000
34136   51500
26480   85000
28702   37000
18877   44000
49872   60000
24608   45000
11911   67000
11067  120000
11468   62000
17027   94000
44595   60000
43083   32000
22483   50000
30608  100000
49795  131939
30591   25000
20276   28000
45096   55000
36435   96000
24016   46500
1466    63000
42782   90000
47940   16391
7139    67000
9419    36000
11387   28000
...       ...
44950  160000
15696   52000
39615   78000
12629   31000
23567   28000
20631   85000
4477   150000
16492   63000
17444   92500
9082    51200
47781   72155
6558    58000
13583   28000
40055   52000
49958   29000
11940   42000
14240   60000
1360    45000
33999   95000
13429   60000
16357   70000
39019   40000
41533   85000
16406  106000
24597  119000
38821   65000
38259   60000
17139  110000
38865   47500
23356   40000

[100 rows x 1 columns]
           x
48529  33600
41429  60000
30482  65000
7742   96000
17216  40000
1128   80000
11725  53000
28533  80792
11807  70000
47204  65000
            x
49346   58444
9850   100000
8480    70000
7656    92000
42561   45000
42104   51000
39225   75600
29088  153000
47387   50000
5434    47500
28061   81500
6401   160000
2828    97101
44113   67000
18590   50800
28826   75000
1838    65000
2941    75000
29697   90000
20286   65000
2839    47183
30745   85000
13891   42000
16210   25000
15830   58000
14695  104944
33245   17500
24079   67855
12767   86388
46555   50252
...       ...
46906   28000
16511   60000
29800   36000
24822   99197
33656   64000
30462   42000
2887    55000
11299   51000
6438    63102
25759   62000
49017  125000
7440    95000
10016   60000
9439    20000
32643   43000
32471   40000
19153   47000
19347   24996
44676   56000
18726   45000
6207    55000
12872   65000
9299    50000
21829   25000
30161   80500
5890    69000
7559    50414
1927    95000
36892   55000
24144   75000

[100 rows x 1 columns]
           x
21213  75000
1627   45000
34224  35000
29472  74000
49101  75000
39944  82000
27498  77500
43255  75000
30981  79000
17960  69000
            x
9007    90000
1170    50000
2234    50000
30251  120000
20278  131000
11874   62000
7487    60000
2435    32000
33345  100000
12219   60000
7997    80000
1694    35000
9594    42000
34258   55000
23046   63000
33832   21840
48180   25000
25198  161000
3353    74000
37551   50000
5449    88300
12487   90000
39241  110000
11442   25000
21595   61500
19491   68000
19712   70000
3422    55000
37456   56000
11151   79500
...       ...
22765   42000
25484   56000
21043   50000
43579   62000
33714   40000
28476   65000
7945   140000
19567   45500
22019  110000
47069   80000
14288   28000
40483   35000
23365   62000
21605   30000
29350   55000
10285   71000
19064   31500
2633    80000
4694    72000
16684   66000
7366    74000
42052   74000
27232   60000
48113   52000
43601   90000
20243   60000
11145   55000
18343   29000
42401   80000
29661  125000

[100 rows x 1 columns]
            x
41741   57500
30909   30000
48106   48000
14150   74000
37810  120000
35519   40000
1043    66000
38183   84000
32257   50000
32169   39000
            x
1243    64000
43819   80000
32080   61600
16255  104000
25370   63000
7992    62000
44633  100400
2486    50200
12850   35000
8191    95785
2829    95000
14257   52000
41820  175000
6616    30000
44152   32000
12407  110000
18119  100000
43075   62500
4260    47059
46936   68675
36792   59000
25082   70000
49001   44000
4736    55000
44669   82000
41646   83000
17052   55000
11186   78048
25115  130000
46603   50000
...       ...
46895   46000
5602    75000
33040   67000
40309   46600
16073   90000
801     90000
20179   60000
30143   15000
48261   80000
26293   75000
30661   94000
29550   52000
417     88511
46919   40000
45138   45000
47672   36000
11241   65000
16151   55000
36382  118560
12640   40000
29331   17160
12864   37000
44453   37000
16808   50000
7051    61000
31065   73000
12021   56000
8925   109000
9814    52000
34974   57000

[100 rows x 1 columns]
           x
27504  47000
1367   60000
36791  25000
15704  68000
25218  50000
13142  30000
33778  42367
45930  72000
5214   36000
5900   29444
            x
42197   58000
8641    46000
7506    68000
37503   90000
18399   79000
9339    79000
19547  127812
44733   41000
33865   41600
48082  105000
23792   97500
12974   56000
32980   47748
29462   34500
18170   35000
33635   29000
648     33600
27123   25104
1634    43000
19945   66000
33587  100000
21778   48000
10408  152000
49208   98000
41903  116000
8486   124111
3281    62400
34180   60000
24709   90000
8927    40000
...       ...
40302   50000
1509    60320
43427   48000
14627   90000
28487   60000
31050   51500
37593   52000
2834    30000
19569  117000
3007   128000
39460   34000
16097   85000
46064   45000
45312   54000
26188   21538
16423   77000
38490   99500
19819   32000
23893   43000
17510   51261
34068  170000
14058   95000
43106   46000
32110   48544
42954   38236
40002  125000
12243  160000
39767   26540
45408   85000
524     52000

[100 rows x 1 columns]
            x
3434    37000
19089   75000
30827   85000
8811    52000
27035   80000
14780   60000
6305    61000
1525   177500
42740   85000
38249  100000
            x
2778    67000
20094   60000
2182   140000
37973   38000
32859   42000
34268   70000
46836   28000
14227   78000
28723   34000
17844   72000
885    120000
33264   33600
44400   43200
865    100000
11159   90000
46349   55000
40438  105600
28547   50000
30200  120000
42675   41000
35387   53500
37190   46000
19101   63999
38416   84000
20197   82500
20940   40000
2839    47183
35403   40000
27107   76700
27446   59000
...       ...
18610   90000
14916   79178
37614   48000
33918   71094
18019   87000
24936   65000
30558  110000
38415   94000
36196  160000
11011   63000
35242   68559
5001    40000
26120   82500
22412   35000
37495  140000
22745   70000
33947   42000
20138   19200
16044   75000
26042   35000
23944   26400
23864   45000
20886  110000
17014   65000
895     61000
15208   95000
23697   95000
32130   68000
24062   44000
17474   38000

[100 rows x 1 columns]
            x
22767   58000
2005    28500
46465   54000
28015   90000
47974   58000
25218   50000
46163  118044
1327    95000
8255    72000
27333   43000
            x
4838   125400
26223  150000
30588   12000
46563   40000
14744   60000
11478   44000
31810   22200
5646    85000
13054  108000
2684   108000
48744   60000
45176   65000
36516  125600
47405   48000
596    104000
13686   72000
40180  100000
12536   95000
47496   30000
9266    92000
40505   78000
14084   30000
45837   50000
20175   75900
25466   38256
16569   72151
10853   34124
24943   40000
28376   80000
48986   45000
...       ...
13910   60000
31699   65000
13986   50000
39212  100000
42773   80000
45851   65000
25942   22000
14836   80000
16028  120000
32734   87000
31210   68500
2640   115000
46557   90000
42258  155000
27553   33875
16520   41500
15544   43000
5683   119000
48614   45000
31626   30000
49445   49500
26747   38000
3341    22000
36804  130000
32327   75000
20309   80000
33434   60000
48983   41000
31246   85000
32407   48000

[100 rows x 1 columns]
            x
28301   42000
13759   30000
3532    39000
13195   59500
26007   86302
32659   65000
2100    50000
47607   35000
13145  116800
34651   36000
            x
47287   60000
12541   42000
27405   41000
5542    85000
22686   78000
23878   47206
46633   15000
2602    24000
1953    40000
22108   70000
42106   48000
24894   68000
39992  130000
21561   80000
2820    45000
40940   50000
41954   69000
12801  100000
34811   29000
15365   69000
26588   84000
18301   40000
45881   61000
5687    35000
36077   69000
4683    41188
11498   57000
22473   50000
42803   40000
22009   13200
...       ...
25401   85000
283     58989
6456   120000
24346  125000
2745    85000
18675  100000
31793   66000
1462    41600
32620   99000
5863    55000
7818    71800
31797   83000
44350   62300
32684   65000
20653   70000
7636   125000
37362   43000
6413   130000
32234  119000
2171    95000
13242   86000
14721   87500
26982   52000
8285    72002
25895  100000
48697   95000
48430   22000
43838   78500
40720   43000
23449   47000

[100 rows x 1 columns]
           x
46649  54000
18778  90000
14703  68000
8050   50000
31957  12000
13960  85000
22833  70000
46813  43500
4175   25000
45543  55000
            x
1258    58520

            x
5759   110000
5367    86000
40098   79500
18914   96000
44573  170000
10802   55000
18707  160000
41935  102600
13279   55000
49618   51480
18991   60000
24101  105294
8460    75000
37547  104250
10254   80000
23428   67000
15706   50000
44054   65000
16487   45000
16997   64000
40297   75000
40527   35000
5869    32000
15178  115752
37583  150000
23501   70000
2803    67500
17778   30000
46317   65000
27670   25000
...       ...
26021  130000
36429  170000
19516   60000
22294   24000
43491   50000
43568  175000
10896  116000
43731  100000
3655    25200
18110   32000
19634   93000
7907    25000
11011   63000
39802  130000
47408   78000
19054   42500
7463    42000
5883   110000
46498   83000
21895   35000
40684   70000
15861   43000
36931   59000
20420   45000
24122  110000
32687   80000
6579    72000
42235  116699
23476   81000
12386   96000

[100 rows x 1 columns]
            x
14295   70000
30501  145000
41504   73500
26736   75000
13442   42565
33004   95000
30541   66000
28122   88819
5619    39000
32267  160000
            x
29743   51500
10129   50000
32378   40000
5775    65000
31207   75000
49278   60000
13744   35325
9440    75000
16434   51500
5072    75000
2923    65000
26710   43000
29007   80000
682     42000
1087    55000
938     85000
35963   42000
36152  109000
48290   36000
41241   33000
1208    26000
48210   40000
24602  109000
14495   58000
8998    28620
14057  120000
20143   80000
37341   46000
40942   55000
36011  100000
...       ...
37012   50000
36945   36500
34246   48000
38778   40000
40088  108000
35164   48000
5382    72500
23667   77500
41558   72000
30056   24000
48070   75000
44865   29310
6301    89000
26758   86000
3544    92341
14540  135000
1833    45000
995     50000
22909   87000
7678    95000
38054  125000
397    110000
119     26000
2528    60000
14188   40000
1102    44532
43532   73000
32221   48000
17156   51000
18853   54000

[100 rows x 1 columns]
            x
5838    38000
26341   48000
48868   38788
44737   50000
12628   80000
10903  110000
8611    29000
27537  106000
25404   90000
22610  125000
            x
632     34000
47089   50000
4774   126000
23703   84000
30496   65000
3060    55000
20625  118000
28794   55000
8039    94500
28481   60000
21416   50000
14605   75000
34485   90000
22083   40000
9135    38900
25637   46000
36534   42000
4391    50000
46972   59987
16701   24000
17496   35000
27759   65000
35762   34000
39141   75000
8081    86607
13286   87500
30236   33000
42057  102000
33995   29000
44557   85000
...       ...
28267   60000
15793   30000
22354   60000
20720   45000
15884   31000
9856   110000
37197   40000
22926   28000
23246   81000
31292   79000
35434   48000
37076   81000
37201   30000
46756   52000
17240  110000
7435    40000
23976   35004
9276    87106
16326   50000
22316   36000
2848    70000
21598   98000
30294   52750
21373   30000
10240   93000
36837   43500
43958   58000
654     75000
47886   45000
12969   20000

[100 rows x 1 columns]
            x
23776   55000
38381   71000
23145   60000
29532  112000
24493   50000
9729    65000
12717   54000
42251   38000
15051   55000
39289   41000
            x
31921   48000
35509   98500
16996   77000
14288   28000
1573    45000
24862   62000
7382    33700
6045    45000
8042    74500
46716   50854
47885   50000
22192   82000
27800   50000
18552   80000
6644    48000
20740   39000
31011   50000
36559   75000
12280   67900
15704   68000
29558   50000
20509  106000
13784   60000
18446  118000
47281  144000
15121   43000
28231   49500
10428   42000
20950   90000
36111   58000
...       ...
28613  106000
13603   48000
26448   35000
48291  127000
4838   125400
44549  112545
20650   36000
16956  103500
45009   58000
2713    25000
11259   60000
36614  105000
18186   38000
3438   100584
30502  100000
692     65000
11035   19755
4357    45000
37436   67000
4187   120000
49910   45000
3347    90000
23914  178000
27860   37000
47720   65000
24001  120000
34312   32000
6320    32000
42412   58000
11883  150000

[100 rows x 1 columns]
            x
556     80000
19995  110000
48754   75000
16951   85000
6507    25000
47189   51000
48709   51000
37169  110000
7       85000
45764   65000
            x
37670  118000
24211   25000
28586   40000
46207   35000
16089   60000
1662    30000
26091  119000
28949   25000
6125    72000
38796  130000
41273   47000
46099   26000
22311   36500
40597   70000
18613  101000
35085   75000
16968  120000
35927   90000
18968   75000
34016  128000
26185   75000
6097    85000
37858  115000
14301   44000
33962   45000
41587   38000
31205   14472
25810   78000
28184   45000
20007  128000
...       ...
44148   47000
1840    34000
46604   80000
507     35000
3018    35000
7788    45400
31442   52000
34857  165000
16301   45000
7640    60000
17174   49000
40850   64000
23421   53000
11327  162000
30039  110000
49572   65000
46633   15000
36695   37000
21180   72000
17985   81000
35706  105000
36800   27000
26686   40000
30766   69500
6609   120000
22610  125000
49237   70000
8679   100000
27500   60000
10885   50000

[100 rows x 1 columns]
            x
30125  136000
28532   48000
36357   74000
15069   40167
43000   80000
47731   32000
5142    85000
33713  100000
3206   115000
9376   170000
            x
29974   55200
18651   31000
40820   75000
5215    68000
6842    20000
45523   34026
40477   64000
39606   44772
17728  102589
49120   35000
17543   50000
9432    58800
2561    67000
26558  135000
16513   60000
36792   59000
19208   76735
32529   52000
3407    60000
21228   60000
3616    28000
49158  148510
48855   62000
12243  160000
2125    51488
31963   57000
46703   40000
40513   90000
49795  131939
7476   100000
...       ...
1716    50000
18836   92000
41975   55000
29312   46915
22958    8820
24898   72100
14677   40000
25082   70000
48123   56000
8021   105000
37719   66000
6174    82000
43434   65000
21812  160000
14089   65000
25913   60500
23081   21000
18886   55000
25010   72000
6207    55000
17643   90500
13452   74000
46731   54000
48200   95000
19981   50424
37387  152000
29734   60000
29958   82000
46464   30000
12969   20000

[100 rows x 1 columns]
            x
18871   82000
48695   41000
25055   39000
14787   51000
13804   82000
30791   60000
18120   84000
42695   62270
24370  108000
47158   49000
            x
30788   50000
46920   56463
21192  122200
26441   66233
40955   70000
5342    76000
27511   60000
6680    57036
8467    72000
29154   48000
49382  130000
11525   75000
35211   58000
37600   38000
33637  100000
13235  120000
23106   65000
38639   65000
15504   16428
52      85000
28684   25000
880     65000
32792  130000
13086   40000
6189    32000
1003    36700
24558   35000
49334   60000
22036  115000
4193   130000
...       ...
20720   45000
11364  108000
19530   35000
182     55059
30092  150000
9803    90000
30683   55000
33671  100000
47577   73000
11382   97000
36748  100000
42695   62270
45022  100000
47973   92000
646     98000
26813   34445
33321   90000
37850   38000
10758   61500
4590    60000
36257   45000
16385   95000
46821   60000
27145   60000
6670   120000
40676   36000
26927   17724
48482   73000
42265  160000
24661   60000

[100 rows x 1 columns]
           x
11252  41000
26608  10000
11241  65000
32634  47000
1174   80000
4790   60000
14936  40664
23290  32000
31266  80000
15365  69000
            x
43780   78000
4631    33000
14953   95000
27170  124800
42208   60000
45492  125000
43475   80000
42139   55000
5410    72000
16774  180000
21868   52243
514     65940
25381   26000
34534  171000
25228  106000
48845   85461
41953   24960
19196   71500
32455   80000
2938    85000
2839    47183
32250   26880
22946   75000
44147   40000
12534  104000
8611    29000
9343    27000
42226   58000
30691   26000
6326    60000
...       ...
26067  106000
19966  166500
23024  102500
39040   22000
44597   86000
404    150000
11033   31587
37380  109600
27739   85000
35893   72000
5329    48000
16309   55000
25102   35000
49564   25000
23551  167000
49266   82800
36510   40000
37410   60000
42359   89000
28399   50000
27607   65000
18833   85000
9224    19000
25844  100000
12007   32000
18971   36729
10354   39000
19027   51000
27906  125000
7482    48000

[100 rows x 1 columns]
           x
39421  60800
39708  45334
49665  22599
46493  48000
43841  42000
39659  35000
45089  48000
22543  98000
13411  16048
7242   30000
            x
42841   59184
18804   80000
19449   47586
43224   60000
48725   76000
32445  140000
8675   110000
2960    70000
30434   94000
29468   47000
29215   85000
1077    65000
20656  105000
29103   43900
19590   60000
15393   26000
34743   18588
34063  150000
15937  109000
683     42000
17555   60000
34389   71000
37304   85000
23462   80000
25116   28000
9168    50000
23498   65000
8018    47000
37683   37180
2329    38000
...       ...
2750    24996
47609   24240
35149   50000
13514   77000
5978    37000
43739   51000
43092   55500
15266   55000
34284    8000
34441   38000
16518   80000
23644   60000
14501   36000
23882   75000
27238   86000
30442   65400
23731   45000
18995   50325
1010    35000
45256   42000
3464    96500
43035   58000
34123   53000
29366   38000
40029  123000
16503   20200
18805  150000
35080   52887
42498   50000
31633   55000

[100 rows x 1 columns]
           x
40104  93000
30383  96300
39766  48000
14503  59000
3157   50000
43760  97000
27514  32000
26280  30000
43308  80000
39078  72000
            x
45439   72000
47366   53000
25897  144000
19821   81000
45476   28000
43357   61000
20024   53000
48681   90000
31908   92615
18630   44000
6165    68000
27721   50000
46505   24000
42370   81000
36537   55000
47898   97000
39603   34000
13354   46000
31209   10000
15653   30000
21120   70000
29699    8412
19693   80000
24274   67500
49277   81000
28688   60000
16740  150000
29777  125000
12820   66000
31026   51454
...       ...
3621    56000
35914   72100
12955  114000
24727   83000
46362   78000
28996   53000
7262    75000
17763   80000
43049   45000
40830   55149
40555   90000
41927   75000
4792    70000
15854   49000
7003    49000
35990  105000
27732   51000
24570   65000
9068    32000
28211   71000
25494   88000
5027    28000
25716   45000
12836   38700
23684  175000
24159   67034
29184   39000
27200   50000
35806   35001
26390   25000

[100 rows x 1 columns]
            x
25049   48483
41765   72000
33850  110000
37838   35000
26520   63500
23610   30000
38577   72800
44784   84000
4534    40000
38017   17000
            x
16149   61800
37411   90000
40742  152000
6823   133000
20014   40000
35609   51000
15688   55000
17357   60000
22105   55200
47829   10000
27564   76000
39470   78500
44344   55000
28826   75000
42247   59000
39299   73000
40042   53000
29685   43000
26768   47000
32686   40800
13217   63000
25493   85000
44915   43000
4741   120000
14584   50000
32909   82000
33910   40000
1285    85847
3205   110000
38863   62000
...       ...
30504   41652
12638   55000
23383   35000
32770   38000
16138  122000
25598   99500
28826   75000
20315   55000
3976   100000
27095   58000
2053    38000
5687    35000
30900   81000
42288   65000
20237  114000
21482   65000
29653   20000
8630    26522
37825   76000
2160    42000
39992  130000
8749   100000
31292   79000
46721   83182
2111    65000
16106   45000
367     38000
37792   56000
45852   30000
3012    98000

[100 rows x 1 columns]
            x
9815    38800
48225   39893
37690   35000
7826   150000
43828   51000
3722   101400
11799   73400
40909   75000
14802   35000
46373   19500
            x
8087    96000
948     71500
17008   65000
2382    45000
29304   34800
38318   50000
33050   35394
42326   36000
18775   55000
40386  109000
16724   57300
30930   60000
25631   32239
45060   41000
778     30000
17155   71000
316     78300
22812   75000
7776   107000
25887  110000
1681    32000
18018  115000
21045   50000
29116   44000
31878  105000
39442   56000
47985   20004
1660    55000
29990   35000
38724   90000
...       ...
4045    33000
19184   42000
25637   46000
4327    54392
26928   92500
42029   92000
27055   70990
44128   27000
32298   36000
26908   21000
10819   50000
18219  100000
45088   52000
13563  100000
26680   65000
16693   81000
18925   70000
46115   55000
6649   110000
26795   46000
4453    73000
9707    52000
12984   21000
16974   36200
46074   40000
24735   70000
45812   35000
40764   60000
18137   80000
24368   50000

[100 rows x 1 columns]
            x
40226  100000
37180   80000
27550   50000
46708  126000
48578   93100
25330   48000
24836   75000
35960   38000
43618   40000
30663   55000
            x
572     77000
1808    54000
37191   75000
44128   27000
12267   23000
32684   65000
44821   40000
32084  112000
17559   55400
24762  109000
23964  100000
33636   70000
2951    39600
41818   35000
49714   40000
32454  130000
25826   99000
29126   61000
48033   50000
46666   55000
10672   40000
49407   50000
597     80000
3051    34000
29619   40000
22197   60000
29628   48470
2303    70000
48893  125000
38277   63000
...       ...
26359  150000
23245   65000
20834  105000
41191   60000
8142    63000
21651   28000
19110   52000
21173   52000
36819   60000
42358   45000
3230   180000
47063   51000
7278    40000
24801   88580
36098   86000
43893   60000
757     42000
30819   31428
21066   38000
33492   58000
7505    57000
49307   24500
25805   42240
3348   104000
7439    63000
6958    39000
41303   24000
34479   90000
7246    38166
1117    40000

[100 rows x 1 columns]
            x
30837   65000
14954   56000
6385    28000
44652   64000
37642   43000
7948   120000
32247   60000
23234   44500
28160   30000
36771   43000
            x
979    100000
41718   26000
11261   46400
23962   76000
25123   60000
2907    60094
5107    65000
38267  102000
37950   36000
23738   54000
36935   25000
27561   80000
12865   50000
464     88000
27336   99000
48298  140000
15819   75000
35832   51300
25876  107000
21935   60000
3768    27040
34195   49000
36639   75000
26789   88000
43138   63000
7647    30000
41254   41000
11672   95000
23809   30000
46010   80000
...       ...
33145   50000
8966    75000
19304  108000
13456  105000
17911  114000
12871   46000
33939  140000
6454   185000
29633  123000
47017   27000
27577   93000
46584   63000
47974   58000
9932    72000
18838   60000
44695   60000
34082   52000
27340   27000
5010   123000
5152    50000
43796   95000
18730  108000
34698   68000
18899  115000
23784   55000
46379   52000
2059   110500
8295    78000
5650    40000
37597   70000

[100 rows x 1 columns]
            x
41209   41000
12578  125000
31479   40000
15769   43500
2563    45000
20123   34000
47303   62000
32972   45000
38707   87000
4805    40000
            x
1838    65000
22789   44000
4945    72000
49321   58000
23028  120000
40031   13000
36318   53500
3072    72000
35855   57000
22035   90000
20929   50000
20260   70000
19610   50000
37541   36000
38264   45000
26267   55000
4403    70000
45904   26500
24923   40000
20315   55000
2165   100000
1689    61200
45427   33000
7881    60000
43239   40000
34644  130000
34667  110000
29601   24000
14148   27000
10679  120000
...       ...
12115   67000
35839   73550
24610   75000
14935  110000
23530   71000
22572   70000
39347   65000
42736   40000
31423   70000
20170   52000
3452    53301
16502   93000
8226    94000
25258   80000
27841  115000
24051   70000
46343   54295
23318   68000
46929   66948
20076   95000
2644    40500
14256   52000
33273   81000
32828   40000
3648    60000
20422   37128
48701   59400
40375   60000
33917   40000
15693  150000

[100 rows x 1 columns]
           x
22098  57000
47815  40000
41649  63000
4557   62000
18022  91000
45326  60000
16166  70500
40504  25000
21486  80000
20510  74000
            x
27849   60000
21813  120000
29977  177000
8871   100000
43617   90000
16198   42000
36440   71000
48469   87000
49001   44000
34447   42000
19864  135000
30647   78000
20362   42000
39973   50000
37749   42000
34060   65000
34620   42000
21966   50000
41706   74000
22499   65000
28724  130000
46854   70000
18054  136843
12652   88000
30654   38000
5611   105000
43672   45000
37958   62000
47997   75000
5828    34840
...       ...
2766    90000
29347  116000
10430   71000
11409   80000
22803   55000
36686   80000
17115   95000
1876   115000
19492   97500
26677   78000
17517   96000
45852   30000
45673   47050
43162   54500
673     33280
35903   67000
22921   85000
38551   96000
27487   81000
35499   76750
39540   70000
42481   87000
25238   60000
20857  105000
16378  125000
38581   86500
2005    28500
40319   50000
17485   60000
28546   74000

[100 rows x 1 columns]
            x
47384   56000
24270  155000
1740    50000
18300   40000
8090   148000
17948   94000
29898   53000
5119    98000
29919   83000
24538   72000
            x
43316  180000
1936    68000
2054    43000
24254  100000
42840   75000
6163    87060
28085   45000
5865   120000
45875   43000
32279   65000
8440    27000
5517   125000
45705   40000
49916   57000
23328   45000
47910   67000
33524  100000
20533  125000
16782   45000
48664   45000
13597   27000
26823   56400
47093  132000
41914   41000
4505   124000
20442   48000
27361   48000
47323   33500
27068   49000
41364   85000
...       ...
48736   56000
37840   37000
30854   62000
37321   41200
23169   50000
2563    45000
14596  100000
42245   93200
11266   35000
26577   60000
848     34500
29140  180000
29265   50000
11350   95000
37476   95000
28324   47000
5643    50000
47279   83382
21430   99000
10729   24000
33175  150000
28360  140000
38723   58000
24762  109000
41674   77500
21226   67500
17391   65000
15405   30000
37317   65000
45525   36000

[100 rows x 1 columns]
            x
20999  108000
87      50660
31468   71000
21205   60000
23722   31500
11995   55000
4142    42000
44681   30000
5751    67700
36232  160000
            x
12678   65000
45835   40000
10024   64000
33840   70000
35351   38000
2007    59655
32747   75000
15519  115000
38221   42000
1349    24000
22594   66000
27208   60000
22254   30012
48622   65000
35000   49000
10424   65000
26234   43000
5346   108000
17844   72000
17190   86000
16110   89000
27538   36600
4434    88000
48469   87000
2987    50000
4327    54392
44531   90000
15061   60000
12216   55000
40747   80000
...       ...
29438   53000
5339    30000
22228   28800
7533    55200
15866  165000
1695    51000
26023   70000
26145   78000
46483   39000
13354   46000
22448   78506
40970   69190
2318   102000
7995    72000
17474   38000
48188  122500
1473    85000
4436    65000
37047  105000
36950   30000
48625   35000
9537    65000
33978   22000
28107  115000
11601   51985
46769   25200
39511  120000
7397   147500
9720    26000
23346  130000

[100 rows x 1 columns]
            x
12202   45000
38841   95000
32939   32000
8176    53000
44218   74100
49249  165000
17959  140000
47680   75000
290     44000
42828   62400
            x
21777   62400
39369   54000
43961   47300
48880  104000
46794   45000
30772   65000
32111   40000
27652   80000
3339    43000
49979   68000
26746   54375
1006    37000
14881   30000
20015   55000
10301   81000
45960   90000
1051   144000
34834   43875
13084   53111
7698    63000
18563  100000
49307   24500
321     60000
44653  128000
45063   55000
30350   57000
43620   80000
34856   41000
28991   85000
14459   68500
...       ...
28289   39000
7740    72500
27730   73000
19485  150000
46819   87000
35459   35000
35943   80000
49587  150000
27199   27250
22022  130000
47641   60000
43843  160000
21213   75000
46090   50000
19069  120000
45617   80000
23348  154000
44804  132000
39098   43000
4522    70000
41172   78000
33094  105000
37154   50000
29931  105000
43430  100241
49341   40000
26961   95000
23524  161500
48522   41850
28042  100000

[100 rows x 1 columns]
            x
35140   66000
16599   85000
12843   50000
46331   47000
35162   67012
38860   44570
14152  105000
7425    65750
1907    45000
14754   32000
            x
28300   38000
42382   60000
32475  134151
8394   150000
27853   80000
15101   82000
5005    65000
4762    45000
13246   72000
4614    86400
25356   40000

            x
37058   34600
15236   40000
20502   52000
40512   40000
39758   45000
19355  146000
43348   70000
12470   50000
11090   35000
37469   56000
28102   45000
3423    49000
37317   65000
2955    35628
1643    53408
36193  120000
13451   50000
8423    28000
47565   25000
9954    30000
27594   20000
21530  100000
43320   65000
37120  133000
22059   48600
41308   38000
1909    62000
20135   45000
41073   64822
12338   26000
...       ...
32986   72000
47712   60000
9616    85000
35329   70514
105     45000
30429   85000
31107   31000
42144   20000
45808  157333
49327   75000
30771   66144
24952   96000
15722   44000
24275   50000
21076   41600
9011   100000
23158   65000
41106   75660
36895  150750
31502   57400
43816   79000
42381   95000
620     85000
2875    62000
47049   82000
36633   56800
12467   36000
46862   40000
13504  180000
12979   65000

[100 rows x 1 columns]
           x
13350  45000
22589  81000
11175  90000
11966  44000
42206  39500
18670  59400
38649  23608
40693  30160
30378  96000
18228  65000
            x
3214    30000
36193  120000
47755   42000
44615   35000
1244    41000
2150    55000
17361  134000
29701   72500
34135  125000
46661   25000
40461   21000
22609   53000
41101   70000
29180   51996
14294   55000
18225   50000
21516   42000
48001   80000
22128   94000
42456  120000
9488    72500
3999    60000
333     65000
45171   82000
37206  105000
31043   37440
19544   40000
4821    45000
40057  133000
32007   48000
...       ...
44281   70000
9349    80000
22758  108000
49240   45000
39470   78500
5307    77744
20565   52000
38568   96000
47347   28000
4979   106000
6682    39480
44508   38702
9163    46000
300     82500
37706   80000
16555   68000
23431  198000
10487   36000
47557   65000
12525   80000
26063   67000
10518   45000
4509    50648
8197    51000
22932   60000
16175   65000
7604    55736
27279   21184
30112   60000
25059   65000

[100 rows x 1 columns]
            x
6680    57036
31870  125000
47061   80000
40912   72000
22806   37000
37629  105000
43595   77000
26862  110000
49805   53000
15045   62000
            x
41513   36000
3920    50000
21561   80000
7941    52000
23169   50000
37488  167000
19017   46000
47323   33500
1317    31000
31598   76800
30123   79631
38934   42000
4532    80000
16958  125000
40536   52000
45616   41000
30078   50000
7915    32640
7500    27000
38178   33000
29163   36791
45007   69000
39281   75000
42318   80000
29944   86000
27931   65000
24824  108000
35033   36000
19609   28000
7771    52000
...       ...
31621  105000
12445  185000
5089    65000
24167   50000
6719    80000
18883   50000
38539   97472
45361   58000
16342   70000
796     64000
18328   43000
20341  106000
25260   40000
19763   25000
43105   50000
1548    24000
46545  190000
46570   52000
9331   135000
25302  175000
8983   125000
22495   60000
12621   85000
44361   30000
22197   60000
43521  160000
23044   36000
9546   170000
47160   55000
45389   87000

[100 rows x 1 columns]
            x
38263   75000
22059   48600
1668    59496
40569   35000
49885   36000
40963   39000
25383  115000
19215   43000
33623   55000
44597   86000
            x
37160   95000
42457  130068
21059   45000
49512   25000
11118   55000
5042    73500
4586    65000
46128   77000
11531   56000
17521   90000
37573   65000
5553   126000
168     36000
46069   42504
30987   48000
30150   38000
40283  107000
2706    89000
20009   66500
44191   86000
10821   55000
2925    32000
48929   30000
20082   35000
40134   36500
21354   31530
21885  142000
14832  168000
25836   90000
384     75000
...       ...
13744   35325
18658   98000
47339  168586
30782  100000
45371   25000
32887   83000
22720  100000
22225   75000
21182   48000
13405   62400
13387  136248
48923   73000
5035   130000
16546   70000
29499  110000
9416    47200
41736   62000
41270   56000
2222    32000
32345   14369
17482   50000
33254   30000
45053   25000
3332    75000
14769  160396
11438   42000
7558    62400
1640    70000
40781  108000
6477    36000

[100 rows x 1 columns]
           x
38625  50000
14962  69850
17020  31000
29852  46000
3428   54216
33999  95000
8915   80000
32708  98000
40965  32400
2593   45000
            x
44562   75000
8781    60000
20747   76500
17779   45000
42231  108000
4256   140000
48681   90000
12096   46856
16321   42000
42532   90000
9175    80000
29103   43900
9887    90000
11853   93996
33604  100000
19996   45000
12632   47000
49595   91000
45598   64000
35779   50000
11741  105000
26542   43453
10790   71000
46312   73000
18194   29000
296     52000
30356   42000
6100    52000
10657  115000
31296  105000
...       ...
20500   80000
129     85000
14463   52500
28646   41000
4570    48000
24493   50000
13122   40000
37435   47000
9435    62000
19121   40000
47907   85000
38792  107000
41083   40000
33554   45000
29097  104000
16557   34000
7485    39000
37084   65000
8509    55000
32868   48000
7471    94000
19708   40000
13718   65000
41386   40000
10230  120000
37390   64000
24272   58200
21273  127500
35602  181000
29158   90000

[100 rows x 1 columns]
            x
36394   40600
21765  110000
48680   45000
43481   40000
25722   28000
3730    50000
32836   40000
17305  113000
48051   51000
3741    35000
            x
26525   90000
48820  115000
8064    19200
15049   40000
48830   36500
46580   50000
25927   66347
11396   93000
33443  110000
42107   48000
4407    35000
30266  110000
32358  120000
30258   49504
46746   52800
4312    35000
23372   75000
41021   52000
2386    60000
22151   53643
26694   82000
11966   44000
40938   70000
11260   22000
47801   70000
14118   76846
32222   62000
39121   44000
18976   30000
20505  120000
...       ...
47836   53000
45752  110000
26294   98000
38996   30410
39908   50000
10312  128000
28393   55000
38069  100000
22533   28000
28326   90000
28734   40000
29690   34474
19088   45000
15444   48000
2109    18300
35708   48000
39419  147000
49317   46000
28721  110000
43857   41000
42459   70000
15825   60000
13270  120000
13408   24000
517     27000
30315   58000
12269   45000
19154    9660
5687    35000
8786    48000

[100 rows x 1 columns]
            x
15490   30000
22807   86000
46700   85000
11593   93000
21356   90000
27402   35000
1303    75000
17217   92000
41262   75000
10988  140000
            x
49897   62000
12604   43000
49209  103000
19998   65000
15418   90000
2404    99996
23562   23000
45668   91000
303     70000
16875   46000
31216   50000
45708   58000
38339   62000
19148   76734
10796   58000
22059   48600
27385   51500
18843   85000
626     55000
26523   62000
48886   75000
21629   72000
34257   80000
34258   55000
19894   25000
49831   40000
2315    53000
29144   44000
48408  106000
43435   52000
...       ...
22265  180000
25302  175000
30529  140000
23174   28000
15249   43000
2524    80000
14526   65000
44090   78000
20187  100000
6897    75000
24261   42000
762     82000
25379  125000
37697   43000
45492  125000
12482  140000
49026  110500
38571  105000
456     50096
16298   30000
45911   35800
38518   60000
20874   69800
21862   86000
15484   62000
22217   38000
30939   28000
49498   80000
40751   32000
17163   80000

[100 rows x 1 columns]
           x
8232   28000
19669  70000
41389  55000
36436  94420
3608   45000
3315   60408
14527  80000
39321  80000
34472  55000
36037  42500
            x
20060   65000
18264   53000
5159    43000
38134   85000
24335   60000
18918   45000
9180    38480
34948   27000
23075   95500
6969    35000
18370  175000
2584    48434
31075   61000
36663   78000
30652   50000
22546   72000
49195   79045
25659   75000
31431   50000
7250    40310
6983    44482
775     36000
47092   30000
49361   85000
43372  110000
21138   75000
42010   42000
42922   36000
46138  105000
14803   19000
...       ...
20726   39030
34943   21304
38430   82000
43616   25000
6662    23258
25774   56000
14553  195000
22747   64000
421     51376
11091  185000
5217   116000
54     110000
38770  157000
28813  125000
7188    60000
35691   54000
22055   45000
36175   21000
12351  110000
46388   55000
40985   18500
2486    50200
117    110000
41290   42000
10467  160000
7       85000
8570    27600
20967   48000
37795   78000
7033    60000

[100 rows x 1 columns]
            x
421     51376
39901   45000
22261   30000
2919   100000
37925   73000
32249   42120
9598    85800
19048  123000
21452   36300
39968   47000
            x
13816   75000
29405   62400
14979   60000
44536  100000
40446  164542
41439   84000
45492  125000
23988   28342
18823   24000
47652   65000
43603   75000
21407   92500
18644   45000
28809   70000
28681   70000
23484  170000
37610   80000
16834  152000
3894    84000
23760   67000
43329   77000
20631   85000
30617   26000
34831  130000
24218   36000
36457   64000
30022   58240
29334   87135
24790   55000
23370   55000
...       ...
3142   101914
9998    54000
46460  125000
44354  100000
32714   39000
28342  125000
24616   60000
44920   35000
43695  105488
32283  130000
31368   45000
10270   69000
1872    40000
35733  191000
14925   50000
5407    55000
14298   40000
23852  114600
26003   65000
44383   46000
46289   95000
5872    55000
25830   46000
20039   78604
5202    38000
21777   62400
29686   99075
21989   52000
49055   88000
44635   38000

[100 rows x 1 columns]
            x
39665  125000
33017   27584
31090   24000
12192  130000
44294   42000
31962   45000
25182   22800
398     56000
6837    95000
40891  140000
            x
3582   107000
28455   95000
6232    40000
16828   45128
5588    55000
25363   48000
40932   56000
3590   150000
11189   40000
10769  150000
19592  115000
8533   180000
2307    56000
14864   34569
15262   78000
17539   75000
49253   60228
14522   55000
29648   72000
12473  120000
7005    42000
48659   79000
17824   99700
30366   67000
18886   55000
38953   65000
4575   140000
11235   69600
42609   53800
18022   91000
...       ...
35333   36000
37558   67000
23671  160000
30920  112000
4590    60000
39627   46500
48176  150000
7997    80000
20868   37000
12689   70000
2033    66702
7582    55000
20487  150000
19513   60000
32137  180000
9116    43000
1207    96000
35850   18000
16579   90088
22749   92000
25060   30000
34248   65000
6840    65000
7890    60000
22166   85835
11582   86125
42090   71500
48747   55000
18483  110000
1164    88690

[100 rows x 1 columns]
            x
3467    61000
875    150000
21872   43000
11481   52000
47011   52000
20001  177800
3627    45000
17725   44160
14810   48000
425     85000
            x
46507   45000
22559   90000
7722    50000
34787   51000
20262   65000
29888   95000
38041   78000
47328   90000
25395   45996
43180   65293
35722   88000
12943   36000
29204   75000
20884   80000
22346   21000
42065   47300
46859  100000
44508   38702
29442   48000
38541   59012
49807   30000
12918   24000
28455   95000
25578   19019
35122   25691
7084    45000
33995   29000
36147  115000
9244    28000
12285   56000
...       ...
11488   70000
12603   61000
268     96500
49399   28800
22792   85000
14251   80000
3770    75000
5622    38000
41966   80000
8226    94000
10767   75000
12324   40000
12943   36000
42629   78000
32313   75000
2719    63000
4042    20271
15151   38000
30318   70000
13918   44400
26561   42252
44859  127000
20308   38000
38036  110000
10480  110000
47115  110000
37128   63000
22038   67000
9526    85000
18584   48600

[100 rows x 1 columns]
            x
34351   55000
11994   46000
6921    52000
36441   71000
40696   75000
27593   78000
49342   24500
24385  160000
39787   87500
37556   82000
            x
45952   70366
9489   110000
36062   35000
42102   25000
42833  138300
37865   34000
11968   53000
48355   28000
20855   70000
37310  130000
704    120000
2865   134400
10473  102000
7176   105000
13020   25000
33271   87000
13724   31000
24057   63000
46961   48000
3222   119000
5395    35000
20733   84000
11324   51710
8770    12000
16745   45000
22032   60000
26976   54157
4091    52000
11451   75000
8368   120000
...       ...
4850    60000
20247   60000
46966   91480
5372    33000
9036    60000
30594   55000
33474  117400
3322    70000
19024   47000
8727    96152
7176   105000
22434  150000
35648   85000
44177   35000
36576   75000
27315  156000
30159   45000
1653    40000
24596   45314
49124   40000
14322   60000
22935   54000
36031   50000
46511   65000
41719  130000
25333  160000
32812   47000
14769  160396
26956   52000
18631   43000

[100 rows x 1 columns]
            x
32286   71015
4762    45000
10818   82000
2627    15000
27194  102000
23395   65000
7770    33977
33380   58000
28200   78000
15796   72000
            x
4571    78815
1410    87000
24566   48000
12596   85000
36925   79289
17473   45000
6007    53000
45481   92000
21832   92000
30216   70000
13216   50000
37875   40000
33753   30000
45943   87370
23892   46000
106    190000
24396   60000
4751    21208
30798   60000
6342    94000
16745   45000
28713   72000
34009   26000
15930  120000
43090   55000
19923   72000
13888   52000
40508   88000
119     26000
34683  105000
...       ...
34184   89000
49991   70000
15412   25000
29321   70000
38084   46000
49871   59000
48697   95000
34924   60500
27112   98000
10425   45000
29124  100000
39993   32880
28077   60000
26167   55000
10707   89000
5720    49000
12979   65000
2845    80000
22304   70000
5859    33000
46326   95000
18070   37800
9430    75000
42191   49000
19488   92000
27000   32000
11195   41000
1787   128000
22100   38400
10824  110000

[100 rows x 1 columns]
            x
27547   53750
31637   18000
4843   105000
35339  120000
384     75000
10401   50000
12254   60000
36679   60000
34113   60000
2125    51488
            x
39799   80000
3026    40000
13965  145986
49804   64740
25986   37000
13211   60000
15091   38000
2610   106000
47113   70000
47527   93000
49002  165000
20710   68000
18269  120000
23834   92000
9408    30000
31815   18000
22008   85000
39279   20000
38373   26500
43782   15000
8067    64000
23857   27985
15246   85000
28195   59000
41886   72000
29136   42000
42914   95000
6765   120000
21886   48925
47853   80000
...       ...
12328   51000
48409   30000
23066   32320
43201   90000
20371   51000
8685    60000
8135    34000
26272   48000
48327   57000
2152    60000
12924   20000
12921   40000
2231   145000
11318   30000
26227  135200
8918   175000
34419   95000
46147   70000
12403   13750
19175   60000
41613   45600
48524  127000
37727   24000
40855   45000
31663   94000
36625  155000
17028   75000
33574   72000
2786    60000
22327   83200

[100 rows x 1 columns]
            x
34437   70000
9810    30000
31937   55000
10113   27000
13379   45000
10342  120000
44981   85000
924     45000
44856  120000
3954    63000
            x
35860   46000
45224   32000
22969   29400
18445   43000
28745   47000
22781   47500
49204   75000
30948   50000
5235    40000
20491   45000
29134   38000
18861   80000
36313   71000
4649   150000
9616    85000
38465   29000
46321   35000
16213  114000
9007    90000
12759   70000
43880  120000
19214  170000
33634   52000
5487    53000
748     72250
32144   35000
41815   45000
2637    80000
20242   55000
9127    52200
...       ...
32783   29000
45416   32000
12382   55000
2723    55000
4695    40000
13256   67350
14196   80000
22731   19000
38402   47000
9310   100000
16501   65000
15359   28000
21574   54324
7539    73000
19189  155000
47336   65000
29742   45000
27237   68000
8659   113953
25388   42000
27037   37500
39147   53248
36686   80000
29474   99000
30464   54000
34923   56472
8638    68000
44981   85000
45073   50000
12914  130000

[100 rows x 1 columns]
            x
36040   99000
45663   36000
42057  102000
39132   80000
17880   39000
37460  140000
38917   50000
11402   40000
3446    56000
8998    28620
            x
47815   40000
41918   40000
10864   43000
23643   75000
27448   49500
177     42500
32643   43000
37434   65000
1239    75000
24562   34000
23599   80000
32188   35000
16574   50000
33023   55000
30037   42048
21668  140000
26762   70000
30309   44310
20835   39000
12741  125000
25014   60000
24282   30000
26486   28275
40982   61000
32813   40000
42822  138000
47691   62000
6099    35000
20140  139380
28329  130000
...       ...
14936   40664
25074   29586
46099   26000
29865   45000
10516   44219
26580   94000
15618  110000
6921    52000
31265  110000
18585   30000
35381   91000
5547    99303
2726    96000
47476   75000
39015   70000
38752   98000
36548   53000
40436   30000
12842   65000
24555   45000
14034   82000
20118   50000
8823    45000
17297   60000
2478    90000
10088  126000
44415   31200
29221   52416
33974  104000
30665   80000

[100 rows x 1 columns]
            x
47005  109000
21086   48000
31748   74000
29753   97000
17893   95000
19322  133500
1207    96000
44802   86000
27674   98000
321     60000
            x
14592   75160
12590  140000
12022  100000
2718    82000
20595   49240
33152   90000
47429   55000
24355  150000
30201   52000
31395  100000
4560    55000
8535    74000
186    144842
17715   50000
32638   84000
12750   65000
8203    75000
15426   42453
36288   66000
7567    30000
44081   99167
8264    93000
42814   45000
19844   50000
23858   33000
3523    50000
37852   55000
39037   85000
5866   134000
8970    59000
...       ...
41498   25000
39060  120000
13935  112000
33992  115000
1667    65000
31838   90000
15415  110000
761    115000
13417   54000
18702   37000
3472    82200
23754   75000
14453   56000
13273   49478
40834   60000
33049   40000
319     60000
36790   43000
21158   50000
47691   62000
30488   84000
33892   70000
26814  120000
21064   27000
22808   90000
31540   60000
47865   80000
32502   68500
24069  150000
4075    55000

[100 rows x 1 columns]
           x
21934  36275
19437  80000
2389   56000
34246  48000
43204  36000
27169  68000
36440  71000
12938  60000
9980   38000
2904   45000
            x
1934    60000
27048   60560
729     50000
15531  135000
36675   33000
28735   58000
35107  134000
22691   60000
33170   62000
30720   98000
32932   69000
33510   82000
4470    35000
26085  115000
6686   155400
3962    70000
9493    40000
5131    75000
211     79728
18977   28000
2025    45000
46849   64000
19344   40000
25849   42000
31776   99000
37168   28945
14405  100000
36617   98200
14999   65000
16993   26000
...       ...
44213   73000
10510   77000
21938   70000
9555    57000
4188    24000
11510   49379
14228   55000
10202   60000
15963   75000
47499  110000
21714  118000
17072   80000
28422   55000
11178  101004
12311   59400
3149    30000
9404    90000
43747   65000
48594   41000
17110   45000
9384   149700
23345   60000
25029   68000
11313   52000
17459   40000
31545   90000
31077   65000
25198  161000
5250    30000
39139  120000

[100 rows x 1 columns]
            x
17690   22000
45056  102000
28991   85000
25938  140000
16533  130000
29057   23000
48145  150000
41519   62450
49747  124000
12744   85225
            x
43729   54000
13320   60000
46549  132000
48952   56000
32161   35444
44257   45000
28182   85000
8447    46000
46672  130000
10483   57000
47756   93000
26000   45000
36749   35000
26335   32000
2262   165000
45663   36000
28725   60000
40016   60000
16050   65000
1017    85000
21471   59000
20526   45000
49262   60000
1423    67566
14256   52000
31591   82000
2030    80000
42882   63000
12549   65000
41194   44000
...       ...
40404  110000
10790   71000
48774   53000
37450   75000
22661  148000
41844   86000
11789   70000
9825    55000
32150   60000
11378   33000
17871   40000
24686   40000
375     70000
33487   30000
41780   93000
24016   46500
38961   60000
48176  150000
29349   80000
38279   60000
3905    39000
32383   21600
3948    67500
39486   12000
4560    55000
21337  116000
43796   95000
36184   90000
4080    60000
22371   42000

[100 rows x 1 columns]
            x
14266   74000
29253   46000
33     153000
24320  111000
30254   56532
8390    85000
8190    50555
27706   63000
27358  118000
40065   50000
            x
48986   45000
27513  130000
40594   67000
28538   38000
12318   55000
335     43401
36115  118971
18943   74000
49253   60228
29121   51000
19935   90000

            x
15699   58800
40530   60000
27661  135000
24922   67000
18615   43000
22526   83600
46251   85000
32083   55000
25965   85000
15668   70000
37630   74000
29470  132250
11508   70000
3283    69000
35942   55000
7728    71000
39180   68000
11790  110000
4764    43680
42230   64600
8951    73000
42779   42000
48713  119250
4903    75000
31736   88000
43232   36000
23746   55000
18599   22000
12435  140000
34570   40000
...       ...
6756   130000
46344   50000
37985   47000
3440   120000
5299    40000
4629    60000
18605   75000
21007   75000
39313   62000
8828    35000
36370  190000
44687   79000
7378    90100
2569    47712
7080    70000
47889   25000
8969    81000
48076   68500
43359   45000
9009    72000
37223  100000
11420   58000
34789   80000
27228   64000
37928   28920
49926   48500
39159   45000
18046   40440
34167   94000
49207   45000

[100 rows x 1 columns]
            x
6298    30000
49124   40000
37894   52000
34662  110000
14759   24000
18379   60000
3091    25000
2168    40000
19613   42000
12775  144000
            x
29861   38000
34608  103000
36659   15000
5317    85000
23459   68000
4500   110000
48803   98000
46531   48000
22132   45000
40684   70000
30304   34000
81      30000
10522   50000
42576   30000
8610    64000
23748   38280
42921   29926
44202   60000
19190   42000
18831   75000
4634    82000
15550   45000
32006   48000
19693   80000
8514    85000
33263   34272
25224   61220
20206   60000
11484   45000
20085   66000
...       ...
5678    32500
32948   84000
46028  102000
5570    55000
19552   55000
34741   36000
24018   29872
49689   83000
15221   54000
45718   55000
4849   108000
3857   150000
18766   87000
24324  136000
1627    45000
18249   33800
26193  100000
49259   36000
4722    43000
14953   95000
18122   55000
47754   60000
13887   30000
25165   74000
16894  100000
5503    68000
10827   60000
24759   52000
26716   82000
15653   30000

[100 rows x 1 columns]
            x
6743   100000
17919  140000
237     91063
30954  104000
16516   54000
42845   72000
43916   30000
21370  100000
18809   47800
16383   70000
            x
1376    61000
40209   33500
11387   28000
672    105000
41021   52000
8660   131000
41891  102000
37610   80000
13830   68000
623    115000
15410  145000
34834   43875
45541   89500
33341   65273
27931   65000
14424   35000
30207   83000
41110   75000
42351   80000
19456   81000
19321   52000
27309   61000
5899   120000
16919  120000
5459    85000
45408   85000
23135  115000
31980   40000
18200   45000
1566    33000
...       ...
3021    65000
27412   40000
20071   68000
46024   42000
42048   82000
29063   39168
38580   82000
28818   44000
42886   55000
39493   48500
33758   75000
48178   48400
36600  105000
1384    13200
29269   73000
2569    47712
20100   75000
5090    57000
684     85000
19916   70000
8871   100000
20003   80000
8208    52000
7126    35000
22586   40000
18198   65000
6034    65000
49099  110000
26326   75000
40993   43000

[100 rows x 1 columns]
            x
4507   105000
39004   82000
23354   30000
13544   68000
26854   39000
47223  120000
17228   44000
23129   53000
39073   42000
3254    36120
            x
8470    65000
23730   85000
26969   35000
34740   95000
9876    39900
15087   40000
23130   75000
45779   43000
998     65000
19485  150000
28380   42000
34222   43000
17164   45000
23738   54000
45314   45000
22088   73000
3085    40000
2706    89000
7898    90000
41287   94000
26837   52000
38931   92000
22221   78000
17375   59000
38740   38000
6964    35000
21060   50000
43882   42000
36872   69000
30474   40000
...       ...
20281   43200
13734   80000
23549   52000
10834   70000
36172   19200
11858   92000
39540   70000
23408   40000
32617   93000
15690   27000
27171   30000
37939  130000
14828   29328
20369   59000
21351   60000
29772  120000
39647  110000
31971   43000
19918   42000
42014   48500
30601   52000
4675   106224
5057    42000
26195   21000
856     62000
7739    29120
46876  110000
3854    70000
45070   80000
23651   79000

[100 rows x 1 columns]
            x
42014   48500
1782    33000
11370  179000
9683    98000
46136  116000
34389   71000
1364    78000
14356   50000
10813   45000
26608   10000
            x
23816   25000
1081    36000
44797   64000
29652   41000
35805   59636
13828   57640
31599  110000
42340   85000
23408   40000
43934   48000
28314   65307
1861   123531
27636   63000
10836   60000
48580   61000
16892   82500
38716   37500
16022   92500
36794  157000
38942  140000
28183   61713
49892   30000
27294   65000
16354   41000
46471   40000
41458   55000
10871   59000
45884   30000
49740   76000
28495   95000
...       ...
6162    42000
20700   70000
48892   70000
13669   95000
33066   35000
19061   72000
281    150000
14757   70000
8688    35000
1821    95000
15078  142000
40683   62100
4616   124000
20866   60000
2653    67000
36955   38415
39391   50000
26663   40000
49468   43000
13384   45000
42694   80000
17287   25945
12464   70000
22950   98000
18023   55000
18247   97000
8889   137000
30045  123000
45165   90000
31802   80000

[100 rows x 1 columns]
            x
42725   85000
22519   38000
23554   38000
45889   41000
36216  120000
39438  132000
30596   40000
28634   40000
19645   96000
9758    34075
            x
22951   53514
8865   140000
47854   87000
25281   60000
7785    65000
46340   73000
39840   80000
41561   95000
33634   52000
365     54000
40660   82000
42612   70000
31501   75000
47894   66700
9982    45000
34372   55000
15428   65000
33985  180000
20795  106000
38405  125000
15813   41000
35544   69810
26779   55000
47808  122000
15268   47000
45107   90000
14302   90000
12205   48000
48858   36000
13336   55000
...       ...
35944   47000
18300   40000
24634   29000
17985   81000
42104   51000
36288   66000
19717   49000
14624  100000
29614   53000
30746   55824
11551   49000
31923   85000
48343  120000
30798   60000
3876    24000
28515   48552
9619    52000
31687   76000
18170   35000
25010   72000
20216  145000
32644  170000
30078   50000
29884   70000
48688   65000
14994   82645
39117   87405
12471   56000
46858   66000
29948   76080

[100 rows x 1 columns]
            x
26757  100000
29371   46000
49258   95000
49001   44000
48180   25000
33110   32000
11729   45000
31456   75000
42193   40000
3791    50000
            x
25802   70000
30506   47500
12309   24000
10845   42000
28949   25000
6393    56000
17161   95975
9462    64040
43038   70000
19997  112000
2803    67500
49121   26000
25535   90000
25259   49000
32749   64000
49350   79000
4594    49200
8658    53000
39199   85000
27628   35000
5568    35000
3623    40000
23033  146816
7623    45275
17273   82500
39231   46000
5050    55000
8704    40000
38999   30000
11682   93000
...       ...
37985   47000
36687   58000
39743   20000
23473   92000
33525   20000
48614   45000
15420  135000
11071   37500
16480  102000
9084    52000
35621  100000
4973    42000
8934    48000
12440   90000
30631  110000
27922  100000
36449   21000
45112   54996
35417   90000
6889    74000
2765    80000
35257   42000
47725   72000
30737   52500
15313   54000
1435    52000
15465   15000
23168   30378
2289   110000
1061    95000

[100 rows x 1 columns]
            x
48182   93600
44813   65000
28527   60000
13235  120000
49920  165000
43480   60000
48223  180000
6564    36000
8634    78000
9757   130000
            x
31901   53000
36225  102000
29800   36000
21552  160000
49864  115000
30768   66500
39539   56000
43980   85000
16755   25000
27101   59886
24706   45000
16698  110000
7970    46000
33701  105000
32512   29700
27955   49000
41898   80000
24574   50000
19734   58000
16962   40000
1417    62000
14276  100000
48135   74000
3806    13200
27877   75000
24741   55000
1418    33280
19544   40000
4360    54000
22142   87000
...       ...
27412   40000
46843   75000
36599   52000
30536   34000
18885   72000
18638   45000
39054   80000
33625   76500
33349   49600
33301   62000
33325   65000
48577   61054
26532   70000
47897  128124
3732   125000
10245   87000
23107   60000
13282   90000
29911   78000
45994   77000
21468   45000
31189   60000
25880  150000
29994   48000
22768  145000
36895  150750
31438   40000
8265    68000
49371   72000
10040   45000

[100 rows x 1 columns]
            x
45403   72000
8660   131000
951     40390
46538  150000
38640   95000
19734   58000
38678  130000
5163    43700
12746   45000
41000   75000
            x
13378   45000
5282    85000
36052   29000
33727   30000
2930   118000
37214  150000
38156  147000
29932   50156
14573   51924
41762  148000
20773   23000
32569   55000
47247  100000
18877   44000
13035   85000
25595  100000
11771   83500
38961   60000
32395   83000
22741   25000
44707  113500
21425  148516
41008  105000
22044  125000
24703   72000
47926   40000
25208  120000
25717   64000
19224   90000
28538   38000
...       ...
40656   75000
21054   45000
49937   98352
37493   30000
39853   88000
26330   53000
22912   70000
3204    65000
48622   65000
48497   67500
19873   52000
326     30000
28225   87278
7285    48000
14138   40000
31398   39000
16653   75000
29618   62000
39403   65000
32580   59600
6256   152000
34757   85000
23860  100000
45695   60000
10493   99000
21007   75000
46116   69882
49646   78000
20686   70000
2279    75000

[100 rows x 1 columns]
            x
4449    65000
38305  130000
27908   47000
19877  150000
10537   65000
40263   67000
23498   65000
901     60000
37441   43908
22084  108000
            x
14489   52000
14630   73000
19544   40000
40956   81000
21010  190000
8531    95000
8252    71000
15692   52000
26157   35000
31529   54000
6084   140000
3164   143000
18398   92600
25306   80000
40971   64400
3997    68000
26075   90000
14590   60000
38654   42000
24412   65000
46374   18800
35224   69400
45972  137500
12190   75000
46784   49836
29839   23842
22312   38000
2426   130000
20300   39000
34139   48000
...       ...
7613    40000
37828   45000
48628   77000
14107   50000
17947   49000
41760   36000
41823  102000
45990  105000
19667   93000
49232  100000
25173   75000
7942    35000
9189    38700
41144   32000
25365   45000
39016   75000
39481   50000
8660   131000
4602    50177
32991   60000
24279   37167
28832   28000
42700   48000
15556  130000
33003  112900
32403   82300
17453   50000
33036   55000
7130    75000
3794    48173

[100 rows x 1 columns]
            x
30880   80000
14009  115000
48087   88000
46566   50000
617     55000
8027    35000
4688    73000
7711    18500
24261   42000
13837   79500
            x
28389   63000
45380   80000
32188   35000
32365   31164
18036  103500
12581   96000
11440   72000
44729  130000
47946  162000
6888    60000
26357  145000
49789  115000
19544   40000
3563    35698
28659   40000
30792  110000
29845   63000
17241   60000
23169   50000
34029  120000
24293   70000
10692   65000
20492   28000
26301   88000
25126   24000
9925   125000
8418    70000
32573   21500
48241   65000
35332   56000
...       ...
16688   81000
19354   35000
14090   47000
13150   92000
47986   40000
14398  150000
34020  106000
30385   92374
9390    82000
27892  104400
12241   55000
40928   68000
27036   95000
22731   19000
6303    65000
11843   50000
9684    70000
29288   30000
35119   33000
30915   77700
287     52000
23905   35360
39850   23500
29161   65000
48187   28000
18838   60000
19222   60000
40259   54888
21319   85000
46271   80000

[100 rows x 1 columns]
           x
1377   80000
48490  80000
3459   55000
17681  90000
22544  48000
13875  68000
12289  56000
38591  88000
22916  80000
7712   65000
            x
30910   67000
20990   60000
3551    90000
23606   45000
45685  190000
9496    70000
14495   58000
42026   42936
39043   75000
45285   43000
46405  180000
33442   95000
16785   53500
36243  120000
14802   35000
23929  135600
44742   44000
16149   61800
16284   45000
4541    39200
27716  109000
2402    66000
19314   42000
22532   32000
30236   33000
40580  139000
13566   26000
30598   52000
48771   30000
49238   73000
...       ...
19650   64000
40462  130000
13053   84000
637     85000
45614  102000
29949   36000
29973  102780
25203   70000
34059   53000
13609   65000
7866    25000
44542  103000
20528   48000
27400   89000
4437    75000
6212    70500
15845   76800
11966   44000
14761   72000
41749   72000
32011   37100
38572  105000
25898   40000
16716   52800
13816   75000
29554   56000
22592   85000
15818   48000
14212   22000
37141   35000

[100 rows x 1 columns]
            x
34949   50000
19848   44500
29126   61000
43444  106684
24991   70000
10943   20000
6483    40000
20868   37000
10215   76450
9992    90000
            x
31933   50000
31995   55000
24027   46000
8420    63000
3354    45000
1969    28000
36658   55000
44864  140000
8724    60000
31984   90000
49811   80000
6595    44000
2056    25000
23419   30000
16963  112000
48177   84000
42654   60000
21988   43000
8857    94000
43704   45000
8718    88000
44765   45000
9191    35000
42781   77000
34982  122000
6865    63175
36796   72000
14400  101000
10102   43218
19496   60000
...       ...
32840   51000
32712   68000
4101   130000
3162    64609
45631   50000
28022   46000
32      40000
31345  110000
19940   45000
23958   22000
27240   38800
33332   96000
30205  155000
43483  109000
10916   50000
10390   45000
40743   43680
44715   38000
35240   35000
27273  104000
38363   63000
8423    28000
4417   120000
28604  120000
16308   95000
3442    70000
44319   96000
11829  113000
16511   60000
22223   56000

[100 rows x 1 columns]
            x
637     85000
33898   25000
46354  100000
31010   48320
28330  110000
30915   77700
47909   95000
6039    52225
49316   21000
28771   65000
            x
33751   54080
34253  145000
8415    42000
48342   27000
25162   89000
31843   38000
10617  149000
36245  140000
37103   65000
27443   28000
40182   60000
9217    80000
15801   60000
38595   43880
4216   160000
19123   75000
21452   36300
27093   70000
4135    80000
47459   68399
31720   93600
47822   60000
31222   85000
11733   80000
25906   94000
28794   55000
13674   64000
35155   85000
40412   90000
9443    50000
...       ...
329     70000
46167   60000
24602  109000
16990  110000
30870   78000
5797   100000
20858  120000
46744   21000
34121   65000
42593   90000
28177  120000
34413   41000
34450   52800
19669   70000
6724    45000
585    130000
41786   80000
43905   63000
3304    85000
704    120000
40591   80000
18862   43896
1679    80000
16830   60000
2062    50000
3279    55000
33633   78000
20694  125000
16873   75000
20543  100049

[100 rows x 1 columns]
            x
4500   110000
21659   80000
45291   45000
19800   24000
37488  167000
45729   34000
4271    32000
16985  150000
13564   47520
6905    84000
            x
48596   72000
41567  130000
3632    25300
24878   82000
29478   35900
10828   34000
33108   50000
44899  114053
45731   65000
13436   70000
6283    40000
18908   85000
36511  118000
7881    60000
24873   90000
4890    30000
37733   25000
19724   95000
42888  140000
26733   59300
22732   74000
5907    20000
17693   32000
8104    33000
32039   49000
4819    32000
40644   58000
18343   29000
8407   178000
47888  101000
...       ...
14475   51000
9177    97000
41534   41000
29454   28000
21136   80000
20940   40000
7466    87000
428     20000
41714   67000
9402    65000
42900   49000
22487  120000
18786  100000
38881   52400
1989    40000
33964   39600
33736   46000
1888    85000
44249   47800
32955  100000
30032  105000
29712   64000
44685   60000
20287   75000
48291  127000
23594   76336
49361   85000
22870   31000
26634   82000
33064   48000

[100 rows x 1 columns]
            x
8697    36000
20522   35000
34658   60000
36215   43000
19455   55000
10519   47500
44555  130000
44426   69000
3415    39000
17299   93000
            x
6440    49140
9300    81000
18965  140000
32343   40000
239     61000
16116   42000
3823    48000
34113   60000
44687   79000
7716    40000
35994   75000
8571    60000
43588   34654
11059   11295
48176  150000
41846   65000
47476   75000
43852   48000
46266   75000
48160   74600
571     80000
41675   84870
15065   79000
23888  128000
14323  102280
25767   50000
39984   26750
33136   55000
17233   90000
32120  114000
...       ...
36555   55000
1398    30000
12192  130000
14651  130000
25889   25000
39810   48500
34111   90000
23287   65000
1547   150000
11326   52000
22980   86400
15505   58000
12963   50000
35310   45000
21600   60000
29981   78000
34558  125000
45105   75000
24576   36000
45436   50000
40107   68500
33148   45000
14648   33400
2768    46000
33495   37000
24768   72720
45190   96208
22831  185000
34838   45000
25417   65000

[100 rows x 1 columns]
            x
42574   95000
13746   58600
42494   71000
8886    45000
45244   58000
24679  180000
20463   61000
30242   51996
28095   72000
18692   71500
            x
34315   46000
5979    84000
1149    35000
37843   79000
8396    27500
29421   42000
45449   35000
42056   78000
22161   92259
904    145000
26236   21000
19026   42000
41974  103000
27038   36000
23303   96000
42967   48962
23411   55000
45706  145000
48121  185000
42824   39200
25303   42000
17377   38000
43874  170000
44610   71416
26366   32000
19424   73000
30366   67000
24837   80000
32729   35000
14526   65000
...       ...
39837   45000
36735  120000
20780   46000
1797    70000
31952   92000
6900    45000
901     60000
11872   52000
23930   25884
42125   36000
49632   52000
32199   82000
24464   52000
14166   61800
11422   88000
23813   89000
48585   90000
40057  133000
35138   46740
43177   65000
49000   43000
25429   56160
27566   30000
7089    82116
19563   38000
43423   72000
24530  180000
20994  111000
42796   57000
40499  135000

[100 rows x 1 columns]
            x
7394   113000
23215   38700
7032   100000
4983    55000
25551   55500
46503   95000
20499  100000
40629  100000
26020  129000
20627  125000
            x
2404    99996
18778   90000
29111   59000
16866   69000
32867   82500
43456   38000
24114   56000
27937  105000
5378   140000
22111   52000
25139   37873
3095    84000
10572   96000
46415   65000
2051   100000
31030   96000
31835   45000
16884   90000
45094   50000
35423   55000
44067   65000
13988  100800
19617  100000
3720   112000
14873   75900
225     90576
6213    55000
32969  100000
48370  165000
48791   40000
...       ...
27471   80000
45275  120000
37850   38000
26425   50000
2037    56000
36897  120000
25593   37116
20926   48000
34214   48000
21971   58000
36893   94000
32754   31564
18044  145000
14313   81000
3683    32000
21382  180000
48505   38000
44456   74000
4085    90000
14207   37000
22135   78000
13915   45000
12281   47000
45999   24000
5633    65000
17995   33204
40613   63000
37883   68369
43528  128000
40579   85000

[100 rows x 1 columns]
            x
38569   50000
4270    52000
22366  139000
27774   56000
15917   52000
26968   65000
23700   33276
35632   40000
29419   60000
12465   38000
            x
3438   100584
14164  194000
24936   65000
47276   56000
593     24000
41761   40000
28732   60000
36908   42000
47075   72500
30434   94000
28455   95000
17755   58000
13771   60000
21228   60000
31563  150000
5593    51000
39544   70050
28270  115000
34598   70000
5837    15800
8047   154000
2717    45000
32746   90000
45323  120000
37840   37000
5214    36000
32540   75000
499     80000
15026   57000
526     42000
...       ...
555    115000
17489   80000
47374  105400
44067   65000
42667   60480
34542  175000
21937   80863
20669   75000
1271    90000
33167   80000
7328    61000
30440   80000
5823    65000
18376  104000
11132   80000
29989   60000
23668   80206
24511  120000
17846   75000
42797   66000
13685   50000
11561   30000
37591   54500
22011   65004
27367  120000
4576    34000
28550   50000
40145   58909
28875   52000
8573   107700

[100 rows x 1 columns]
            x
7216    45000
35368   18000
4197    80000
41015   45000
22099   60000
34746  190000
47358   35000
42638   51000
39811   48000
39984   26750
            x
18576  125000
14305   24000
14281   55000
981     70000
27845  121200
19800   24000
25836   90000
1822    36000

            x
20770   60000
39241  110000
35074   80000
42223   58000
920     81000
48981   84000
42240   75000
39541   62000
11273  110000
45996   22852
14303  107000
5295    77000
2583    70000
46357   94000
43683  145000
7180    60000
45831   35000
7794    93000
23413   41000
44621   55000
35904   57000
16219  125000
22025   24000
5328    71000
19573  130000
45066   62500
7950   160000
42197   58000
38600   83000
39235  150000
...       ...
43979   30000
12145   78500
362     49700
35703   75000
34073  100300
36232  160000
5303   126000
34203   85000
34809   57000
34316   67000
8950    72000
33344   45000
8571    60000
46524   46000
25392   67000
3785    21000
14073   23000
6641   145000
31684   40000
15936   18900
2470    65000
27660   67500
1915    38000
16909   49000
9194    60000
49916   57000
46866   80000
18750   45000
43829  120000
18993  145000

[100 rows x 1 columns]
            x
45372  120000
7934    70000
15512   54000
33438   77400
45763   42000
13605   72000
27043   32797
23666  125000
12480   40000
38843   55000
            x
21655   60000
34496   55000
30695   74666
45554   47000
36771   43000
20531   61800
24452   70000
39037   85000
6495   184000
20182   45000
16304   75000
25560   30000
36618   27680
40371   47000
32600  150000
20901   36000
28752   27900
2472    80000
4928    70000
49235   50000
26327   73000
47842   36000
43244  110000
47548   70000
40349  118392
12737  125000
10423  110000
37783   50000
28270  115000
16179   40560
...       ...
34550   41000
40245   35000
19371   70000
14224   70700
34618   15580
49130   50000
39526   30000
4912    98226
36333   20000
37119   65000
278     21300
4585    35000
30431   77000
48131   35000
33042  123000
41759   35000
28152   93400
22704   74000
7915    32640
22112   55000
47130   41000
47554   52600
14065   51000
34782   30012
25008   72000
14265   90800
31952   92000
34460  125000
6647    40000
3934    47100

[100 rows x 1 columns]
            x
48174   37550
23855  120000
39576   33182
37787  150000
34016  128000
5809    41000
29886   52800
35921   55000
34315   46000
12478   56000
            x
34885   50000
42272   35000
32850   70500
32651   89000
43678   56010
39770  130000
32674   60000
23444   90000
45757   63000
44473   60000
41787   67000
17796   57000
28719   75000
163     39942
41855   54600
42943   75000
39369   54000
45328   47500
45795   85000
33774  135000
17092   70000
20223  100000
29330   94979
18527   85000
47572   45000
22613   86400
35877   28000
38683  125384
38325   90000
45455   85000
...       ...
21160   50236
10020   84000
34619   62758
44920   35000
49052   60000
49363  110000
35843   36000
10711   65000
3582   107000
2554    64000
41399   60000
32681   74000
34119   35000
42687   69996
19295   46000
7726   110000
30357   80000
35119   33000
15147   26400
45592   67000
71      34248
3403    81700
6732    90000
16748   43440
24186   49000
39183  125000
49554   43000
14585   75000
2645    57000
29904   62000

[100 rows x 1 columns]
            x
22363  135000
14124   76000
19876   12000
44604   81000
15338   53309
10929   42487
21646   78155
16533  130000
19396  115000
49765   95000
            x
6634    40000
41670   78000
40958   41280
29711   70000
35410   50000
19741   55000
15471   62000
19369   77000
31251   33000
44108   95000
40270   60900
46061   63000
20980   21000
43676   65000
4308    34000
40863   76500
29609   95000
4495    72000
12994  102000
3461    31000
24611   70000
40717   55000
13421   50000
10763   85000
14676   75000
15249   43000
48396   75000
16351  100000
20338  150000
29869   85000
...       ...
36219  102456
16676   77000
14586   48000
12364   80000
3240    36500
22014   27600
36730   65000
23593   49980
22010   50000
17235  120000
23386   20572
24340  160000
15577   61000
30512   46600
22552   55000
34483   40000
5830    82500
37877  160000
31922   80000
20116   36000
15221   54000
311    112000
7259    43000
7098    30000
19315   43000
6619   100000
22108   70000
44706   57000
23144   50000
28228   61000

[100 rows x 1 columns]
            x
30599   22000
28809   70000
22210  115000
21751   85000
47595   65000
8147    80000
25102   35000
15921   83200
9563    30540
25025   62000
            x
19353   96000
5635    45600
4843   105000
3388    68000
734     49300
11703   53000
31974   36000
46668   89000
4003   110000
34602   58594
46588   39000
19063   32000
38398   25000
36132   80000
30198   68000
40591   80000
31352   60000
16854   23000
20370   60000
7334    45700
22301   68000
44628   70000
17495   36396
25041   48000
43458   48605
22746  102000
38884   38000
27887   67020
21658   69500
1005    70000
...       ...
10852   43000
5400    85000
35852   43500
6756   130000
49449   98000
35691   54000
23509   75000
27413  132000
38239   50000
19780   75000
47678   40000
12654  110000
23889   72000
39033   60000
3026    40000
49821   50000
27967   50000
32421   75000
46746   52800
43032   82000
43507   70000
14717   45000
11899   33000
7880    77424
18024   49000
38777  100000
48952   56000
2796    40000
2371    48000
28685   60000

[100 rows x 1 columns]
            x
1434    60000
11574   58000
18473   16000
9338   125000
27419   45000
8532    40000
2842    60000
6554    30000
40364   80000
13875   68000
            x
42035   90000
34426   80000
26081   73000
41114   40000
30679   63000
11800   78000
6393    56000
41902   45000
42208   60000
36412  120000
3822    80000
32630   28000
5877    80000
33731   65000
27245   75996
49027   45000
41870   90000
23241   85000
11154   32000
3751    60000
9000    60000
18307   50000
24284   66000
5667    95000
22713   84000
19147   18000
25280   70000
18392   44000
12590  140000
28824   81341
...       ...
45351   55000
48654   48000
43134   65000
35226   72000
22735  150000
16892   82500
49492   22000
20290  114000
44612   50000
27790   65000
28471   78000
47808  122000
45741   42000
464     88000
4495    72000
32228   60000
27736   85000
22136   49000
1230    45000
36592   35000
11294   35000
36068   43000
27407   90000
28128   75000
42429  122000
6350    44000
26688   66000
24494   88000
33162   75000
4300    55000

[100 rows x 1 columns]
            x
17637   33300
24100   58000
15877  102600
32781   50000
35243   25000
25872   65000
30175  135000
7944    51000
34075   37000
24895   52931
            x
43740   54650
7838    90000
47220   42000
39695  110000
34030   81788
40301  105000
36478   45000
16385   95000
39277   25000
49795  131939
47444   78000
35043   51600
40395   60000
34778  104000
27325   36000
39732   77000
38567   60000
34955   42000
8872   100000
8872   100000
13371   52000
16011   52000
43322   33000
15398   65000
6112    32000
22111   52000
8      120000
3930    62744
38696   60000
27872   45000
...       ...
3715    23000
12939   67641
9153    45000
9338   125000
39531   91000
6264    16000
43298   54000
35926   46000
43373   33000
32378   40000
28138   32760
26759   91800
5531    53004
18261   36294
19905  130000
24787   70000
43305   75000
30863   65000
47693   96000
20006   26000
28543   63000
29475  175000
28689   36000
33908   65000
13291   40000
33805   35000
40342   78400
24305   68000
43157  100000
13796  150000

[100 rows x 1 columns]
            x
566     66500
30237   47000
6650    39000
5638    40000
20002   18737
27584   44300
43726   87000
9591    52000
10232   30000
22908  130000
            x
46955  113000
10448   30000
43367   16307
19115   60000
23370   55000
45395   78000
27565   74000
6940    40500
26413   24000
17000   88800
24375   75000
22434  150000
17524  135000
18743   60000
32085   30000
13274   70000
42380   35000
32909   82000
45451   40000
39885   37000
33108   50000
30426  100000
16278   57000
42953   52000
38615   32000
2190    65000
9032    45000
44206   45000
30500  100000
29306   40000
...       ...
39981  115000
16187  127000
17153   50000
28610  108000
41670   78000
19719  125000
1186   180000
15005   84554
29132  135000
15951   98000
9210    95000
12245   49028
49512   25000
17026   45500
33652   50000
47061   80000
25629   72000
34031   62000
44435  120000
2018    60000
47289   56000
30733   52000
17006   50000
47429   55000
22572   70000
5936    38000
19177   38000
48613   56628
14607   90000
46623   41500

[100 rows x 1 columns]
            x
33862   32500
45212  120000
38919   46000
32859   42000
37104  112000
28228   61000
41780   93000
42746  108000
28764   50000
19555   52000
            x
41468   51900
29053   75000
37676  105000
36837   43500
12799  185000
15282  120000
4611    49861
49716   43000
30188   45000
34919   67700
29925   86000
37701   35000
31492   45000
2264    45000
43621   54600
7881    60000
12752  117000
46392   50000
19639   82000
23502   54602
35703   75000
11748   48000
37879  100000
5285    90000
33240   40596
46425   50000
31314   45931
25133   55000
35737   55500
7639    36900
...       ...
4432    60000
894     80000
8056    90000
30414   55000
14915   63200
16370   62000
32021   45000
26942   90000
14346   96000
46806   42000
4489    28000
36656   65000
5205    47928
44748  120000
47199   77000
26785   80004
37780  150000
29796   65000
3969    55000
24457   62000
4826    74122
44188  120000
29446   62000
48711   48000
35488   49512
30010   76000
6744    80000
46578  115000
49609   75000
16146   26000

[100 rows x 1 columns]
            x
48586   41386
31453   85000
7217   127000
5338    90000
15336   65000
13877   26000
3001   125000
5081    35000
39827   98000
24331   45000
            x
7947    70000
37915   60000
40313  122582
6508   155000
15244   81000
42885   75000
37515   34000
43109   55000
38519   45000
6930    62000
31782   83000
41708  195250
33729   55000
24941   55000
11945  148000
28404   44000
30866   47000
37193   56000
34586  100000
27634   34000
18074   50000
21509   55000
16494  120000
32531  130000
15631   73000
24694  110000
38595   43880
45138   45000
48473  125000
28303   93500
...       ...
13446   76290
12770  107000
18830   72000
2716    91000
32379  130000
10278   43000
172     36000
28654   82000
15923   22000
24967   40000
13131   38000
47403   15000
46793   84000
10430   71000
39738   96000
39383   62000
29020   60000
20863   80000
44708   30000
46692   35000
31561   80000
29405   62400
40778   45000
42903   34000
46202   39000
4443    28616
2614    45000
46886   45000
13008   54000
46601  166000

[100 rows x 1 columns]
            x
22172   43000
13661  102000
39657   95000
44566  175000
15426   42453
24670   53280
43560  150000
30956   50000
32268  119867
22652   40000
            x
16343   18330
30614   60000
17553   79000
42586   57600
48036   19000
46119   86095
8080    73000
3342   128000
21413   85000
8822    35000
47683   65000
34534  171000
4208    73703
14818  100000
7719   125000
45822   60000
36616   50000
40052   46425
31223   72000
11941   24000
30945  175000
46918   75000
18712   62000
6969    35000
28813  125000
34948   27000
49015   44517
38568   96000
47723   67000
7060    60000
...       ...
10850   67000
5258    32000
6508   155000
12061  120000
26989   36000
37505   30000
13243   75000
46964   52000
30815   50000
5891    42000
17141   16464
11828   34000
22560   75000
25055   39000
43904   70000
45163   68000
42941   48000
40132   59947
44341   45000
18329   50000
42534   24000
17131   19000
14138   40000
8243   115000
47338   80000
38284   50458
49546   40296
5202    38000
15024   44000
3446    56000

[100 rows x 1 columns]
           x
36724  80000
20704  75000
8350   65000
22390  36000
31323  60000
4871   76000
14855  50000
26388  90000
20550  43000
28018  58000
            x
15980   33800
10748   50000
44689   75000
25960   26500
28825  106000
44210  117000
13658   41000
49064   28400
35065   26000
39231   46000
29719   22632
5230    37488
40498   37500
48303   74000
19280   84000
24989   80000
15229   99714
37836   35000
21290   95000
24725   54000
39043   75000
15717   68000
25885   70000
32825   30000
26415   60000
22005  140000
34691   95000
4523   109000
1077    65000
8545    25000
...       ...
34711   60000
41628   52500
15430   66500
29191   67000
39107   45000
27219   35251
1557    50000
39308   21221
33703   50000
8080    73000
29419   60000
32274  100156
25823   54000
11658   75000
22818   72500
6191    77400
16591  140000
18836   92000
23424   85391
37459  175600
28562   46000
21239   52000
20917   75000
15144   72000
4830   140000
38277   63000
41747   32000
22547  100000
6610    87000
26593   34000

[100 rows x 1 columns]
            x
14445   45000
30872   93000
12483   62000
45743   34500
1070   100000
39742   95004
13754   90000
44730  102050
3439    52800
40915  151000
            x
32214   71000
3306    22584
8662    72000
40118   80000
17345   68000
31021   16000
30093  125000
7174   120000
49878   91000
405     49070
10064   23500
4852    46000
32222   62000
31643   29880
40085   74000
47117  105000
26066   61000
10209   85000
36417   28000
42738   72500
46303   75000
6020    34550
16820   56000
46453   80000
5983    50000
34097  127500
48017   85000
7929    35000
35253   15000
27378   23000
...       ...
33795  100000
41150   59200
49075   62400
8234    53000
36751   45000
2839    47183
28868   35000
8559    60000
14910   75000
31767   50000
15606   80000
35071   49000
26724   65000
992    100495
20538   40000
35182   35000
25322   26000
45939   37000
32010   11844
17817   62000
39239   45000
11103   65000
17258  150000
20333  112000
22375   70000
21816   66000
4064    35000
26334   47500
47027   80000
43505   35000

[100 rows x 1 columns]
            x
34295   52000
17775   85000
6996   110000
7890    60000
48273   67000
345     54000
32095   37000
49503  100000
20946   15372
41696   45156
            x
49000   43000
14659   30000
29152   40000
20001  177800
31082   80000
6548   120000
4955    79432
42285   70800
29836   70000
7502   110410
4746    98000
34341   75000
42807   80000
8659   113953
48640   36000
22848   35000
41371  100000
9638   145000
28123   88000
6608    69000
15776   62000
2269   120000
48899  114000
9749   128400
23479   55000
45614  102000
5438   117000
4201    50900
15280   45000
3164   143000
...       ...
10444  130000
16265   53337
3182    45000
42448   38400
15968   59000
15582   52062
30645   95000
25615   52000
42135   85000
6548   120000
18338   56000
18465   65000
6341    75000
40096   38750
21019   35577
4216   160000
33228   87445
6016    75000
27721   50000
33871   92000
31455   58000
22267   43763
16985  150000
41664   30000
36128   60000
20103   98000
37084   65000
36820   32240
34808   40000
35928   63000

[100 rows x 1 columns]
            x
25408   40000
32382   71000
6949   136500
21123   42000
4641    71000
26068   95000
30223   59000
20269   61000
11065   85000
36236   36000
            x
35662   65000
30778   30000
14565  118000
35061   67000
37318   60000
10460   48000
11497   42000
40695   61000
19473   83688
48737   95000
31818   30000
32924   84908
44179   54000
16199  120000
29438   53000
8782    90000
3212    44000
1599    48000
47743  130000
33455   35000
16713  119200
33915   60000
10130   90000
27509   56000
20745   95000
5528    36000
35088   28000
2380   102000
3897   105000
38975   65000
...       ...
45675   60000
28151   70000
37448   35000
26846   95000
25540   40000
16813   53000
41968   52000
35783  120000
43722   50000
7714    24625
40284   80000
3642    65000
502     35000
24652   98000
30378   96000
40952   80000
49741   55000
42982   56000
15328   48000
7990    55000
33537  120000
11069   49800
47247  100000
322     85000
12903  120000
36324   82000
10177  120000
30950   89000
7506    68000
45541   89500

[100 rows x 1 columns]
            x
47278   55000
25186   90000
46695   43000
15337   12000
24535   93600
41676   95000
40402   45000
42704   62000
20130   62000
49193  103900
            x
45487   53000
2958    45000
20479  135000
22241   33000
14206   50000
17144   55000
13436   70000
20825   35000
5005    65000
23726   40000
23474   84000
14493  115000
6036    42000
40642   50000
39381  110000
4796   168000
30310   69000
7543    42000
5728    80000
40211   58000
22110   13500
13180   49800
25595  100000
7392    42000
30321   40200
10150  130000
15206  102000
39377  130000
11740   42000
5173    58000
...       ...
47602   58800
31752   38500
28592   54000
7693    94000
22846   77100
1753    99135
7070    50000
20525   82000
26612   59000
19249   44851
16104   41000
34266   38368
14383  106000
32768   40000
15158   43655
48320   73200
26400   10492
16512   81500
30213   32000
41209   41000
48108   88000
42555   71200
33131   48000
529     40000
17731   64000
1988    67500
31944  105000
42647   55000
20603   98000
48566   69000

[100 rows x 1 columns]
           x
33343  48000
13942  41000
4898   42000
26122  56000
3739   44678
43671  60480
13105  28300
2675   40000
21538  62000
5112   75000
            x
31214   60000
21157   20400
38367  175000
45032   59900
6108    45000
42834   80000
44768   95000
46586   62000
31639   40000
20182   45000
25203   70000
6487    80000
36324   82000
16262  100000
49110   70000
33269   72000
12595   95500
43242   41000
29090   62000
30219   29435
5569   122000
19509  115000
24737  105144
2704   180000
13487   47000
28766   40000
89      45000
24573   45000
4485    65000
31760   37300
...       ...
1162    50000
20231   62400
27231   20000
20683   62000
17125   83000
20864   50000
33862   32500
15260   50000
46641  100000
47124   70000
34446   35000
26844   68500
47039   47000
14266   74000
688    170000
4172    65000
19976   68000
14479  120000
7174   120000
1445    50000
5625    45000
5914    46000
13796  150000
12327   67000
33421   52000
6126   186000
12481   60000
42095   42000
16369  120000
27532   45000

[100 rows x 1 columns]
           x
11744  82000
44134  45000
2724   57600
35223  72000
33009  77000
47403  15000
34832  37000
18934  51000
38787  92000
30220  30000
            x
37047  105000
37539   14000
1856   126000
42921   29926
33156   57996
20246   25000
36473   26000
19991   59000
7658   103000
38884   38000
17935   32000
11118   55000
15160   56160
35896  105000
13070   25000
18833   85000
29914  120000
41273   47000
10764   85000
1042    80000
12287   85000
43354   75000
36952   97000
22123   34000
1973    63800
4592    30000
3192    64000
1706    38000
45183   85000
17623   59000
...       ...
39622   36200
18121   92000
4479    85000
18591   32000
40889   47000
28349   83000
15904   67398
22931  130000
37955   32000
17669  111000
32664   75000
27545  100000
23566  130000
22667   56000
28587   35500
39896   25000
28846   90000
4411    55000
33686   92000
18842  110000
2576    55000
42221   25000
46242   44023
14833   65000
22210  115000
27454   76000
6698    82000
29794   69000
13178   72000
15651   40000

[100 rows x 1 columns]
            x
32501   55000
2611    74000
26227  135200
18573   37200
9623    60000
19790   90000
10079   65000
19862  163177
19482   50000
12474   77000
            x
33632   25000
2955    35628
30615  117000
27848   75000
3096    65000
21960   42000
37892   95000
37473  125000
40578  126000
32372  117000
6454   185000
36897  120000
7363    52000
24535   93600
3347    90000
2121    65000
21362   58000
38390   70000
5537    42000
35615   36000
47101   48000
4857    75000
13905   45000
19322  133500
238     53300
24271   56000
47703   96000
14178  125000
21227   30000
7867    45000
...       ...
29277   78000
48772   98000
21728   50000
15928   85000
21584  145000
18539   55000
2442    80000
16578   42000
11148   48000
7225    84996
3122    28000
27819   45000
8404    45000
41136   49000
42563  110000
5867   170000
35064   25000
15173   35651
41666   25000
28021   85000
18105   55000
37784   40000
10071   90000
27410   72936
16959   96000
21723   55000
6701   123000
29430   22800
1608    25000
11078   85000

[100 rows x 1 columns]
            x
17933  105000
21600   60000
26165   52000
17250   70000
22555   74000
35544   69810
27758   75000
25096   49500
25316  106000
11743   57250
            x
36722   85000
39273   75000
49290   94600
48839  100000
38133   29000
20343  165000
438     80000
4737    90000
7373   100000
27343   48000

            x
24175   30000
3029    36000
21151   53880
5149   140000
5970    20064
8792    90000
6599    70000
23234   44500
38388   80000
4369    42000
16892   82500
39345   94800
43055  118000
22991   45000
9585   100000
31242   65000
31227  145000
28582   32000
35951   54400
34829   93000
43233   40000
49285   50000
17727   60000
43616   25000
9885    46927
20320   26000
13270  120000
37724   40000
43885   34000
3949   150000
...       ...
23339   60000
22757   75000
26710   43000
38755   33000
43214   87300
23566  130000
47524   70000
2844    29000
21574   54324
41431   75306
26624   43076
1718    60000
9964    65000
5322    58500
10663   33000
40173   80000
9049   100000
36812  125000
11215   47000
42244   18022
20381   35000
18032   45000
49874   65000
30087   54235
345     54000
15376   52000
11281   66000
1549   120000
21835   43000
49028   54000

[100 rows x 1 columns]
            x
43642   58000
22284   51000
33307   70000
38238   37000
34820   45000
2587    60000
4516    45000
29582   43000
19224   90000
19081  165000
            x
33406   40000
18529   55000
5675    38000
16362   90000
15331   55400
38559   68000
49832   35000
13279   55000
412     67600
41943   53000
14984   84000
30533   24000
11998   42000
307    106000
49193  103900
11957   42000
44477   40000
21086   48000
26191   65000
24869   94000
16874   42000
674     32000
12516  100000
3058    68000
10338   27000
31406  138000
6890    56500
49762   60000
30551   30207
43464   95000
...       ...
33177   72000
7593    80000
47370  140000
5784    42500
33918   71094
30571   40000
43725   56492
23771  180000
42042   31000
28376   80000
7963    24000
23614   65000
18121   92000
18178   26000
1152    53000
2718    82000
2922    30000
27469  104000
21525   55200
34332   68000
5921   104500
2009    65000
46758   50537
13119   47000
21663   28000
25431  121000
43858  132000
36587   70000
44266   52000
30530   65000

[100 rows x 1 columns]
            x
21011  112000
9223    75000
22934   73000
27812   60000
10510   77000
524     52000
22502  120000
29934   80000
11223   36000
26446   36000
            x
42724   70000
40792   35000
48415   45000
36155   25000
23205  105000
44915   43000
14083   30000
30529  140000
44140   53000
5164    55000
8880    90000
22292   40800
14944   58500
39138   50000
13584   70000
47714   33000
29593   74400
25135   20000
36149   65000
12371   46250
38099   65000
19668   57000
32415   62000
35477  113000
39194   27993
44344   55000
6348    44000
10784   68000
44378   55000
39215   67000
...       ...
27911   68604
26316   70000
15217  155000
26352   30000
29558   50000
12597   25000
49921   84237
7288    64238
11      60000
39631  170000
22793   40000
49820   80000
567     64000
49583   40000
35915   45000
18324   45000
44756   35000
22324   90000
28499   50000
38061   75000
33197   68000
2686   120000
9356    54000
46039  100000
5800    60000
5622    38000
37730   83000
39929   45000
44687   79000
9050    19000

[100 rows x 1 columns]
            x
49912   36000
42816   50457
32411   86000
22266  155000
17888   70000
21110   51000
25789   30000
17138   64750
7422    62042
33474  117400
            x
47121   40000
5095    60000
37482   30000
2833    62000
43820   62000
11185   72000
7659    90000
17610   22000
32531  130000
9680    85000
17939  137000
3946   103000
23160   50000
4025    28000
26662   45000
15956  120586
33427   72000
5146    40000
44480   50445
21798   52000
27192  160000
30863   65000
43053   35000
47586   65000
44784   84000
35978   47000
46229   30000
49679  145000
38850   44000
4395    88000
...       ...
45530  119000
39514  100000
1705    70000
48750   57000
11353   62000
11584   50000
2823    74000
31532   55000
19635   24000
17374   66000
44043   57000
48439   80000
9312    92000
32654   67000
1189    52000
40429   55000
18636   50000
48708   57996
35002   50000
45188   39000
49952   43000
5994    55300
26713   43500
2790    57000
33252   70000
34591   60000
25571   57000
47659   55000
4714   130000
16752  110000

[100 rows x 1 columns]
            x
45389   87000
45855   53000
6773   100000
45923   48000
26123   43000
13680   95000
12365   90000
29420   62000
92      50000
39993   32880
            x
19262   65000
40388   45000
37299   85000
7025    46000
102     59500
21098   75000
46935   57500
1368    60000
43002   71000
7784    56000
28336   65000
25473   58000
14298   40000
23227   72000
40508   88000
35385  160000
39176   36500
17209   18000
45525   36000
8136    92000
8403    52000
49160   30000
46202   39000
20094   60000
5752    55000
19267   70000
44068   92000
18954   90000
21046   75000
9066    62000
...       ...
7584    45000
37773   90000
35206   70000
42375   64000
40908   94500
15870   52000
21943   20000
41640   34500
8889   137000
30402   98000
8673    51756
42703   43000
39762  160000
13334   55000
38777  100000
29734   60000
12474   77000
27209   75000
40664   80000
37638  101000
7580    48050
19710  125000
35707   28500
38985   48000
23120   65000
26807   60000
35244   42000
47205   35000
39983   30000
37497   35000

[100 rows x 1 columns]
            x
5283    50000
13540   91000
5178    45000
10792  104000
12269   45000
11390   40000
20326   70000
11778   94000
45857   93840
33487   30000
            x
22866   50000
41008  105000
34924   60500
15826   52000
28079   38000
12144   59527
49526   66000
12595   95500
8084    76000
26858   40000
41391   36000
26080   55000
25516   64200
9979    75000
15707   23196
20176   49000
40770   57312
221     90000
48616   34000
10135   45000
24011   62000
37015  105000
27649   69600
1446    45000
14114   35000
39728  100000
49589   28000
26078   80000
44406   96000
30471   26665
...       ...
21127   46000
38733   52000
24808   36000
26655   41000
22911   85000
19564   45000
31820   38000
30417  105000
1785    42000
17212   61000
29193   32095
19445  113000
40801   92000
35615   36000
19770   40000
5987    60000
31085  110000
30639   56000
32207  137000
13896   52127
26631   67995
17599   60000
24161   34014
179     41000
2193    75000
24682   50400
48559   90000
41347   25000
2563    45000
8367   150000

[100 rows x 1 columns]
            x
43913   42000
39032   95000
45572  115000
16844   42802
6083    42000
39663   60000
12258   75000
35614   50400
12192  130000
47246   72000
            x
9737    39528
8678    98000
16345   40000
49603  125000
30236   33000
40787   72000
33887   38000
40022  125000
37326  175000
32295   73000
39122   30000
45059   86500
1978    60000
17501   35000
13554   67000
18213   23000
6932    78000
11852  150000
28875   52000
24332   25608
8704    40000
8909    33580
14506  132000
10483   57000
12440   90000
27432   38500
36956   63000
35398   64000
48901   63000
42186   81840
...       ...
2658    87000
26170  125000
42208   60000
4776    20800
37884   75000
30194   38000
19399  122000
40264   52000
24      70000
778     30000
8558   110000
23168   30378
48861   43000
25573   80000
9330    34145
26295   41000
192     90000
24608   45000
30695   74666
27756   58000
34383  130000
38245   48000
25787   54000
27631   65000
38364   80000
37315   65000
17045   52000
26644  136000
40676   36000
25555   40000

[100 rows x 1 columns]
            x
2072    23000
38133   29000
24418   72000
29675  130000
13626   88000
36498   65000
49677   70000
36709   35000
47268   65000
40664   80000
            x
12975   25000
32639   32560
43194  100000
47308   90000
49228  112140
24145   34000
39739   25000
12891   31928
41058   53560
23809   30000
38574   45000
32770   38000
32818   45000
4711    28000
2234    50000
956     56400
18035  104000
5791    39000
15690   27000
19969   45000
14433   99000
21568   70000
10372  130000
1510    70000
27301   47254
23913   17998
19668   57000
5390    39048
37160   95000
16543   90000
...       ...
13666   90000
26482  100000
48254   85000
22718  120000
48237   42000
13243   75000
43489   53000
26528   50000
28227   77220
35402   30000
24860   60000
27998  142000
3171    65000
8076    40000
23336   23579
20715   45000
16872   85000
49228  112140
43050   25000
5605    27185
16781  101837
2472    80000
17371   90000
3077    38000
45879  125000
1125    97200
18559   37800
14829   70000
9482    50000
31349   65000

[100 rows x 1 columns]
            x
17874  120000
6131    45000
2466    75000
7345    50000
20029   94000
21025  100000
6547   116505
29079   55000
42709  139000
47992   80000
            x
36416  149000
4887    75000
41876  100000
27811   24000
16644  107000
24613   70200
45658  100000
26409  170000
45424   72000
21853   67000
24819   50000
41230   70000
15312   52000
45007   69000
48916   67000
20785   28000
19692   50000
6825    60000
31777   71000
48430   22000
46980  100000
2024    90000
40190   30000
30722   18000
3219    65000
856     62000
17631   50000
23569   35000
29613  125000
5638    40000
...       ...
13382   95000
517     27000
49239   52000
19697  130000
15658   30000
31680   33000
30615  117000
13423   49000
11646   42000
18015   69000
3504    90000
37352   65000
43093   55000
49322   43000
43454  135465
49122   37200
7226    22000
31949   54000
7640    60000
37135   74714
20843   98000
29127   50000
7571    90000
33499   69839
7250    40310
4760    45000
37766   60000
17581    9984
37535   32000
24795   45000

[100 rows x 1 columns]
            x
28154   62400
35254   61000
24599   49500
22534  100656
23104   30000
1321   115000
9442    14172
47515   35000
10215   76450
48009   68000
            x
36920   52000
40716   80000
34917   95000
6965    80000
22261   30000
355     72000
32162   84000
35819   30000
36113   70000
21949   85000
32821   35000
35959  129000
9370    50000
40823  114600
27498   77500
34235   90183
18361   43450
15565   44000
5154    70000
15840   73000
33905   65000
19069  120000
4064    35000
13375   70000
17915   66000
16132   32800
34176   82837
9516    55000
3747    30000
10266   84000
...       ...
41579  100000
17210   48000
42819  102000
31829   40000
25386   55000
2887    55000
32779   90000
29069   46000
11663   51974
5874    50000
6230    30000
18259   90000
37136   48609
40730   50000
42570   40000
42714   45000
4211    80000
13368   30000
8689    71000
43729   54000
44325   70000
43486   75000
9601    30000
48512   90000
40179   48000
27873  110000
29737   95000
33362   96000
42221   25000
11813   65000

[100 rows x 1 columns]
            x
19063   32000
20541   49000
15001  102000
46694   54000
10275   28000
39748   36000
41039   36000
13492   35048
21181   60000
34765   45000
            x
9797   125000
43944   52000
15799   95000
31462  128000
48239   72000
10296   76000
24605   25000
11831   64500
32673   82500
10502   23964
9991    90000
13511   43929
24279   37167
4011    48000
13771   60000
33730   39144
22452   44000
30021   60000
3890    61140
41665   65000
44316   40000
23493   40000
22380   66900
27611   63000
23584   85000
26509   65000
24244   15600
12822   65000
24979   27000
39156   12000
...       ...
28219   60000
13167   76183
23313   18000
24526   58563
19869   50000
22387   37500
27828   75000
20508  150000
16713  119200
48032   81000
22790   40000
31154   50000
3967   100000
20791  105000
30771   66144
25531   64500
32985   80000
1079    98000
1580    85000
21131   68000
12910   82000
37829   80000
18855   53100
26402   80000
5608    90000
29035   85000
18394   56000
3081    28000
35656   57240
26820  112860

[100 rows x 1 columns]
            x
49161  125000
21586   95000
36819   60000
30584   44500
40092   70000
34213  115000
12852   54000
18014   90000
23875   19896
42158   92586
            x
37428  110000
13235  120000
39906   81000
31587   39690
33175  150000
36808  165000
5603   100000
8663    40000
27818   82000
36228   52000
26624   43076
26456   28000
38341   40000
21671   60000
19410   63450
25842   40000
30561   33990
40484   41600
40060   40164
362     49700
11414   50000
27090   45600
21628   69440
42404   82000
2042    90825
11113   38500
915     30000
33432   45000
18598   40000
24725   54000
...       ...
1070   100000
34847   65000
1200    74000
1784    86000
20685   88500
46876  110000
250     39996
41253   58000
15262   78000
3398    56000
37441   43908
49662   48000
39969   53000
692     65000
877     98000
47906   35000
20798   38000
27880   70000
18515   19140
48149   72000
20288  100000
30592   55000
43160   40000
7375    87500
20456   69000
18897   70500
1269    41000
3005    72000
34700   64000
25018   97000

[100 rows x 1 columns]
            x
29334   87135
22917   60981
38652   49000
49043   40000
49642  135000
28206   50000
822    100000
4621    72000
34114   65000
7122   100000
            x
34445   70000
26587   45000
37164   50000
20669   75000
31925   48000
47986   40000
46508   83720
39932   35696
35253   15000
47384   56000
10554   24000
6232    40000
32494   34000
36538  120000
13993   65000
28331  119000
19999  113000
42826   45000
27557  150000
14883   44000
12728   54000
23698   80000
20072   60000
1533    60000
9130    85000
12232   80000
4077    87404
36892   55000
30717   40344
39943   84000
...       ...
26367   61000
31167   52645
19840   51000
45202   48000
46495   75000
20384  100000
4331   147000
10989  108000
26451   70000
30585  115000
484    120000
46599   83000
362     49700
43192   34000
45905   50000
8423    28000
21845   92000
24334   90000
4131    98000
38669   87000
3415    39000
33446   66000
6335    35000
23650   90000
38636   36000
44770   29000
12508  100000
47913   85000
6563    22000
15193   30000

[100 rows x 1 columns]
            x
15343   27000
23285   39000
38738   61000
19428  150000
18532   33000
18644   45000
6405    52000
6762    91000
30565   24600
4497    54000
            x
38634   33600
12811   60000
17874  120000
5617    61300
33346  185000
33366   30800
41448   37440
2984    58000
40626  125000
716     72000
8441    49000
7297    90000
9231   150000
8603    42000
49271   25000
15548   24000
24418   72000
16824   65000
24559   90000
711     39000
49870   60000
41730   63000
28935  100000
46797  108000
32439   55000
45061   38000
34516   32000
41874   54000
36663   78000
36347   62000
...       ...
10916   50000
40031   13000
25768  102000
18479   84000
13531   55000
46279   45000
27054   62000
13829  140000
38859   60000
27232   60000
17945  104000
18464   54996
22162  105000
36977   80000
49875   57000
17044   85000
27564   76000
42041   50000
15535   75000
5414    36068
46609   53500
6851    50000
17846   75000
7778    60000
17676   60000
33125   62000
29938   43000
1860    57000
14087  108000
36578   75000

[100 rows x 1 columns]
            x
49959  115000
48033   50000
11116   60000
45391   26526
39530   48600
4829   150000
40560   38500
47439   60000
31139   45000
34503   80000
            x
26274   95000
38498   28800
44753  125000
1239    75000
17445  105000
13507   62400
1617    43000
28739   34500
7779    49000
14263  104525
35756   75000
23559   26000
17089   50000
27410   72936
38380   90000
14673   85000
44680   28800
17061   41000
28769   80400
35682   42380
22000   63000
845    114000
36446   95000
41695   90000
31412   40000
3032    79000
18885   72000
34845   90000
22069   56000
5819    25000
...       ...
33838   98000
27931   65000
41476   36000
29872  175000
28880   50000
42849  117000
10005   60000
13190   45000
35890  104000
49673   91520
38980   35000
127     51000
31393   79000
2210    50000
28416   74000
9935    59000
41741   57500
13990   65000
24049   60000
25075   70000
18283  112000
8579    44000
18611   80000
10865   43500
39780   50000
38963   61000
28137   70000
6200    45000
8299    39000
19517   83000

[100 rows x 1 columns]
            x
15669  150000
12180   70000
27141   43000
42900   49000
6817    65000
12702   90000
18457   72000
17711  100000
36985   80000
3912    60000
            x
1356    59000
31713   50400
3544    92341
20503   60000
48239   72000
21072   60000
47732  110000
9342   160000
43367   16307
10184   55000
15759   84996
14590   60000
24210  125000
44297   60000
27162  123000
37013  132000
25702  103000
44135   37800
11727  135000
43603   75000
35791   24000
37746   52000
20713   79000
40418   87054
19327   85000
16898   34000
3769   108000
44943   60000
17628   66000
20265   82656
...       ...
10755   60000
10046   50000
522     32760
39349   95000
30533   24000
13281  105000
20831  120000
14677   40000
1934    60000
22011   65004
32903   60000
10346  125000
41604   57000
42      55000
36327   38500
3503   154000
4694    72000
44824   45000
1031    85000
33072  100000
18046   40440
518     75000
25301   49989
5179    85000
37488  167000
14037  150000
26995   80500
6236    36400
35524   65000
26255   38500

[100 rows x 1 columns]
           x
6471   52000
21808  87500
26824  78000
41355  72000
11995  55000
45536  52000
18640  52566
25884  42000
30278  85000
2103   40000
            x
24102   72800
38616   55000
14092   42000
19373   32000
34780   51000
23656   32000
23992   60012
2883    46000
19609   28000
5913    73000
34526   78000
29892   42000
10475   42000
25983   72000
39431   96000
30511   41832
5329    48000
31639   40000
7097   112500
12663   43000
22067   85000
25503   46004
17243   65000
42354   70800
36531   38000
23069  100000
32783   29000
44261   55000
49438  124384
10282   40000
...       ...
1007    90000
21746   75444
32620   99000
40064   40000
43752   30000
20691   72000
38657   60000
12417  120000
27060   63600
9262    30000
45882   58000
18515   19140
3865    52000
15499  125000
14767   38000
19286   52000
47015   70000
48958  114000
36323   38000
11915  120000
401     48000
17921   88000
15583   68000
34254   60000
30801   28000
4599    28800
34512   76000
2440   165000
19875   65000
41996   44500

[100 rows x 1 columns]
            x
43688   81800
4073    65000
16602   42552
41747   32000
2165   100000
24301   52000
8614    80000
546     50000
44630   60000
10475   42000
            x
44242   20000
40772   53000
21332   94000
5442   104000
30203   47000
4954   107000
49140   98000
49794   21718
45001   19000
46744   21000
13313   33500
35164   48000
31154   50000
27935   70000
12619   59000
22526   83600
10397   90000
8381    80000
11534   82900
44600  135000
22495   60000
16856   33000
952     50000
49589   28000
9262    30000
4407    35000
1709    31000
34124   35000
27396   83000
15438   65000
...       ...
5108   170000
15275   58000
4177    89000
43382   38000
37271   95000
5609    50000
20457   73000
25411  140000
17522   36400
30405   35000
8661    76500
9598    85800
28036   70000
25074   29586
42293  102000
30     126000
14026   90000
38983   48000
11253   97000
9244    28000
44393   60000
9167   155000
28759   33000
48626   62000
24735   70000
22549  170000
7439    63000
15383   85000
1407   120000
37394  100000

[100 rows x 1 columns]
            x
36487   88000
11925   65000
4736    55000
49393   59000
32758   55000
38247  118000
39832   78000
35000   49000
46977   33000
23378   75000
            x
24945   40000
14318   53000
49794   21718
42483   54996
8692   100000
28960   40000
24051   70000
44568   95000
21208   70000
4776    20800
11516  120000
3613   110000
38842   47000
35975   52000
16528  106500
26803  155000
32761   45000
47642   43680
35808  120000
17394   92000
23423   62000
22503  143000
12973   48000
22227   46925
13093   43360
2984    58000
41452   65000
35449   30000
11525   75000
31370   57000
...       ...
11853   93996
23836   51209
6796    48000
43452  100000
49284   70000
46312   73000
28900   91700
39088   35000
53      30000
288     79100
35896  105000
12747   36480
3483    71000
15423   47840
9243    51400
2357    80000
13517   75000
47127   45000
26065   40000
15961   47000
40174   52000
13396  148000
39775  110000
39894   94992
36947   72000
34494   30000
848     34500
41189   46000
48468   61296
20714  119496

[100 rows x 1 columns]
            x
32951  100000
26939   63000
42778   36000
12704   87000
47874   66000
765     32000
9636    44000
35532   39000
20776   42650
33843  100000
            x
33568   60000
40443   94000
30932   85000
28549   50000
42404   82000
22031   70000
1167    48000
25505   97000

47574   48814
            x
28628   96000
47435   18000
11615   96000
4118    72000
29482  120000
6323    85000
1927    95000
21795   25000
9720    26000
2474   100000
43027   45000
1467    84700
16874   42000
27394  150000
44733   41000
46132   30000
46169   36000
21587   72000
26094  165000
7509    35000
29179  138000
13752   41000
32965   54000
48543  150000
16715   60000
12492   42000
48535   34000
44056   53000
23404   45000
28071   83395
...       ...
39986   75000
24165   66300
10677   55000
9909    83500
7218    90000
29196   50000
33689   72000
37160   95000
28992   45000
2229    98000
19554   50000
25519   42000
10167   65000
17545   55000
38585   55000
46436   52000
37013  132000
7776   107000
45470   46000
30029   33000
9936    63210
23875   19896
26606  105000
45555   39000
34753   95000
29843   38000
22495   60000
25315   95000
34776   42000
47160   55000

[100 rows x 1 columns]
           x
29559  55000
42322  38000
34832  37000
42794  62000
36273  38000
22787  55000
19786  35000
3280   80000
33781  46000
22639  47186
            x
21936  112000
6283    40000
6734    62413
26036   62000
20476   68500
9359    53000
37759  100000
9565    11690
20845  110000
35468  190000
354    103000
44361   30000
32373   26400
28883   65000
48880  104000
22982   52500
2562    93000
13647   40000
12712   73000
33369   85000
10357   74000
11930   44000
20165  100000
27466   96000
31151   95000
19476   90000
41445   40000
28803   54000
28917   40000
22263   47000
...       ...
24438  110000
940     42000
7286    20000
2543    32000
13467  102000
5251    45000
49877   24000
18563  100000
35136   96000
23201   32000
42402   60000
24280   53000
42271   64000
14525  100000
30698   70000
23196   60000
9336    98000
10106   48000
43231   45000
18121   92000
11055   80000
22857   42000
21982   65000
27365   84000
5458    48000
28      36000
1323    83300
28708   23000
8408   120000
22854   70575

[100 rows x 1 columns]
            x
45425   39520
7624    45000
46134   30338
35410   50000
48964   39000
29542   80000
369    110000
46371   83004
45287   50000
9030   151000
            x
11825   26000
11057   46900
36585  104000
44320   37200
32220   66000
16636   59000
16576   55000
39649   75000
1936    68000
24694  110000
21479   32000
31307   35194
49057   40000
18210   65000
30952   65000
27318   97704
17529   90000
29867   67500
33690   72900
17290   65000
31603   55000
31091   52000
3860    32000
44315   27000
12426   66000
18442   50000
49224   30000
1842   195000
21267   37550
9988    94000
...       ...
22808   90000
36491   54000
48018  101000
46294   72947
2902    48880
15209   20000
29970  135000
469     75000
38020   59500
11159   90000
32344   60000
12019  110000
1811    88000
41682   87000
48251   92300
39623   24000
39249   80000
5707   120000
32356   70400
1207    96000
48164   69000
30597   87788
2298    85000
15463   34200
2895   100000
46825   50000
2276    75000
25124   29004
42810   60000
11218  103400

[100 rows x 1 columns]
           x
13837  79500
31990  55000
3052   58350
4610   30000
11536  62000
21375  52000
35346  75000
6901   22000
11390  40000
39134  83000
            x
17703  131000
36811   44000
30659   50400
46848   82000
43309   27000
30016   42000
42844  100000
47255  160000
20427   85000
40172   51660
32077   53760
6105    97000
18660  126000
22793   40000
29730   65000
42215   45000
23530   71000
34342   42500
5070   115000
17858   80000
44155   90000
31655   20400
46604   80000
30421   28500
26061  122000
14948  145000
18340   95000
18349   43000
25940   47500
29578   50000
...       ...
12282   40000
23433   44000
1399    26400
34197   92480
11229   11592
7391    24000
3844    37000
26288   28080
38869   40000
4764    43680
30140   76000
9249    55000
17157   40000
749     64800
11791   50000
9025   140000
29001   57000
26754   40450
16396   44000
49396   40000
9017    30000
8667    70000
17335  120000
29409   43000
7219   118000
36916   13200
32012   23004
43195  119000
31789   24000
46882  125000

[100 rows x 1 columns]
            x
14276  100000
6206    54000
49816   70002
1214    40000
6101    44500
47376   80400
42043   30000
17882   24000
43365   30000
6070    95000
            x
8786    48000
5999    60000
46020   92000
46524   46000
11561   30000
27648   45000
21157   20400
3496    60000
8718    88000
12661   76000
8842    95000
14496   55000
48190   50000
46382   42000
18991   60000
35538   63000
30789   96000
49492   22000
46712   77000
6831   132000
24800  175000
40757   87000
38116  139294
37436   67000
38158   62000
22923   24277
12035   27000
41870   90000
19305   30000
22090   20000
...       ...
7001    54000
16541   50600
18932   77000
37468   50000
27985   37000
35293   72000
44802   86000
6116    15000
3145    45000
3807    56000
25558  105000
44731  125000
7384    55000
36717   47000
36630   40000
32283  130000
7158    43000
34942   36000
22876   50000
39653   32000
16539   44000
3300    50400
32414  107000
24119   43000
45059   86500
3899    30000
17932   92000
10392  125000
20709   90000
48471   65000

[100 rows x 1 columns]
            x
41798   56000
46222   53000
25486   68000
28535   75000
2107    46800
34097  127500
7733    83000
2076    55000
9168    50000
20008   85000
            x
30008   85000
251     55000
32275   31200
24572   50000
7852    35000
47043   90000
7126    35000
34928   35000
11671  108000
14586   48000
12254   60000
23147   35000
42105   42000
7993    90000
14067   30000
30600   55000
40561   75000
13897   36000
4975    53000
8269    60000
13353   41005
14547   36000
16689  102489
31923   85000
40685   70000
1768    52800
33830   29702
1466    63000
34099  150000
44663   81000
...       ...
3346    45000
27772  125000
42682   41496
2301   145986
28582   32000
6822    43000
31874   40000
20615   54099
40535   50000
22765   42000
6625    44000
30955   78000
49298   83000
14981   52000
22889   40000
19060  125000
43312   75000
30058   81000
23433   44000
36566   29000
2339   160000
3808    78000
21685   60000
17501   35000
25603   38000
10416   45000
24376  110000
25170   75000
17928  198000
5342    76000

[100 rows x 1 columns]
            x
41821   54996
31665   85000
3125    53000
25595  100000
754     55000
20055  120000
15956  120586
16113   69500
28928  125000
12802   91000
            x
45741   42000
31915   39000
31885   36000
14140   60000
14331   43408
27164   28000
28843   36000
38161   92000
10875   91200
30157  110000
39666   54000
28993   40000
29878   69500
28242   53000
37252   35000
11984   43000
44756   35000
34932   40000
45207  120000
13792   44000
5411   100000
34466  110000
46348   53000
7608    57000
48241   65000
41530   79199
19629   32000
17746   40000
25737   59000
22285  104000
...       ...
6841    50000
23698   80000
43766   60000
3309    40000
13523  133000
30604   74028
24868  160000
46666   55000
45977   45000
6847    80000
42156   70000
9845    80000
4959    83460
30906   70000
35104  114000
35961   42000
25460  137000
11716   40000
28566  110000
33821   55000
29901   50000
23126   34000
26100   80000
5666   125000
43109   55000
27126   60000
27356   50000
42051  114000
19433   70000
32486   66000

[100 rows x 1 columns]
            x
37544  133495
12712   73000
36505   53000
48031   50000
230     56000
17639   70000
34412   30000
34401   32000
46783   42000
38503   42500
            x
32780   30000
38423  110000
12323   42000
48930   48000
38020   59500
30462   42000
8147    80000
22864  102000
34747   70000
39337   55000
16     150000
23502   54602
34671   52000
32071   52500
43833  107000
1915    38000
10229  125000
7495    70000
49800   47412
13231   41000
22955  110000
44616   50000
14784   50000
38392   72000
40208   76400
14332   50000
22417   62340
13451   50000
5019   160000
25135   20000
...       ...
33706   15000
20948  182000
43881   65600
17066   36000
48707   69000
11484   45000
45098   42000
32872   51996
22969   29400
44322  100000
28231   49500
37813   40000
18759   95000
42965  150000
38130   30000
17066   36000
43541   38000
49715   45000
10089   36000
4964    58000
39702   57000
24537   65000
31217   21085
825     87500
23039   80000
43250  105000
39253   70000
4035    80000
42883  110000
49485   10624

[100 rows x 1 columns]
            x
13822   60000
1699    30500
16701   24000
30326   52000
44654  110000
41017  130000
12681   55000
8206    51000
1679    80000
34066   75000
            x
20812  120000
2729    83200
47203   85000
48073   93000
24971   40000
21595   61500
18834   40400
17576   90000
11924   62000
38076   74500
41411  110000
5985    21609
33938   42000
36113   70000
44818   28000
23783   71000
12213   75000
6322    60000
44624   75000
24898   72100
33652   50000
26015   75000
11186   78048
32398   99000
1393   100000
36962   90000
13361   58000
9782    70000
32272   75000
10289   67000
...       ...
33738   92000
35157   40000
27606   50000
2836    43000
8667    70000
24614   78000
25043   60000
12784   23000
32275   31200
33518   92000
37206  105000
43031   44100
30102   35000
6600    46875
11276   75000
24520   85000
33045  120000
32958   65000
48817   60000
287     52000
36187   68000
8217    38000
17308   50000
16467   50000
32301   88740
12907   28269
48176  150000
25857   91000
7889    35000
27052   28600

[100 rows x 1 columns]
            x
46613  150000
131     68000
47705   50000
31996   65867
42620  100000
8669    32000
23372   75000
19841   52000
3911    90000
48408  106000
            x
38829  110000
39732   77000
18929   45000
33918   71094
34053   36000
30092  150000
27760   44000
22867  105000
4360    54000
4533    90000
41366   30000
26998   45000
32609   60000
37637   65000
19684   33000
23260   50000
35720  144000
40437   78500
6053    58500
35631   42640
40685   70000
29363   90000
48548   80000
33475   45000
10555   52000
35757  118000
27191   55200
49947  129600
4902   110000
9050    19000
...       ...
27529   74000
12547   25000
8314    21000
15106   71000
17023   65000
13471   40000
42667   60480
34608  103000
3642    65000
14206   50000
43815   98000
9296    57000
839     75000
2144   115000
22746  102000
133     70000
16427   75000
18143   61000
4027    72500
4190    50000
8260    62000
21423  107000
35110  118000
7652    50000
38995   84000
42709  139000
42054   53000
28198   80000
14679  140000
19697  130000

[100 rows x 1 columns]
            x
42253   97000
15870   52000
3566    51000
48522   41850
39651   72000
285     71000
17790   54831
21800  120000
6581    45000
49719   70000
            x
21053   82000
44635   38000
14828   29328
18392   44000
4679    86500
24623   40000
4618    65000
25673  155000
478     40900
20118   50000
35943   80000
49367   30000
4719   117700
4990    58240
2827    42000
30900   81000
20132   81000
45938   85000
27400   89000
42357  130000
20133  100000
8520    50000
15293  137000
25247   94000
38774   82000
48427  111000
4918    83000
35723   75000
14813   54000
4112    60995
...       ...
40330  108600
44012   50000
25067   33000
41356   55000
23346  130000
35345  115000
48737   95000
23945   50000
45170   55000
48439   80000
45839   40000
29294   32000
16253   56000
22223   56000
1672    47000
15968   59000
3329    20988
39538   38000
30676   48000
49517   30028
1189    52000
49723   24000
35019   30000
18110   32000
30541   66000
15065   79000
19848   44500
17252   67000
38568   96000
18292   45000

[100 rows x 1 columns]
            x
19567   45500
21983   51000
41706   74000
43301   48000
1533    60000
6734    62413
30445   49000
42143  102000
31354   32000
34457   30000
            x
25601   50000
32694   73000
21399  100000
24938   44000
49904   50000
8090   148000
4127    57000
41909   75000
31012   40000
46536   50000
17303   85000
25796   34800
24094   31000
7731    70000
32082   60000
5404    45000
47472   42000
41898   80000
2789    65000
39793   65000
344    130000
21850  105000
726    120000
25669   32000
11693   70000
15772   90000
44005   35000
39017   72000
7567    30000
7639    36900
...       ...
26958   66000
10692   65000
3149    30000
47440   55000
15624   54000
17186   75000
40762   55000
36235   28000
1259   111600
10968   79780
30946   90000
18232   25000
46871   30000
43214   87300
38408   85000
16309   55000
21867   72000
16654   45000
5448   104000
11328  119000
35212   50000
48318   72375
31024   54000
3668    90300
42544  125000
38624  110000
20520  136500
49706   45600
9162    70000
30128   31000

[100 rows x 1 columns]
            x
20827   30000
656     95000
22738   70000
19982  175000
33401   45000
21854  128000
46788   48360
4044    55000
32485   36000
29558   50000
            x
34294   36000
37171   70000
42874   85000
29888   95000
31597   54996
30801   28000
23282   53160
39264   41000
36230  125000
22259   48000
46999   35000
47781   72155
3769   108000
32528   60000
30630   50000
47035   53000
37285   70000
1158    61235
21190   32000
33031   52000
32822   77000
13240   93926
48048   50000
10442   34687
39948   90000
19061   72000
23912  120000
16195   75000
31137   72000
7149    44000
...       ...
26904   75000
1094    48500
5647    87000
11501   60000
33315  137000
24604   65000
23089  120000
4417   120000
19065   92000
17547   65000
6901    22000
43433   67000
27797   86000
23559   26000
31205   14472
41814   50000
32431   77000
28234   75000
5461    60000
26604  150000
17192   29000
39183  125000
43246   68000
25456  100000
49362   55000
4777    98000
48092   19120
28957   64700
31454  120000
20605   56000

[100 rows x 1 columns]
            x
13132   64000
49919   85000
40041   73363
20538   40000
1790   120000
28350   33000
41311   43750
18131  125000
25920   82000
29818   65000
            x
38820   60000
24466  120000
21442   70000
5589    30000
8633    96000
19181   80000
19620   48000
19223   50000
15528   48000
36967   63000
39714   22000
33146   23200
27055   70990
24111   30000
45554   47000
30385   92374
20599   43000
46112  100000
49918   89000
3386    74800
35476   77000
11426   42000
44869   36000
31786   60000
40838  100000
41293  107000
30264  110000
4920   100000
7562    72500
10281   75000
...       ...
44831   29000
48300   55000
30741   80000
3422    55000
44488   85000
41655   86500
13788   30000
29935   63000
40350   33744
47501   80000
48073   93000
48852   95000
21539   79000
35534   92000
10447   56000
7662    25000
13217   63000
1241    55000
36559   75000
22592   85000
39468   55000
42868   85000
23862   70000
5266    76000
16232   50004
1422    80000
34058   43861
17308   50000
37215   35363
40809   55000

[100 rows x 1 columns]
            x
24871  102000
30008   85000
38202   65000
31360   51200
32618   70000
41857  165000
32656   38000
40440   30000
19580   81000
12303   65800
            x
31516   42000
23704   65000
4226    40000
1516    62000
28628   96000
46515   35000
23952   85000
19256   40000
14391   48879
30282   86000
20626   35360
31430   98000
11540   34403
2982   108160
49770   40000
10795   70000
18745   75000
39851  154000
9262    30000
3072    72000
28460   95000
28530   45000
44730  102050
44051   50000
11322   98400
25310   75000
31242   65000
39473   70000
47892   91000
44646   48000
...       ...
36021   72000
12766   75000
30974   72000
5084    80000
20354   58000
35841   43000
25585   33000
5198    50000
20524   86000
25960   26500
10926   45000
42710   12000
36583   48000
14412  110000
42324   81000
45995   15000
22694   70000
13466  118000
7208    49000
39998   57200
22476  125000
49411  108000
13898   80000
8012    85000
4806    35000
19919   50000
48889   51000
15505   58000
39829   75000
11614   95000

[100 rows x 1 columns]
            x
38821   65000
39407   72000
22888   50000
9764    47500
7393    41000
18671   44000
278     21300
7570    90000
16680   50000
1270   115000
            x
618     85000
35936   24000
32037   55000
29639   30000
33229   30000
18898   70000
46199   30000
32182   75000
29352  110000
24941   55000
16793   45000
47372   54586
7697    32500
34856   41000
33494   15000
2452   180000
5911    45000
40407   90000
49665   22599
31763  110000
19710  125000
13359   70000
9116    43000
3901    62000
12282   40000
30864   70000
7563    50000
12899   60000
48033   50000
11955  100000
...       ...
48503   67000
20231   62400
32921   37000
30048  110000
18633   60000
2617    66000
8238    50000
49245   60000
37900   80000
37010  105000
4617    55000
15853   81984
33893   48000
20951   40000
47214   48000
15617   59000
35787   53964
11116   60000
9349    80000
36971   40246
46663   50000
12857   38000
23089  120000
29447   55000
45869   45000
37007   85250
36321   64869
33970   75000
28477  110000
45622   24000

[100 rows x 1 columns]
            x
34202   75000
35309   53500
4387    83000
18313   50000
31188   50000
2949    37800
41290   42000
11124   92872
34277  120000
36681   62800
            x
11978   37980
40964   55000
37489   62000
48234   19000
11547   78000
30148   75000
16991   74000
8423    28000
43278   60000
28266  150000
25989   55000
11550   86600
35782  135000
37159   32000
41184   70000
36218   82200
24151   48000
14109   75000
28680   46000
47411   80000
37114   28000
21752   52000
5228    40000
4763    71000
49290   94600
42873   72800
29749   85000
43278   60000
1132    70000
6649   110000
...       ...
11863   66920
23634   60000
20566   47000
31311   58000
37349  100000
4151    70000
16398   50000
17049   55000
8396    27500
43743   54000
18825   55000
43523   98000
47685   40000
36574  173156
9619    52000
33538   35000
42402   60000
11056   70000
26514   47800
9379    40000
18198   65000
11602   55000
1499   120000
48480   45000
37906   52500
34271   32000
10145   37000
46065   58000
6283    40000
994     40000

[100 rows x 1 columns]
            x
40056   52000
5546    52000
21629   72000
30158   40000
43220   48000
34189   75000
19582   39500
40464  100000
41513   36000
20832   48500
            x
9157    55000
588     73000
24273   57000
29797   41000
4607    70000
18654   48000
918     77000
41900   50000
17249   31000
39504   28536
7466    87000
38956  104000
44809   49750
18837   57000
38545   61000
4421    92000
15701   42500
26431  100000
35203   41496
39245   70000
18078  111000
4100    57000
24436   36000
43612   55000
10028   82060
49749  150000
15989  102000
20413   40000
34805   48000
39012  180000
...       ...
1407   120000
40465   62000
46395   14000
8758    67500
27087   45000
26236   21000
37212   83000
43355   52340
5428    13900
36303   50000
36870   54996
14930   55000
5653    65000
1788   132000
14444   35000
13204   37000
818     88000
11756   43000
8073    39520
46386   56000
44023   65000
21363   90000
34415   12000
919    117500
35224   69400
16398   50000
22906   60000
12745   40000
34783   75000
44082   40000

[100 rows x 1 columns]
            x
38034  120000
8754   130000
34461   58000
32275   31200
43757   35000
37990  105000
44975   70000
9921    72000
7981    17000
19552   55000
            x
33017   27584
45147  110000
39526   30000
7404    88000
22452   44000
4361    55000
41510   90000
12506   52000
2315    53000
14116   85000
23833   59000
5721    61973
42124   44000
37193   56000
36126   30000
26670  100000
38103   58000
48608  123000
24786   86000
36353   58000
1638   110000
48303   74000
35771   54000
1721    15600
30987   48000
40981   74000
47987   65000
16361  135000
13507   62400
18369   70000
...       ...
9978    48000
11136   36000
32282   45000
21592   34800
40017   60000
45070   80000
33996   52000
49457   32800
3129   110000
29618   62000
21803  120000
26624   43076
47262   56000
24865   45000
41950  108000
6482    55894
8543    78750
8310   111000
11873   95000
45949   76000
3302    36000
32359   35000
37380  109600
29397   78000
25444   65000
818     88000
49138   27000
45149   88992
26406   35000
5693    70000

[100 rows x 1 columns]
            x
27876   75000
6419    35000
34236   37000
3290   102000
14169   26352
10123   75000
7817    53000
17463  100000
25681   61044
2118   130000
            x
32376   40000
6603    25656
27195  178000
23717   73000
33957   71000
2952    96000
17429   24000
48245  140000

            x
31485   35000
31291  130000
21018   80000
25814  130000
41270   56000
47      84032
20857  105000
16660   53000
14017   83500
17344   54000
13271   30000
18351   58000
22293   60000
35214   52000
39768   40000
34070   24900
33479  160000
26114   65000
21015   87000
32582   97000
22368   29000
3769   108000
29066   73500
15874   30586
11808   35000
33445   89400
13348  100000
23288   97000
34692   52400
43851   55000
...       ...
23757   40000
23350   40000
5556   101000
20288  100000
982     47000
5716    37356
16872   85000
27919   60000
35859   80000
39926   75000
32185   75000
24797   89000
41640   34500
8527    36000
23169   50000
9154    50000
7986    71000
10168   52276
16049   85000
25543   55000
40936   92000
17269   29000
37666   46000
28614   65000
8309    85000
37174  135000
43897   39324
36267  100000
17616   39520
43431  110000

[100 rows x 1 columns]
            x
24021   65000
18828   48000
9154    50000
7184    58000
49808   96000
4955    79432
24801   88580
10267   57500
31932   65000
28644  118000
            x
37936   45000
12213   75000
25368   98000
28040   86000
1641    45392
45252  106000
19592  115000
43024   61000
27464   40000
9003   156000
40356   57000
19756   35000
21303   25000
4994    50000
26164   25000
12141   62000
19191   45000
20801   60000
9397    95000
39592  101000
27815   35000
30823   75000
3004    62000
29765   30792
47169   65000
40745   40000
38149   42500
19441   38000
29440   68000
49173   48000
...       ...
9580    32750
44379   70000
8930   120000
43655   39132
31146   75000
29052   92000
21468   45000
36314   80000
39510   63000
24032   82000
46098   65000
32514  130000
40017   60000
22857   42000
14074  140000
44648   60000
30632  104000
35345  115000
13549   65000
14304   61516
163     39942
48551   81120
20254  130000
39898  120000
49688   76000
2641    70000
13833   31000
20753  135000
47478   53160
20176   49000

[100 rows x 1 columns]
            x
22140  103000
22458  125000
45036   95000
48185   30000
38259   60000
39460   34000
22918   23000
22079   46000
16147   49000
8171    45000
            x
402     26000
12572   72000
32855   84000
5900    29444
10417  100000
3810    45000
18312  125000
46690   41000
2474   100000
29739   85000
31729   18480
17367  140000
42247   59000
42513   75000
21641   32666
13663   60000
37728   97000
36670   92000
36514   55000
16259   38000
6538    70000
41342   55000
24410   13000
39870   46000
27098   50000
3088    38000
43061   45600
36950   30000
14465   39600
5881    80000
...       ...
43678   56010
15119   50000
32887   83000
38607   68000
4874    43000
26183   55000
909     29265
11959  116262
28639   50000
29252   90000
4492    65000
29060   33000
27454   76000
46101   70000
26204   68000
7163    72000
12120   43000
4941    77500
2088    35000
31286   52000
38143   63100
11427  180000
30196   70500
26308   60000
25500   75000
38724   90000
39943   84000
49526   66000
38419   85725
32973   80000

[100 rows x 1 columns]
           x
38637  38000
21217  68000
11924  62000
469    75000
29731  60000
35851  45000
15432  98000
3281   62400
41292  46000
43080  47777
            x
38854   49000
1190    23000
358     77000
17922   52000
42127   45000
36602   60000
23475   22000
24555   45000
32533  100000
715    110000
25915  102000
26785   80004
16254   38397
44441   30000
22059   48600
11841   41000
28718   50000
32203   32000
20198   41500
13367   72000
9004    41000
38757   70000
13115  114000
36913   40000
6018    70720
37671   45000
21526   80000
46623   41500
46060   50000
18245  120000
...       ...
6041    30000
27481   38000
5051    55000
26822   50000
8765    42500
25223   94000
1015   172000
42187   52000
47424   34000
7376    90000
18653   70000
325     42500
31032  107000
31068   32500
17538   35000
34067  135000
15204   25000
21445  139000
15916   30000
9490    69000
3258    60000
4876    55000
29403   80000
27609  109000
19207  100300
22281   56000
15866  165000
43781   48000
20643   53000
48642  145000

[100 rows x 1 columns]
            x
16185   40000
36107   45000
39182   65000
46313   80000
9723    63000
3383    50000
42543   35000
30272  115000
28093   60800
38883   79000
            x
40553   96000
7948   120000
24211   25000
40748   36000
19616   54000
47485   70000
22011   65004
20348   63970
48251   92300
37627  100000
24481   91800
15452   60500
40042   53000
47065   55000
7904    29000
49112   60000
43306   70000
11668   42000
31279   47500
38711   39000
15076  135000
44752  135000
21667   60000
8321    50000
45313   90000
24849   48000
23574   90000
14667   23823
10757   31000
15998   56000
...       ...
534     40000
23505   28600
35739   40000
21641   32666
2530    69583
24157   40000
30987   48000
12448   85000
44436   40560
29265   50000
45710   51000
40591   80000
48594   41000
38321   70000
32310   48000
33213   45000
38370   63000
2746    47000
18793   56000
13884   58000
683     42000
16277   70000
36975   51000
14344   52500
45473   80000
14969   45172
32776   27000
18812   31361
8134   110000
28805   60978

[100 rows x 1 columns]
            x
41711   77000
36678  120000
48723   60000
4021    30840
4366   155000
7099    39600
17840   44000
20178   49000
39519   54760
39145   70000
            x
44220   76000
38543   16627
19329   73000
11925   65000
42628   70000
20237  114000
13931  130000
1383    46000
19870   60500
8257    88000
27570   38600
27121   86000
44086   38000
37266   50364
35015   49000
49017  125000
42710   12000
31328   72000
6333    49000
35914   72100
42443  103000
24172   85000
40790   60000
42457  130068
21789   94000
49116   52000
22094   84000
24355  150000
34548   62200
43024   61000
...       ...
43880  120000
27741   32000
42130  120000
44937   89500
8069    90000
13485   67920
23181   42000
5933    70000
23846   45000
4895    61000
34961   40000
1619   114000
21903   82000
11544   51996
6945    79000
19761   21600
31358   85000
40617   48500
32583   75500
49409   40000
38489   80000
2154    75000
1953    40000
37428  110000
24654   60000
348     79000
29837   70000
20281   43200
46581   55000
3068    80000

[100 rows x 1 columns]
            x
7217   127000
41789   60000
1326    39315
47015   70000
39087   70200
33588   50000
11030  160575
37976   75000
48857   33280
24971   40000
            x
49838   70000
32005   85000
19567   45500
40570   68000
32893   40000
3392    55000
45221  101000
11078   85000
6831   132000
43857   41000
2990    60000
44360   95892
31976   42000
48517   55608
7936    94000
23806  169000
41598   58680
42469  100000
43854   52000
25694   50000
3584   125000
10351   49000
7777   110000
40086   93569
17320   46000
36191  113000
35550   45600
16180   40000
451     95000
21031  150000
...       ...
47420   42000
35827  110000
6700    57000
41405  154043
23186   78000
1154   150000
3488    26240
32597   50000
15783   67000
46456   64000
32314   38000
39422   80000
35494   85000
16152   30000
29011   35000
30329   50000
6430    80000
9999   110000
955     83000
11453   23000
11546   75000
3677    90000
26365   43936
13894   72000
12415   50000
20020   75108
35971   48000
14      90000
13275  130000
12880   63000

[100 rows x 1 columns]
            x
5113    48000
17528   66000
33510   82000
32232   80000
43264   28000
10286  140000
5567    34132
28247   50000
4000    47000
48738  120000
            x
39994   39600
1416    97000
43883   88000
49536   90000
45192   42000
4534    40000
35758   45000
38030   65000
49939   90000
43310  100000
4653    80000
26902  160000
40994  110000
47737   92000
30079   45000
1491    33000
30915   77700
21341  121000
48270   48000
9760    56000
18032   45000
24656   32448
4840    91228
6360    77000
30922   68000
40443   94000
47530   42000
32791  180000
264     45000
3376    65000
...       ...
40016   60000
3073    36000
42737   63762
7022    82812
11902   50000
25323   45000
12568  120000
24997  127000
8932    67400
4907    52000
23637   88088
18673   31200
34296   45000
26855   45000
46106   63000
27704   90000
25868   18000
16801   73000
25928  150000
33728   44000
1590   158000
48959   86460
45966   80000
10949  115000
46665   92000
46740   32000
22160   30000
7410    44200
41743   57000
11327  162000

[100 rows x 1 columns]
            x
24708  125000
28967   60000
14814   48000
20071   68000
47390   53000
5845    35000
19972  118000
16555   68000
47974   58000
18029   86000
            x
40997   33000
22016   50000
8934    48000
38402   47000
44940  165000
40149   70400
44869   36000
12970   45000
5384   145000
3895    35000
6002    38650
33123   21000
45811   78500
11657   80000
24425   69000
29043   58000
2021    70000
3198   122000
42466   45000
12591   39200
20663   35000
48133   50000
9058    38000
40069   90000
39702   57000
30295   40000
43929   50000
29970  135000
40917   80000
44954   44000
...       ...
13258   82000
37891   55000
47379   56100
36978   70000
39247  180000
14160   95000
40475   60000
14185   70700
10844   42000
18745   75000
20137   64000
45607   35000
38243   75000
38751   42000
46944   50000
6751    38000
17030   24000
2415    70000
38503   42500
44213   73000
12480   40000
49001   44000
39463   99744
3881    60000
4693    37332
26792   29112
42667   60480
27238   86000
26696   55000
2581   115000

[100 rows x 1 columns]
            x
4309   150000
3644    37000
42082   50000
2205    55000
30269   89000
49665   22599
11834  110000
30286   74000
10904   75000
9545    68000
            x
48354  120000
28457   55000
18954   90000
20669   75000
33606   36000
31741   32000
19454  155000
26815   65000
38687   93677
40824   85000
29841  105000
20739   66000
14264   56000
15691   38000
33466   80000
3481    65000
11455  124000
34499  116480
5602    75000
46157   77000
34847   65000
41550   12744
23474   84000
41895   92000
41570   25000
44785   65000
45455   85000
2058    65000
6875   131000
38754   26000
...       ...
31296  105000
46444   56916
25376  180000
1529    73000
31302   78592
39483  101000
29137   60000
14338   36840
23445  115000
42266   65000
36689   75000
40626  125000
49502   15384
20404   47000
35054   71500
46351   28000
10201   60000
4032    83002
4452    31080
17639   70000
2962   125000
31644   38000
21571   34056
17657   84000
32911   65000
2386    60000
5472    57996
15237   21250
41940  161000
14739   42000

[100 rows x 1 columns]
            x
44294   42000
1887    32000
23822   44480
27083   92000
5602    75000
43698  112000
45614  102000
49651   13000
6575    90000
9203    56000
            x
2850    60000
22907  120000
4765   115000
25173   75000
19867  112000
45994   77000
47906   35000
39015   70000
32699   50000
31192   68780
34579  135000
28841   51000
8831   130000
29359   50000
47196   60000
7498    45000
25064   66000
5683   119000
45272   55000
2935    56000
6374    27000
12859   60000
4859    56000
29163   36791
30920  112000
37564   31200
41551  140000
29726   59000
38864   47000
44305   87000
...       ...
31034   53000
39591  154000
26869   50000
6770   125000
43026   40000
46920   56463
28516   75000
779     75000
36397   98000
29318   62000
43211   78000
43105   50000
42684   70000
25813   78000
14894  135000
47314   90000
47658   25000
27133  120000
15242   75000
23312   47000
17691   40000
43467   95000
45289  165000
310     48000
21373   30000
45580   73000
24493   50000
20114   69000
13483   62400
13844   78000

[100 rows x 1 columns]
            x
3567    35000
4157    75000
34177  195000
34668   79000
25864   38000
44270   20000
41770   32000
42614   55000
22062  158000
988     96366
            x
24984  116004
31356   41000
26681   53000
9642    50000
10724   85000
25349   82000
18287   31000
22163   65000
29500   96771
41181   78000
37774   30000
4978    48000
41327   60000
24095   91000
46908   58000
32558   31724
17188   45000
30658   65000
10118  145000
24931   52000
1717    62000
48928   86000
24568   63223
10274   78000
45932   68000
33137   75000
20369   59000
33090   80000
44599   55000
42911   48000
...       ...
44830   90577
3771    66000
45741   42000
972     24000
31587   39690
25321   75000
5274    67615
42290   40000
34056   45000
43325   56000
7677    60000
46166   47000
4910    51000
5495    50000
9918    42000
13864   54000
32591   60000
45778   40320
9058    38000
43130   90000
44815   80000
32449   93500
26115  195000
1190    23000
46338   47500
32719   37000
48352   80000
28497   92000
14095   75000
31271   60000

[100 rows x 1 columns]
            x
14666   68124
25239   70000
18341   82000
19607   85000
37303  100360
11872   52000
28768   60000
48861   43000
39856   45000
38899  110000
            x
499     80000
9531    40000
5684    55000
12069   60000
20207   57000
25277   51000
33199   47000
26128   45000
44400   43200
41249   35632
44058   68000
43258   75000
48964   39000
20830   60000
23630   68000
5087    60000
47033   47000
27444   68000
43583   49431
41917   47000
6854    95000
40692   63000
40246  110500
17698   93600
32380   72000
8459    80000
24138   47000
8089    90000
2745    85000
13290   60000
...       ...
33287  120000
24803  104000
9280   100000
1318    75000
1745    42500
19083   37000
41887   90000
5401    40000
22195   67000
12393  116000
47359   85000
34006   35000
29751   52000
3357    60000
7396    40000
48999   60000
13220   45000
49595   91000
1454   135000
21566   68804
40199   65000
40548   43000
42291  120000
21543   30000
46820   91670
46585   44000
13973   90000
21022  110000
28637   53000
49696   23000

[100 rows x 1 columns]
            x
16880   57000
27328   71000
14599   51700
31454  120000
45434   90000
16712   98000
19495   75000
36404   49500
48112   74000
32736   50000
            x
37924   65000
5809    41000
23188   90000
24244   15600
10286  140000
166     40000
26055   29000
25665   33357
5892    80000
34632   75000
3029    36000
19989  152440
34483   40000
10982   91000
40281   75000
36068   43000
33232   32000
43778   36600
26438   52000
38403   93370
5955    75000
48713  119250
12077   70000
22952   94000
16581  105000
23212   95000
14366   69160
27824   35000
24303   40000
4092    82400
...       ...
38312   48000
18047   42000
35212   50000
40697   43000
48256   37184
32821   35000
30100   43000
22292   40800
36172   19200
28572   71712
896     54000
17514   42000
17033  115000
16656   65000
48333   78000
1294    70000
46290   80000
42720   33050
37907   40000
2140    68000
7832    85000
44212  120000
39751   30000
32555   44000
20373   40000
30277   70000
21112   89000
10229  125000
11621   60000
12946  120000

[100 rows x 1 columns]
           x
1660   55000
29255  65000
19156  56000
2527   63000
24720  76000
38297  40000
20588  43000
7563   50000
38927  31500
42858  35000
            x
43289  150000
27842   76494
30525   28000
32092   55000
3994    70000
37004   82000
22295   82000
34160  115000
8200   125000
33175  150000
17910   41000
1898    55000
33275   65234
19619  115000
14267   20598
34966   52000
39164  108000
27265   43000
7837    22000
29282   80000
12865   50000
48870   40000
18076   74000
40177   40000
37930   86250
17484   37200
6665    90000
46096   71000
24017  123000
47407   51000
...       ...
31247   38000
11597   45000
37231   80000
3136    95000
9887    90000
24282   30000
32578  140000
19947   50000
33929   58000
8696    40000
48981   84000
15072   60000
8994    28000
24091   83000
32182   75000
37668   32000
28983   74628
13036   34000
42275  120000
45706  145000
2159    45008
25488   75000
15366   51000
9436    56000
9198    59207
7777   110000
9090   195000
33547   68000
45047   75000
41735   78000

[100 rows x 1 columns]
            x
13960   85000
46154  150000
24419   60000
28024  105000
43757   35000
13650   79000
46      25000
40056   52000
17770   83000
2054    43000
            x
40276   71000
8238    50000
5549    75000
5316    45000
1032    48000
29616   61800
22365   65000
702     48000
16941   50000
19516   60000
33874   45000
25051  106000
22540  105000
26443   50000
40117   88500
12959   70000
7529    53000
15733  150000
22352  150000
2134    21000
20627  125000
12120   43000
44551   80000
2740    65000
18744   27600
9449    31000
41471   52250
547     69000
25966   97500
49392   48000
...       ...
13717   35333
12745   40000
33661  120000
10006   56000
47552   19000
26589   48000
45863  100000
9238    35206
2241    65000
45120   50464
22041   60000
25671  100000
17989   60000
42092   62000
24701  111000
23906   45000
49100   65000
26547   70000
27225   45000
29843   38000
22141   69500
30193   38600
5320    43000
30408   60000
33421   52000
16670   35000
26144  105000
49628   95000
40594   67000
21901   44400

[100 rows x 1 columns]
            x
9251    30000
23479   55000
398     56000
24065   60000
26740   22000
11682   93000
47021   50000
40398   82000
44941   48000
24784  110000
            x
28236   29000
30758   91000
376    180000
48790   74000
36993   50000
20349   78000
38994  120000
23579   52000
13255   78000
35274   35000
36892   55000
9390    82000
46240   60000
39804   72000
22717   65000
2738    70230
44412   98000
36308   50000
33124   67000
26713   43500
31604   65000
8575    33000
21234   37000
22303   32000
11495  105000
43826   60000
45071  100000
22831  185000
8428    94800
25663   37000
...       ...
26466   87000
32849   60000
26844   68500
20507   34000
45056  102000
12483   62000
11130   70000
41868   60000
10156   40000
17909   69000
32935   24000
22745   70000
6473   140000
23853   65000
2249    95000
25890   35000
1604    85000
34085   54600
44643   40000
42072   29500
39179   60000
6674    66800
23533   50000
47022   32000
48532   48000
23052   58000
24282   30000
31908   92615
35346   75000
28441   68000

[100 rows x 1 columns]
            x
12303   65800
14577  132000
3372   102000
47405   48000
45811   78500
8206    51000
10069   90000
24522  120000
45057   65000
15010   35000
            x
26494   60000
9072   105000
29447   55000
36505   53000
19796  180000
7661    40000
39466   70416
13795   68000
28213   33000
48356   70000
30460   50000
16807   84000
35342  120000
4954   107000
32940   75000
5550    42000
33771  145000
40997   33000
20120   49000
42704   62000
35220   44000
16331   60000
21828   46800
47784   95000
5384   145000
24768   72720
26915   86000
10461  130000
36096   98000
13396  148000
...       ...
9469    92000
35965   40000
14367  110000
12381   72000
25225   96000
911     85000
31361   72000
11925   65000
37094   28000
3583    43000
12964   57000
41796   29224
41556   60000
23051   72000
39097   76000
35771   54000
35114   55000
45759   71000
6665    90000
46117   40560
3818    60000
11485  120000
33216   74000
36087   75000
29268   55000
28574   60000
45422   62000
42818  104000
41537   72000
9541    57000

[100 rows x 1 columns]
           x
46286  51013
27481  38000
23515  55000
48156  25000
33032  22226
49035  56544
29325  35000
36892  55000
6990   53000
8519   43000
            x
10251   30000
24059   40000
47414   92000
48406   60000
37442   70000
8127    56000
31023   54704
35440   42000
44405   80000
9894    70000
25260   40000
38334  150000
13356   80000
29752  108000
29388   73000
18041   23000
8020   150000
44527   54433
3810    45000
7907    25000
49505  122000
33806   98000
48292   68000
47702   78000
1066    95000
35649   51200
16175   65000
41089  122000
45298   24996
9073    52000
...       ...
37158  102000
41741   57500
30285   65000
49328   72000
32446  110000
40455   66000
23729   60000
46912   45000
10662   47000
27936   40000
32401   56000
20647   60000
47025   56000
49884   45000
14930   55000
27622   39000
30505  180000
36065   14900
23628   52000
6295    76500
17780  153000
39930   50858
37932   68000
1637    34000
3498   119537
41797   53893
20164  120000
20846   41000
24446   24200
35396   58000

[100 rows x 1 columns]
            x
48599   40000
2260    71000
18636   50000
40372  100000
23078   27370
28495   95000
14780   60000
43202  141000
39995   52000
18878   70000
            x
45556   48000
37039   75000
1427    55000
6412    54000
18229   45000
44978   55000
7540    30000
38529   99600
21523   48000
45918   53500

            x
143     34122
12190   75000
11154   32000
7098    30000
43122  106500
32365   31164
24645  175000
31388   30000
12044  115000
39791  115000
24738   40000
30363   35000
9038    60000
43870   72090
38929  110000
16894  100000
3247    65000
15912   85000
41966   80000
1929    34080
14173   35000
33993  136000
4128    43000
39978   58000
11772   42000
42351   80000
33449   55000
29619   40000
4239    55000
3581    45000
...       ...
36541   74042
4133    53000
7727    85000
34497   50000
34906  120000
48775  100000
48310   55000
32776   27000
13662   75000
38971   82000
24065   60000
7998    66000
14957   50000
31207   75000
3406    30000
12256  150000
28617   55000
32127  120000
20624   81000
9575    72000
14134   45000
22064   80300
20604   63000
32990   75000
14998   56000
13313   33500
39605   51000
29717  112000
28289   39000
9685    82000

[100 rows x 1 columns]
            x
18610   90000
3236    71000
14569  107120
47507   50000
24000   71000
43269   63372
8996   110000
40439   44000
17906   18000
34350   93600
            x
43226   37702
45463   80000
5741    90000
5652    50000
39617   40000
18664   78000
4008    42000
10345   51000
47925   75000
18894  104000
41397   36000
32975   35000
14143   45000
2305    87000
9546   170000
8172   102000
25749   50000
11186   78048
36920   52000
21886   48925
18380   49000
21457   51000
8886    45000
20105  156800
20499  100000
29086   27000
10948   52000
2344    59000
27177  147000
35010  100000
...       ...
6374    27000
31214   60000
48176  150000
6498    47200
5611   105000
49472   82000
5958    80000
23900   75000
44256   87000
5711    35000
5710   120000
24825   40000
49194   39814
34889   26000
37177  123000
39565   55000
23635   74800
42828   62400
35182   35000
21575  120000
3312    93000
44510   48000
40393   60000
37875   40000
45766   82000
20305   43000
21719  150000
19082   70000
49900   67973
45748   56000

[100 rows x 1 columns]
            x
21540   65000
33525   20000
40137   80000
22762   98000
29651  100000
47705   50000
23655   83000
37026   68000
48530   75000
5870    28600
            x
29177  150000
41246  100000
16506   35000
31968   36000
14467   70000
16965   93000
15368   25000
47355   69000
2948   100000
14191   70885
47209   48000
20947   80000
23539   70000
11474   41000
18351   58000
11168   54000
15489   80000
47187   75000
34570   40000
46314  180000
42407  125000
49401   43000
49951   45000
41142   85000
49937   98352
7063    55000
6349    60000
3319    67000
26195   21000
25775   42000
...       ...
43207   45900
39894   94992
9767    30000
49399   28800
14199  102000
4051    49000
48006  100350
45965   85000
26132  135000
47033   47000
36487   88000
1771    28161
26034   58000
47120   60000
21255   90000
47533   75000
22202   76800
19219   70000
42380   35000
4484    90000
23377   56400
32567   85000
48819   80000
2230    30000
31963   57000
33126   47000
37826   43520
46681   82000
47806  121000
12240   46000

[100 rows x 1 columns]
            x
39284   31200
14710   60000
31312  100000
26656   48000
19843   43000
3152   140000
30245   71000
27908   47000
21366   52000
40188   70000
            x
2190    65000
3488    26240
6768    54080
35882   33000
33995   29000
6675    42000
26401   68000
5778    40000
36141  140000
33561   26500
16178   54000
7407    35000
9011   100000
23420   51000
46192   30000
27183   66000
20943   15000
17716   65000
40753   80000
47180   55000
37951   76000
19448   68000
19404   81700
12672   70000
29108  110000
41603   71000
39919   45000
6039    52225
17023   65000
38003   25000
...       ...
47805   48000
43371   58400
42941   48000
8563   109000
42428   96000
3670    60000
2879    68000
27778  180000
36262   33000
14164  194000
20269   61000
33949   20315
946     91000
5       33000
47657   62000
15194   69996
21471   59000
3113    40000
36919   90000
20540  154500
29015   70000
638     40000
17754  145000
18270   45000
2004    42000
1686    51600
6890    56500
37409  140000
31683   48000
20336  100000

[100 rows x 1 columns]
            x
41879  120000
7157    51000
29201   32000
36079  120000
28023   80000
36777  140000
42382   60000
37950   36000
871    100000
13360   49800
            x
45971   42000
22212   62000
20617   62000
5146    40000
43150   78000
13277  106000
32012   23004
18358   55000
29663  109000
23460   69000
14697   30000
4309   150000
46486   33000
12679   91300
31917   60000
28795   55000
22099   60000
48238   65000
26062  110000
36964   55000
28969   85000
7014    46000
19716   78000
8551    40000
42372   63000
1440    95342
33424   55000
30282   86000
24168  100000
31143   60000
...       ...
27655   80000
46142  120000
37298   80000
38266   18200
1581    48000
28704   45000
28970   36000
9059    90000
49454   37000
45455   85000
8402    40000
7060    60000
25413   19000
39462   85000
43295   60000
37700   65000
35307   30000
36678  120000
25866   65000
7041    85000
46383   25000
31473  125000
36347   62000
3288    75000
44974  109000
3478    36000
2929    34880
39587  120000
40979   97000
18622   91955

[100 rows x 1 columns]
            x
15354   75000
20633  100000
9952    54000
48138  130000
39930   50858
8166    40000
22864  102000
40591   80000
23963   33000
32810   40000
            x
23765   28200
42563  110000
48062  100000
38325   90000
43245   38000
26394   60000
20644   25000
4295    82000
45987   28000
33981   34560
1207    96000
43902   51000
30300   65000
13329  102000
43002   71000
23663  110000
35437   54000
1372    93000
12979   65000
47662   80000
18789   35065
37134  127630
11134   37000
21238  123000
25276   55000
34435   68000
9882    87000
16029   58000
12564   95000
10013   47000
...       ...
14825   37440
4523   109000
9408    30000
14319   45000
3319    67000
37253   24000
29963   50000
47898   97000
31619   50000
24500   80000
26628   35000
34601   70000
31451   45000
43908   71000
2168    40000
42658   75000
31562  140000
20426   61000
14601   79000
9739    59500
11647   50000
9093    68023
28090   39000
22120   60000
19776   80000
26533  160000
32936   60000
3334   150000
25549  100000
28631   76800

[100 rows x 1 columns]
            x
7178    60000
17016   45000
17998   13000
35021  180000
31350  100000
14933  110000
36390   60900
13741   50000
4299    72000
15062   63000
            x
23308  135000
550     58160
26534   33331
3799    20000
9531    40000
29190   40000
4360    54000
23633   55000
38120   51280
11383   70000
17982   58000
22899  112000
2485    60000
39040   22000
25020   48000
14585   75000
29991   30000
3862    90000
18554   36000
5022    38000
44991   43000
22797   43680
20578   30000
49937   98352
35724   57000
29691   52588
231     51000
43059   65000
16990  110000
21290   95000
...       ...
5990    88000
31495   42000
17149   75000
21413   85000
17073   46500
30709  120000
4985    50980
14350   43962
24660   75000
16057   78000
41492   80000
30755   15024
7429    65000
30192   70000
16145   35000
49600   50000
39923   27000
40961   82000
39239   45000
16309   55000
30968   28700
21959   34278
12952   95000
24334   90000
17319  110000
11266   35000
5704    35000
42657  150000
5686    29000
23719  142000

[100 rows x 1 columns]
            x
14072   90000
36515  122000
8620   150000
46340   73000
45899   78000
33542   78000
13266   62000
35075   45000
15729   55000
45847   99552
            x
3556    37000
25832   50000
26850   54000
42485   43000
20031   53560
35633   80000
23327   87000
8966    75000
38936   87000
38526   23340
24046  170000
45649   54000
23725   58000
33274   70000
29398   24960
20789   42000
8366    66766
42642   90000
11308   70000
43850   26026
42064   45000
5426    80000
10874  108000
33809   70000
16500   80000
39251   55000
23243  160000
49879   39200
46039  100000
35877   28000
...       ...
3676    62500
18506   58000
32270   88268
22564  129000
5840    25000
13135   30000
23820   97500
37584   47000
37196   39500
19948   80000
46934   70000
4689   110000
13385   28000
556     80000
36044  155000
2211    60000
8445    65388
39963   90000
46470   45000
35488   49512
49963  130000
15511   96000
91      45000
41409   62400
49666  180000
39972   62612
9950    32000
9105    55000
27791   72500
108     25000

[100 rows x 1 columns]
           x
497    55000
45943  87370
35330  58000
18988  97000
16327  85000
39605  51000
38591  88000
36810  64000
5745   47000
22479  55000
            x
22185  125000
6460    38000
8006   100000
32208   60000
46642   81640
10134   40000
16120   55000
11342   50000
8206    51000
11703   53000
48756   73560
12234   65000
26104   63000
43738   73000
41215   70000
46482  105780
19865   65000
32064  100000
535     92000
43917   50000
44483   30000
39766   48000
11918   55000
46726   35000
11385   62000
46663   50000
37205  130000
30223   59000
46801   42000
8895    44000
...       ...
25968   37524
31779   29000
17301   50000
32930   40000
38325   90000
7696    73000
11062   60000
44832   45000
45864   69000
5956    27000
16184   33343
18281  146760
33322   65000
24134   62000
31518   57000
2728    74567
42035   90000
47618   50000
36047   55000
38746   65000
7207    66393
44074   85000
30300   65000
15607  165000
46682   35000
49009   45600
37458   45600
27257  137000
14862   50000
28344  102000

[100 rows x 1 columns]
            x
49778   27000
7620   100000
35368   18000
26624   43076
48780   80000
26268   32400
27884   45000
15759   84996
43858  132000
32723  113000
            x
20173   41000
6614    80000
28355   55000
7876    88000
43409   36000
20460  100000
42608   48500
32430   35000
47173   43000
11799   73400
45328   47500
29904   62000
30955   78000
41623  115000
46108   55000
25564   82000
36053   50000
42226   58000
37794   64000
26140   34320
17113   38000
3377   110000
3438   100584
16960   61000
17837   55900
24017  123000
10786  106000
45881   61000
46119   86095
41125   53600
...       ...
7252    19000
19586   68000
19936   22000
26616   67000
48776   42000
17170   65000
36489   84000
49377   26000
34182   90000
36969   67000
11992   55668
47718  100000
1       52000
48579   46000
21135   76870
22833   70000
45801  102000
44288   71000
21756   40000
4486    87000
13934   80000
7280    40000
19619  115000
22203   56000
21110   51000
40433   50000
18449   65000
42825   68455
46506   43000
49861   84000

[100 rows x 1 columns]
            x
9037    52000
18615   43000
12739   46000
21675   38000
282     75000
48103   72000
29060   33000
40478  108000
11281   66000
22652   40000
            x
31207   75000
30032  105000
36606   52000
22583   75000
49550   56000
17472   30000
24465  175000
20535   45000
16385   95000
42744   67675
30462   42000
11962  135000
11751  120000
46631   65000
9484    75000
31984   90000
12042   59000
41004   38000
23983   43000
9461    27000
37655   80000
4411    55000
43736   95600
8476    33500
11177   85000
265     95400
26117   95000
39962   75000
12784   23000
15326   45000
...       ...
45760   60000
6482    55894
16437  160000
15173   35651
29422   60000
32000  110000
8803    90000
22289   85000
13906   60000
40584  125000
27994   42400
18741   75000
3562   120000
49796   55000
10754   55000
46670   57000
49537  104000
90      26000
48427  111000
39012  180000
12971  199000
39476   37000
34929   71000
21499   60000
16658   47000
24237  178000
6735    55000
34533   37000
29363   90000
23956  103000

[100 rows x 1 columns]
            x
5846    84000
45208  100000
39465  112500
34083   47301
2345   123000
14090   47000
48978   30000
47473   33000
31785   40000
5764    72000
            x
24833   44000
4137    95000
12407  110000
1144    55000
20614   48000
29426   55000
5253    30000
11615   96000
42384   98800
8977    65000
22360  110000
16720   30000
20260   70000
26361   50000
5744    28000
22225   75000
46081   60000
15040   73000
13429   60000
17161   95975
42678   40000
14830   46000
9965   160000
46575   45000
18465   65000
45028  160000
2384    55000
19212   32000
37031   40000
20317   47000
...       ...
40761   13200
15924   37200
39338   50000
20735  151000
29692   98000
25182   22800
28961   67000
8343    85000
36212   45000
33302  150000
17098   67356
5384   145000
199     40000
16680   50000
7605    84000
890     37098
27886   92700
1248    65000
2000    70500
34980   80000
3438   100584
46280   60000
13527   46000
13068  125000
34943   21304
6419    35000
20317   47000
826     39036
24040   90000
13243   75000

[100 rows x 1 columns]
            x
22363  135000
44697   50000
21994   30000
23118   43000
17548   61639
31171   40000
8842    95000
15211   75000
9486   130000
4638    89000
            x
29081   80000
6049    65000
1789    44000
11037   70000
45862   60000
45326   60000
10598  101500
22983  185000
40839   80000
15278   41000
9777    23000
8724    60000
24896   66462
1611    38500
16312   90000
17248  150000
24968   32789
12763   57600
37277  139008
31139   45000
47328   90000
34392   45000
37150   45000
48675   65000
1875    60000
35656   57240
2953    84000
40985   18500
44348   65000
25696   75000
...       ...
11376   65000
16996   77000
13374   51000
14665   72000
37411   90000
17591   25000
44199   55000
37494   37000
25232   52000
48421   45000
20533  125000
6370    65000
4394    65000
31575   57500
34297  102870
28291   28000
13513   54000
2193    75000
29796   65000
19199   54436
15314   79000
17854   35000
35569   35000
39112   90000
12434   82000
34482   58000
43482   32000
25136   60000
35380   63000
20587   30000

[100 rows x 1 columns]
            x
24546   37000
49220  115000
9033    54184
12681   55000
43401   72000
33116   40000
7645    40000
33129   25000
38560   70000
19325   67000
            x
26125   36000
39218   22000
2414    70000
48299   64000
6869   102000
22515   75000
25747   51600
43723  155000
40977   96664
11230  130000
9213    74326
10220  123000
42136   60000
46776   71102
48468   61296
43223   45000
13878   75000
15635   89900
7468    75000
27861   50000
34730   55000
2465   107909
46422   90000
28400   50000
41041   94500
15013   42640
49179   90000
25269   95000
6430    80000
5458    48000
...       ...
31713   50400
11175   90000
15298   40000
35172  125000
33803   40000
14180   90000
28320  195000
15743   70000
42564   80000
32017   63000
8619    85000
46112  100000
21337  116000
4026    60000
8457    76000
2587    60000
36588   19000
39785  147000
36211  102000
22670   31000
42150  140000
38124   70000
46754   54000
23599   80000
15695   65000
11511   85000
47641   60000
44971   23088
31442   52000
33596   91000

[100 rows x 1 columns]
            x
49672  140000
26448   35000
36226   40000
27145   60000
15010   35000
4395    88000
38873   66385
30943  150000
19031   45000
46657   80000
            x
46257   78000
7803    60000
1795    72000
16181  100000
9447    29000
47719   48000
46769   25200
33580   85000
46966   91480
11634   57000
22170   37000
31736   88000
684     85000
25514   51000
35520  125000
1953    40000
11089   29000
26721   81972
980     70000
14816   41000
49701   33375
17053   72000
34813   55000
6383    60000
21659   80000
19239   65000
27898   48137
19844   50000
21095  122000
18073   75000
...       ...
45466  110004
7694    89000
10447   56000
25967  100000
11511   85000
30439   98000
39881   90000
13335  150000
16018   27000
11218  103400
25211   41000
31269  120000
27970   85600
22553   30000
10269   67000
221     90000
18898   70000
46685   83500
13899   60000
37228   72000
31415  104911
31272   50000
43951   50000
18786  100000
48170   42313
13496  100000
34091   40000
4282    38987
5620    65000
31360   51200

[100 rows x 1 columns]
            x
47412   77000
490     45999
16749  140000
17643   90500
40966  127000
23336   23579
32956   50000
3773   116000
31755   50000
20479  135000
            x
5544    74717
35302   85000
6634    40000
14492   41000
22016   50000
22361   60000
47303   62000
23053   96000
1027    42000
18975   45000
13827   41250
18966   70000
10772   78000
21025  100000
30727   48000
45393   71508
34203   85000
23541   52000
45655  105000
32275   31200
36753   40000
42365   68000
2543    32000
836    150000
31156   71000
5996    51000
2665    62000
3089    31992
33641   35000
36457   64000
...       ...
2306    51000
28695   32000
38281   67000
15073  132300
42629   78000
48427  111000
14560   58000
47672   36000
12853   77000
27691   53000
37904   89000
22503  143000
43085  108000
42364  100000
44344   55000
41402   43000
38715  118000
34324   73000
40475   60000
49560   45000
39525   45650
16754   67000
29058   32560
40553   96000
4729    58000
24189   51265
8862    45000
26975  125000
40203  155000
26957   50000

[100 rows x 1 columns]
            x
8968    62500
35642   71968
46639   30000
26436  103500
20605   56000
11099   62000
26516   85000
30089   60000
17402   79300
23387   70000
            x
41897   80000
35983   93000
13651   70000
13429   60000
5023    84000
34749   52000
10701  120000
16980   60000
5185    92000
49470   33000
25625  155000
39798   80000
1879    10000
49045   65000
38649   23608
46697   71000
34969   51000
16894  100000
31482   73000
30290   49500
3316    62000
19074   27050
43694   68984
31115   60000
18168   64311
13962   55000
42117   45000
17782   44000
6212    70500
49686   62000
...       ...
49388   60000
47978   42000
21107   65000
1712    76450
11918   55000
8603    42000
3680   189000
35715  111000
44623   66000
11686   98401
49229   30000
8401    70000
49362   55000
22468   77000
16496  100000
30292   32000
39384   40000
27999  110000
6509    60000
13976   58000
27470   95000
37208  100000
30299   70000
39375  115000
28841   51000
44650   59864
607     38496
28633   49200
31915   39000
27341   80000

[100 rows x 1 columns]
            x
25977   25000
39233   74000
26322   70000
17877   74280
21234   37000
14730   62000
14205   50000
7748   121752
14855   50000
15876   60000
            x
24010   50000
42771  110000
25020   48000
30323   64000
1554    22800
28857  121000
29233   26400
2986   100000
22071   42960
31867   40000
16362   90000
3424    50000
9860    40000
14608   43000
27241  122500
42176   75000
40959   73000
14451   95000
47641   60000
2825    50000
31027   75000
33454   84842
21076   41600
19719  125000
28506   93114
43093   55000
11420   58000
43785   92000
16300   30000
19386   50000
...       ...
33530   80000
23882   75000
338     19500
3630    80000
27155   99000
24278   65000
49037   56000
19913   36000
13426   55040
535     92000
18128  110000
48297   52000
28497   92000
47432   78000
43559  110000
28666   75000
20074  117000
16436   42000
40608  109000
34862   52000
47524   70000
28017   55300
22404   33000
11195   41000
49146  100812
17193   50000
21502   56000
19180   70000
42379   58000
47360   86000

[100 rows x 1 columns]
            x
33794   60000
5223   132000
9536    60000
478     40900
37339  125000
30873   90000
38337   40000
18612   73539
4726    89451
44342   88518
            x
32044   60000
3232    30000
12005   49620
45939   37000
23697   95000
22825   79475
5633    65000
17259  120000
32763   32000
30149   85000
31024   54000
42161   60000
7264   184000
33385   85000
14058   95000
34487   60000
33751   54080
3524    70000
19571   49000
23860  100000
49689   83000
43475   80000
48336   39000
28165   52000
15163  100000
27103   29000
40264   52000
5980    31000
37453   54000
31768   55000
...       ...
39637   37400
45556   48000
24005   69000
10205   80000
38966   40000
21249   37000
40895   80000
25830   46000
37489   62000
27576   75000
12624   58000
22060   53200
48116   41604
46458  102000
10598  101500
41939   35000
21142   44000
20780   46000
46499   52000
6273    75000
47075   72500
5491    82000
20102   29000
37299   85000
17578   25000
28447   40800
34198   50000
29675  130000
31794   34000
16357   70000

[100 rows x 1 columns]
            x
12568  120000
46057  125000
36885   54000
13501   45000
4204   170000
34743   18588
19220   40000
48928   86000
25423  100000
32565   62400
            x
43077   40000
32792  130000
19664   73161
6324    63540
34331   27300
24478   50000
32146   60000
11412  112000